window.rawProblems = window.rawProblems || [];

window.rawProblems.push(
  { id: 2001, title: "Number of Pairs of Interchangeable Rectangles", diff: "Medium", topics: "Array, Hash Table, Math, Counting", slug: "number-of-pairs-of-interchangeable-rectangles" },
  { id: 2002, title: "Maximum Product of the Length of Two Palindromic Subsequences", diff: "Medium", topics: "String, Backtracking, Bit Manipulation", slug: "maximum-product-of-the-length-of-two-palindromic-subsequences" },
  { id: 2003, title: "Smallest Missing Genetic Value in Each Subtree", diff: "Hard", topics: "Array, Hash Table, Tree, Depth-First Search", slug: "smallest-missing-genetic-value-in-each-subtree" },
  { id: 2004, title: "The Number of Seniors and Juniors to Join the Company", diff: "Hard", topics: "Database", slug: "the-number-of-seniors-and-juniors-to-join-the-company" },
  { id: 2005, title: "Subtree Removal Game with Fibonacci Tree", diff: "Hard", topics: "Tree, Dynamic Programming, Game Theory", slug: "subtree-removal-game-with-fibonacci-tree" },
  { id: 2006, title: "Count Number of Pairs With Absolute Difference K", diff: "Easy", topics: "Array, Hash Table, Counting", slug: "count-number-of-pairs-with-absolute-difference-k" },
  { id: 2007, title: "Find Original Array From Doubled Array", diff: "Medium", topics: "Array, Hash Table, Greedy, Sorting", slug: "find-original-array-from-doubled-array" },
  { id: 2008, title: "Maximum Earnings From Taxi", diff: "Medium", topics: "Array, Dynamic Programming, Sorting", slug: "maximum-earnings-from-taxi" },
  { id: 2009, title: "Minimum Number of Operations to Make Array Continuous", diff: "Hard", topics: "Array, Binary Search, Sliding Window, Sorting", slug: "minimum-number-of-operations-to-make-array-continuous" },
  { id: 2010, title: "The Number of Seniors and Juniors to Join the Company II", diff: "Hard", topics: "Database", slug: "the-number-of-seniors-and-juniors-to-join-the-company-ii" },
  { id: 2011, title: "Final Value of Variable After Performing Operations", diff: "Easy", topics: "Array, String, Simulation", slug: "final-value-of-variable-after-performing-operations" },
  { id: 2012, title: "Sum of Beauty in the Array", diff: "Medium", topics: "Array", slug: "sum-of-beauty-in-the-array" },
  { id: 2013, title: "Detect Squares", diff: "Medium", topics: "Hash Table, Math, Design, Counting", slug: "detect-squares" },
  { id: 2014, title: "Longest Subsequence Repeated k Times", diff: "Hard", topics: "String, Backtracking, Breadth-First Search", slug: "longest-subsequence-repeated-k-times" },
  { id: 2015, title: "Average Height of Buildings in Each Segment", diff: "Hard", topics: "Array, Ordered Set, Prefix Sum", slug: "average-height-of-buildings-in-each-segment" },
  { id: 2016, title: "Maximum Difference Between Increasing Elements", diff: "Easy", topics: "Array", slug: "maximum-difference-between-increasing-elements" },
  { id: 2017, title: "Grid Game", diff: "Medium", topics: "Array, Matrix, Prefix Sum", slug: "grid-game" },
  { id: 2018, title: "Check if Word Can Be Placed In Crossword", diff: "Medium", topics: "Array, Matrix", slug: "check-if-word-can-be-placed-in-crossword" },
  { id: 2019, title: "The Score of Students Solving Math Expression", diff: "Hard", topics: "Array, Dynamic Programming, String", slug: "the-score-of-students-solving-math-expression" },
  { id: 2020, title: "Number of Accounts That Did Not Stream", diff: "Medium", topics: "Database", slug: "number-of-accounts-that-did-not-stream" },
  { id: 2021, title: "Brightest Position on Street", diff: "Medium", topics: "Array, Prefix Sum, Sorting", slug: "brightest-position-on-street" },
  { id: 2022, title: "Convert 1D Array Into 2D Array", diff: "Easy", topics: "Array, Matrix", slug: "convert-1d-array-into-2d-array" },
  { id: 2023, title: "Number of Pairs of Strings With Concatenation Equal to Target", diff: "Medium", topics: "Array, Hash Table, String", slug: "number-of-pairs-of-strings-with-concatenation-equal-to-target" },
  { id: 2024, title: "Maximize the Confusion of an Exam", diff: "Medium", topics: "String, Binary Search, Sliding Window", slug: "maximize-the-confusion-of-an-exam" },
  { id: 2025, title: "Maximum Number of Ways to Partition an Array", diff: "Hard", topics: "Array, Hash Table, Prefix Sum", slug: "maximum-number-of-ways-to-partition-an-array" },
  { id: 2026, title: "Low-Quality Problems", diff: "Easy", topics: "Database", slug: "low-quality-problems" },
  { id: 2027, title: "Minimum Moves to Convert String", diff: "Easy", topics: "String, Greedy", slug: "minimum-moves-to-convert-string" },
  { id: 2028, title: "Find Missing Observations", diff: "Medium", topics: "Array, Math", slug: "find-missing-observations" },
  { id: 2029, title: "Stone Game IX", diff: "Medium", topics: "Array, Math, Game Theory", slug: "stone-game-ix" },
  { id: 2030, title: "Smallest K-Length Subsequence With Occurrences of a Letter", diff: "Hard", topics: "String, Stack, Greedy, Monotonic Stack", slug: "smallest-k-length-subsequence-with-occurrences-of-a-letter" },
  { id: 2031, title: "Count Subarrays With More Ones Than Zeros", diff: "Medium", topics: "Array, Binary Indexed Tree, Segment Tree, Prefix Sum", slug: "count-subarrays-with-more-ones-than-zeros" },
  { id: 2032, title: "Two Out of Three", diff: "Easy", topics: "Array, Hash Table", slug: "two-out-of-three" },
  { id: 2033, title: "Minimum Operations to Make a Uni-Value Grid", diff: "Medium", topics: "Array, Math, Matrix, Sorting", slug: "minimum-operations-to-make-a-uni-value-grid" },
  { id: 2034, title: "Stock Price Fluctuation", diff: "Medium", topics: "Hash Table, Design, Heap (Priority Queue), Ordered Set", slug: "stock-price-fluctuation" },
  { id: 2035, title: "Partition Array Into Two Arrays to Minimize Sum Difference", diff: "Hard", topics: "Array, Bit Manipulation, Divide and Conquer", slug: "partition-array-into-two-arrays-to-minimize-sum-difference" },
  { id: 2036, title: "Maximum Alternating Subarray Sum", diff: "Medium", topics: "Array, Dynamic Programming", slug: "maximum-alternating-subarray-sum" },
  { id: 2037, title: "Minimum Number of Moves to Seat Everyone", diff: "Easy", topics: "Array, Greedy, Sorting", slug: "minimum-number-of-moves-to-seat-everyone" },
  { id: 2038, title: "Remove Colored Pieces if Both Neighbors are the Same Color", diff: "Medium", topics: "String, Game Theory", slug: "remove-colored-pieces-if-both-neighbors-are-the-same-color" },
  { id: 2039, title: "The Time When the Network Becomes Idle", diff: "Medium", topics: "Breadth-First Search, Graph", slug: "the-time-when-the-network-becomes-idle" },
  { id: 2040, title: "Kth Smallest Product of Two Sorted Arrays", diff: "Hard", topics: "Array, Binary Search", slug: "kth-smallest-product-of-two-sorted-arrays" },
  { id: 2041, title: "Accepted Candidates From the Interviews", diff: "Medium", topics: "Database", slug: "accepted-candidates-from-the-interviews" },
  { id: 2042, title: "Check if Numbers Are Ascending in a Sentence", diff: "Easy", topics: "String", slug: "check-if-numbers-are-ascending-in-a-sentence" },
  { id: 2043, title: "Simple Bank System", diff: "Medium", topics: "Array, Design, Simulation", slug: "simple-bank-system" },
  { id: 2044, title: "Count Number of Maximum Bitwise-OR Subsets", diff: "Medium", topics: "Array, Backtracking, Bit Manipulation", slug: "count-number-of-maximum-bitwise-or-subsets" },
  { id: 2045, title: "Second Minimum Time to Reach Destination", diff: "Hard", topics: "Breadth-First Search, Graph, Shortest Path", slug: "second-minimum-time-to-reach-destination" },
  { id: 2046, title: "Sort Linked List Already Sorted Using Absolute Values", diff: "Medium", topics: "Linked List", slug: "sort-linked-list-already-sorted-using-absolute-values" },
  { id: 2047, title: "Number of Valid Words in a Sentence", diff: "Easy", topics: "String", slug: "number-of-valid-words-in-a-sentence" },
  { id: 2048, title: "Next Greater Numerically Balanced Number", diff: "Medium", topics: "Backtracking, Enumeration", slug: "next-greater-numerically-balanced-number" },
  { id: 2049, title: "Count Nodes With the Highest Score", diff: "Medium", topics: "Tree, Depth-First Search", slug: "count-nodes-with-the-highest-score" },
  { id: 2050, title: "Parallel Courses III", diff: "Hard", topics: "Dynamic Programming, Graph, Topological Sort", slug: "parallel-courses-iii" },
  { id: 2051, title: "The Category of Each Member in the Store", diff: "Easy", topics: "Database", slug: "the-category-of-each-member-in-the-store" },
  { id: 2052, title: "Minimum Cost to Separate Sentence Into Rows", diff: "Hard", topics: "String, Dynamic Programming", slug: "minimum-cost-to-separate-sentence-into-rows" },
  { id: 2053, title: "Kth Distinct String in an Array", diff: "Easy", topics: "Array, Hash Table, String, Counting", slug: "kth-distinct-string-in-an-array" },
  { id: 2054, title: "Two Best Non-Overlapping Events", diff: "Medium", topics: "Array, Binary Search, Dynamic Programming, Sorting", slug: "two-best-non-overlapping-events" },
  { id: 2055, title: "Plates Between Candles", diff: "Medium", topics: "Array, String, Prefix Sum", slug: "plates-between-candles" },
  { id: 2056, title: "Number of Valid Move Combinations On Chessboard", diff: "Hard", topics: "Backtracking, Simulation", slug: "number-of-valid-move-combinations-on-chessboard" },
  { id: 2057, title: "Smallest Index With Equal Value", diff: "Easy", topics: "Array", slug: "smallest-index-with-equal-value" },
  { id: 2058, title: "Find the Minimum and Maximum Number of Nodes Between Critical Points", diff: "Medium", topics: "Linked List", slug: "find-the-minimum-and-maximum-number-of-nodes-between-critical-points" },
  { id: 2059, title: "Minimum Operations to Convert Number", diff: "Medium", topics: "Array, Breadth-First Search", slug: "minimum-operations-to-convert-number" },
  { id: 2060, title: "Check if an Original String Exists Given Two Encoded Strings", diff: "Hard", topics: "String, Dynamic Programming, Depth-First Search", slug: "check-if-an-original-string-exists-given-two-encoded-strings" },
  { id: 2061, title: "Number of Spaces Cleaning Robot Cleaned", diff: "Medium", topics: "Array, Hash Table, Simulation, Matrix", slug: "number-of-spaces-cleaning-robot-cleaned" },
  { id: 2062, title: "Count Vowel Substrings of a String", diff: "Easy", topics: "Hash Table, String, Sliding Window", slug: "count-vowel-substrings-of-a-string" },
  { id: 2063, title: "Vowels of All Substrings", diff: "Medium", topics: "String, Dynamic Programming, Math", slug: "vowels-of-all-substrings" },
  { id: 2064, title: "Minimized Maximum of Products Distributed to Any Store", diff: "Medium", topics: "Array, Binary Search", slug: "minimized-maximum-of-products-distributed-to-any-store" },
  { id: 2065, title: "Maximum Path Quality of a Graph", diff: "Hard", topics: "Graph, Backtracking", slug: "maximum-path-quality-of-a-graph" },
  { id: 2066, title: "Account Balance", diff: "Easy", topics: "Database", slug: "account-balance" },
  { id: 2067, title: "Number of Equal Count Substrings", diff: "Medium", topics: "String, Sliding Window", slug: "number-of-equal-count-substrings" },
  { id: 2068, title: "Check Whether Two Strings are Almost Equivalent", diff: "Easy", topics: "Hash Table, String, Counting", slug: "check-whether-two-strings-are-almost-equivalent" },
  { id: 2069, title: "Walking Robot Simulation II", diff: "Medium", topics: "Design, Simulation", slug: "walking-robot-simulation-ii" },
  { id: 2070, title: "Most Beautiful Item for Each Query", diff: "Medium", topics: "Array, Binary Search, Sorting", slug: "most-beautiful-item-for-each-query" },
  { id: 2071, title: "Maximum Number of Tasks You Can Assign", diff: "Hard", topics: "Array, Binary Search, Greedy, Queue, Sorting", slug: "maximum-number-of-tasks-you-can-assign" },
  { id: 2072, title: "The Winner University", diff: "Easy", topics: "Database", slug: "the-winner-university" },
  { id: 2073, title: "Time Needed to Buy Tickets", diff: "Easy", topics: "Array, Queue, Simulation", slug: "time-needed-to-buy-tickets" },
  { id: 2074, title: "Reverse Nodes in Even Length Groups", diff: "Medium", topics: "Linked List", slug: "reverse-nodes-in-even-length-groups" },
  { id: 2075, title: "Decode the Slanted Ciphertext", diff: "Medium", topics: "String", slug: "decode-the-slanted-ciphertext" },
  { id: 2076, title: "Process Restricted Friend Requests", diff: "Hard", topics: "Array, Union Find", slug: "process-restricted-friend-requests" },
  { id: 2077, title: "Paths in Maze That Lead to Same Room", diff: "Medium", topics: "Graph", slug: "paths-in-maze-that-lead-to-same-room" },
  { id: 2078, title: "Two Furthest Houses With Different Colors", diff: "Easy", topics: "Array", slug: "two-furthest-houses-with-different-colors" },
  { id: 2079, title: "Watering Plants", diff: "Medium", topics: "Array, Simulation", slug: "watering-plants" },
  { id: 2080, title: "Range Frequency Queries", diff: "Medium", topics: "Array, Hash Table, Binary Search, Design", slug: "range-frequency-queries" },
  { id: 2081, title: "Sum of k-Mirror Numbers", diff: "Hard", topics: "Math, Enumeration", slug: "sum-of-k-mirror-numbers" },
  { id: 2082, title: "The Number of Rich Customers", diff: "Easy", topics: "Database", slug: "the-number-of-rich-customers" },
  { id: 2083, title: "Substrings That Begin and End With the Same Letter", diff: "Medium", topics: "Hash Table, String, Counting", slug: "substrings-that-begin-and-end-with-the-same-letter" },
  { id: 2084, title: "Drop Type 1 Orders for Customers With Type 0 Orders", diff: "Medium", topics: "Database", slug: "drop-type-1-orders-for-customers-with-type-0-orders" },
  { id: 2085, title: "Count Common Words With One Occurrence", diff: "Easy", topics: "Array, Hash Table, String, Counting", slug: "count-common-words-with-one-occurrence" },
  { id: 2086, title: "Minimum Number of Food Buckets to Feed the Hamsters", diff: "Medium", topics: "String, Greedy", slug: "minimum-number-of-food-buckets-to-feed-the-hamsters" },
  { id: 2087, title: "Minimum Cost Homecoming of a Robot in a Grid", diff: "Medium", topics: "Array, Greedy, Matrix", slug: "minimum-cost-homecoming-of-a-robot-in-a-grid" },
  { id: 2088, title: "Count Fertile Pyramids in a Land", diff: "Hard", topics: "Array, Dynamic Programming, Matrix", slug: "count-fertile-pyramids-in-a-land" },
  { id: 2089, title: "Find Target Indices After Sorting Array", diff: "Easy", topics: "Array, Sorting", slug: "find-target-indices-after-sorting-array" },
  { id: 2090, title: "K Radius Subarray Averages", diff: "Medium", topics: "Array, Prefix Sum", slug: "k-radius-subarray-averages" },
  { id: 2091, title: "Removing Minimum and Maximum From Array", diff: "Medium", topics: "Array, Greedy", slug: "removing-minimum-and-maximum-from-array" },
  { id: 2092, title: "Find All People With Secret", diff: "Hard", topics: "Depth-First Search, Breadth-First Search, Union Find, Graph, Sorting", slug: "find-all-people-with-secret" },
  { id: 2093, title: "Minimum Cost to Reach City With Discounts", diff: "Medium", topics: "Graph, Heap (Priority Queue), Shortest Path", slug: "minimum-cost-to-reach-city-with-discounts" },
  { id: 2094, title: "Finding 3-Digit Even Numbers", diff: "Easy", topics: "Array, Hash Table, Enumeration, Sorting", slug: "finding-3-digit-even-numbers" },
  { id: 2095, title: "Delete the Middle Node of a Linked List", diff: "Medium", topics: "Linked List, Two Pointers", slug: "delete-the-middle-node-of-a-linked-list" },
  { id: 2096, title: "Step-By-Step Directions From a Binary Tree Node to Another", diff: "Medium", topics: "String, Tree, Depth-First Search, Binary Tree", slug: "step-by-step-directions-from-a-binary-tree-node-to-another" },
  { id: 2097, title: "Valid Arrangement of Pairs", diff: "Hard", topics: "Depth-First Search, Graph, Eulerian Circuit", slug: "valid-arrangement-of-pairs" },
  { id: 2098, title: "Subsequence of Size K With the Largest Even Sum", diff: "Medium", topics: "Array, Greedy, Sorting", slug: "subsequence-of-size-k-with-the-largest-even-sum" },
  { id: 2099, title: "Find Subsequence of Length K With the Largest Sum", diff: "Easy", topics: "Array, Hash Table, Sorting, Heap (Priority Queue)", slug: "find-subsequence-of-length-k-with-the-largest-sum" },
  { id: 2100, title: "Find Good Days to Rob the Bank", diff: "Medium", topics: "Array, Dynamic Programming", slug: "find-good-days-to-rob-the-bank" },
  { id: 2101, title: "Detonate the Maximum Bombs", diff: "Medium", topics: "Depth-First Search, Breadth-First Search, Graph", slug: "detonate-the-maximum-bombs" },
  { id: 2102, title: "Sequentially Ordinal Rank Tracker", diff: "Hard", topics: "Design, Heap (Priority Queue), Ordered Set", slug: "sequentially-ordinal-rank-tracker" },
  { id: 2103, title: "Rings and Rods", diff: "Easy", topics: "Hash Table, String", slug: "rings-and-rods" },
  { id: 2104, title: "Sum of Subarray Ranges", diff: "Medium", topics: "Array, Stack, Monotonic Stack", slug: "sum-of-subarray-ranges" },
  { id: 2105, title: "Watering Plants II", diff: "Medium", topics: "Array, Two Pointers, Simulation", slug: "watering-plants-ii" },
  { id: 2106, title: "Maximum Fruits Harvested After at Most K Steps", diff: "Hard", topics: "Array, Binary Search, Prefix Sum, Sliding Window", slug: "maximum-fruits-harvested-after-at-most-k-steps" },
  { id: 2107, title: "Number of Unique Flavors After Sharing K Candies", diff: "Medium", topics: "Array, Hash Table, Sliding Window", slug: "number-of-unique-flavors-after-sharing-k-candies" },
  { id: 2108, title: "Find First Palindromic String in the Array", diff: "Easy", topics: "Array, Two Pointers, String", slug: "find-first-palindromic-string-in-the-array" },
  { id: 2109, title: "Adding Spaces to a String", diff: "Medium", topics: "Array, String, Simulation", slug: "adding-spaces-to-a-string" },
  { id: 2110, title: "Number of Smooth Descent Periods of a Stock", diff: "Medium", topics: "Array, Dynamic Programming", slug: "number-of-smooth-descent-periods-of-a-stock" },
  { id: 2111, title: "Minimum Operations to Make the Array K-Increasing", diff: "Hard", topics: "Array, Binary Search, Dynamic Programming, Greedy", slug: "minimum-operations-to-make-the-array-k-increasing" },
  { id: 2112, title: "The Airport With the Most Traffic", diff: "Hard", topics: "Database", slug: "the-airport-with-the-most-traffic" },
  { id: 2113, title: "Elements in Array After Removing and Replacing Elements", diff: "Medium", topics: "Array, Simulation", slug: "elements-in-array-after-removing-and-replacing-elements" },
  { id: 2114, title: "Maximum Number of Words Found in Sentences", diff: "Easy", topics: "String", slug: "maximum-number-of-words-found-in-sentences" },
  { id: 2115, title: "Find All Possible Recipes from Given Supplies", diff: "Medium", topics: "Graph, Topological Sort, Hash Table", slug: "find-all-possible-recipes-from-given-supplies" },
  { id: 2116, title: "Check if a Parentheses String Can Be Valid", diff: "Medium", topics: "String, Greedy, Stack", slug: "check-if-a-parentheses-string-can-be-valid" },
  { id: 2117, title: "Abbreviating the Product of a Range", diff: "Hard", topics: "Math", slug: "abbreviating-the-product-of-a-range" },
  { id: 2118, title: "Build the Equation", diff: "Hard", topics: "Database", slug: "build-the-equation" },
  { id: 2119, title: "A Number After a Double Reversal", diff: "Easy", topics: "Math", slug: "a-number-after-a-double-reversal" },
  { id: 2120, title: "Execution of All Suffix Instructions Staying in a Grid", diff: "Medium", topics: "Array, Simulation", slug: "execution-of-all-suffix-instructions-staying-in-a-grid" },
  { id: 2121, title: "Intervals Between Identical Elements", diff: "Medium", topics: "Array, Hash Table, Prefix Sum", slug: "intervals-between-identical-elements" },
  { id: 2122, title: "Recover the Original Array", diff: "Hard", topics: "Array, Hash Table, Sorting", slug: "recover-the-original-array" },
  { id: 2123, title: "Minimum Operations to Remove Adjacent Ones in Matrix", diff: "Hard", topics: "Graph, Bipartite Matching, Matrix", slug: "minimum-operations-to-remove-adjacent-ones-in-matrix" },
  { id: 2124, title: "Check if All A's Appears Before All B's", diff: "Easy", topics: "String", slug: "check-if-all-as-appears-before-all-bs" },
  { id: 2125, title: "Number of Laser Beams in a Bank", diff: "Medium", topics: "Array, Matrix", slug: "number-of-laser-beams-in-a-bank" },
  { id: 2126, title: "Destroying Asteroids", diff: "Medium", topics: "Array, Greedy, Sorting", slug: "destroying-asteroids" },
  { id: 2127, title: "Maximum Employees to Be Invited to a Meeting", diff: "Hard", topics: "Depth-First Search, Graph, Topological Sort", slug: "maximum-employees-to-be-invited-to-a-meeting" },
  { id: 2128, title: "Remove All Ones With Row and Column Flips", diff: "Medium", topics: "Array, Bit Manipulation, Matrix", slug: "remove-all-ones-with-row-and-column-flips" },
  { id: 2129, title: "Capitalize the Title", diff: "Easy", topics: "String", slug: "capitalize-the-title" },
  { id: 2130, title: "Maximum Twin Sum of a Linked List", diff: "Medium", topics: "Linked List, Two Pointers, Stack", slug: "maximum-twin-sum-of-a-linked-list" },
  { id: 2131, title: "Longest Palindrome by Concatenating Two Letter Words", diff: "Medium", topics: "Array, Hash Table, String, Greedy", slug: "longest-palindrome-by-concatenating-two-letter-words" },
  { id: 2132, title: "Stamping the Grid", diff: "Hard", topics: "Array, Matrix, Prefix Sum", slug: "stamping-the-grid" },
  { id: 2133, title: "Check if Every Row and Column Contains All Numbers", diff: "Easy", topics: "Array, Hash Table, Matrix", slug: "check-if-every-row-and-column-contains-all-numbers" },
  { id: 2134, title: "Minimum Swaps to Group All 1's Together II", diff: "Medium", topics: "Array, Sliding Window", slug: "minimum-swaps-to-group-all-1s-together-ii" },
  { id: 2135, title: "Count Words Obtained After Adding a Letter", diff: "Hard", topics: "Array, Hash Table, Bit Manipulation, String, Sorting", slug: "count-words-obtained-after-adding-a-letter" },
  { id: 2136, title: "Earliest Possible Day of Full Bloom", diff: "Hard", topics: "Array, Greedy, Sorting", slug: "earliest-possible-day-of-full-bloom" },
  { id: 2137, title: "Pour Water Between Buckets to Make Water Levels Equal", diff: "Medium", topics: "Array, Binary Search", slug: "pour-water-between-buckets-to-make-water-levels-equal" },
  { id: 2138, title: "Divide a String Into Groups of Size k", diff: "Easy", topics: "String", slug: "divide-a-string-into-groups-of-size-k" },
  { id: 2139, title: "Minimum Moves to Reach Target Score", diff: "Medium", topics: "Greedy", slug: "minimum-moves-to-reach-target-score" },
  { id: 2140, title: "Solving Questions With Brainpower", diff: "Medium", topics: "Array, Dynamic Programming", slug: "solving-questions-with-brainpower" },
  { id: 2141, title: "Maximum Running Time of N Computers", diff: "Hard", topics: "Array, Binary Search, Greedy", slug: "maximum-running-time-of-n-computers" },
  { id: 2142, title: "The Number of Passengers in Each Bus I", diff: "Hard", topics: "Database", slug: "the-number-of-passengers-in-each-bus-i" },
  { id: 2143, title: "Choose Numbers From Two Arrays in Range", diff: "Hard", topics: "Array, Dynamic Programming", slug: "choose-numbers-from-two-arrays-in-range" },
  { id: 2144, title: "Minimum Cost of Buying Candies With Discount", diff: "Easy", topics: "Array, Greedy, Sorting", slug: "minimum-cost-of-buying-candies-with-discount" },
  { id: 2145, title: "Count the Hidden Sequences", diff: "Medium", topics: "Array, Prefix Sum", slug: "count-the-hidden-sequences" },
  { id: 2146, title: "K Highest Ranked Items Within a Price Range", diff: "Medium", topics: "Array, Breadth-First Search, Matrix, Heap (Priority Queue)", slug: "k-highest-ranked-items-within-a-price-range" },
  { id: 2147, title: "Number of Ways to Divide a Long Corridor", diff: "Hard", topics: "String, Dynamic Programming, Combinatorics", slug: "number-of-ways-to-divide-a-long-corridor" },
  { id: 2148, title: "Count Elements With Strictly Smaller and Greater Elements", diff: "Easy", topics: "Array, Sorting", slug: "count-elements-with-strictly-smaller-and-greater-elements" },
  { id: 2149, title: "Rearrange Array Elements by Sign", diff: "Medium", topics: "Array, Two Pointers", slug: "rearrange-array-elements-by-sign" },
  { id: 2150, title: "Find All Lonely Numbers in the Array", diff: "Easy", topics: "Array, Hash Table, Counting", slug: "find-all-lonely-numbers-in-the-array" },
  { id: 2151, title: "Maximum Good People Based on Statements", diff: "Hard", topics: "Array, Bit Manipulation, Backtracking", slug: "maximum-good-people-based-on-statements" },
  { id: 2152, title: "Minimum Number of Lines to Cover Points", diff: "Hard", topics: "Array, Dynamic Programming, Bit Manipulation, Geometry", slug: "minimum-number-of-lines-to-cover-points" },
  { id: 2153, title: "The Number of Passengers in Each Bus II", diff: "Hard", topics: "Database", slug: "the-number-of-passengers-in-each-bus-ii" },
  { id: 2154, title: "Keep Multiplying Found Values by Two", diff: "Easy", topics: "Array, Hash Table", slug: "keep-multiplying-found-values-by-two" },
  { id: 2155, title: "All Divisions With the Highest Score of a Binary Array", diff: "Medium", topics: "Array, Prefix Sum", slug: "all-divisions-with-the-highest-score-of-a-binary-array" },
  { id: 2156, title: "Find Substring With Given Hash Value", diff: "Hard", topics: "String, Sliding Window, Rolling Hash, Hash Function", slug: "find-substring-with-given-hash-value" },
  { id: 2157, title: "Groups of Strings", diff: "Hard", topics: "Hash Table, String, Bit Manipulation, Union Find", slug: "groups-of-strings" },
  { id: 2158, title: "Amount of New Area Painted Each Day", diff: "Hard", topics: "Array, Ordered Set", slug: "amount-of-new-area-painted-each-day" },
  { id: 2159, title: "Order Two Columns Independently", diff: "Medium", topics: "Database", slug: "order-two-columns-independently" },
  { id: 2160, title: "Minimum Sum of Four Digit Number After Splitting Digits", diff: "Easy", topics: "Math, Greedy, Sorting", slug: "minimum-sum-of-four-digit-number-after-splitting-digits" },
  { id: 2161, title: "Partition Array According to Given Pivot", diff: "Medium", topics: "Array, Two Pointers, Simulation", slug: "partition-array-according-to-given-pivot" },
  { id: 2162, title: "Minimum Cost to Set Cooking Time", diff: "Medium", topics: "Math, String, Enumeration", slug: "minimum-cost-to-set-cooking-time" },
  { id: 2163, title: "Minimum Difference in Sums After Removal of Elements", diff: "Hard", topics: "Array, Heap (Priority Queue), Prefix Sum", slug: "minimum-difference-in-sums-after-removal-of-elements" },
  { id: 2164, title: "Sort Even and Odd Indices Independently", diff: "Easy", topics: "Array, Sorting", slug: "sort-even-and-odd-indices-independently" },
  { id: 2165, title: "Smallest Value of the Rearranged Number", diff: "Medium", topics: "Math, Sorting", slug: "smallest-value-of-the-rearranged-number" },
  { id: 2166, title: "Design Bitset", diff: "Medium", topics: "Array, String, Design", slug: "design-bitset" },
  { id: 2167, title: "Minimum Time to Remove All Cars Containing Illegal Goods", diff: "Hard", topics: "String, Dynamic Programming, Greedy", slug: "minimum-time-to-remove-all-cars-containing-illegal-goods" },
  { id: 2168, title: "Unique Substrings With Equal Digit Frequency", diff: "Medium", topics: "Hash Table, String, Rolling Hash, Hash Function", slug: "unique-substrings-with-equal-digit-frequency" },
  { id: 2169, title: "Count Operations to Obtain Zero", diff: "Easy", topics: "Math, Simulation", slug: "count-operations-to-obtain-zero" },
  { id: 2170, title: "Minimum Operations to Make the Array Alternating", diff: "Medium", topics: "Array, Hash Table, Greedy, Counting", slug: "minimum-operations-to-make-the-array-alternating" },
  { id: 2171, title: "Removing Minimum Number of Magic Beans", diff: "Medium", topics: "Array, Prefix Sum, Sorting", slug: "removing-minimum-number-of-magic-beans" },
  { id: 2172, title: "Maximum AND Sum of Array", diff: "Hard", topics: "Array, Dynamic Programming, Bit Manipulation", slug: "maximum-and-sum-of-array" },
  { id: 2173, title: "Longest Winning Streak", diff: "Medium", topics: "Database", slug: "longest-winning-streak" },
  { id: 2174, title: "Remove All Ones With Row and Column Flips II", diff: "Medium", topics: "Array, Backtracking, Matrix", slug: "remove-all-ones-with-row-and-column-flips-ii" },
  { id: 2175, title: "The Change in Global Rankings", diff: "Medium", topics: "Database", slug: "the-change-in-global-rankings" },
  { id: 2176, title: "Count Equal and Divisible Pairs in an Array", diff: "Easy", topics: "Array", slug: "count-equal-and-divisible-pairs-in-an-array" },
  { id: 2177, title: "Find Three Consecutive Integers That Sum to a Given Number", diff: "Medium", topics: "Math", slug: "find-three-consecutive-integers-that-sum-to-a-given-number" },
  { id: 2178, title: "Maximum Split of Positive Even Integers", diff: "Medium", topics: "Math, Greedy", slug: "maximum-split-of-positive-even-integers" },
  { id: 2179, title: "Count Good Triplets in an Array", diff: "Hard", topics: "Array, Binary Indexed Tree, Segment Tree", slug: "count-good-triplets-in-an-array" },
  { id: 2180, title: "Count Integers With Even Digit Sum", diff: "Easy", topics: "Math", slug: "count-integers-with-even-digit-sum" },
  { id: 2181, title: "Merge Nodes in Between Zeros", diff: "Medium", topics: "Linked List", slug: "merge-nodes-in-between-zeros" },
  { id: 2182, title: "Construct String With Repeat Limit", diff: "Medium", topics: "Hash Table, String, Greedy, Heap (Priority Queue), Counting", slug: "construct-string-with-repeat-limit" },
  { id: 2183, title: "Count Array Pairs Divisible by K", diff: "Hard", topics: "Array, Hash Table, Math, Number Theory", slug: "count-array-pairs-divisible-by-k" },
  { id: 2184, title: "Number of Ways to Build Sturdy Brick Wall", diff: "Hard", topics: "Dynamic Programming, Bit Manipulation", slug: "number-of-ways-to-build-sturdy-brick-wall" },
  { id: 2185, title: "Counting Words With a Given Prefix", diff: "Easy", topics: "String", slug: "counting-words-with-a-given-prefix" },
  { id: 2186, title: "Minimum Number of Steps to Make Two Strings Anagram II", diff: "Medium", topics: "Hash Table, String, Counting", slug: "minimum-number-of-steps-to-make-two-strings-anagram-ii" },
  { id: 2187, title: "Minimum Time to Complete Trips", diff: "Medium", topics: "Array, Binary Search", slug: "minimum-time-to-complete-trips" },
  { id: 2188, title: "Minimum Time to Finish the Race", diff: "Hard", topics: "Array, Dynamic Programming", slug: "minimum-time-to-finish-the-race" },
  { id: 2189, title: "Number of Ways to Build House of Cards", diff: "Medium", topics: "Dynamic Programming", slug: "number-of-ways-to-build-house-of-cards" },
  { id: 2190, title: "Most Frequent Number Following Key In an Array", diff: "Easy", topics: "Array, Hash Table, Counting", slug: "most-frequent-number-following-key-in-an-array" },
  { id: 2191, title: "Sort the Jumbled Numbers", diff: "Medium", topics: "Array, Sorting", slug: "sort-the-jumbled-numbers" },
  { id: 2192, title: "All Ancestors of a Node in a Directed Acyclic Graph", diff: "Medium", topics: "Depth-First Search, Breadth-First Search, Graph, Topological Sort", slug: "all-ancestors-of-a-node-in-a-directed-acyclic-graph" },
  { id: 2193, title: "Minimum Number of Moves to Make Palindrome", diff: "Hard", topics: "String, Greedy, Two Pointers", slug: "minimum-number-of-moves-to-make-palindrome" },
  { id: 2194, title: "Cells in a Range on an Excel Sheet", diff: "Easy", topics: "String", slug: "cells-in-a-range-on-an-excel-sheet" },
  { id: 2195, title: "Append K Integers With Minimal Sum", diff: "Medium", topics: "Array, Greedy, Sorting", slug: "append-k-integers-with-minimal-sum" },
  { id: 2196, title: "Create Binary Tree From Descriptions", diff: "Medium", topics: "Hash Table, Tree, Depth-First Search, Binary Tree", slug: "create-binary-tree-from-descriptions" },
  { id: 2197, title: "Replace Non-Coprime Numbers in Array", diff: "Hard", topics: "Array, Math, Stack, Number Theory", slug: "replace-non-coprime-numbers-in-array" },
  { id: 2198, title: "Number of Single Divisor Triplets", diff: "Medium", topics: "Array, Hash Table, Counting", slug: "number-of-single-divisor-triplets" },
  { id: 2199, title: "Finding the Topic of Each Post", diff: "Hard", topics: "Database", slug: "finding-the-topic-of-each-post" },
  { id: 2200, title: "Find All K-Distant Indices in an Array", diff: "Easy", topics: "Array, Two Pointers", slug: "find-all-k-distant-indices-in-an-array" },
  { id: 2201, title: "Count Artifacts That Can Be Extracted", diff: "Medium", topics: "Array, Hash Table, Matrix, Simulation", slug: "count-artifacts-that-can-be-extracted" },
  { id: 2202, title: "Maximize the Topmost Element After K Moves", diff: "Medium", topics: "Array, Greedy", slug: "maximize-the-topmost-element-after-k-moves" },
  { id: 2203, title: "Minimum Weighted Subgraph With the Required Paths", diff: "Hard", topics: "Graph, Shortest Path, Heap (Priority Queue)", slug: "minimum-weighted-subgraph-with-the-required-paths" },
  { id: 2204, title: "Distance to a Cycle in Undirected Graph", diff: "Hard", topics: "Graph, Breadth-First Search", slug: "distance-to-a-cycle-in-undirected-graph" },
  { id: 2205, title: "The Number of Users That Are Eligible for Discount", diff: "Easy", topics: "Database", slug: "the-number-of-users-that-are-eligible-for-discount" },
  { id: 2206, title: "Divide Array Into Equal Pairs", diff: "Easy", topics: "Array, Hash Table, Bit Manipulation, Counting", slug: "divide-array-into-equal-pairs" },
  { id: 2207, title: "Maximize Number of Subsequences in a String", diff: "Medium", topics: "String, Greedy, Counting", slug: "maximize-number-of-subsequences-in-a-string" },
  { id: 2208, title: "Minimum Operations to Halve Array Sum", diff: "Medium", topics: "Array, Greedy, Heap (Priority Queue)", slug: "minimum-operations-to-halve-array-sum" },
  { id: 2209, title: "Minimum White Tiles After Covering With Carpets", diff: "Hard", topics: "String, Dynamic Programming", slug: "minimum-white-tiles-after-covering-with-carpets" },
  { id: 2210, title: "Count Hills and Valleys in an Array", diff: "Easy", topics: "Array", slug: "count-hills-and-valleys-in-an-array" },
  { id: 2211, title: "Count Collisions on a Road", diff: "Medium", topics: "String, Stack, Simulation", slug: "count-collisions-on-a-road" },
  { id: 2212, title: "Maximum Points in an Archery Competition", diff: "Medium", topics: "Array, Backtracking, Bit Manipulation", slug: "maximum-points-in-an-archery-competition" },
  { id: 2213, title: "Longest Substring of One Repeating Character", diff: "Hard", topics: "String, Segment Tree", slug: "longest-substring-of-one-repeating-character" },
  { id: 2214, title: "Minimum Health to Beat Game", diff: "Medium", topics: "Array, Greedy", slug: "minimum-health-to-beat-game" },
  { id: 2215, title: "Find the Difference of Two Arrays", diff: "Easy", topics: "Array, Hash Table", slug: "find-the-difference-of-two-arrays" },
  { id: 2216, title: "Minimum Deletions to Make Array Beautiful", diff: "Medium", topics: "Array, Stack, Greedy", slug: "minimum-deletions-to-make-array-beautiful" },
  { id: 2217, title: "Find Palindrome With Fixed Length", diff: "Medium", topics: "Math", slug: "find-palindrome-with-fixed-length" },
  { id: 2218, title: "Maximum Value of K Coins From Piles", diff: "Hard", topics: "Array, Dynamic Programming, Prefix Sum", slug: "maximum-value-of-k-coins-from-piles" },
  { id: 2219, title: "Maximum Sum Score of Array", diff: "Medium", topics: "Array, Prefix Sum", slug: "maximum-sum-score-of-array" },
  { id: 2220, title: "Minimum Bit Flips to Convert Number", diff: "Easy", topics: "Bit Manipulation", slug: "minimum-bit-flips-to-convert-number" },
  { id: 2221, title: "Find Triangular Sum of an Array", diff: "Medium", topics: "Array, Math, Simulation", slug: "find-triangular-sum-of-an-array" },
  { id: 2222, title: "Number of Ways to Select Buildings", diff: "Medium", topics: "String, Dynamic Programming, Prefix Sum", slug: "number-of-ways-to-select-buildings" },
  { id: 2223, title: "Sum of Scores of Built Strings", diff: "Hard", topics: "String, Z Function, Rolling Hash", slug: "sum-of-scores-of-built-strings" },
  { id: 2224, title: "Minimum Number of Operations to Convert Time", diff: "Easy", topics: "Greedy, String", slug: "minimum-number-of-operations-to-convert-time" },
  { id: 2225, title: "Find Players With Zero or One Losses", diff: "Medium", topics: "Array, Hash Table, Sorting", slug: "find-players-with-zero-or-one-losses" },
  { id: 2226, title: "Maximum Candies Allocated to K Children", diff: "Medium", topics: "Array, Binary Search", slug: "maximum-candies-allocated-to-k-children" },
  { id: 2227, title: "Encrypt and Decrypt Strings", diff: "Hard", topics: "Hash Table, String, Design", slug: "encrypt-and-decrypt-strings" },
  { id: 2228, title: "Users With Two Purchases Within Seven Days", diff: "Easy", topics: "Database", slug: "users-with-two-purchases-within-seven-days" },
  { id: 2229, title: "Check if an Array Is Consecutive", diff: "Easy", topics: "Array, Hash Table", slug: "check-if-an-array-is-consecutive" },
  { id: 2230, title: "The Users That Are Eligible for Discount", diff: "Easy", topics: "Database", slug: "the-users-that-are-eligible-for-discount" },
  { id: 2231, title: "Largest Number After Digit Swaps by Parity", diff: "Easy", topics: "Array, Greedy, Sorting", slug: "largest-number-after-digit-swaps-by-parity" },
  { id: 2232, title: "Minimize Result by Adding Parentheses to Expression", diff: "Medium", topics: "String, Enumeration", slug: "minimize-result-by-adding-parentheses-to-expression" },
  { id: 2233, title: "Maximum Product After K Increments", diff: "Medium", topics: "Array, Greedy, Heap (Priority Queue)", slug: "maximum-product-after-k-increments" },
  { id: 2234, title: "Maximum Total Beauty of the Gardens", diff: "Hard", topics: "Array, Binary Search, Greedy, Sorting, Prefix Sum", slug: "maximum-total-beauty-of-the-gardens" },
  { id: 2235, title: "Add Two Integers", diff: "Easy", topics: "Math", slug: "add-two-integers" },
  { id: 2236, title: "Root Equals Sum of Children", diff: "Easy", topics: "Tree, Depth-First Search, Breadth-First Search, Binary Tree", slug: "root-equals-sum-of-children" },
  { id: 2237, title: "Count Positions on Street With Required Brightness", diff: "Medium", topics: "Array, Prefix Sum", slug: "count-positions-on-street-with-required-brightness" },
  { id: 2238, title: "Number of Times a Driver Was a Passenger", diff: "Medium", topics: "Database", slug: "number-of-times-a-driver-was-a-passenger" },
  { id: 2239, title: "Find Closest Number to Zero", diff: "Easy", topics: "Array", slug: "find-closest-number-to-zero" },
  { id: 2240, title: "Number of Ways to Buy Pens and Pencils", diff: "Medium", topics: "Math, Enumeration", slug: "number-of-ways-to-buy-pens-and-pencils" },
  { id: 2241, title: "Design an ATM Machine", diff: "Medium", topics: "Array, Greedy, Design", slug: "design-an-atm-machine" },
  { id: 2242, title: "Maximum Score of a Node Sequence", diff: "Hard", topics: "Graph, Greedy, Heap (Priority Queue)", slug: "maximum-score-of-a-node-sequence" },
  { id: 2243, title: "Calculate Digit Sum of a String", diff: "Easy", topics: "String, Simulation", slug: "calculate-digit-sum-of-a-string" },
  { id: 2244, title: "Minimum Rounds to Complete All Tasks", diff: "Medium", topics: "Array, Hash Table, Greedy, Counting", slug: "minimum-rounds-to-complete-all-tasks" },
  { id: 2245, title: "Maximum Trailing Zeros in a Cornered Path", diff: "Hard", topics: "Array, Matrix, Prefix Sum", slug: "maximum-trailing-zeros-in-a-cornered-path" },
  { id: 2246, title: "Longest Path With Different Adjacent Characters", diff: "Hard", topics: "Tree, Depth-First Search, Dynamic Programming", slug: "longest-path-with-different-adjacent-characters" },
  { id: 2247, title: "Maximum Cost of Trip With K Highways", diff: "Hard", topics: "Graph, Dynamic Programming, Bit Manipulation", slug: "maximum-cost-of-trip-with-k-highways" },
  { id: 2248, title: "Intersection of Multiple Arrays", diff: "Easy", topics: "Array, Hash Table, Counting", slug: "intersection-of-multiple-arrays" },
  { id: 2249, title: "Count Lattice Points Inside a Circle", diff: "Medium", topics: "Array, Geometry, Math", slug: "count-lattice-points-inside-a-circle" },
  { id: 2250, title: "Count Number of Rectangles Containing Each Point", diff: "Medium", topics: "Array, Binary Search, Sorting", slug: "count-number-of-rectangles-containing-each-point" }

);