window.rawProblems = window.rawProblems || [];

window.rawProblems.push(
  { id: 2501, title: "Longest Square Streak in an Array", diff: "Medium", topics: "Array, Hash Table, Binary Search, Dynamic Programming, Sorting", slug: "longest-square-streak-in-an-array" },
  { id: 2502, title: "Design Memory Allocator", diff: "Medium", topics: "Array, Hash Table, Design, Simulation", slug: "design-memory-allocator" },
  { id: 2503, title: "Maximum Number of Points From Grid Queries", diff: "Hard", topics: "Array, Breadth-First Search, Union Find, Matrix, Heap (Priority Queue), Sorting", slug: "maximum-number-of-points-from-grid-queries" },
  { id: 2504, title: "Concatenate the Name and the Profession", diff: "Easy", topics: "Database", slug: "concatenate-the-name-and-the-profession" },
  { id: 2505, title: "Bitwise OR of All Subsequence Sums", diff: "Hard", topics: "Array, Bit Manipulation", slug: "bitwise-or-of-all-subsequence-sums" },
  { id: 2506, title: "Count Pairs Of Similar Strings", diff: "Easy", topics: "Array, Hash Table, Bit Manipulation, String", slug: "count-pairs-of-similar-strings" },
  { id: 2507, title: "Smallest Value After Replacing With Sum of Prime Factors", diff: "Medium", topics: "Math, Number Theory, Simulation", slug: "smallest-value-after-replacing-with-sum-of-prime-factors" },
  { id: 2508, title: "Add Edges to Make Degrees of All Nodes Even", diff: "Hard", topics: "Graph, Greedy", slug: "add-edges-to-make-degrees-of-all-nodes-even" },
  { id: 2509, title: "Cycle Length Queries in a Tree", diff: "Hard", topics: "Tree, Bit Manipulation", slug: "cycle-length-queries-in-a-tree" },
  { id: 2510, title: "Check if There is a Path With Equal Number of 0's And 1's", diff: "Medium", topics: "Array, Dynamic Programming, Matrix", slug: "check-if-there-is-a-path-with-equal-number-of-0s-and-1s" },
  { id: 2511, title: "Maximum Enemy Forts That Can Be Captured", diff: "Easy", topics: "Array, Two Pointers", slug: "maximum-enemy-forts-that-can-be-captured" },
  { id: 2512, title: "Reward Top K Students", diff: "Medium", topics: "Array, Hash Table, String, Sorting, Heap (Priority Queue)", slug: "reward-top-k-students" },
  { id: 2513, title: "Minimize the Maximum of Two Arrays", diff: "Medium", topics: "Math, Binary Search, Number Theory", slug: "minimize-the-maximum-of-two-arrays" },
  { id: 2514, title: "Count Anagrams", diff: "Hard", topics: "Math, String, Combinatorics", slug: "count-anagrams" },
  { id: 2515, title: "Shortest Distance to Target String in a Circular Array", diff: "Easy", topics: "Array, String", slug: "shortest-distance-to-target-string-in-a-circular-array" },
  { id: 2516, title: "Take K of Each Character From Left and Right", diff: "Medium", topics: "Hash Table, String, Sliding Window", slug: "take-k-of-each-character-from-left-and-right" },
  { id: 2517, title: "Maximum Tastiness of Candy Basket", diff: "Medium", topics: "Array, Binary Search, Greedy, Sorting", slug: "maximum-tastiness-of-candy-basket" },
  { id: 2518, title: "Number of Great Partitions", diff: "Hard", topics: "Array, Dynamic Programming", slug: "number-of-great-partitions" },
  { id: 2519, title: "Count the Number of K-Big Indices", diff: "Hard", topics: "Array, Binary Indexed Tree, Segment Tree, Ordered Set", slug: "count-the-number-of-k-big-indices" },
  { id: 2520, title: "Count the Digits That Divide a Number", diff: "Easy", topics: "Math", slug: "count-the-digits-that-divide-a-number" },
  { id: 2521, title: "Distinct Prime Factors of Product of Array", diff: "Medium", topics: "Array, Math, Number Theory", slug: "distinct-prime-factors-of-product-of-array" },
  { id: 2522, title: "Partition String Into Substrings With Values at Most K", diff: "Medium", topics: "String, Greedy", slug: "partition-string-into-substrings-with-values-at-most-k" },
  { id: 2523, title: "Closest Prime Numbers in Range", diff: "Medium", topics: "Math, Number Theory", slug: "closest-prime-numbers-in-range" },
  { id: 2524, title: "Maximum Frequency Score of a Subarray", diff: "Hard", topics: "Array, Hash Table, Sliding Window, Ordered Set", slug: "maximum-frequency-score-of-a-subarray" },
  { id: 2525, title: "Categorize Box According to Criteria", diff: "Easy", topics: "Math", slug: "categorize-box-according-to-criteria" },
  { id: 2526, title: "Find Consecutive Integers from a Data Stream", diff: "Medium", topics: "Design, Queue, Data Stream", slug: "find-consecutive-integers-from-a-data-stream" },
  { id: 2527, title: "Find Xor-Beauty of Array", diff: "Medium", topics: "Array, Bit Manipulation", slug: "find-xor-beauty-of-array" },
  { id: 2528, title: "Maximize the Minimum Powered City", diff: "Hard", topics: "Array, Binary Search, Greedy, Prefix Sum", slug: "maximize-the-minimum-powered-city" },
  { id: 2529, title: "Maximum Count of Positive Integer and Negative Integer", diff: "Easy", topics: "Array, Binary Search, Counting", slug: "maximum-count-of-positive-integer-and-negative-integer" },
  { id: 2530, title: "Maximal Score After Applying K Operations", diff: "Medium", topics: "Array, Greedy, Heap (Priority Queue)", slug: "maximal-score-after-applying-k-operations" },
  { id: 2531, title: "Make Number of Distinct Characters Equal", diff: "Medium", topics: "Hash Table, String, Enumeration", slug: "make-number-of-distinct-characters-equal" },
  { id: 2532, title: "Time to Cross a Bridge", diff: "Hard", topics: "Simulation, Heap (Priority Queue)", slug: "time-to-cross-a-bridge" },
  { id: 2533, title: "Number of Good Binary Strings", diff: "Medium", topics: "Dynamic Programming", slug: "number-of-good-binary-strings" },
  { id: 2534, title: "Time Taken to Cross the Door", diff: "Hard", topics: "Array, Queue, Simulation", slug: "time-taken-to-cross-the-door" },
  { id: 2535, title: "Difference Between Element Sum and Digit Sum of an Array", diff: "Easy", topics: "Array, Math", slug: "difference-between-element-sum-and-digit-sum-of-an-array" },
  { id: 2536, title: "Increment Submatrices by One", diff: "Medium", topics: "Array, Matrix, Prefix Sum", slug: "increment-submatrices-by-one" },
  { id: 2537, title: "Count the Number of Good Subarrays", diff: "Medium", topics: "Array, Hash Table, Sliding Window", slug: "count-the-number-of-good-subarrays" },
  { id: 2538, title: "Difference Between Maximum and Minimum Price Sum", diff: "Hard", topics: "Tree, Depth-First Search, Dynamic Programming", slug: "difference-between-maximum-and-minimum-price-sum" },
  { id: 2539, title: "Count the Number of Good Subsequences", diff: "Hard", topics: "Hash Table, Math, Combinatorics, Counting", slug: "count-the-number-of-good-subsequences" },
  { id: 2540, title: "Minimum Common Value", diff: "Easy", topics: "Array, Hash Table, Two Pointers, Binary Search", slug: "minimum-common-value" },
  { id: 2541, title: "Minimum Operations to Make Array Equal II", diff: "Medium", topics: "Array, Math, Greedy", slug: "minimum-operations-to-make-array-equal-ii" },
  { id: 2542, title: "Maximum Subsequence Score", diff: "Medium", topics: "Array, Greedy, Heap (Priority Queue), Sorting", slug: "maximum-subsequence-score" },
  { id: 2543, title: "Check if Point Is Reachable", diff: "Hard", topics: "Math, Number Theory", slug: "check-if-point-is-reachable" },
  { id: 2544, title: "Alternating Digit Sum", diff: "Easy", topics: "Math", slug: "alternating-digit-sum" },
  { id: 2545, title: "Sort the Students by Their Kth Score", diff: "Medium", topics: "Array, Matrix, Sorting", slug: "sort-the-students-by-their-kth-score" },
  { id: 2546, title: "Apply Bitwise Operations to Make Strings Equal", diff: "Medium", topics: "String, Bit Manipulation", slug: "apply-bitwise-operations-to-make-strings-equal" },
  { id: 2547, title: "Minimum Cost to Split an Array", diff: "Hard", topics: "Array, Dynamic Programming", slug: "minimum-cost-to-split-an-array" },
  { id: 2548, title: "Maximum Price to Fill a Bag", diff: "Medium", topics: "Greedy, Sorting", slug: "maximum-price-to-fill-a-bag" },
  { id: 2549, title: "Count Distinct Numbers on Board", diff: "Easy", topics: "Math, Simulation", slug: "count-distinct-numbers-on-board" },
  { id: 2550, title: "Count Collisions of Monkeys on a Polygon", diff: "Medium", topics: "Math, Fast Exponentiation", slug: "count-collisions-of-monkeys-on-a-polygon" },
  { id: 2551, title: "Put Marbles in Bags", diff: "Hard", topics: "Array, Greedy, Sorting", slug: "put-marbles-in-bags" },
  { id: 2552, title: "Count Increasing Quadruplets", diff: "Hard", topics: "Array, Dynamic Programming, Binary Indexed Tree, Prefix Sum", slug: "count-increasing-quadruplets" },
  { id: 2553, title: "Separate the Digits in an Array", diff: "Easy", topics: "Array, Simulation", slug: "separate-the-digits-in-an-array" },
  { id: 2554, title: "Maximum Number of Integers to Choose From a Range I", diff: "Medium", topics: "Array, Greedy, Hash Table", slug: "maximum-number-of-integers-to-choose-from-a-range-i" },
  { id: 2555, title: "Maximize Win From Two Segments", diff: "Medium", topics: "Array, Binary Search, Sliding Window, Dynamic Programming", slug: "maximize-win-from-two-segments" },
  { id: 2556, title: "Disconnect Path in a Binary Matrix by at Most One Flip", diff: "Medium", topics: "Array, Depth-First Search, Matrix", slug: "disconnect-path-in-a-binary-matrix-by-at-most-one-flip" },
  { id: 2557, title: "Maximum Number of Integers to Choose From a Range II", diff: "Medium", topics: "Math, Greedy, Binary Search", slug: "maximum-number-of-integers-to-choose-from-a-range-ii" },
  { id: 2558, title: "Take Gifts From the Richest Pile", diff: "Easy", topics: "Array, Heap (Priority Queue), Simulation", slug: "take-gifts-from-the-richest-pile" },
  { id: 2559, title: "Count Vowel Strings in Ranges", diff: "Medium", topics: "Array, String, Prefix Sum", slug: "count-vowel-strings-in-ranges" },
  { id: 2560, title: "House Robber IV", diff: "Medium", topics: "Array, Binary Search, Greedy", slug: "house-robber-iv" },
  { id: 2561, title: "Rearranging Fruits", diff: "Hard", topics: "Array, Greedy, Hash Table, Sorting", slug: "rearranging-fruits" },
  { id: 2562, title: "Find the Array Concatenation Value", diff: "Easy", topics: "Array, Two Pointers, Simulation", slug: "find-the-array-concatenation-value" },
  { id: 2563, title: "Count the Number of Fair Pairs", diff: "Medium", topics: "Array, Two Pointers, Binary Search, Sorting", slug: "count-the-number-of-fair-pairs" },
  { id: 2564, title: "Substring XOR Queries", diff: "Medium", topics: "Hash Table, String, Bit Manipulation", slug: "substring-xor-queries" },
  { id: 2565, title: "Subsequence With the Minimum Score", diff: "Hard", topics: "String, Binary Search, Two Pointers", slug: "subsequence-with-the-minimum-score" },
  { id: 2566, title: "Maximum Difference by Remapping a Digit", diff: "Easy", topics: "Math, Greedy", slug: "maximum-difference-by-remapping-a-digit" },
  { id: 2567, title: "Minimum Score by Changing Two Elements", diff: "Medium", topics: "Array, Greedy, Sorting", slug: "minimum-score-by-changing-two-elements" },
  { id: 2568, title: "Minimum Impossible OR", diff: "Medium", topics: "Array, Bit Manipulation, Greedy", slug: "minimum-impossible-or" },
  { id: 2569, title: "Handling Sum Queries After Update", diff: "Hard", topics: "Array, Segment Tree, Lazy Propagation", slug: "handling-sum-queries-after-update" },
  { id: 2570, title: "Merge Two 2D Arrays by Summing Values", diff: "Easy", topics: "Array, Hash Table, Two Pointers", slug: "merge-two-2d-arrays-by-summing-values" },
  { id: 2571, title: "Minimum Operations to Reduce an Integer to 0", diff: "Medium", topics: "Bit Manipulation, Greedy", slug: "minimum-operations-to-reduce-an-integer-to-0" },
  { id: 2572, title: "Count the Number of Square-Free Subsets", diff: "Medium", topics: "Array, Dynamic Programming, Bit Manipulation, Math", slug: "count-the-number-of-square-free-subsets" },
  { id: 2573, title: "Find the String with LCP", diff: "Hard", topics: "String, Greedy, Matrix", slug: "find-the-string-with-lcp" },
  { id: 2574, title: "Left and Right Sum Differences", diff: "Easy", topics: "Array, Prefix Sum", slug: "left-and-right-sum-differences" },
  { id: 2575, title: "Find the Divisibility Array of a String", diff: "Medium", topics: "Array, Math, String", slug: "find-the-divisibility-array-of-a-string" },
  { id: 2576, title: "Find the Maximum Number of Marked Indices", diff: "Medium", topics: "Array, Two Pointers, Greedy, Sorting", slug: "find-the-maximum-number-of-marked-indices" },
  { id: 2577, title: "Minimum Time to Visit a Cell In a Grid", diff: "Hard", topics: "Array, Breadth-First Search, Graph, Heap (Priority Queue), Matrix", slug: "minimum-time-to-visit-a-cell-in-a-grid" },
  { id: 2578, title: "Split With Minimum Sum", diff: "Easy", topics: "Math, Greedy, Sorting", slug: "split-with-minimum-sum" },
  { id: 2579, title: "Count Total Number of Colored Cells", diff: "Medium", topics: "Math", slug: "count-total-number-of-colored-cells" },
  { id: 2580, title: "Count Ways to Group Overlapping Ranges", diff: "Medium", topics: "Array, Sorting", slug: "count-ways-to-group-overlapping-ranges" },
  { id: 2581, title: "Count Number of Possible Root Nodes", diff: "Hard", topics: "Tree, Depth-First Search, Dynamic Programming", slug: "count-number-of-possible-root-nodes" },
  { id: 2582, title: "Pass the Pillow", diff: "Easy", topics: "Math, Simulation", slug: "pass-the-pillow" },
  { id: 2583, title: "Kth Largest Sum in a Binary Tree", diff: "Medium", topics: "Tree, Breadth-First Search, Binary Tree, Heap (Priority Queue)", slug: "kth-largest-sum-in-a-binary-tree" },
  { id: 2584, title: "Split the Array to Make Coprime Products", diff: "Hard", topics: "Array, Hash Table, Math, Number Theory", slug: "split-the-array-to-make-coprime-products" },
  { id: 2585, title: "Number of Ways to Earn Points", diff: "Hard", topics: "Array, Dynamic Programming", slug: "number-of-ways-to-earn-points" },
  { id: 2586, title: "Count the Number of Vowel Strings in Range", diff: "Easy", topics: "Array, String", slug: "count-the-number-of-vowel-strings-in-range" },
  { id: 2587, title: "Rearrange Array to Maximize Prefix Score", diff: "Medium", topics: "Array, Greedy, Sorting, Prefix Sum", slug: "rearrange-array-to-maximize-prefix-score" },
  { id: 2588, title: "Count the Number of Beautiful Subarrays", diff: "Medium", topics: "Array, Hash Table, Bit Manipulation, Prefix Sum", slug: "count-the-number-of-beautiful-subarrays" },
  { id: 2589, title: "Minimum Time to Complete All Tasks", diff: "Hard", topics: "Array, Greedy, Prefix Sum, Segment Tree", slug: "minimum-time-to-complete-all-tasks" },
  { id: 2590, title: "Design a Todo List", diff: "Medium", topics: "Hash Table, Design, Ordered Set", slug: "design-a-todo-list" },
  { id: 2591, title: "Distribute Money to Maximum Children", diff: "Easy", topics: "Math, Greedy", slug: "distribute-money-to-maximum-children" },
  { id: 2592, title: "Maximize Greatness of an Array", diff: "Medium", topics: "Array, Greedy, Sorting", slug: "maximize-greatness-of-an-array" },
  { id: 2593, title: "Find Score of an Array After Marking All Elements", diff: "Medium", topics: "Array, Heap (Priority Queue), Sorting, Simulation", slug: "find-score-of-an-array-after-marking-all-elements" },
  { id: 2594, title: "Minimum Time to Repair Cars", diff: "Medium", topics: "Array, Binary Search", slug: "minimum-time-to-repair-cars" },
  { id: 2595, title: "Number of Even and Odd Bits", diff: "Easy", topics: "Bit Manipulation", slug: "number-of-even-and-odd-bits" },
  { id: 2596, title: "Check Knight Tour Configuration", diff: "Medium", topics: "Array, Matrix, Simulation", slug: "check-knight-tour-configuration" },
  { id: 2597, title: "The Number of Beautiful Subsets", diff: "Medium", topics: "Array, Backtracking, Dynamic Programming, Sorting", slug: "the-number-of-beautiful-subsets" },
  { id: 2598, title: "Smallest Missing Non-negative Integer After Operations", diff: "Medium", topics: "Array, Hash Table, Math", slug: "smallest-missing-non-negative-integer-after-operations" },
  { id: 2599, title: "Make the Prefix Sum Non-negative", diff: "Medium", topics: "Array, Greedy, Heap (Priority Queue), Prefix Sum", slug: "make-the-prefix-sum-non-negative" },
  { id: 2600, title: "K Items With the Maximum Sum", diff: "Easy", topics: "Math, Greedy", slug: "k-items-with-the-maximum-sum" },
  { id: 2601, title: "Prime Subtraction Operation", diff: "Medium", topics: "Array, Math, Binary Search, Greedy, Number Theory", slug: "prime-subtraction-operation" },
  { id: 2602, title: "Minimum Operations to Make All Array Elements Equal", diff: "Medium", topics: "Array, Binary Search, Prefix Sum, Sorting", slug: "minimum-operations-to-make-all-array-elements-equal" },
  { id: 2603, title: "Collect Coins in a Tree", diff: "Hard", topics: "Tree, Depth-First Search, Breadth-First Search, Topological Sort", slug: "collect-coins-in-a-tree" },
  { id: 2604, title: "Minimum Time to Eat All Grains", diff: "Hard", topics: "Array, Binary Search, Greedy", slug: "minimum-time-to-eat-all-grains" },
  { id: 2605, title: "Form Smallest Number From Two Digit Arrays", diff: "Easy", topics: "Array, Hash Table", slug: "form-smallest-number-from-two-digit-arrays" },
  { id: 2606, title: "Find the Substring With Maximum Cost", diff: "Medium", topics: "Array, Hash Table, String, Dynamic Programming", slug: "find-the-substring-with-maximum-cost" },
  { id: 2607, title: "Make K-Subarray Sums Equal", diff: "Medium", topics: "Array, Math, Greedy, Sorting, Number Theory", slug: "make-k-subarray-sums-equal" },
  { id: 2608, title: "Shortest Cycle in a Graph", diff: "Hard", topics: "Graph, Breadth-First Search", slug: "shortest-cycle-in-a-graph" },
  { id: 2609, title: "Find the Longest Balanced Substring of a Binary String", diff: "Easy", topics: "String", slug: "find-the-longest-balanced-substring-of-a-binary-string" },
  { id: 2610, title: "Convert an Array Into a 2D Array With Conditions", diff: "Medium", topics: "Array, Hash Table", slug: "convert-an-array-into-a-2d-array-with-conditions" },
  { id: 2611, title: "Mice and Cheese", diff: "Medium", topics: "Array, Greedy, Sorting, Heap (Priority Queue)", slug: "mice-and-cheese" },
  { id: 2612, title: "Minimum Reverse Operations", diff: "Hard", topics: "Array, Breadth-First Search, Ordered Set", slug: "minimum-reverse-operations" },
  { id: 2613, title: "Beautiful Pairs", diff: "Hard", topics: "Divide and Conquer, Geometry", slug: "beautiful-pairs" },
  { id: 2614, title: "Prime In Diagonal", diff: "Easy", topics: "Array, Matrix, Math, Number Theory", slug: "prime-in-diagonal" },
  { id: 2615, title: "Sum of Distances", diff: "Medium", topics: "Array, Hash Table, Prefix Sum", slug: "sum-of-distances" },
  { id: 2616, title: "Minimize the Maximum Difference of Pairs", diff: "Medium", topics: "Array, Binary Search, Dynamic Programming, Greedy, Sorting", slug: "minimize-the-maximum-difference-of-pairs" },
  { id: 2617, title: "Minimum Number of Visited Cells in a Grid", diff: "Hard", topics: "Array, Breadth-First Search, Matrix, Monotonic Stack, Ordered Set", slug: "minimum-number-of-visited-cells-in-a-grid" },
  { id: 2618, title: "Check if Object Instance of Class", diff: "Easy", topics: "JavaScript", slug: "check-if-object-instance-of-class" },
  { id: 2619, title: "Array Prototype Last", diff: "Easy", topics: "JavaScript", slug: "array-prototype-last" },
  { id: 2620, title: "Counter", diff: "Easy", topics: "JavaScript", slug: "counter" },
  { id: 2621, title: "Sleep", diff: "Easy", topics: "JavaScript", slug: "sleep" },
  { id: 2622, title: "Cache With Time Limit", diff: "Medium", topics: "JavaScript", slug: "cache-with-time-limit" },
  { id: 2623, title: "Memoize", diff: "Medium", topics: "JavaScript", slug: "memoize" },
  { id: 2624, title: "Snail Traversal", diff: "Medium", topics: "JavaScript", slug: "snail-traversal" },
  { id: 2625, title: "Flatten Deeply Nested Array", diff: "Medium", topics: "JavaScript", slug: "flatten-deeply-nested-array" },
  { id: 2626, title: "Array Reduce Transformation", diff: "Easy", topics: "JavaScript", slug: "array-reduce-transformation" },
  { id: 2627, title: "Debounce", diff: "Medium", topics: "JavaScript", slug: "debounce" },
  { id: 2628, title: "JSON Deep Equal", diff: "Medium", topics: "JavaScript", slug: "json-deep-equal" },
  { id: 2629, title: "Function Composition", diff: "Easy", topics: "JavaScript", slug: "function-composition" },
  { id: 2630, title: "Memoize II", diff: "Hard", topics: "JavaScript", slug: "memoize-ii" },
  { id: 2631, title: "Group By", diff: "Medium", topics: "JavaScript", slug: "group-by" },
  { id: 2632, title: "Curry", diff: "Medium", topics: "JavaScript", slug: "curry" },
  { id: 2633, title: "Convert Object to JSON String", diff: "Medium", topics: "JavaScript", slug: "convert-object-to-json-string" },
  { id: 2634, title: "Filter Elements from Array", diff: "Easy", topics: "JavaScript", slug: "filter-elements-from-array" },
  { id: 2635, title: "Apply Transform Over Each Element in Array", diff: "Easy", topics: "JavaScript", slug: "apply-transform-over-each-element-in-array" },
  { id: 2636, title: "Promise Pool", diff: "Medium", topics: "JavaScript", slug: "promise-pool" },
  { id: 2637, title: "Promise Time Limit", diff: "Medium", topics: "JavaScript", slug: "promise-time-limit" },
  { id: 2638, title: "Count the Number of K-Free Subsets", diff: "Medium", topics: "Array, Dynamic Programming, Hash Table", slug: "count-the-number-of-k-free-subsets" },
  { id: 2639, title: "Find the Width of Columns of a Grid", diff: "Easy", topics: "Array, Matrix", slug: "find-the-width-of-columns-of-a-grid" },
  { id: 2640, title: "Find the Score of All Prefixes of an Array", diff: "Medium", topics: "Array, Prefix Sum", slug: "find-the-score-of-all-prefixes-of-an-array" },
  { id: 2641, title: "Cousins in Binary Tree II", diff: "Medium", topics: "Tree, Depth-First Search, Breadth-First Search, Binary Tree", slug: "cousins-in-binary-tree-ii" },
  { id: 2642, title: "Design Graph With Shortest Path Calculator", diff: "Hard", topics: "Graph, Design, Shortest Path", slug: "design-graph-with-shortest-path-calculator" },
  { id: 2643, title: "Row With Maximum Ones", diff: "Easy", topics: "Array, Matrix", slug: "row-with-maximum-ones" },
  { id: 2644, title: "Find the Maximum Divisibility Score", diff: "Easy", topics: "Array, Math", slug: "find-the-maximum-divisibility-score" },
  { id: 2645, title: "Minimum Additions to Make Valid String", diff: "Medium", topics: "String, Greedy", slug: "minimum-additions-to-make-valid-string" },
  { id: 2646, title: "Minimize the Total Price of the Trips", diff: "Hard", topics: "Tree, Dynamic Programming, Depth-First Search", slug: "minimize-the-total-price-of-the-trips" },
  { id: 2647, title: "Color the Triangle Red", diff: "Hard", topics: "Math", slug: "color-the-triangle-red" },
  { id: 2648, title: "Generate Fibonacci Sequence", diff: "Easy", topics: "JavaScript", slug: "generate-fibonacci-sequence" },
  { id: 2649, title: "Nested Array Generator", diff: "Medium", topics: "JavaScript", slug: "nested-array-generator" },
  { id: 2650, title: "Design Cancellable Function", diff: "Hard", topics: "JavaScript", slug: "design-cancellable-function" },
  { id: 2651, title: "Calculate Delayed Arrival Time", diff: "Easy", topics: "Math", slug: "calculate-delayed-arrival-time" },
  { id: 2652, title: "Sum Multiples", diff: "Easy", topics: "Math, Enumeration", slug: "sum-multiples" },
  { id: 2653, title: "Sliding Subarray Beauty", diff: "Medium", topics: "Array, Binary Search, Counting Sort, Hash Table, Sliding Window", slug: "sliding-subarray-beauty" },
  { id: 2654, title: "Minimum Number of Operations to Make All Array Elements Equal to 1", diff: "Hard", topics: "Array, Math, Number Theory", slug: "minimum-number-of-operations-to-make-all-array-elements-equal-to-1" },
  { id: 2655, title: "Find Maximal Uncovered Ranges", diff: "Medium", topics: "Array, Sorting", slug: "find-maximal-uncovered-ranges" },
  { id: 2656, title: "Maximum Sum With Exactly K Elements", diff: "Easy", topics: "Math, Greedy", slug: "maximum-sum-with-exactly-k-elements" },
  { id: 2657, title: "Find the Prefix Common Array of Two Arrays", diff: "Medium", topics: "Array, Hash Table, Bit Manipulation, Prefix Sum", slug: "find-the-prefix-common-array-of-two-arrays" },
  { id: 2658, title: "Maximum Number of Fish in a Grid", diff: "Medium", topics: "Array, Depth-First Search, Breadth-First Search, Union Find, Matrix", slug: "maximum-number-of-fish-in-a-grid" },
  { id: 2659, title: "Make Array Empty", diff: "Hard", topics: "Array, Binary Indexed Tree, Segment Tree, Sorting", slug: "make-array-empty" },
  { id: 2660, title: "Determine the Winner of a Bowling Game", diff: "Easy", topics: "Array, Simulation", slug: "determine-the-winner-of-a-bowling-game" },
  { id: 2661, title: "First Completely Painted Row or Column", diff: "Medium", topics: "Array, Hash Table, Matrix", slug: "first-completely-painted-row-or-column" },
  { id: 2662, title: "Minimum Cost of a Path With Special Roads", diff: "Medium", topics: "Graph, Heap (Priority Queue), Shortest Path", slug: "minimum-cost-of-a-path-with-special-roads" },
  { id: 2663, title: "Lexicographically Smallest Beautiful String", diff: "Hard", topics: "String, Greedy", slug: "lexicographically-smallest-beautiful-string" },
  { id: 2664, title: "The Knight’s Tour", diff: "Medium", topics: "Array, Backtracking, Matrix", slug: "the-knights-tour" },
  { id: 2665, title: "Counter II", diff: "Easy", topics: "JavaScript", slug: "counter-ii" },
  { id: 2666, title: "Allow One Function Call", diff: "Easy", topics: "JavaScript", slug: "allow-one-function-call" },
  { id: 2667, title: "Create Hello World Function", diff: "Easy", topics: "JavaScript", slug: "create-hello-world-function" },
  { id: 2668, title: "Find Latest Salaries", diff: "Medium", topics: "Database", slug: "find-latest-salaries" },
  { id: 2669, title: "Count Artist Occurrences On Spotify Ranking List", diff: "Easy", topics: "Database", slug: "count-artist-occurrences-on-spotify-ranking-list" },
  { id: 2670, title: "Find the Distinct Difference Array", diff: "Easy", topics: "Array, Hash Table, Prefix Sum", slug: "find-the-distinct-difference-array" },
  { id: 2671, title: "Frequency Tracker", diff: "Medium", topics: "Hash Table, Design", slug: "frequency-tracker" },
  { id: 2672, title: "Number of Adjacent Elements With the Same Color", diff: "Medium", topics: "Array, Simulation", slug: "number-of-adjacent-elements-with-the-same-color" },
  { id: 2673, title: "Make Costs of Paths Equal in a Binary Tree", diff: "Medium", topics: "Tree, Greedy, Depth-First Search", slug: "make-costs-of-paths-equal-in-a-binary-tree" },
  { id: 2674, title: "Split a Circular Linked List", diff: "Medium", topics: "Linked List, Two Pointers", slug: "split-a-circular-linked-list" },
  { id: 2675, title: "Array of Objects to Matrix", diff: "Easy", topics: "JavaScript", slug: "array-of-objects-to-matrix" },
  { id: 2676, title: "Throttle", diff: "Medium", topics: "JavaScript", slug: "throttle" },
  { id: 2677, title: "Chunk Array", diff: "Easy", topics: "JavaScript", slug: "chunk-array" },
  { id: 2678, title: "Number of Senior Citizens", diff: "Easy", topics: "Array, String", slug: "number-of-senior-citizens" },
  { id: 2679, title: "Sum in a Matrix", diff: "Medium", topics: "Array, Matrix, Sorting", slug: "sum-in-a-matrix" },
  { id: 2680, title: "Maximum OR", diff: "Medium", topics: "Array, Bit Manipulation, Greedy, Prefix Sum", slug: "maximum-or" },
  { id: 2681, title: "Power of Heroes", diff: "Hard", topics: "Array, Math, Sorting, Prefix Sum", slug: "power-of-heroes" },
  { id: 2682, title: "Find the Losers of the Circular Game", diff: "Easy", topics: "Array, Hash Table, Simulation", slug: "find-the-losers-of-the-circular-game" },
  { id: 2683, title: "Neighboring Bitwise XOR", diff: "Medium", topics: "Array, Bit Manipulation", slug: "neighboring-bitwise-xor" },
  { id: 2684, title: "Maximum Number of Moves in a Grid", diff: "Medium", topics: "Array, Dynamic Programming, Matrix", slug: "maximum-number-of-moves-in-a-grid" },
  { id: 2685, title: "Count the Number of Complete Components", diff: "Medium", topics: "Depth-First Search, Breadth-First Search, Union Find, Graph", slug: "count-the-number-of-complete-components" },
  { id: 2686, title: "Immediate Food Delivery III", diff: "Medium", topics: "Database", slug: "immediate-food-delivery-iii" },
  { id: 2687, title: "Bikes Last Time Used", diff: "Easy", topics: "Database", slug: "bikes-last-time-used" },
  { id: 2688, title: "Find Active Users", diff: "Medium", topics: "Database", slug: "find-active-users" },
  { id: 2689, title: "Extract Kth Character From The Rope Tree", diff: "Easy", topics: "Tree, Depth-First Search", slug: "extract-kth-character-from-the-rope-tree" },
  { id: 2690, title: "Infinite Method Object", diff: "Medium", topics: "JavaScript", slug: "infinite-method-object" },
  { id: 2691, title: "Immutability Helper", diff: "Medium", topics: "JavaScript", slug: "immutability-helper" },
  { id: 2692, title: "Make Object Immutable", diff: "Hard", topics: "JavaScript", slug: "make-object-immutable" },
  { id: 2693, title: "Call Function with Custom Context", diff: "Medium", topics: "JavaScript", slug: "call-function-with-custom-context" },
  { id: 2694, title: "Event Emitter", diff: "Medium", topics: "JavaScript, Design", slug: "event-emitter" },
  { id: 2695, title: "Array Wrapper", diff: "Easy", topics: "JavaScript", slug: "array-wrapper" },
  { id: 2696, title: "Minimum String Length After Removing Substrings", diff: "Easy", topics: "String, Stack", slug: "minimum-string-length-after-removing-substrings" },
  { id: 2697, title: "Lexicographically Smallest Palindrome", diff: "Easy", topics: "Two Pointers, String, Greedy", slug: "lexicographically-smallest-palindrome" },
  { id: 2698, title: "Find the Punishment Number of an Integer", diff: "Medium", topics: "Math, Backtracking", slug: "find-the-punishment-number-of-an-integer" },
  { id: 2699, title: "Modify Graph Edge Weights", diff: "Hard", topics: "Graph, Shortest Path, Heap (Priority Queue)", slug: "modify-graph-edge-weights" },
  { id: 2700, title: "Differences Between Two Objects", diff: "Easy", topics: "JavaScript", slug: "differences-between-two-objects" },
  { id: 2701, title: "Consecutive Transactions with Increasing Amounts", diff: "Hard", topics: "Database", slug: "consecutive-transactions-with-increasing-amounts" },
  { id: 2702, title: "Minimum Operations to Make Numbers Non-positive", diff: "Hard", topics: "Array, Binary Search", slug: "minimum-operations-to-make-numbers-non-positive" },
  { id: 2703, title: "Return Length of Arguments Passed", diff: "Easy", topics: "JavaScript", slug: "return-length-of-arguments-passed" },
  { id: 2704, title: "To Be Or Not To Be", diff: "Easy", topics: "JavaScript", slug: "to-be-or-not-to-be" },
  { id: 2705, title: "Compact Object", diff: "Medium", topics: "JavaScript", slug: "compact-object" },
  { id: 2706, title: "Buy Two Chocolates", diff: "Easy", topics: "Array, Sorting", slug: "buy-two-chocolates" },
  { id: 2707, title: "Extra Characters in a String", diff: "Medium", topics: "String, Dynamic Programming, Trie", slug: "extra-characters-in-a-string" },
  { id: 2708, title: "Maximum Strength of a Group", diff: "Medium", topics: "Array, Dynamic Programming, Greedy", slug: "maximum-strength-of-a-group" },
  { id: 2709, title: "Greatest Common Divisor Traversal", diff: "Hard", topics: "Array, Union Find, Math, Number Theory", slug: "greatest-common-divisor-traversal" },
  { id: 2710, title: "Remove Trailing Zeros From a String", diff: "Easy", topics: "String", slug: "remove-trailing-zeros-from-a-string" },
  { id: 2711, title: "Difference of Number of Distinct Values on Diagonals", diff: "Medium", topics: "Array, Hash Table, Matrix", slug: "difference-of-number-of-distinct-values-on-diagonals" },
  { id: 2712, title: "Minimum Cost to Make All Characters Equal", diff: "Medium", topics: "String, Greedy", slug: "minimum-cost-to-make-all-characters-equal" },
  { id: 2713, title: "Maximum Strictly Increasing Cells in a Matrix", diff: "Hard", topics: "Array, Dynamic Programming, Graph, Matrix, Sorting", slug: "maximum-strictly-increasing-cells-in-a-matrix" },
  { id: 2714, title: "Find Shortest Path with K Hops", diff: "Hard", topics: "Graph, Shortest Path", slug: "find-shortest-path-with-k-hops" },
  { id: 2715, title: "Timeout Cancellation", diff: "Easy", topics: "JavaScript", slug: "timeout-cancellation" },
  { id: 2716, title: "Minimize String Length", diff: "Easy", topics: "Hash Table, String", slug: "minimize-string-length" },
  { id: 2717, title: "Semi-Ordered Permutation", diff: "Easy", topics: "Array, Simulation", slug: "semi-ordered-permutation" },
  { id: 2718, title: "Sum of Matrix After Queries", diff: "Medium", topics: "Array, Hash Table, Matrix, Simulation", slug: "sum-of-matrix-after-queries" },
  { id: 2719, title: "Count of Integers", diff: "Hard", topics: "Math, Dynamic Programming, Digit DP", slug: "count-of-integers" },
  { id: 2720, title: "Popularity Percentage", diff: "Hard", topics: "Database", slug: "popularity-percentage" },
  { id: 2721, title: "Execute Asynchronous Functions in Parallel", diff: "Medium", topics: "JavaScript", slug: "execute-asynchronous-functions-in-parallel" },
  { id: 2722, title: "Join Two Arrays by ID", diff: "Medium", topics: "JavaScript", slug: "join-two-arrays-by-id" },
  { id: 2723, title: "Add Two Promises", diff: "Easy", topics: "JavaScript", slug: "add-two-promises" },
  { id: 2724, title: "Sort By", diff: "Easy", topics: "JavaScript", slug: "sort-by" },
  { id: 2725, title: "Interval Cancellation", diff: "Easy", topics: "JavaScript", slug: "interval-cancellation" },
  { id: 2726, title: "Calculator with Method Chaining", diff: "Easy", topics: "JavaScript", slug: "calculator-with-method-chaining" },
  { id: 2727, title: "Is Object Empty", diff: "Easy", topics: "JavaScript", slug: "is-object-empty" },
  { id: 2728, title: "Count Houses in a Circular Street", diff: "Hard", topics: "Interactive", slug: "count-houses-in-a-circular-street" },
  { id: 2729, title: "Check if The Number is Fascinating", diff: "Easy", topics: "Math", slug: "check-if-the-number-is-fascinating" },
  { id: 2730, title: "Find the Longest Semi-Repetitive Substring", diff: "Medium", topics: "String, Sliding Window", slug: "find-the-longest-semi-repetitive-substring" },
  { id: 2731, title: "Movement of Robots", diff: "Medium", topics: "Array, Math, Sorting", slug: "movement-of-robots" },
  { id: 2732, title: "Find a Good Subset of the Matrix", diff: "Hard", topics: "Array, Bit Manipulation, Matrix", slug: "find-a-good-subset-of-the-matrix" },
  { id: 2733, title: "Neither Minimum nor Maximum", diff: "Easy", topics: "Array", slug: "neither-minimum-nor-maximum" },
  { id: 2734, title: "Lexicographically Smallest String After Substring Operation", diff: "Medium", topics: "String, Greedy", slug: "lexicographically-smallest-string-after-substring-operation" },
  { id: 2735, title: "Collecting Chocolates", diff: "Medium", topics: "Array, Dynamic Programming", slug: "collecting-chocolates" },
  { id: 2736, title: "Maximum Sum Queries", diff: "Hard", topics: "Array, Binary Indexed Tree, Segment Tree, Sorting", slug: "maximum-sum-queries" },
  { id: 2737, title: "Find the Closest Marked Node", diff: "Hard", topics: "Graph, Shortest Path", slug: "find-the-closest-marked-node" },
  { id: 2738, title: "Count Occurrences in Text", diff: "Easy", topics: "Database", slug: "count-occurrences-in-text" },
  { id: 2739, title: "Total Distance Traveled", diff: "Easy", topics: "Math, Simulation", slug: "total-distance-traveled" },
  { id: 2740, title: "Find the Value of the Partition", diff: "Medium", topics: "Array, Sorting", slug: "find-the-value-of-the-partition" },
  { id: 2741, title: "Special Permutations", diff: "Medium", topics: "Dynamic Programming, Bit Manipulation", slug: "special-permutations" },
  { id: 2742, title: "Painting the Walls", diff: "Hard", topics: "Array, Dynamic Programming", slug: "painting-the-walls" },
  { id: 2743, title: "Count Substrings Without Repeating Character", diff: "Medium", topics: "Hash Table, String, Sliding Window", slug: "count-substrings-without-repeating-character" },
  { id: 2744, title: "Find Maximum Number of String Pairs", diff: "Easy", topics: "Array, Hash Table, String", slug: "find-maximum-number-of-string-pairs" },
  { id: 2745, title: "Construct the Longest New String", diff: "Medium", topics: "Math, Greedy, Dynamic Programming", slug: "construct-the-longest-new-string" },
  { id: 2746, title: "Decremental String Concatenation", diff: "Medium", topics: "String, Dynamic Programming", slug: "decremental-string-concatenation" },
  { id: 2747, title: "Count Zero Request Servers", diff: "Medium", topics: "Array, Binary Search, Sliding Window, Sorting", slug: "count-zero-request-servers" },
  { id: 2748, title: "Number of Beautiful Pairs", diff: "Easy", topics: "Array, Math, Number Theory", slug: "number-of-beautiful-pairs" },
  { id: 2749, title: "Minimum Operations to Make the Integer Zero", diff: "Medium", topics: "Bit Manipulation, Greedy", slug: "minimum-operations-to-make-the-integer-zero" },
  { id: 2750, title: "Ways to Split Array Into Good Subarrays", diff: "Medium", topics: "Array, Math, Combinatorics", slug: "ways-to-split-array-into-good-subarrays" }

);