window.rawProblems = window.rawProblems || [];

window.rawProblems.push(
  { id: 1001, title: "Grid Illumination", diff: "Hard", topics: "Array, Hash Table", slug: "grid-illumination" },
  { id: 1002, title: "Find Common Characters", diff: "Easy", topics: "Array, Hash Table, String", slug: "find-common-characters" },
  { id: 1003, title: "Check If Word Is Valid After Substitutions", diff: "Medium", topics: "String, Stack", slug: "check-if-word-is-valid-after-substitutions" },
  { id: 1004, title: "Max Consecutive Ones III", diff: "Medium", topics: "Array, Binary Search, Sliding Window, Prefix Sum", slug: "max-consecutive-ones-iii" },
  { id: 1005, title: "Maximize Sum Of Array After K Negations", diff: "Easy", topics: "Array, Greedy, Sorting, Heap (Priority Queue)", slug: "maximize-sum-of-array-after-k-negations" },
  { id: 1006, title: "Clumsy Factorial", diff: "Medium", topics: "Math, Stack, Simulation", slug: "clumsy-factorial" },
  { id: 1007, title: "Minimum Domino Rotations For Equal Row", diff: "Medium", topics: "Array, Greedy", slug: "minimum-domino-rotations-for-equal-row" },
  { id: 1008, title: "Construct Binary Search Tree from Preorder Traversal", diff: "Medium", topics: "Array, Stack, Tree, Binary Search Tree, Monotonic Stack, Binary Tree", slug: "construct-binary-search-tree-from-preorder-traversal" },
  { id: 1009, title: "Complement of Base 10 Integer", diff: "Easy", topics: "Bit Manipulation", slug: "complement-of-base-10-integer" },
  { id: 1010, title: "Pairs of Songs With Total Durations Divisible by 60", diff: "Medium", topics: "Array, Hash Table, Counting", slug: "pairs-of-songs-with-total-durations-divisible-by-60" },
  { id: 1011, title: "Capacity To Ship Packages Within D Days", diff: "Medium", topics: "Array, Binary Search", slug: "capacity-to-ship-packages-within-d-days" },
  { id: 1012, title: "Numbers With Repeated Digits", diff: "Hard", topics: "Math, Dynamic Programming, Bit Manipulation, Digit DP", slug: "numbers-with-repeated-digits" },
  { id: 1013, title: "Partition Array Into Three Parts With Equal Sum", diff: "Easy", topics: "Array, Greedy", slug: "partition-array-into-three-parts-with-equal-sum" },
  { id: 1014, title: "Best Sightseeing Pair", diff: "Medium", topics: "Array, Dynamic Programming", slug: "best-sightseeing-pair" },
  { id: 1015, title: "Smallest Integer Divisible by K", diff: "Medium", topics: "Hash Table, Math, Number Theory", slug: "smallest-integer-divisible-by-k" },
  { id: 1016, title: "Binary String With Substrings Representing 1 To N", diff: "Medium", topics: "String", slug: "binary-string-with-substrings-representing-1-to-n" },
  { id: 1017, title: "Convert to Base -2", diff: "Medium", topics: "Math", slug: "convert-to-base--2" },
  { id: 1018, title: "Binary Prefix Divisible By 5", diff: "Easy", topics: "Array, Math", slug: "binary-prefix-divisible-by-5" },
  { id: 1019, title: "Next Greater Node In Linked List", diff: "Medium", topics: "Linked List, Stack, Monotonic Stack", slug: "next-greater-node-in-linked-list" },
  { id: 1020, title: "Number of Enclaves", diff: "Medium", topics: "Array, Depth-First Search, Breadth-First Search, Union Find, Matrix", slug: "number-of-enclaves" },
  { id: 1021, title: "Remove Outermost Parentheses", diff: "Easy", topics: "String", slug: "remove-outermost-parentheses" },
  { id: 1022, title: "Sum of Root To Leaf Binary Numbers", diff: "Easy", topics: "Tree, Depth-First Search, Binary Tree", slug: "sum-of-root-to-leaf-binary-numbers" },
  { id: 1023, title: "Camelcase Matching", diff: "Medium", topics: "Array, Two Pointers, String", slug: "camelcase-matching" },
  { id: 1024, title: "Video Stitching", diff: "Medium", topics: "Array, Dynamic Programming, Greedy", slug: "video-stitching" },
  { id: 1025, title: "Divisor Game", diff: "Easy", topics: "Math, Dynamic Programming, Game Theory", slug: "divisor-game" },
  { id: 1026, title: "Maximum Difference Between Node and Ancestor", diff: "Medium", topics: "Tree, Depth-First Search, Binary Tree", slug: "maximum-difference-between-node-and-ancestor" },
  { id: 1027, title: "Longest Arithmetic Subsequence", diff: "Medium", topics: "Array, Hash Table, Dynamic Programming", slug: "longest-arithmetic-subsequence" },
  { id: 1028, title: "Recover a Tree From Preorder Traversal", diff: "Hard", topics: "String, Tree, Depth-First Search, Binary Tree", slug: "recover-a-tree-from-preorder-traversal" },
  { id: 1029, title: "Two City Scheduling", diff: "Medium", topics: "Array, Greedy, Sorting", slug: "two-city-scheduling" },
  { id: 1030, title: "Matrix Cells in Distance Order", diff: "Easy", topics: "Array, Matrix, Sorting", slug: "matrix-cells-in-distance-order" },
  { id: 1031, title: "Maximum Sum of Two Non-Overlapping Subarrays", diff: "Medium", topics: "Array, Sliding Window, Prefix Sum", slug: "maximum-sum-of-two-non-overlapping-subarrays" },
  { id: 1032, title: "Stream of Characters", diff: "Hard", topics: "String, Design, Trie, Data Stream", slug: "stream-of-characters" },
  { id: 1033, title: "Moving Stones Until Consecutive", diff: "Medium", topics: "Math, Greedy", slug: "moving-stones-until-consecutive" },
  { id: 1034, title: "Coloring A Border", diff: "Medium", topics: "Array, Depth-First Search, Breadth-First Search, Matrix", slug: "coloring-a-border" },
  { id: 1035, title: "Uncrossed Lines", diff: "Medium", topics: "Array, Dynamic Programming", slug: "uncrossed-lines" },
  { id: 1036, title: "Escape a Large Maze", diff: "Hard", topics: "Array, Hash Table, Depth-First Search, Breadth-First Search", slug: "escape-a-large-maze" },
  { id: 1037, title: "Valid Boomerang", diff: "Easy", topics: "Array, Math, Geometry", slug: "valid-boomerang" },
  { id: 1038, title: "Binary Search Tree to Greater Sum Tree", diff: "Medium", topics: "Tree, Depth-First Search, Binary Search Tree, Binary Tree", slug: "binary-search-tree-to-greater-sum-tree" },
  { id: 1039, title: "Minimum Score Triangulation of Polygon", diff: "Medium", topics: "Array, Dynamic Programming", slug: "minimum-score-triangulation-of-polygon" },
  { id: 1040, title: "Moving Stones Until Consecutive II", diff: "Medium", topics: "Array, Greedy, Sliding Window, Sorting", slug: "moving-stones-until-consecutive-ii" },
  { id: 1041, title: "Robot Bounded In Circle", diff: "Medium", topics: "Math, String, Simulation", slug: "robot-bounded-in-circle" },
  { id: 1042, title: "Flower Planting With No Adjacent", diff: "Medium", topics: "Graph, Greedy", slug: "flower-planting-with-no-adjacent" },
  { id: 1043, title: "Partition Array for Maximum Sum", diff: "Medium", topics: "Array, Dynamic Programming", slug: "partition-array-for-maximum-sum" },
  { id: 1044, title: "Longest Duplicate Substring", diff: "Hard", topics: "String, Binary Search, Sliding Window, Rolling Hash, Suffix Array, Hash Function", slug: "longest-duplicate-substring" },
  { id: 1045, title: "Customers Who Bought All Products", diff: "Medium", topics: "Database", slug: "customers-who-bought-all-products" },
  { id: 1046, title: "Last Stone Weight", diff: "Easy", topics: "Array, Heap (Priority Queue)", slug: "last-stone-weight" },
  { id: 1047, title: "Remove All Adjacent Duplicates In String", diff: "Easy", topics: "String, Stack", slug: "remove-all-adjacent-duplicates-in-string" },
  { id: 1048, title: "Longest String Chain", diff: "Medium", topics: "Array, Hash Table, String, Dynamic Programming, Sorting", slug: "longest-string-chain" },
  { id: 1049, title: "Last Stone Weight II", diff: "Medium", topics: "Array, Dynamic Programming", slug: "last-stone-weight-ii" },
  { id: 1050, title: "Actors and Directors Who Cooperated At Least Three Times", diff: "Easy", topics: "Database", slug: "actors-and-directors-who-cooperated-at-least-three-times" },
  { id: 1051, title: "Height Checker", diff: "Easy", topics: "Array, Counting Sort, Sorting", slug: "height-checker" },
  { id: 1052, title: "Grumpy Bookstore Owner", diff: "Medium", topics: "Array, Sliding Window", slug: "grumpy-bookstore-owner" },
  { id: 1053, title: "Previous Permutation With One Swap", diff: "Medium", topics: "Array, Greedy", slug: "previous-permutation-with-one-swap" },
  { id: 1054, title: "Distant Barcodes", diff: "Medium", topics: "Array, Hash Table, Greedy, Sorting, Heap (Priority Queue)", slug: "distant-barcodes" },
  { id: 1055, title: "Shortest Way to Form String", diff: "Medium", topics: "Hash Table, String, Greedy", slug: "shortest-way-to-form-string" },
  { id: 1056, title: "Confusing Number", diff: "Easy", topics: "Math", slug: "confusing-number" },
  { id: 1057, title: "Campus Bikes", diff: "Medium", topics: "Array, Greedy, Sorting, Heap (Priority Queue)", slug: "campus-bikes" },
  { id: 1058, title: "Minimize Rounding Error to Meet Target", diff: "Hard", topics: "Array, Math, Greedy", slug: "minimize-rounding-error-to-meet-target" },
  { id: 1059, title: "All Paths from Source Lead to Destination", diff: "Medium", topics: "Depth-First Search, Breadth-First Search, Graph", slug: "all-paths-from-source-lead-to-destination" },
  { id: 1060, title: "Missing Element in Sorted Array", diff: "Medium", topics: "Array, Binary Search", slug: "missing-element-in-sorted-array" },
  { id: 1061, title: "Lexicographically Smallest Equivalent String", diff: "Medium", topics: "String, Union Find", slug: "lexicographically-smallest-equivalent-string" },
  { id: 1062, title: "Longest Repeating Substring", diff: "Medium", topics: "String, Binary Search, Dynamic Programming, Rolling Hash, Hash Function", slug: "longest-repeating-substring" },
  { id: 1063, title: "Number of Valid Subarrays", diff: "Hard", topics: "Array, Stack, Monotonic Stack", slug: "number-of-valid-subarrays" },
  { id: 1064, title: "Fixed Point", diff: "Easy", topics: "Array, Binary Search", slug: "fixed-point" },
  { id: 1065, title: "Index Pairs of a String", diff: "Easy", topics: "Array, String, Trie", slug: "index-pairs-of-a-string" },
  { id: 1066, title: "Campus Bikes II", diff: "Medium", topics: "Array, Dynamic Programming, Bit Manipulation, Backtracking", slug: "campus-bikes-ii" },
  { id: 1067, title: "Digit Count in Range", diff: "Hard", topics: "Math, Dynamic Programming, Digit DP", slug: "digit-count-in-range" },
  { id: 1068, title: "Product Sales Analysis I", diff: "Easy", topics: "Database", slug: "product-sales-analysis-i" },
  { id: 1069, title: "Product Sales Analysis II", diff: "Easy", topics: "Database", slug: "product-sales-analysis-ii" },
  { id: 1070, title: "Product Sales Analysis III", diff: "Medium", topics: "Database", slug: "product-sales-analysis-iii" },
  { id: 1071, title: "Greatest Common Divisor of Strings", diff: "Easy", topics: "Math, String", slug: "greatest-common-divisor-of-strings" },
  { id: 1072, title: "Flip Columns For Maximum Number of Equal Rows", diff: "Medium", topics: "Array, Hash Table, Matrix", slug: "flip-columns-for-maximum-number-of-equal-rows" },
  { id: 1073, title: "Adding Two Negabinary Numbers", diff: "Medium", topics: "Array, Math", slug: "adding-two-negabinary-numbers" },
  { id: 1074, title: "Number of Submatrices That Sum to Target", diff: "Hard", topics: "Array, Hash Table, Matrix, Prefix Sum", slug: "number-of-submatrices-that-sum-to-target" },
  { id: 1075, title: "Project Employees I", diff: "Easy", topics: "Database", slug: "project-employees-i" },
  { id: 1076, title: "Project Employees II", diff: "Easy", topics: "Database", slug: "project-employees-ii" },
  { id: 1077, title: "Project Employees III", diff: "Medium", topics: "Database", slug: "project-employees-iii" },
  { id: 1078, title: "Occurrences After Bigram", diff: "Easy", topics: "String", slug: "occurrences-after-bigram" },
  { id: 1079, title: "Letter Tile Possibilities", diff: "Medium", topics: "Hash Table, String, Backtracking, Counting", slug: "letter-tile-possibilities" },
  { id: 1080, title: "Insufficient Nodes in Root to Leaf Paths", diff: "Medium", topics: "Tree, Depth-First Search, Binary Tree", slug: "insufficient-nodes-in-root-to-leaf-paths" },
  { id: 1081, title: "Smallest Subsequence of Distinct Characters", diff: "Medium", topics: "String, Stack, Greedy, Monotonic Stack", slug: "smallest-subsequence-of-distinct-characters" },
  { id: 1082, title: "Sales Analysis I", diff: "Easy", topics: "Database", slug: "sales-analysis-i" },
  { id: 1083, title: "Sales Analysis II", diff: "Easy", topics: "Database", slug: "sales-analysis-ii" },
  { id: 1084, title: "Sales Analysis III", diff: "Easy", topics: "Database", slug: "sales-analysis-iii" },
  { id: 1085, title: "Sum of Digits in the Minimum Number", diff: "Easy", topics: "Array, Math", slug: "sum-of-digits-in-the-minimum-number" },
  { id: 1086, title: "High Five", diff: "Easy", topics: "Array, Hash Table, Sorting, Heap (Priority Queue)", slug: "high-five" },
  { id: 1087, title: "Brace Expansion", diff: "Medium", topics: "String, Backtracking", slug: "brace-expansion" },
  { id: 1088, title: "Confusing Number II", diff: "Hard", topics: "Math, Backtracking", slug: "confusing-number-ii" },
  { id: 1089, title: "Duplicate Zeros", diff: "Easy", topics: "Array, Two Pointers", slug: "duplicate-zeros" },
  { id: 1090, title: "Largest Values From Labels", diff: "Medium", topics: "Array, Greedy, Sorting, Heap (Priority Queue)", slug: "largest-values-from-labels" },
  { id: 1091, title: "Shortest Path in Binary Matrix", diff: "Medium", topics: "Array, Breadth-First Search, Matrix", slug: "shortest-path-in-binary-matrix" },
  { id: 1092, title: "Shortest Common Supersequence", diff: "Hard", topics: "String, Dynamic Programming", slug: "shortest-common-supersequence" },
  { id: 1093, title: "Statistics from a Large Sample", diff: "Medium", topics: "Math, Probability and Statistics", slug: "statistics-from-a-large-sample" },
  { id: 1094, title: "Car Pooling", diff: "Medium", topics: "Array, Prefix Sum, Sorting, Heap (Priority Queue)", slug: "car-pooling" },
  { id: 1095, title: "Find in Mountain Array", diff: "Hard", topics: "Array, Binary Search, Interactive", slug: "find-in-mountain-array" },
  { id: 1096, title: "Brace Expansion II", diff: "Hard", topics: "String, Stack, Recursion", slug: "brace-expansion-ii" },
  { id: 1097, title: "Game Play Analysis V", diff: "Hard", topics: "Database", slug: "game-play-analysis-v" },
  { id: 1098, title: "Unpopular Books", diff: "Medium", topics: "Database", slug: "unpopular-books" },
  { id: 1099, title: "Two Sum Less Than K", diff: "Easy", topics: "Array, Two Pointers, Binary Search, Sorting", slug: "two-sum-less-than-k" },
  { id: 1100, title: "Find K-Length Substrings With No Repeated Characters", diff: "Medium", topics: "Hash Table, String, Sliding Window", slug: "find-k-length-substrings-with-no-repeated-characters" },
  { id: 1101, title: "The Earliest Moment When Everyone Become Friends", diff: "Medium", topics: "Array, Union Find, Sorting", slug: "the-earliest-moment-when-everyone-become-friends" },
  { id: 1102, title: "Path With Maximum Minimum Value", diff: "Medium", topics: "Array, Binary Search, Depth-First Search, Breadth-First Search, Union Find, Heap (Priority Queue), Matrix", slug: "path-with-maximum-minimum-value" },
  { id: 1103, title: "Distribute Candies to People", diff: "Easy", topics: "Math, Simulation", slug: "distribute-candies-to-people" },
  { id: 1104, title: "Path In Zigzag Labelled Binary Tree", diff: "Medium", topics: "Math, Tree", slug: "path-in-zigzag-labelled-binary-tree" },
  { id: 1105, title: "Filling Bookcase Shelves", diff: "Medium", topics: "Array, Dynamic Programming", slug: "filling-bookcase-shelves" },
  { id: 1106, title: "Parsing A Boolean Expression", diff: "Hard", topics: "String, Stack, Recursion", slug: "parsing-a-boolean-expression" },
  { id: 1107, title: "New Users Daily Count", diff: "Medium", topics: "Database", slug: "new-users-daily-count" },
  { id: 1108, title: "Defanging an IP Address", diff: "Easy", topics: "String", slug: "defanging-an-ip-address" },
  { id: 1109, title: "Corporate Flight Bookings", diff: "Medium", topics: "Array, Prefix Sum", slug: "corporate-flight-bookings" },
  { id: 1110, title: "Delete Nodes And Return Forest", diff: "Medium", topics: "Array, Hash Table, Tree, Depth-First Search, Binary Tree", slug: "delete-nodes-and-return-forest" },
  { id: 1111, title: "Maximum Nesting Depth of Two Valid Parentheses Strings", diff: "Medium", topics: "String, Stack, Greedy", slug: "maximum-nesting-depth-of-two-valid-parentheses-strings" },
  { id: 1112, title: "Highest Grade For Each Student", diff: "Medium", topics: "Database", slug: "highest-grade-for-each-student" },
  { id: 1113, title: "Reported Posts", diff: "Easy", topics: "Database", slug: "reported-posts" },
  { id: 1114, title: "Print in Order", diff: "Easy", topics: "Concurrency", slug: "print-in-order" },
  { id: 1115, title: "Print FooBar Alternately", diff: "Medium", topics: "Concurrency", slug: "print-foobar-alternately" },
  { id: 1116, title: "Print Zero Even Odd", diff: "Medium", topics: "Concurrency", slug: "print-zero-even-odd" },
  { id: 1117, title: "Building H2O", diff: "Medium", topics: "Concurrency", slug: "building-h2o" },
  { id: 1118, title: "Number of Days in a Month", diff: "Easy", topics: "Math", slug: "number-of-days-in-a-month" },
  { id: 1119, title: "Remove Vowels from a String", diff: "Easy", topics: "String", slug: "remove-vowels-from-a-string" },
  { id: 1120, title: "Maximum Average Subtree", diff: "Medium", topics: "Tree, Depth-First Search, Binary Tree", slug: "maximum-average-subtree" },
  { id: 1121, title: "Divide Array Into Increasing Sequences", diff: "Hard", topics: "Greedy", slug: "divide-array-into-increasing-sequences" },
  { id: 1122, title: "Relative Sort Array", diff: "Easy", topics: "Array, Hash Table, Sorting, Counting Sort", slug: "relative-sort-array" },
  { id: 1123, title: "Lowest Common Ancestor of Deepest Leaves", diff: "Medium", topics: "Tree, Depth-First Search, Binary Tree", slug: "lowest-common-ancestor-of-deepest-leaves" },
  { id: 1124, title: "Longest Well-Performing Interval", diff: "Medium", topics: "Array, Hash Table, Stack, Monotonic Stack, Prefix Sum", slug: "longest-well-performing-interval" },
  { id: 1125, title: "Smallest Sufficient Team", diff: "Hard", topics: "Array, Dynamic Programming, Bit Manipulation", slug: "smallest-sufficient-team" },
  { id: 1126, title: "Active Businesses", diff: "Medium", topics: "Database", slug: "active-businesses" },
  { id: 1127, title: "User Purchase Platform", diff: "Hard", topics: "Database", slug: "user-purchase-platform" },
  { id: 1128, title: "Number of Equivalent Domino Pairs", diff: "Easy", topics: "Array, Hash Table, Counting", slug: "number-of-equivalent-domino-pairs" },
  { id: 1129, title: "Shortest Path with Alternating Colors", diff: "Medium", topics: "Breadth-First Search, Graph", slug: "shortest-path-with-alternating-colors" },
  { id: 1130, title: "Minimum Cost Tree From Leaf Values", diff: "Medium", topics: "Array, Dynamic Programming, Stack, Greedy, Monotonic Stack", slug: "minimum-cost-tree-from-leaf-values" },
  { id: 1131, title: "Maximum of Absolute Value Expression", diff: "Medium", topics: "Array, Math", slug: "maximum-of-absolute-value-expression" },
  { id: 1132, title: "Reported Posts II", diff: "Medium", topics: "Database", slug: "reported-posts-ii" },
  { id: 1133, title: "Largest Unique Number", diff: "Easy", topics: "Array, Hash Table, Sorting", slug: "largest-unique-number" },
  { id: 1134, title: "Armstrong Number", diff: "Easy", topics: "Math", slug: "armstrong-number" },
  { id: 1135, title: "Connecting Cities With Minimum Cost", diff: "Medium", topics: "Union Find, Graph, Minimum Spanning Tree", slug: "connecting-cities-with-minimum-cost" },
  { id: 1136, title: "Parallel Courses", diff: "Medium", topics: "Breadth-First Search, Graph, Topological Sort", slug: "parallel-courses" },
  { id: 1137, title: "N-th Tribonacci Number", diff: "Easy", topics: "Math, Dynamic Programming, Memoization", slug: "n-th-tribonacci-number" },
  { id: 1138, title: "Alphabet Board Path", diff: "Medium", topics: "Hash Table, String, Simulation", slug: "alphabet-board-path" },
  { id: 1139, title: "Largest 1-Bordered Square", diff: "Medium", topics: "Array, Dynamic Programming, Matrix", slug: "largest-1-bordered-square" },
  { id: 1140, title: "Stone Game II", diff: "Medium", topics: "Array, Math, Dynamic Programming, Game Theory", slug: "stone-game-ii" },
  { id: 1141, title: "User Activity for the Past 30 Days I", diff: "Easy", topics: "Database", slug: "user-activity-for-the-past-30-days-i" },
  { id: 1142, title: "User Activity for the Past 30 Days II", diff: "Easy", topics: "Database", slug: "user-activity-for-the-past-30-days-ii" },
  { id: 1143, title: "Longest Common Subsequence", diff: "Medium", topics: "String, Dynamic Programming", slug: "longest-common-subsequence" },
  { id: 1144, title: "Decrease Elements To Make Array Zigzag", diff: "Medium", topics: "Array, Greedy", slug: "decrease-elements-to-make-array-zigzag" },
  { id: 1145, title: "Binary Tree Coloring Game", diff: "Medium", topics: "Tree, Depth-First Search, Binary Tree", slug: "binary-tree-coloring-game" },
  { id: 1146, title: "Snapshot Array", diff: "Medium", topics: "Array, Hash Table, Binary Search, Design", slug: "snapshot-array" },
  { id: 1147, title: "Longest Chunked Palindrome Decomposition", diff: "Hard", topics: "Two Pointers, String, Greedy", slug: "longest-chunked-palindrome-decomposition" },
  { id: 1148, title: "Article Views I", diff: "Easy", topics: "Database", slug: "article-views-i" },
  { id: 1149, title: "Article Views II", diff: "Medium", topics: "Database", slug: "article-views-ii" },
  { id: 1150, title: "Check If a Number Is Majority Element in a Sorted Array", diff: "Easy", topics: "Array, Binary Search", slug: "check-if-a-number-is-majority-element-in-a-sorted-array" },
  { id: 1151, title: "Minimum Swaps to Group All 1's Together", diff: "Medium", topics: "Array, Sliding Window", slug: "minimum-swaps-to-group-all-1s-together" },
  { id: 1152, title: "Analyze User Website Visit Pattern", diff: "Medium", topics: "Array, Hash Table, String, Sorting", slug: "analyze-user-website-visit-pattern" },
  { id: 1153, title: "String Transforms Into Another String", diff: "Hard", topics: "Hash Table, String", slug: "string-transforms-into-another-string" },
  { id: 1154, title: "Day of the Year", diff: "Easy", topics: "Math, String", slug: "day-of-the-year" },
  { id: 1155, title: "Number of Dice Rolls With Target Sum", diff: "Medium", topics: "Dynamic Programming", slug: "number-of-dice-rolls-with-target-sum" },
  { id: 1156, title: "Swap For Longest Repeated Character Substring", diff: "Medium", topics: "Hash Table, String, Sliding Window", slug: "swap-for-longest-repeated-character-substring" },
  { id: 1157, title: "Online Majority Element In Subarray", diff: "Hard", topics: "Array, Binary Search, Design, Segment Tree, Randomized", slug: "online-majority-element-in-subarray" },
  { id: 1158, title: "Market Analysis I", diff: "Medium", topics: "Database", slug: "market-analysis-i" },
  { id: 1159, title: "Market Analysis II", diff: "Hard", topics: "Database", slug: "market-analysis-ii" },
  { id: 1160, title: "Find Words That Can Be Formed by Characters", diff: "Easy", topics: "Array, Hash Table, String, Counting", slug: "find-words-that-can-be-formed-by-characters" },
  { id: 1161, title: "Maximum Level Sum of a Binary Tree", diff: "Medium", topics: "Tree, Depth-First Search, Breadth-First Search, Binary Tree", slug: "maximum-level-sum-of-a-binary-tree" },
  { id: 1162, title: "As Far from Land as Possible", diff: "Medium", topics: "Array, Breadth-First Search, Dynamic Programming, Matrix", slug: "as-far-from-land-as-possible" },
  { id: 1163, title: "Last Substring in Lexicographical Order", diff: "Hard", topics: "Two Pointers, String", slug: "last-substring-in-lexicographical-order" },
  { id: 1164, title: "Product Price at a Given Date", diff: "Medium", topics: "Database", slug: "product-price-at-a-given-date" },
  { id: 1165, title: "Single-Row Keyboard", diff: "Easy", topics: "Hash Table, String", slug: "single-row-keyboard" },
  { id: 1166, title: "Design File System", diff: "Medium", topics: "Hash Table, String, Design, Trie", slug: "design-file-system" },
  { id: 1167, title: "Minimum Cost to Connect Sticks", diff: "Medium", topics: "Array, Greedy, Heap (Priority Queue)", slug: "minimum-cost-to-connect-sticks" },
  { id: 1168, title: "Optimize Water Distribution in a Village", diff: "Hard", topics: "Union Find, Graph, Minimum Spanning Tree", slug: "optimize-water-distribution-in-a-village" },
  { id: 1169, title: "Invalid Transactions", diff: "Medium", topics: "Array, Hash Table, String, Sorting", slug: "invalid-transactions" },
  { id: 1170, title: "Compare Strings by Frequency of the Smallest Character", diff: "Medium", topics: "Array, String, Binary Search, Sorting", slug: "compare-strings-by-frequency-of-the-smallest-character" },
  { id: 1171, title: "Remove Zero Sum Consecutive Nodes from Linked List", diff: "Medium", topics: "Hash Table, Linked List, Prefix Sum", slug: "remove-zero-sum-consecutive-nodes-from-linked-list" },
  { id: 1172, title: "Dinner Plate Stacks", diff: "Hard", topics: "Stack, Design, Heap (Priority Queue), Ordered Set", slug: "dinner-plate-stacks" },
  { id: 1173, title: "Immediate Food Delivery I", diff: "Easy", topics: "Database", slug: "immediate-food-delivery-i" },
  { id: 1174, title: "Immediate Food Delivery II", diff: "Medium", topics: "Database", slug: "immediate-food-delivery-ii" },
  { id: 1175, title: "Prime Arrangements", diff: "Easy", topics: "Math", slug: "prime-arrangements" },
  { id: 1176, title: "Diet Plan Performance", diff: "Easy", topics: "Array, Sliding Window", slug: "diet-plan-performance" },
  { id: 1177, title: "Can Make Palindrome from Substring", diff: "Medium", topics: "Array, Hash Table, String, Prefix Sum, Bit Manipulation", slug: "can-make-palindrome-from-substring" },
  { id: 1178, title: "Number of Valid Words for Each Puzzle", diff: "Hard", topics: "Array, Hash Table, String, Bit Manipulation, Trie", slug: "number-of-valid-words-for-each-puzzle" },
  { id: 1179, title: "Reformat Department Table", diff: "Easy", topics: "Database", slug: "reformat-department-table" },
  { id: 1180, title: "Count Substrings with Only One Distinct Letter", diff: "Easy", topics: "String", slug: "count-substrings-with-only-one-distinct-letter" },
  { id: 1181, title: "Before and After Puzzle", diff: "Medium", topics: "Array, Hash Table, String", slug: "before-and-after-puzzle" },
  { id: 1182, title: "Shortest Distance to Target Color", diff: "Medium", topics: "Array, Binary Search, Dynamic Programming", slug: "shortest-distance-to-target-color" },
  { id: 1183, title: "Maximum Number of Ones", diff: "Hard", topics: "Greedy, Math", slug: "maximum-number-of-ones" },
  { id: 1184, title: "Distance Between Bus Stops", diff: "Easy", topics: "Array", slug: "distance-between-bus-stops" },
  { id: 1185, title: "Day of the Week", diff: "Easy", topics: "Math", slug: "day-of-the-week" },
  { id: 1186, title: "Maximum Subarray Sum with One Deletion", diff: "Medium", topics: "Array, Dynamic Programming", slug: "maximum-subarray-sum-with-one-deletion" },
  { id: 1187, title: "Make Array Strictly Increasing", diff: "Hard", topics: "Array, Binary Search, Dynamic Programming", slug: "make-array-strictly-increasing" },
  { id: 1188, title: "Design Bounded Blocking Queue", diff: "Medium", topics: "Concurrency", slug: "design-bounded-blocking-queue" },
  { id: 1189, title: "Maximum Number of Balloons", diff: "Easy", topics: "Hash Table, String, Counting", slug: "maximum-number-of-balloons" },
  { id: 1190, title: "Reverse Substrings Between Each Pair of Parentheses", diff: "Medium", topics: "String, Stack", slug: "reverse-substrings-between-each-pair-of-parentheses" },
  { id: 1191, title: "K-Concatenation Maximum Sum", diff: "Medium", topics: "Array, Dynamic Programming", slug: "k-concatenation-maximum-sum" },
  { id: 1192, title: "Critical Connections in a Network", diff: "Hard", topics: "Depth-First Search, Graph, Biconnected Component", slug: "critical-connections-in-a-network" },
  { id: 1193, title: "Monthly Transactions I", diff: "Medium", topics: "Database", slug: "monthly-transactions-i" },
  { id: 1194, title: "Tournament Winners", diff: "Hard", topics: "Database", slug: "tournament-winners" },
  { id: 1195, title: "Fizz Buzz Multithreaded", diff: "Medium", topics: "Concurrency", slug: "fizz-buzz-multithreaded" },
  { id: 1196, title: "How Many Apples Can You Put into the Basket", diff: "Easy", topics: "Array, Greedy, Sorting", slug: "how-many-apples-can-you-put-into-the-basket" },
  { id: 1197, title: "Minimum Knight Moves", diff: "Medium", topics: "Breadth-First Search", slug: "minimum-knight-moves" },
  { id: 1198, title: "Find Smallest Common Element in All Rows", diff: "Medium", topics: "Array, Binary Search, Matrix", slug: "find-smallest-common-element-in-all-rows" },
  { id: 1199, title: "Minimum Time to Build Blocks", diff: "Hard", topics: "Array, Dynamic Programming, Greedy, Heap (Priority Queue)", slug: "minimum-time-to-build-blocks" },
  { id: 1200, title: "Minimum Absolute Difference", diff: "Easy", topics: "Array, Sorting", slug: "minimum-absolute-difference" },
  { id: 1201, title: "Ugly Number III", diff: "Medium", topics: "Math, Binary Search, Number Theory", slug: "ugly-number-iii" },
  { id: 1202, title: "Smallest String With Swaps", diff: "Medium", topics: "Array, Hash Table, String, Union Find, Graph, Sorting", slug: "smallest-string-with-swaps" },
  { id: 1203, title: "Sort Items by Groups Respecting Dependencies", diff: "Hard", topics: "Depth-First Search, Breadth-First Search, Graph, Topological Sort", slug: "sort-items-by-groups-respecting-dependencies" },
  { id: 1204, title: "Last Person to Fit in the Bus", diff: "Medium", topics: "Database", slug: "last-person-to-fit-in-the-bus" },
  { id: 1205, title: "Monthly Transactions II", diff: "Medium", topics: "Database", slug: "monthly-transactions-ii" },
  { id: 1206, title: "Design Skiplist", diff: "Hard", topics: "Linked List, Design, Randomized", slug: "design-skiplist" },
  { id: 1207, title: "Unique Number of Occurrences", diff: "Easy", topics: "Array, Hash Table", slug: "unique-number-of-occurrences" },
  { id: 1208, title: "Get Equal Substrings Within Budget", diff: "Medium", topics: "String, Sliding Window, Prefix Sum", slug: "get-equal-substrings-within-budget" },
  { id: 1209, title: "Remove All Adjacent Duplicates in String II", diff: "Medium", topics: "String, Stack", slug: "remove-all-adjacent-duplicates-in-string-ii" },
  { id: 1210, title: "Minimum Moves to Reach Target with Rotations", diff: "Hard", topics: "Array, Breadth-First Search, Matrix", slug: "minimum-moves-to-reach-target-with-rotations" },
  { id: 1211, title: "Queries Quality and Percentage", diff: "Easy", topics: "Database", slug: "queries-quality-and-percentage" },
  { id: 1212, title: "Team Scores in Football Tournament", diff: "Medium", topics: "Database", slug: "team-scores-in-football-tournament" },
  { id: 1213, title: "Intersection of Three Sorted Arrays", diff: "Easy", topics: "Array, Two Pointers", slug: "intersection-of-three-sorted-arrays" },
  { id: 1214, title: "Two Sum BSTs", diff: "Medium", topics: "Two Pointers, Binary Search, Tree, Depth-First Search, Binary Search Tree, Binary Tree", slug: "two-sum-bsts" },
  { id: 1215, title: "Stepping Numbers", diff: "Medium", topics: "Breadth-First Search, Depth-First Search", slug: "stepping-numbers" },
  { id: 1216, title: "Valid Palindrome III", diff: "Hard", topics: "String, Dynamic Programming", slug: "valid-palindrome-iii" },
  { id: 1217, title: "Minimum Cost to Move Chips to The Same Position", diff: "Easy", topics: "Array, Math, Greedy", slug: "minimum-cost-to-move-chips-to-the-same-position" },
  { id: 1218, title: "Longest Arithmetic Subsequence of Given Difference", diff: "Medium", topics: "Array, Hash Table, Dynamic Programming", slug: "longest-arithmetic-subsequence-of-given-difference" },
  { id: 1219, title: "Path with Maximum Gold", diff: "Medium", topics: "Array, Backtracking, Matrix", slug: "path-with-maximum-gold" },
  { id: 1220, title: "Count Vowels Permutation", diff: "Hard", topics: "Dynamic Programming", slug: "count-vowels-permutation" },
  { id: 1221, title: "Split a String in Balanced Strings", diff: "Easy", topics: "String, Greedy, Counting", slug: "split-a-string-in-balanced-strings" },
  { id: 1222, title: "Queens That Can Attack the King", diff: "Medium", topics: "Array, Matrix, Simulation", slug: "queens-that-can-attack-the-king" },
  { id: 1223, title: "Dice Roll Simulation", diff: "Hard", topics: "Dynamic Programming", slug: "dice-roll-simulation" },
  { id: 1224, title: "Maximum Equal Frequency", diff: "Hard", topics: "Array, Hash Table", slug: "maximum-equal-frequency" },
  { id: 1225, title: "Report Contiguous Dates", diff: "Hard", topics: "Database", slug: "report-contiguous-dates" },
  { id: 1226, title: "The Dining Philosophers", diff: "Medium", topics: "Concurrency", slug: "the-dining-philosophers" },
  { id: 1227, title: "Airplane Seat Assignment Probability", diff: "Medium", topics: "Math, Probability and Statistics", slug: "airplane-seat-assignment-probability" },
  { id: 1228, title: "Missing Number In Arithmetic Progression", diff: "Easy", topics: "Array, Math", slug: "missing-number-in-arithmetic-progression" },
  { id: 1229, title: "Meeting Scheduler", diff: "Medium", topics: "Array, Two Pointers, Sorting", slug: "meeting-scheduler" },
  { id: 1230, title: "Toss Strange Coins", diff: "Medium", topics: "Dynamic Programming, Probability and Statistics", slug: "toss-strange-coins" },
  { id: 1231, title: "Divide Chocolate", diff: "Hard", topics: "Array, Binary Search", slug: "divide-chocolate" },
  { id: 1232, title: "Check If It Is a Straight Line", diff: "Easy", topics: "Array, Math, Geometry", slug: "check-if-it-is-a-straight-line" },
  { id: 1233, title: "Remove Sub-Folders from the Filesystem", diff: "Medium", topics: "Array, String, Trie, Sorting", slug: "remove-sub-folders-from-the-filesystem" },
  { id: 1234, title: "Replace the Substring for Balanced String", diff: "Medium", topics: "String, Sliding Window", slug: "replace-the-substring-for-balanced-string" },
  { id: 1235, title: "Maximum Profit in Job Scheduling", diff: "Hard", topics: "Array, Binary Search, Dynamic Programming, Sorting", slug: "maximum-profit-in-job-scheduling" },
  { id: 1236, title: "Web Crawler", diff: "Medium", topics: "Depth-First Search, Breadth-First Search, String, Interactive", slug: "web-crawler" },
  { id: 1237, title: "Find Positive Integer Solution for a Given Equation", diff: "Easy", topics: "Math, Binary Search, Interactive", slug: "find-positive-integer-solution-for-a-given-equation" },
  { id: 1238, title: "Circular Permutation in Binary Representation", diff: "Medium", topics: "Bit Manipulation, Math", slug: "circular-permutation-in-binary-representation" },
  { id: 1239, title: "Maximum Length of a Concatenated String with Unique Characters", diff: "Medium", topics: "Array, String, Backtracking, Bit Manipulation", slug: "maximum-length-of-a-concatenated-string-with-unique-characters" },
  { id: 1240, title: "Tiling a Rectangle with the Fewest Squares", diff: "Hard", topics: "Dynamic Programming, Backtracking", slug: "tiling-a-rectangle-with-the-fewest-squares" },
  { id: 1241, title: "Number of Comments per Post", diff: "Easy", topics: "Database", slug: "number-of-comments-per-post" },
  { id: 1242, title: "Web Crawler Multithreaded", diff: "Medium", topics: "Concurrency", slug: "web-crawler-multithreaded" },
  { id: 1243, title: "Array Transformation", diff: "Easy", topics: "Array, Simulation", slug: "array-transformation" },
  { id: 1244, title: "Design A Leaderboard", diff: "Medium", topics: "Hash Table, Design, Sorting", slug: "design-a-leaderboard" },
  { id: 1245, title: "Tree Diameter", diff: "Medium", topics: "Tree, Depth-First Search, Breadth-First Search, Graph", slug: "tree-diameter" },
  { id: 1246, title: "Palindrome Removal", diff: "Hard", topics: "Array, Dynamic Programming", slug: "palindrome-removal" },
  { id: 1247, title: "Minimum Swaps to Make Strings Equal", diff: "Medium", topics: "String, Greedy", slug: "minimum-swaps-to-make-strings-equal" },
  { id: 1248, title: "Count Number of Nice Subarrays", diff: "Medium", topics: "Array, Hash Table, Sliding Window, Prefix Sum", slug: "count-number-of-nice-subarrays" },
  { id: 1249, title: "Minimum Remove to Make Valid Parentheses", diff: "Medium", topics: "String, Stack", slug: "minimum-remove-to-make-valid-parentheses" },
  { id: 1250, title: "Check If It Is a Good Array", diff: "Hard", topics: "Array, Math, Number Theory", slug: "check-if-it-is-a-good-array" }
);