window.rawProblems = window.rawProblems || [];

window.rawProblems.push(
  { id: 1251, title: "Average Selling Price", diff: "Easy", topics: "Database", slug: "average-selling-price" },
  { id: 1252, title: "Cells with Odd Values in a Matrix", diff: "Easy", topics: "Array, Matrix, Simulation", slug: "cells-with-odd-values-in-a-matrix" },
  { id: 1253, title: "Reconstruct a 2-Row Binary Matrix", diff: "Medium", topics: "Array, Greedy, Matrix", slug: "reconstruct-a-2-row-binary-matrix" },
  { id: 1254, title: "Number of Closed Islands", diff: "Medium", topics: "Array, Depth-First Search, Breadth-First Search, Union Find, Matrix", slug: "number-of-closed-islands" },
  { id: 1255, title: "Maximum Score Words Formed by Letters", diff: "Hard", topics: "Array, String, Backtracking, Bit Manipulation", slug: "maximum-score-words-formed-by-letters" },
  { id: 1256, title: "Encode Number", diff: "Medium", topics: "Math, Bit Manipulation", slug: "encode-number" },
  { id: 1257, title: "Smallest Common Region", diff: "Medium", topics: "Hash Table, Tree, Depth-First Search", slug: "smallest-common-region" },
  { id: 1258, title: "Synonymous Sentences", diff: "Medium", topics: "Hash Table, String, Union Find, Backtracking", slug: "synonymous-sentences" },
  { id: 1259, title: "Handshakes That Don't Cross", diff: "Hard", topics: "Math, Dynamic Programming", slug: "handshakes-that-dont-cross" },
  { id: 1260, title: "Shift 2D Grid", diff: "Easy", topics: "Array, Matrix, Simulation", slug: "shift-2d-grid" },
  { id: 1261, title: "Find Elements in a Contaminated Binary Tree", diff: "Medium", topics: "Hash Table, Tree, Depth-First Search, Breadth-First Search, Design, Binary Tree", slug: "find-elements-in-a-contaminated-binary-tree" },
  { id: 1262, title: "Greatest Sum Divisible by Three", diff: "Medium", topics: "Array, Dynamic Programming", slug: "greatest-sum-divisible-by-three" },
  { id: 1263, title: "Minimum Moves to Move a Box to Their Target Location", diff: "Hard", topics: "Array, Breadth-First Search, Heap (Priority Queue), Matrix", slug: "minimum-moves-to-move-a-box-to-their-target-location" },
  { id: 1264, title: "Page Recommendations", diff: "Medium", topics: "Database", slug: "page-recommendations" },
  { id: 1265, title: "Print Immutable Linked List in Reverse", diff: "Medium", topics: "Linked List, Two Pointers, Stack, Recursion, Interactive", slug: "print-immutable-linked-list-in-reverse" },
  { id: 1266, title: "Minimum Time Visiting All Points", diff: "Easy", topics: "Array, Math, Geometry", slug: "minimum-time-visiting-all-points" },
  { id: 1267, title: "Count Servers that Communicate", diff: "Medium", topics: "Array, Depth-First Search, Breadth-First Search, Union Find, Matrix", slug: "count-servers-that-communicate" },
  { id: 1268, title: "Search Suggestions System", diff: "Medium", topics: "Array, String, Binary Search, Trie, Sorting, Heap (Priority Queue)", slug: "search-suggestions-system" },
  { id: 1269, title: "Number of Ways to Stay in the Same Place After Some Steps", diff: "Hard", topics: "Dynamic Programming", slug: "number-of-ways-to-stay-in-the-same-place-after-some-steps" },
  { id: 1270, title: "All People Report to the Given Manager", diff: "Medium", topics: "Database", slug: "all-people-report-to-the-given-manager" },
  { id: 1271, title: "Hexspeak", diff: "Easy", topics: "Math, String", slug: "hexspeak" },
  { id: 1272, title: "Remove Interval", diff: "Medium", topics: "Array", slug: "remove-interval" },
  { id: 1273, title: "Delete Tree Nodes", diff: "Medium", topics: "Tree, Depth-First Search, Breadth-First Search", slug: "delete-tree-nodes" },
  { id: 1274, title: "Number of Ships in a Rectangle", diff: "Hard", topics: "Divide and Conquer, Interactive", slug: "number-of-ships-in-a-rectangle" },
  { id: 1275, title: "Find Winner on a Tic Tac Toe Game", diff: "Easy", topics: "Array, Hash Table, Matrix, Simulation", slug: "find-winner-on-a-tic-tac-toe-game" },
  { id: 1276, title: "Number of Burgers with No Waste of Ingredients", diff: "Medium", topics: "Math", slug: "number-of-burgers-with-no-waste-of-ingredients" },
  { id: 1277, title: "Count Square Submatrices with All Ones", diff: "Medium", topics: "Array, Dynamic Programming, Matrix", slug: "count-square-submatrices-with-all-ones" },
  { id: 1278, title: "Palindrome Partitioning III", diff: "Hard", topics: "String, Dynamic Programming", slug: "palindrome-partitioning-iii" },
  { id: 1279, title: "Traffic Light Controlled Intersection", diff: "Easy", topics: "Concurrency", slug: "traffic-light-controlled-intersection" },
  { id: 1280, title: "Students and Examinations", diff: "Easy", topics: "Database", slug: "students-and-examinations" },
  { id: 1281, title: "Subtract the Product and Sum of Digits of an Integer", diff: "Easy", topics: "Math", slug: "subtract-the-product-and-sum-of-digits-of-an-integer" },
  { id: 1282, title: "Group the People Given the Group Size They Belong To", diff: "Medium", topics: "Array, Hash Table", slug: "group-the-people-given-the-group-size-they-belong-to" },
  { id: 1283, title: "Find the Smallest Divisor Given a Threshold", diff: "Medium", topics: "Array, Binary Search", slug: "find-the-smallest-divisor-given-a-threshold" },
  { id: 1284, title: "Minimum Number of Flips to Convert Binary Matrix to Zero Matrix", diff: "Hard", topics: "Array, Breadth-First Search, Bit Manipulation, Matrix", slug: "minimum-number-of-flips-to-convert-binary-matrix-to-zero-matrix" },
  { id: 1285, title: "Find the Start and End Number of Continuous Ranges", diff: "Medium", topics: "Database", slug: "find-the-start-and-end-number-of-continuous-ranges" },
  { id: 1286, title: "Iterator for Combination", diff: "Medium", topics: "String, Backtracking, Design, Iterator", slug: "iterator-for-combination" },
  { id: 1287, title: "Element Appearing More Than 25% In Sorted Array", diff: "Easy", topics: "Array", slug: "element-appearing-more-than-25-in-sorted-array" },
  { id: 1288, title: "Remove Covered Intervals", diff: "Medium", topics: "Array, Sorting", slug: "remove-covered-intervals" },
  { id: 1289, title: "Minimum Falling Path Sum II", diff: "Hard", topics: "Array, Dynamic Programming, Matrix", slug: "minimum-falling-path-sum-ii" },
  { id: 1290, title: "Convert Binary Number in a Linked List to Integer", diff: "Easy", topics: "Linked List, Math", slug: "convert-binary-number-in-a-linked-list-to-integer" },
  { id: 1291, title: "Sequential Digits", diff: "Medium", topics: "Backtracking, Enumeration", slug: "sequential-digits" },
  { id: 1292, title: "Maximum Side Length of a Square with Sum Less than or Equal to Threshold", diff: "Medium", topics: "Array, Binary Search, Matrix, Prefix Sum", slug: "maximum-side-length-of-a-square-with-sum-less-than-or-equal-to-threshold" },
  { id: 1293, title: "Shortest Path in a Grid with Obstacles Elimination", diff: "Hard", topics: "Array, Breadth-First Search, Matrix", slug: "shortest-path-in-a-grid-with-obstacles-elimination" },
  { id: 1294, title: "Weather Type in Each Country", diff: "Easy", topics: "Database", slug: "weather-type-in-each-country" },
  { id: 1295, title: "Find Numbers with Even Number of Digits", diff: "Easy", topics: "Array, Math", slug: "find-numbers-with-even-number-of-digits" },
  { id: 1296, title: "Divide Array in Sets of K Consecutive Numbers", diff: "Medium", topics: "Array, Hash Table, Greedy, Sorting", slug: "divide-array-in-sets-of-k-consecutive-numbers" },
  { id: 1297, title: "Maximum Number of Occurrences of a Substring", diff: "Medium", topics: "Hash Table, String, Sliding Window", slug: "maximum-number-of-occurrences-of-a-substring" },
  { id: 1298, title: "Maximum Candies You Can Get from Boxes", diff: "Hard", topics: "Array, Breadth-First Search", slug: "maximum-candies-you-can-get-from-boxes" },
  { id: 1299, title: "Replace Elements with Greatest Element on Right Side", diff: "Easy", topics: "Array", slug: "replace-elements-with-greatest-element-on-right-side" },
  { id: 1300, title: "Sum of Mutated Array Closest to Target", diff: "Medium", topics: "Array, Binary Search, Sorting", slug: "sum-of-mutated-array-closest-to-target" },
  { id: 1301, title: "Number of Paths with Max Score", diff: "Hard", topics: "Array, Dynamic Programming, Matrix", slug: "number-of-paths-with-max-score" },
  { id: 1302, title: "Deepest Leaves Sum", diff: "Medium", topics: "Tree, Depth-First Search, Breadth-First Search, Binary Tree", slug: "deepest-leaves-sum" },
  { id: 1303, title: "Find the Team Size", diff: "Easy", topics: "Database", slug: "find-the-team-size" },
  { id: 1304, title: "Find N Unique Integers Sum up to Zero", diff: "Easy", topics: "Array, Math", slug: "find-n-unique-integers-sum-up-to-zero" },
  { id: 1305, title: "All Elements in Two Binary Search Trees", diff: "Medium", topics: "Tree, Depth-First Search, Binary Search Tree, Sorting, Binary Tree", slug: "all-elements-in-two-binary-search-trees" },
  { id: 1306, title: "Jump Game III", diff: "Medium", topics: "Array, Depth-First Search, Breadth-First Search", slug: "jump-game-iii" },
  { id: 1307, title: "Verbal Arithmetic Puzzle", diff: "Hard", topics: "Array, String, Backtracking", slug: "verbal-arithmetic-puzzle" },
  { id: 1308, title: "Running Total for Different Genders", diff: "Medium", topics: "Database", slug: "running-total-for-different-genders" },
  { id: 1309, title: "Decrypt String from Alphabet to Integer Mapping", diff: "Easy", topics: "String", slug: "decrypt-string-from-alphabet-to-integer-mapping" },
  { id: 1310, title: "XOR Queries of a Subarray", diff: "Medium", topics: "Array, Bit Manipulation, Prefix Sum", slug: "xor-queries-of-a-subarray" },
  { id: 1311, title: "Get Watched Videos by Your Friends", diff: "Medium", topics: "Array, Hash Table, Breadth-First Search, Graph, Sorting", slug: "get-watched-videos-by-your-friends" },
  { id: 1312, title: "Minimum Insertion Steps to Make a String Palindrome", diff: "Hard", topics: "String, Dynamic Programming", slug: "minimum-insertion-steps-to-make-a-string-palindrome" },
  { id: 1313, title: "Decompress Run-Length Encoded List", diff: "Easy", topics: "Array", slug: "decompress-run-length-encoded-list" },
  { id: 1314, title: "Matrix Block Sum", diff: "Medium", topics: "Array, Matrix, Prefix Sum", slug: "matrix-block-sum" },
  { id: 1315, title: "Sum of Nodes with Even-Valued Grandparent", diff: "Medium", topics: "Tree, Depth-First Search, Binary Tree", slug: "sum-of-nodes-with-even-valued-grandparent" },
  { id: 1316, title: "Distinct Echo Substrings", diff: "Hard", topics: "String, Trie, Suffix Array, Rolling Hash, Hash Function", slug: "distinct-echo-substrings" },
  { id: 1317, title: "Convert Integer to the Sum of Two No-Zero Integers", diff: "Easy", topics: "Math", slug: "convert-integer-to-the-sum-of-two-no-zero-integers" },
  { id: 1318, title: "Minimum Flips to Make a OR b Equal to c", diff: "Medium", topics: "Bit Manipulation", slug: "minimum-flips-to-make-a-or-b-equal-to-c" },
  { id: 1319, title: "Number of Operations to Make Network Connected", diff: "Medium", topics: "Depth-First Search, Breadth-First Search, Union Find, Graph", slug: "number-of-operations-to-make-network-connected" },
  { id: 1320, title: "Minimum Distance to Type a Word Using Two Fingers", diff: "Hard", topics: "String, Dynamic Programming", slug: "minimum-distance-to-type-a-word-using-two-fingers" },
  { id: 1321, title: "Restaurant Growth", diff: "Medium", topics: "Database", slug: "restaurant-growth" },
  { id: 1322, title: "Ads Performance", diff: "Easy", topics: "Database", slug: "ads-performance" },
  { id: 1323, title: "Maximum 69 Number", diff: "Easy", topics: "Math, Greedy", slug: "maximum-69-number" },
  { id: 1324, title: "Print Words Vertically", diff: "Medium", topics: "Array, String, Simulation", slug: "print-words-vertically" },
  { id: 1325, title: "Delete Leaves With a Given Value", diff: "Medium", topics: "Tree, Depth-First Search, Binary Tree", slug: "delete-leaves-with-a-given-value" },
  { id: 1326, title: "Minimum Number of Taps to Open to Water a Garden", diff: "Hard", topics: "Array, Dynamic Programming, Greedy", slug: "minimum-number-of-taps-to-open-to-water-a-garden" },
  { id: 1327, title: "List the Products Ordered in a Period", diff: "Easy", topics: "Database", slug: "list-the-products-ordered-in-a-period" },
  { id: 1328, title: "Break a Palindrome", diff: "Medium", topics: "String, Greedy", slug: "break-a-palindrome" },
  { id: 1329, title: "Sort the Matrix Diagonally", diff: "Medium", topics: "Array, Matrix, Sorting", slug: "sort-the-matrix-diagonally" },
  { id: 1330, title: "Reverse Subarray To Maximize Array Value", diff: "Hard", topics: "Array, Greedy", slug: "reverse-subarray-to-maximize-array-value" },
  { id: 1331, title: "Rank Transform of an Array", diff: "Easy", topics: "Array, Hash Table, Sorting", slug: "rank-transform-of-an-array" },
  { id: 1332, title: "Remove Palindromic Subsequences", diff: "Easy", topics: "Two Pointers, String", slug: "remove-palindromic-subsequences" },
  { id: 1333, title: "Filter Restaurants by Vegan-Friendly, Price and Distance", diff: "Medium", topics: "Array, Sorting", slug: "filter-restaurants-by-vegan-friendly-price-and-distance" },
  { id: 1334, title: "Find the City With the Smallest Number of Neighbors at a Threshold Distance", diff: "Medium", topics: "Dynamic Programming, Graph, Shortest Path", slug: "find-the-city-with-the-smallest-number-of-neighbors-at-a-threshold-distance" },
  { id: 1335, title: "Minimum Difficulty of a Job Schedule", diff: "Hard", topics: "Array, Dynamic Programming", slug: "minimum-difficulty-of-a-job-schedule" },
  { id: 1336, title: "Number of Transactions per Visit", diff: "Hard", topics: "Database", slug: "number-of-transactions-per-visit" },
  { id: 1337, title: "The K Weakest Rows in a Matrix", diff: "Easy", topics: "Array, Binary Search, Matrix, Sorting, Heap (Priority Queue)", slug: "the-k-weakest-rows-in-a-matrix" },
  { id: 1338, title: "Reduce Array Size to The Half", diff: "Medium", topics: "Array, Hash Table, Greedy, Sorting, Heap (Priority Queue)", slug: "reduce-array-size-to-the-half" },
  { id: 1339, title: "Maximum Product of Splitted Binary Tree", diff: "Medium", topics: "Tree, Depth-First Search, Binary Tree", slug: "maximum-product-of-splitted-binary-tree" },
  { id: 1340, title: "Jump Game V", diff: "Hard", topics: "Array, Dynamic Programming, Depth-First Search, Sorting", slug: "jump-game-v" },
  { id: 1341, title: "Movie Rating", diff: "Medium", topics: "Database", slug: "movie-rating" },
  { id: 1342, title: "Number of Steps to Reduce a Number to Zero", diff: "Easy", topics: "Math, Bit Manipulation", slug: "number-of-steps-to-reduce-a-number-to-zero" },
  { id: 1343, title: "Number of Sub-arrays of Size K and Average Greater than or Equal to Threshold", diff: "Medium", topics: "Array, Sliding Window", slug: "number-of-sub-arrays-of-size-k-and-average-greater-than-or-equal-to-threshold" },
  { id: 1344, title: "Angle Between Hands of a Clock", diff: "Medium", topics: "Math", slug: "angle-between-hands-of-a-clock" },
  { id: 1345, title: "Jump Game IV", diff: "Hard", topics: "Array, Hash Table, Breadth-First Search", slug: "jump-game-iv" },
  { id: 1346, title: "Check If N and Its Double Exist", diff: "Easy", topics: "Array, Hash Table", slug: "check-if-n-and-its-double-exist" },
  { id: 1347, title: "Minimum Number of Steps to Make Two Strings Anagram", diff: "Medium", topics: "Hash Table, String, Counting", slug: "minimum-number-of-steps-to-make-two-strings-anagram" },
  { id: 1348, title: "Tweet Counts Per Frequency", diff: "Medium", topics: "Hash Table, Design, Binary Search, Ordered Set", slug: "tweet-counts-per-frequency" },
  { id: 1349, title: "Maximum Students Taking Exam", diff: "Hard", topics: "Array, Dynamic Programming, Bit Manipulation, Matrix", slug: "maximum-students-taking-exam" },
  { id: 1350, title: "Students With Invalid Departments", diff: "Easy", topics: "Database", slug: "students-with-invalid-departments" },
  { id: 1351, title: "Count Negative Numbers in a Sorted Matrix", diff: "Easy", topics: "Array, Binary Search, Matrix", slug: "count-negative-numbers-in-a-sorted-matrix" },
  { id: 1352, title: "Product of the Last K Numbers", diff: "Medium", topics: "Array, Design, Prefix Sum, Data Stream", slug: "product-of-the-last-k-numbers" },
  { id: 1353, title: "Maximum Number of Events That Can Be Attended", diff: "Medium", topics: "Array, Greedy, Sorting, Heap (Priority Queue)", slug: "maximum-number-of-events-that-can-be-attended" },
  { id: 1354, title: "Construct Target Array With Multiple Sums", diff: "Hard", topics: "Array, Heap (Priority Queue)", slug: "construct-target-array-with-multiple-sums" },
  { id: 1355, title: "Activity Participants", diff: "Medium", topics: "Database", slug: "activity-participants" },
  { id: 1356, title: "Sort Integers by The Number of 1 Bits", diff: "Easy", topics: "Array, Bit Manipulation, Sorting", slug: "sort-integers-by-the-number-of-1-bits" },
  { id: 1357, title: "Apply Discount Every n Orders", diff: "Medium", topics: "Design", slug: "apply-discount-every-n-orders" },
  { id: 1358, title: "Number of Substrings Containing All Three Characters", diff: "Medium", topics: "Hash Table, String, Sliding Window", slug: "number-of-substrings-containing-all-three-characters" },
  { id: 1359, title: "Count All Valid Pickup and Delivery Options", diff: "Hard", topics: "Math, Dynamic Programming, Combinatorics", slug: "count-all-valid-pickup-and-delivery-options" },
  { id: 1360, title: "Number of Days Between Two Dates", diff: "Easy", topics: "Math, String", slug: "number-of-days-between-two-dates" },
  { id: 1361, title: "Validate Binary Tree Nodes", diff: "Medium", topics: "Depth-First Search, Breadth-First Search, Union Find, Graph", slug: "validate-binary-tree-nodes" },
  { id: 1362, title: "Closest Divisors", diff: "Medium", topics: "Math", slug: "closest-divisors" },
  { id: 1363, title: "Largest Multiple of Three", diff: "Hard", topics: "Array, Dynamic Programming, Greedy, Sorting", slug: "largest-multiple-of-three" },
  { id: 1364, title: "Number of Trusted Contacts of a Customer", diff: "Medium", topics: "Database", slug: "number-of-trusted-contacts-of-a-customer" },
  { id: 1365, title: "How Many Numbers Are Smaller Than the Current Number", diff: "Easy", topics: "Array, Hash Table, Sorting, Counting Sort", slug: "how-many-numbers-are-smaller-than-the-current-number" },
  { id: 1366, title: "Rank Teams by Votes", diff: "Medium", topics: "Array, Hash Table, String, Sorting", slug: "rank-teams-by-votes" },
  { id: 1367, title: "Linked List in Binary Tree", diff: "Medium", topics: "Linked List, Tree, Depth-First Search, Binary Tree", slug: "linked-list-in-binary-tree" },
  { id: 1368, title: "Minimum Cost to Make at Least One Valid Path in a Grid", diff: "Hard", topics: "Array, Breadth-First Search, Graph, Heap (Priority Queue), Matrix", slug: "minimum-cost-to-make-at-least-one-valid-path-in-a-grid" },
  { id: 1369, title: "Get the Second Most Recent Activity", diff: "Hard", topics: "Database", slug: "get-the-second-most-recent-activity" },
  { id: 1370, title: "Increasing Decreasing String", diff: "Easy", topics: "Array, Hash Table, String, Counting", slug: "increasing-decreasing-string" },
  { id: 1371, title: "Find the Longest Substring Containing Vowels in Even Counts", diff: "Medium", topics: "Hash Table, String, Bit Manipulation, Prefix Sum", slug: "find-the-longest-substring-containing-vowels-in-even-counts" },
  { id: 1372, title: "Longest ZigZag Path in a Binary Tree", diff: "Medium", topics: "Dynamic Programming, Tree, Depth-First Search, Binary Tree", slug: "longest-zigzag-path-in-a-binary-tree" },
  { id: 1373, title: "Maximum Sum BST in Binary Tree", diff: "Hard", topics: "Dynamic Programming, Tree, Depth-First Search, Binary Search Tree, Binary Tree", slug: "maximum-sum-bst-in-binary-tree" },
  { id: 1374, title: "Generate a String With Characters That Have Odd Counts", diff: "Easy", topics: "String", slug: "generate-a-string-with-characters-that-have-odd-counts" },
  { id: 1375, title: "Number of Times Binary String Is Prefix-Aligned", diff: "Medium", topics: "Array", slug: "number-of-times-binary-string-is-prefix-aligned" },
  { id: 1376, title: "Time Needed to Inform All Employees", diff: "Medium", topics: "Tree, Depth-First Search, Breadth-First Search", slug: "time-needed-to-inform-all-employees" },
  { id: 1377, title: "Frog Position After T Seconds", diff: "Hard", topics: "Tree, Depth-First Search, Breadth-First Search, Graph, Probability and Statistics", slug: "frog-position-after-t-seconds" },
  { id: 1378, title: "Replace Employee ID With The Unique Identifier", diff: "Easy", topics: "Database", slug: "replace-employee-id-with-the-unique-identifier" },
  { id: 1379, title: "Find a Corresponding Node of a Binary Tree in a Clone of That Tree", diff: "Easy", topics: "Tree, Depth-First Search, Breadth-First Search, Binary Tree", slug: "find-a-corresponding-node-of-a-binary-tree-in-a-clone-of-that-tree" },
  { id: 1380, title: "Lucky Numbers in a Matrix", diff: "Easy", topics: "Array, Matrix", slug: "lucky-numbers-in-a-matrix" },
  { id: 1381, title: "Design a Stack With Increment Operation", diff: "Medium", topics: "Array, Stack, Design", slug: "design-a-stack-with-increment-operation" },
  { id: 1382, title: "Balance a Binary Search Tree", diff: "Medium", topics: "Divide and Conquer, Tree, Depth-First Search, Binary Search Tree, Binary Tree", slug: "balance-a-binary-search-tree" },
  { id: 1383, title: "Maximum Performance of a Team", diff: "Hard", topics: "Array, Greedy, Sorting, Heap (Priority Queue)", slug: "maximum-performance-of-a-team" },
  { id: 1384, title: "Total Sales Amount by Year", diff: "Hard", topics: "Database", slug: "total-sales-amount-by-year" },
  { id: 1385, title: "Find the Distance Value Between Two Arrays", diff: "Easy", topics: "Array, Two Pointers, Binary Search, Sorting", slug: "find-the-distance-value-between-two-arrays" },
  { id: 1386, title: "Cinema Seat Allocation", diff: "Medium", topics: "Array, Hash Table, Bit Manipulation, Greedy", slug: "cinema-seat-allocation" },
  { id: 1387, title: "Sort Integers by The Power Value", diff: "Medium", topics: "Memoization, Dynamic Programming, Sorting", slug: "sort-integers-by-the-power-value" },
  { id: 1388, title: "Pizza With 3n Slices", diff: "Hard", topics: "Array, Dynamic Programming", slug: "pizza-with-3n-slices" },
  { id: 1389, title: "Create Target Array in the Given Order", diff: "Easy", topics: "Array, Simulation", slug: "create-target-array-in-the-given-order" },
  { id: 1390, title: "Four Divisors", diff: "Medium", topics: "Array, Math, Number Theory", slug: "four-divisors" },
  { id: 1391, title: "Check if There is a Valid Path in a Grid", diff: "Medium", topics: "Array, Depth-First Search, Breadth-First Search, Union Find, Matrix", slug: "check-if-there-is-a-valid-path-in-a-grid" },
  { id: 1392, title: "Longest Happy Prefix", diff: "Hard", topics: "String, Rolling Hash, String Matching, Hash Function", slug: "longest-happy-prefix" },
  { id: 1393, title: "Capital Gain/Loss", diff: "Medium", topics: "Database", slug: "capital-gainloss" },
  { id: 1394, title: "Find Lucky Integer in an Array", diff: "Easy", topics: "Array, Hash Table, Counting", slug: "find-lucky-integer-in-an-array" },
  { id: 1395, title: "Count Number of Teams", diff: "Medium", topics: "Array, Dynamic Programming, Binary Indexed Tree", slug: "count-number-of-teams" },
  { id: 1396, title: "Design Underground System", diff: "Medium", topics: "Hash Table, String, Design", slug: "design-underground-system" },
  { id: 1397, title: "Find All Good Strings", diff: "Hard", topics: "String, Dynamic Programming, String Matching, Digit DP", slug: "find-all-good-strings" },
  { id: 1398, title: "Customers Who Bought Products A and B but Not C", diff: "Medium", topics: "Database", slug: "customers-who-bought-products-a-and-b-but-not-c" },
  { id: 1399, title: "Count Largest Group", diff: "Easy", topics: "Hash Table, Math, Counting", slug: "count-largest-group" },
  { id: 1400, title: "Construct K Palindrome Strings", diff: "Medium", topics: "Hash Table, String, Greedy, Counting", slug: "construct-k-palindrome-strings" },
  { id: 1401, title: "Circle and Rectangle Overlapping", diff: "Medium", topics: "Math, Geometry", slug: "circle-and-rectangle-overlapping" },
  { id: 1402, title: "Reducing Dishes", diff: "Hard", topics: "Array, Dynamic Programming, Greedy, Sorting", slug: "reducing-dishes" },
  { id: 1403, title: "Minimum Subsequence in Non-Increasing Order", diff: "Easy", topics: "Array, Greedy, Sorting", slug: "minimum-subsequence-in-non-increasing-order" },
  { id: 1404, title: "Number of Steps to Reduce a Number in Binary Representation to One", diff: "Medium", topics: "String, Bit Manipulation, Simulation", slug: "number-of-steps-to-reduce-a-number-in-binary-representation-to-one" },
  { id: 1405, title: "Longest Happy String", diff: "Medium", topics: "String, Greedy, Heap (Priority Queue)", slug: "longest-happy-string" },
  { id: 1406, title: "Stone Game III", diff: "Hard", topics: "Array, Math, Dynamic Programming, Game Theory", slug: "stone-game-iii" },
  { id: 1407, title: "Top Travellers", diff: "Easy", topics: "Database", slug: "top-travellers" },
  { id: 1408, title: "String Matching in an Array", diff: "Easy", topics: "Array, String, String Matching", slug: "string-matching-in-an-array" },
  { id: 1409, title: "Queries on a Permutation With Key", diff: "Medium", topics: "Array, Binary Indexed Tree, Simulation", slug: "queries-on-a-permutation-with-key" },
  { id: 1410, title: "HTML Entity Parser", diff: "Medium", topics: "Hash Table, String, Simulation", slug: "html-entity-parser" },
  { id: 1411, title: "Number of Ways to Paint N × 3 Grid", diff: "Hard", topics: "Dynamic Programming", slug: "number-of-ways-to-paint-n-3-grid" },
  { id: 1412, title: "Find the Quiet Students in All Exams", diff: "Hard", topics: "Database", slug: "find-the-quiet-students-in-all-exams" },
  { id: 1413, title: "Minimum Value to Get Positive Step by Step Sum", diff: "Easy", topics: "Array, Prefix Sum", slug: "minimum-value-to-get-positive-step-by-step-sum" },
  { id: 1414, title: "Find the Minimum Number of Fibonacci Numbers Whose Sum Is K", diff: "Medium", topics: "Array, Greedy, Math", slug: "find-the-minimum-number-of-fibonacci-numbers-whose-sum-is-k" },
  { id: 1415, title: "The k-th Lexicographical String of All Happy Strings of Length n", diff: "Medium", topics: "String, Backtracking", slug: "the-k-th-lexicographical-string-of-all-happy-strings-of-length-n" },
  { id: 1416, title: "Restore The Array", diff: "Hard", topics: "String, Dynamic Programming", slug: "restore-the-array" },
  { id: 1417, title: "Reformat The String", diff: "Easy", topics: "String", slug: "reformat-the-string" },
  { id: 1418, title: "Display Table of Food Orders in a Restaurant", diff: "Medium", topics: "Array, Hash Table, String, Ordered Set, Sorting", slug: "display-table-of-food-orders-in-a-restaurant" },
  { id: 1419, title: "Minimum Number of Frogs Croaking", diff: "Medium", topics: "String, Greedy, Counting", slug: "minimum-number-of-frogs-croaking" },
  { id: 1420, title: "Build Array Where You Can Find The Maximum Exactly K Comparisons", diff: "Hard", topics: "Dynamic Programming, Prefix Sum", slug: "build-array-where-you-can-find-the-maximum-exactly-k-comparisons" },
  { id: 1421, title: "NPV Queries", diff: "Medium", topics: "Database", slug: "npv-queries" },
  { id: 1422, title: "Maximum Score After Splitting a String", diff: "Easy", topics: "String, Prefix Sum", slug: "maximum-score-after-splitting-a-string" },
  { id: 1423, title: "Maximum Points You Can Obtain from Cards", diff: "Medium", topics: "Array, Sliding Window, Prefix Sum", slug: "maximum-points-you-can-obtain-from-cards" },
  { id: 1424, title: "Diagonal Traverse II", diff: "Medium", topics: "Array, Sorting, Heap (Priority Queue)", slug: "diagonal-traverse-ii" },
  { id: 1425, title: "Constrained Subsequence Sum", diff: "Hard", topics: "Array, Dynamic Programming, Queue, Monotonic Queue", slug: "constrained-subsequence-sum" },
  { id: 1426, title: "Counting Elements", diff: "Easy", topics: "Array, Hash Table", slug: "counting-elements" },
  { id: 1427, title: "Perform String Shifts", diff: "Easy", topics: "String", slug: "perform-string-shifts" },
  { id: 1428, title: "Leftmost Column with at Least a One", diff: "Medium", topics: "Array, Binary Search, Matrix, Interactive", slug: "leftmost-column-with-at-least-a-one" },
  { id: 1429, title: "First Unique Number", diff: "Medium", topics: "Hash Table, Queue, Design, Data Stream", slug: "first-unique-number" },
  { id: 1430, title: "Check If a String Is a Valid Sequence from Root to Leaves Path in a Binary Tree", diff: "Medium", topics: "Tree, Depth-First Search, Binary Tree", slug: "check-if-a-string-is-a-valid-sequence-from-root-to-leaves-path-in-a-binary-tree" },
  { id: 1431, title: "Kids With the Greatest Number of Candies", diff: "Easy", topics: "Array", slug: "kids-with-the-greatest-number-of-candies" },
  { id: 1432, title: "Max Difference You Can Get From Changing an Integer", diff: "Medium", topics: "Math, Greedy", slug: "max-difference-you-can-get-from-changing-an-integer" },
  { id: 1433, title: "Check If a String Can Break Another String", diff: "Medium", topics: "String, Greedy, Sorting", slug: "check-if-a-string-can-break-another-string" },
  { id: 1434, title: "Number of Ways to Wear Different Hats to Each Other", diff: "Hard", topics: "Array, Dynamic Programming, Bit Manipulation", slug: "number-of-ways-to-wear-different-hats-to-each-other" },
  { id: 1435, title: "Create a Session Bar Chart", diff: "Easy", topics: "Database", slug: "create-a-session-bar-chart" },
  { id: 1436, title: "Destination City", diff: "Easy", topics: "Array, Hash Table, String", slug: "destination-city" },
  { id: 1437, title: "Check If All 1's Are at Least Length K Places Away", diff: "Easy", topics: "Array", slug: "check-if-all-1s-are-at-least-length-k-places-away" },
  { id: 1438, title: "Longest Continuous Subarray With Absolute Diff Less Than or Equal to Limit", diff: "Medium", topics: "Array, Queue, Sliding Window, Heap (Priority Queue), Ordered Set, Monotonic Queue", slug: "longest-continuous-subarray-with-absolute-diff-less-than-or-equal-to-limit" },
  { id: 1439, title: "Find the Kth Smallest Sum of a Matrix With Sorted Rows", diff: "Hard", topics: "Array, Binary Search, Matrix, Heap (Priority Queue)", slug: "find-the-kth-smallest-sum-of-a-matrix-with-sorted-rows" },
  { id: 1440, title: "Evaluate Boolean Expression", diff: "Medium", topics: "Database", slug: "evaluate-boolean-expression" },
  { id: 1441, title: "Build an Array With Stack Operations", diff: "Medium", topics: "Array, Stack, Simulation", slug: "build-an-array-with-stack-operations" },
  { id: 1442, title: "Count Triplets That Can Form Two Arrays of Equal XOR", diff: "Medium", topics: "Array, Hash Table, Bit Manipulation, Prefix Sum", slug: "count-triplets-that-can-form-two-arrays-of-equal-xor" },
  { id: 1443, title: "Minimum Time to Collect All Apples in a Tree", diff: "Medium", topics: "Hash Table, Tree, Depth-First Search", slug: "minimum-time-to-collect-all-apples-in-a-tree" },
  { id: 1444, title: "Number of Ways of Cutting a Pizza", diff: "Hard", topics: "Array, Dynamic Programming, Matrix, Prefix Sum", slug: "number-of-ways-of-cutting-a-pizza" },
  { id: 1445, title: "Apples & Oranges", diff: "Medium", topics: "Database", slug: "apples-oranges" },
  { id: 1446, title: "Consecutive Characters", diff: "Easy", topics: "String", slug: "consecutive-characters" },
  { id: 1447, title: "Simplified Fractions", diff: "Medium", topics: "Math, String, Number Theory", slug: "simplified-fractions" },
  { id: 1448, title: "Count Good Nodes in Binary Tree", diff: "Medium", topics: "Tree, Depth-First Search, Binary Tree", slug: "count-good-nodes-in-binary-tree" },
  { id: 1449, title: "Form Largest Integer With Digits That Add up to Target", diff: "Hard", topics: "Array, Dynamic Programming", slug: "form-largest-integer-with-digits-that-add-up-to-target" },
  { id: 1450, title: "Number of Students Doing Homework at a Given Time", diff: "Easy", topics: "Array", slug: "number-of-students-doing-homework-at-a-given-time" },
  { id: 1451, title: "Rearrange Words in a Sentence", diff: "Medium", topics: "String, Sorting", slug: "rearrange-words-in-a-sentence" },
  { id: 1452, title: "People Whose List of Favorite Companies Is Not a Subset of Another List", diff: "Medium", topics: "Array, Hash Table, String", slug: "people-whose-list-of-favorite-companies-is-not-a-subset-of-another-list" },
  { id: 1453, title: "Maximum Number of Darts Inside of a Circular Dartboard", diff: "Hard", topics: "Array, Math, Geometry", slug: "maximum-number-of-darts-inside-of-a-circular-dartboard" },
  { id: 1454, title: "Active Users", diff: "Medium", topics: "Database", slug: "active-users" },
  { id: 1455, title: "Check If a Word Occurs As a Prefix of Any Word in a Sentence", diff: "Easy", topics: "Two Pointers, String", slug: "check-if-a-word-occurs-as-a-prefix-of-any-word-in-a-sentence" },
  { id: 1456, title: "Maximum Number of Vowels in a Substring of Given Length", diff: "Medium", topics: "String, Sliding Window", slug: "maximum-number-of-vowels-in-a-substring-of-given-length" },
  { id: 1457, title: "Pseudo-Palindromic Paths in a Binary Tree", diff: "Medium", topics: "Bit Manipulation, Tree, Depth-First Search, Binary Tree", slug: "pseudo-palindromic-paths-in-a-binary-tree" },
  { id: 1458, title: "Max Dot Product of Two Subsequences", diff: "Hard", topics: "Array, Dynamic Programming", slug: "max-dot-product-of-two-subsequences" },
  { id: 1459, title: "Rectangles Area", diff: "Medium", topics: "Database", slug: "rectangles-area" },
  { id: 1460, title: "Make Two Arrays Equal by Reversing Subarrays", diff: "Easy", topics: "Array, Hash Table, Sorting", slug: "make-two-arrays-equal-by-reversing-subarrays" },
  { id: 1461, title: "Check If a String Contains All Binary Codes of Size K", diff: "Medium", topics: "Hash Table, String, Bit Manipulation, Rolling Hash, Hash Function", slug: "check-if-a-string-contains-all-binary-codes-of-size-k" },
  { id: 1462, title: "Course Schedule IV", diff: "Medium", topics: "Depth-First Search, Breadth-First Search, Graph, Topological Sort", slug: "course-schedule-iv" },
  { id: 1463, title: "Cherry Pickup II", diff: "Hard", topics: "Array, Dynamic Programming, Matrix", slug: "cherry-pickup-ii" },
  { id: 1464, title: "Maximum Product of Two Elements in an Array", diff: "Easy", topics: "Array, Sorting, Heap (Priority Queue)", slug: "maximum-product-of-two-elements-in-an-array" },
  { id: 1465, title: "Maximum Area of a Piece of Cake After Horizontal and Vertical Cuts", diff: "Medium", topics: "Array, Greedy, Sorting", slug: "maximum-area-of-a-piece-of-cake-after-horizontal-and-vertical-cuts" },
  { id: 1466, title: "Reorder Routes to Make All Paths Lead to the City Zero", diff: "Medium", topics: "Depth-First Search, Breadth-First Search, Graph", slug: "reorder-routes-to-make-all-paths-lead-to-the-city-zero" },
  { id: 1467, title: "Probability of a Two Boxes Having The Same Number of Distinct Balls", diff: "Hard", topics: "Math, Dynamic Programming, Backtracking, Probability and Statistics", slug: "probability-of-a-two-boxes-having-the-same-number-of-distinct-balls" },
  { id: 1468, title: "Calculate Salaries", diff: "Medium", topics: "Database", slug: "calculate-salaries" },
  { id: 1469, title: "Find All The Lonely Nodes", diff: "Easy", topics: "Tree, Depth-First Search, Breadth-First Search, Binary Tree", slug: "find-all-the-lonely-nodes" },
  { id: 1470, title: "Shuffle the Array", diff: "Easy", topics: "Array", slug: "shuffle-the-array" },
  { id: 1471, title: "The k Strongest Values in an Array", diff: "Medium", topics: "Array, Two Pointers, Sorting", slug: "the-k-strongest-values-in-an-array" },
  { id: 1472, title: "Design Browser History", diff: "Medium", topics: "Array, Linked List, Stack, Design", slug: "design-browser-history" },
  { id: 1473, title: "Paint House III", diff: "Hard", topics: "Array, Dynamic Programming", slug: "paint-house-iii" },
  { id: 1474, title: "Delete N Nodes After M Nodes of a Linked List", diff: "Easy", topics: "Linked List", slug: "delete-n-nodes-after-m-nodes-of-a-linked-list" },
  { id: 1475, title: "Final Prices With a Special Discount in a Shop", diff: "Easy", topics: "Array, Stack, Monotonic Stack", slug: "final-prices-with-a-special-discount-in-a-shop" },
  { id: 1476, title: "Subrectangle Queries", diff: "Medium", topics: "Array, Design, Matrix", slug: "subrectangle-queries" },
  { id: 1477, title: "Find Two Non-overlapping Sub-arrays Each With Target Sum", diff: "Medium", topics: "Array, Hash Table, Binary Search, Dynamic Programming, Sliding Window", slug: "find-two-non-overlapping-sub-arrays-each-with-target-sum" },
  { id: 1478, title: "Allocate Mailboxes", diff: "Hard", topics: "Array, Dynamic Programming, Sorting", slug: "allocate-mailboxes" },
  { id: 1479, title: "Sales by Day of the Week", diff: "Hard", topics: "Database", slug: "sales-by-day-of-the-week" },
  { id: 1480, title: "Running Sum of 1d Array", diff: "Easy", topics: "Array, Prefix Sum", slug: "running-sum-of-1d-array" },
  { id: 1481, title: "Least Number of Unique Integers after K Removals", diff: "Medium", topics: "Array, Hash Table, Greedy, Sorting, Counting", slug: "least-number-of-unique-integers-after-k-removals" },
  { id: 1482, title: "Minimum Number of Days to Make m Bouquets", diff: "Medium", topics: "Array, Binary Search", slug: "minimum-number-of-days-to-make-m-bouquets" },
  { id: 1483, title: "Kth Ancestor of a Tree Node", diff: "Hard", topics: "Dynamic Programming, Bit Manipulation, Tree, Design", slug: "kth-ancestor-of-a-tree-node" },
  { id: 1484, title: "Group Sold Products By The Date", diff: "Easy", topics: "Database", slug: "group-sold-products-by-the-date" },
  { id: 1485, title: "Clone Binary Tree With Random Pointer", diff: "Medium", topics: "Hash Table, Tree, Depth-First Search, Breadth-First Search, Binary Tree", slug: "clone-binary-tree-with-random-pointer" },
  { id: 1486, title: "XOR Operation in an Array", diff: "Easy", topics: "Array, Bit Manipulation, Math", slug: "xor-operation-in-an-array" },
  { id: 1487, title: "Making File Names Unique", diff: "Medium", topics: "Array, Hash Table, String", slug: "making-file-names-unique" },
  { id: 1488, title: "Avoid Flood in The City", diff: "Medium", topics: "Array, Hash Table, Binary Search, Heap (Priority Queue), Ordered Set", slug: "avoid-flood-in-the-city" },
  { id: 1489, title: "Find Critical and Pseudo-Critical Edges in Minimum Spanning Tree", diff: "Hard", topics: "Array, Union Find, Graph, Sorting, Minimum Spanning Tree", slug: "find-critical-and-pseudo-critical-edges-in-minimum-spanning-tree" },
  { id: 1490, title: "Clone N-ary Tree", diff: "Medium", topics: "Hash Table, Tree, Depth-First Search, Breadth-First Search", slug: "clone-n-ary-tree" },
  { id: 1491, title: "Average Salary Excluding the Minimum and Maximum Salary", diff: "Easy", topics: "Array, Sorting", slug: "average-salary-excluding-the-minimum-and-maximum-salary" },
  { id: 1492, title: "The kth Factor of n", diff: "Medium", topics: "Math", slug: "the-kth-factor-of-n" },
  { id: 1493, title: "Longest Subarray of 1's After Deleting One Element", diff: "Medium", topics: "Array, Dynamic Programming, Sliding Window", slug: "longest-subarray-of-1s-after-deleting-one-element" },
  { id: 1494, title: "Parallel Courses II", diff: "Hard", topics: "Dynamic Programming, Bit Manipulation, Graph", slug: "parallel-courses-ii" },
  { id: 1495, title: "Friendly Movies Streamed Last Month", diff: "Easy", topics: "Database", slug: "friendly-movies-streamed-last-month" },
  { id: 1496, title: "Path Crossing", diff: "Easy", topics: "Hash Table, String", slug: "path-crossing" },
  { id: 1497, title: "Check If Array Pairs Are Divisible by k", diff: "Medium", topics: "Array, Hash Table, Counting", slug: "check-if-array-pairs-are-divisible-by-k" },
  { id: 1498, title: "Number of Subsequences That Satisfy the Given Sum Condition", diff: "Medium", topics: "Array, Two Pointers, Sorting", slug: "number-of-subsequences-that-satisfy-the-given-sum-condition" },
  { id: 1499, title: "Max Value of Equation", diff: "Hard", topics: "Array, Queue, Sliding Window, Heap (Priority Queue), Monotonic Queue", slug: "max-value-of-equation" },
  { id: 1500, title: "Design a File Sharing System", diff: "Medium", topics: "Hash Table, Design, Heap (Priority Queue)", slug: "design-a-file-sharing-system" }
);