window.rawProblems = window.rawProblems || [];

window.rawProblems.push(
  { id: 1751, title: "Maximum Number of Events That Can Be Attended II", diff: "Hard", topics: "Array, Dynamic Programming, Binary Search, Sorting", slug: "maximum-number-of-events-that-can-be-attended-ii" },
  { id: 1752, title: "Check if Array Is Sorted and Rotated", diff: "Easy", topics: "Array", slug: "check-if-array-is-sorted-and-rotated" },
  { id: 1753, title: "Maximum Score From Removing Stones", diff: "Medium", topics: "Array, Greedy, Heap (Priority Queue), Math", slug: "maximum-score-from-removing-stones" },
  { id: 1754, title: "Largest Merge Of Two Strings", diff: "Medium", topics: "Two Pointers, String, Greedy", slug: "largest-merge-of-two-strings" },
  { id: 1755, title: "Closest Subsequence Sum", diff: "Hard", topics: "Array, Two Pointers, Binary Search, Bit Manipulation, Divide and Conquer", slug: "closest-subsequence-sum" },
  { id: 1756, title: "Design Most Recently Used Queue", diff: "Medium", topics: "Binary Indexed Tree, Design", slug: "design-most-recently-used-queue" },
  { id: 1757, title: "Recyclable and Low Fat Products", diff: "Easy", topics: "Database", slug: "recyclable-and-low-fat-products" },
  { id: 1758, title: "Minimum Changes To Make Alternating Binary String", diff: "Easy", topics: "String", slug: "minimum-changes-to-make-alternating-binary-string" },
  { id: 1759, title: "Count Number of Homogenous Substrings", diff: "Medium", topics: "Math, String", slug: "count-number-of-homogenous-substrings" },
  { id: 1760, title: "Minimum Limit of Balls in a Bag", diff: "Medium", topics: "Array, Binary Search", slug: "minimum-limit-of-balls-in-a-bag" },
  { id: 1761, title: "Minimum Degree of a Connected Trio in a Graph", diff: "Hard", topics: "Graph", slug: "minimum-degree-of-a-connected-trio-in-a-graph" },
  { id: 1762, title: "Buildings With an Ocean View", diff: "Medium", topics: "Array, Stack, Monotonic Stack", slug: "buildings-with-an-ocean-view" },
  { id: 1763, title: "Longest Nice Substring", diff: "Easy", topics: "Hash Table, String, Divide and Conquer, Bit Manipulation, Sliding Window", slug: "longest-nice-substring" },
  { id: 1764, title: "Form Array by Concatenating Subarrays of Another Array", diff: "Medium", topics: "Array, Greedy, Knuth–Morris–Pratt (KMP)", slug: "form-array-by-concatenating-subarrays-of-another-array" },
  { id: 1765, title: "Map of Highest Peak", diff: "Medium", topics: "Array, Breadth-First Search, Matrix", slug: "map-of-highest-peak" },
  { id: 1766, title: "Tree of Coprimes", diff: "Hard", topics: "Array, Math, Tree, Depth-First Search, Number Theory", slug: "tree-of-coprimes" },
  { id: 1767, title: "Find the Subtasks That Did Not Execute", diff: "Hard", topics: "Database", slug: "find-the-subtasks-that-did-not-execute" },
  { id: 1768, title: "Merge Strings Alternately", diff: "Easy", topics: "Two Pointers, String", slug: "merge-strings-alternately" },
  { id: 1769, title: "Minimum Number of Operations to Move All Balls to Each Box", diff: "Medium", topics: "Array, String, Prefix Sum", slug: "minimum-number-of-operations-to-move-all-balls-to-each-box" },
  { id: 1770, title: "Maximum Score from Performing Multiplication Operations", diff: "Hard", topics: "Array, Dynamic Programming", slug: "maximum-score-from-performing-multiplication-operations" },
  { id: 1771, title: "Maximize Palindrome Length From Subsequences", diff: "Hard", topics: "String, Dynamic Programming", slug: "maximize-palindrome-length-from-subsequences" },
  { id: 1772, title: "Sort Features by Popularity", diff: "Medium", topics: "Array, Hash Table, String, Sorting", slug: "sort-features-by-popularity" },
  { id: 1773, title: "Count Items Matching a Rule", diff: "Easy", topics: "Array, String", slug: "count-items-matching-a-rule" },
  { id: 1774, title: "Closest Dessert Cost", diff: "Medium", topics: "Array, Backtracking", slug: "closest-dessert-cost" },
  { id: 1775, title: "Equal Sum Arrays With Minimum Number of Operations", diff: "Medium", topics: "Array, Greedy, Counting", slug: "equal-sum-arrays-with-minimum-number-of-operations" },
  { id: 1776, title: "Car Fleet II", diff: "Hard", topics: "Array, Stack, Monotonic Stack", slug: "car-fleet-ii" },
  { id: 1777, title: "Product's Price for Each Store", diff: "Easy", topics: "Database", slug: "products-price-for-each-store" },
  { id: 1778, title: "Shortest Path in a Hidden Grid", diff: "Medium", topics: "Depth-First Search, Breadth-First Search, Interactive", slug: "shortest-path-in-a-hidden-grid" },
  { id: 1779, title: "Find Nearest Point That Has the Same X or Y Coordinate", diff: "Easy", topics: "Array", slug: "find-nearest-point-that-has-the-same-x-or-y-coordinate" },
  { id: 1780, title: "Check if Number is a Sum of Powers of Three", diff: "Medium", topics: "Math", slug: "check-if-number-is-a-sum-of-powers-of-three" },
  { id: 1781, title: "Sum of Beauty of All Substrings", diff: "Medium", topics: "Hash Table, String, Counting", slug: "sum-of-beauty-of-all-substrings" },
  { id: 1782, title: "Count Pairs Of Nodes", diff: "Hard", topics: "Array, Two Pointers, Binary Search, Graph, Sorting", slug: "count-pairs-of-nodes" },
  { id: 1783, title: "Grand Slam Titles", diff: "Medium", topics: "Database", slug: "grand-slam-titles" },
  { id: 1784, title: "Check if Binary String Has at Most One Segment of Ones", diff: "Easy", topics: "String", slug: "check-if-binary-string-has-at-most-one-segment-of-ones" },
  { id: 1785, title: "Minimum Elements to Add to Form a Given Sum", diff: "Medium", topics: "Array, Greedy, Math", slug: "minimum-elements-to-add-to-form-a-given-sum" },
  { id: 1786, title: "Number of Restricted Paths From First to Last Node", diff: "Medium", topics: "Dynamic Programming, Graph, Shortest Path, Heap (Priority Queue)", slug: "number-of-restricted-paths-from-first-to-last-node" },
  { id: 1787, title: "Make the XOR of All Segments Equal to Zero", diff: "Hard", topics: "Array, Dynamic Programming, Bit Manipulation", slug: "make-the-xor-of-all-segments-equal-to-zero" },
  { id: 1788, title: "Maximize the Beauty of the Garden", diff: "Hard", topics: "Array, Hash Table, Prefix Sum", slug: "maximize-the-beauty-of-the-garden" },
  { id: 1789, title: "Primary Department for Each Employee", diff: "Easy", topics: "Database", slug: "primary-department-for-each-employee" },
  { id: 1790, title: "Check if One String Swap Can Make Strings Equal", diff: "Easy", topics: "Hash Table, String, Counting", slug: "check-if-one-string-swap-can-make-strings-equal" },
  { id: 1791, title: "Find Center of Star Graph", diff: "Easy", topics: "Graph", slug: "find-center-of-star-graph" },
  { id: 1792, title: "Maximum Average Pass Ratio", diff: "Medium", topics: "Array, Greedy, Heap (Priority Queue)", slug: "maximum-average-pass-ratio" },
  { id: 1793, title: "Maximum Score of a Good Subarray", diff: "Hard", topics: "Array, Two Pointers, Binary Search, Stack, Monotonic Stack", slug: "maximum-score-of-a-good-subarray" },
  { id: 1794, title: "Count Pairs of Equal Substrings With Minimum Difference", diff: "Medium", topics: "Database", slug: "count-pairs-of-equal-substrings-with-minimum-difference" },
  { id: 1795, title: "Rearrange Products Table", diff: "Easy", topics: "Database", slug: "rearrange-products-table" },
  { id: 1796, title: "Second Largest Digit in a String", diff: "Easy", topics: "Hash Table, String", slug: "second-largest-digit-in-a-string" },
  { id: 1797, title: "Design Authentication Manager", diff: "Medium", topics: "Hash Table, Linked List, Design", slug: "design-authentication-manager" },
  { id: 1798, title: "Maximum Number of Consecutive Values You Can Make", diff: "Medium", topics: "Array, Greedy, Sorting", slug: "maximum-number-of-consecutive-values-you-can-make" },
  { id: 1799, title: "Maximize Score After N Operations", diff: "Hard", topics: "Array, Dynamic Programming, Bit Manipulation, Backtracking, Math", slug: "maximize-score-after-n-operations" },
  { id: 1800, title: "Maximum Ascending Subarray Sum", diff: "Easy", topics: "Array", slug: "maximum-ascending-subarray-sum" },
  { id: 1801, title: "Number of Orders in the Backlog", diff: "Medium", topics: "Array, Heap (Priority Queue), Simulation", slug: "number-of-orders-in-the-backlog" },
  { id: 1802, title: "Maximum Value at a Given Index in a Bounded Array", diff: "Medium", topics: "Array, Binary Search, Greedy", slug: "maximum-value-at-a-given-index-in-a-bounded-array" },
  { id: 1803, title: "Count Pairs With XOR in a Range", diff: "Hard", topics: "Bit Manipulation, Trie", slug: "count-pairs-with-xor-in-a-range" },
  { id: 1804, title: "Implement Trie II (Prefix Tree)", diff: "Medium", topics: "Hash Table, String, Design, Trie", slug: "implement-trie-ii-prefix-tree" },
  { id: 1805, title: "Number of Different Integers in a String", diff: "Easy", topics: "Hash Table, String", slug: "number-of-different-integers-in-a-string" },
  { id: 1806, title: "Minimum Number of Operations to Reinitialize a Permutation", diff: "Medium", topics: "Math, Simulation", slug: "minimum-number-of-operations-to-reinitialize-a-permutation" },
  { id: 1807, title: "Evaluate the Bracket Pairs of a String", diff: "Medium", topics: "Array, Hash Table, String", slug: "evaluate-the-bracket-pairs-of-a-string" },
  { id: 1808, title: "Maximize Number of Nice Divisors", diff: "Hard", topics: "Math, Greedy", slug: "maximize-number-of-nice-divisors" },
  { id: 1809, title: "Ad-Free Sessions", diff: "Easy", topics: "Database", slug: "ad-free-sessions" },
  { id: 1810, title: "Minimum Path Cost in a Hidden Grid", diff: "Hard", topics: "Depth-First Search, Breadth-First Search, Graph, Interactive", slug: "minimum-path-cost-in-a-hidden-grid" },
  { id: 1811, title: "Find Interview Candidates", diff: "Medium", topics: "Database", slug: "find-interview-candidates" },
  { id: 1812, title: "Determine Color of a Chessboard Square", diff: "Easy", topics: "Math, String", slug: "determine-color-of-a-chessboard-square" },
  { id: 1813, title: "Sentence Similarity III", diff: "Medium", topics: "Array, Two Pointers, String", slug: "sentence-similarity-iii" },
  { id: 1814, title: "Count Nice Pairs in an Array", diff: "Medium", topics: "Array, Hash Table, Math, Counting", slug: "count-nice-pairs-in-an-array" },
  { id: 1815, title: "Maximum Number of Groups Getting Fresh Donuts", diff: "Hard", topics: "Array, Dynamic Programming, Bit Manipulation", slug: "maximum-number-of-groups-getting-fresh-donuts" },
  { id: 1816, title: "Truncate Sentence", diff: "Easy", topics: "String", slug: "truncate-sentence" },
  { id: 1817, title: "Finding the Users Active Minutes", diff: "Medium", topics: "Array, Hash Table", slug: "finding-the-users-active-minutes" },
  { id: 1818, title: "Minimum Absolute Sum Difference", diff: "Medium", topics: "Array, Binary Search, Sorting", slug: "minimum-absolute-sum-difference" },
  { id: 1819, title: "Number of Different Subsequences GCDs", diff: "Hard", topics: "Array, Hash Table, Math, Number Theory", slug: "number-of-different-subsequences-gcds" },
  { id: 1820, title: "Maximum Number of Accepted Invitations", diff: "Medium", topics: "Depth-First Search, Breadth-First Search, Graph, Bipartite Matching", slug: "maximum-number-of-accepted-invitations" },
  { id: 1821, title: "Find Customers With Positive Revenue this Year", diff: "Easy", topics: "Database", slug: "find-customers-with-positive-revenue-this-year" },
  { id: 1822, title: "Sign of the Product of an Array", diff: "Easy", topics: "Array, Math", slug: "sign-of-the-product-of-an-array" },
  { id: 1823, title: "Find the Winner of the Circular Game", diff: "Medium", topics: "Array, Math, Recursion, Queue, Simulation", slug: "find-the-winner-of-the-circular-game" },
  { id: 1824, title: "Minimum Sideway Jumps", diff: "Medium", topics: "Array, Dynamic Programming", slug: "minimum-sideway-jumps" },
  { id: 1825, title: "Finding MK Average", diff: "Hard", topics: "Queue, Design, Ordered Set, Heap (Priority Queue), Data Stream", slug: "finding-mk-average" },
  { id: 1826, title: "Faulty Sensor", diff: "Easy", topics: "Array, Two Pointers", slug: "faulty-sensor" },
  { id: 1827, title: "Minimum Operations to Make the Array Increasing", diff: "Easy", topics: "Array, Greedy", slug: "minimum-operations-to-make-the-array-increasing" },
  { id: 1828, title: "Queries on Number of Points Inside a Circle", diff: "Medium", topics: "Array, Geometry", slug: "queries-on-number-of-points-inside-a-circle" },
  { id: 1829, title: "Maximum XOR for Each Query", diff: "Medium", topics: "Array, Bit Manipulation, Prefix Sum", slug: "maximum-xor-for-each-query" },
  { id: 1830, title: "Minimum Number of Operations to Make String Sorted", diff: "Hard", topics: "Math, String, Combinatorics", slug: "minimum-number-of-operations-to-make-string-sorted" },
  { id: 1831, title: "Maximum Transaction Each Day", diff: "Medium", topics: "Database", slug: "maximum-transaction-each-day" },
  { id: 1832, title: "Check if the Sentence Is Pangram", diff: "Easy", topics: "Hash Table, String", slug: "check-if-the-sentence-is-pangram" },
  { id: 1833, title: "Maximum Ice Cream Bars", diff: "Medium", topics: "Array, Greedy, Sorting, Counting Sort", slug: "maximum-ice-cream-bars" },
  { id: 1834, title: "Single-Threaded CPU", diff: "Medium", topics: "Array, Sorting, Heap (Priority Queue)", slug: "single-threaded-cpu" },
  { id: 1835, title: "Find XOR Sum of All Pairs Bitwise AND", diff: "Hard", topics: "Array, Bit Manipulation", slug: "find-xor-sum-of-all-pairs-bitwise-and" },
  { id: 1836, title: "Remove Duplicates From an Unsorted Linked List", diff: "Medium", topics: "Hash Table, Linked List", slug: "remove-duplicates-from-an-unsorted-linked-list" },
  { id: 1837, title: "Sum of Digits in Base K", diff: "Easy", topics: "Math", slug: "sum-of-digits-in-base-k" },
  { id: 1838, title: "Frequency of the Most Frequent Element", diff: "Medium", topics: "Array, Binary Search, Greedy, Sliding Window, Sorting, Prefix Sum", slug: "frequency-of-the-most-frequent-element" },
  { id: 1839, title: "Longest Substring Of All Vowels in Order", diff: "Medium", topics: "String, Sliding Window", slug: "longest-substring-of-all-vowels-in-order" },
  { id: 1840, title: "Maximum Building Height", diff: "Hard", topics: "Array, Greedy", slug: "maximum-building-height" },
  { id: 1841, title: "League Statistics", diff: "Medium", topics: "Database", slug: "league-statistics" },
  { id: 1842, title: "Next Palindrome Using Same Digits", diff: "Hard", topics: "Two Pointers, String", slug: "next-palindrome-using-same-digits" },
  { id: 1843, title: "Suspicious Bank Accounts", diff: "Medium", topics: "Database", slug: "suspicious-bank-accounts" },
  { id: 1844, title: "Replace All Digits with Characters", diff: "Easy", topics: "String", slug: "replace-all-digits-with-characters" },
  { id: 1845, title: "Seat Reservation Manager", diff: "Medium", topics: "Design, Heap (Priority Queue)", slug: "seat-reservation-manager" },
  { id: 1846, title: "Maximum Element After Decreasing and Rearranging", diff: "Medium", topics: "Array, Greedy, Sorting", slug: "maximum-element-after-decreasing-and-rearranging" },
  { id: 1847, title: "Closest Room", diff: "Hard", topics: "Array, Binary Search, Sorting, Heap (Priority Queue)", slug: "closest-room" },
  { id: 1848, title: "Minimum Distance to the Target Element", diff: "Easy", topics: "Array", slug: "minimum-distance-to-the-target-element" },
  { id: 1849, title: "Splitting a String Into Descending Consecutive Values", diff: "Medium", topics: "String, Backtracking", slug: "splitting-a-string-into-descending-consecutive-values" },
  { id: 1850, title: "Minimum Adjacent Swaps to Reach the Kth Smallest Number", diff: "Medium", topics: "String, Greedy, Two Pointers", slug: "minimum-adjacent-swaps-to-reach-the-kth-smallest-number" },
  { id: 1851, title: "Minimum Interval to Include Each Query", diff: "Hard", topics: "Array, Binary Search, Sorting, Heap (Priority Queue)", slug: "minimum-interval-to-include-each-query" },
  { id: 1852, title: "Distinct Numbers in Each Subarray", diff: "Medium", topics: "Array, Hash Table, Sliding Window", slug: "distinct-numbers-in-each-subarray" },
  { id: 1853, title: "Convert Date Format", diff: "Easy", topics: "Database", slug: "convert-date-format" },
  { id: 1854, title: "Maximum Population Year", diff: "Easy", topics: "Array, Prefix Sum, Sorting", slug: "maximum-population-year" },
  { id: 1855, title: "Maximum Distance Between a Pair of Values", diff: "Medium", topics: "Array, Two Pointers, Binary Search", slug: "maximum-distance-between-a-pair-of-values" },
  { id: 1856, title: "Maximum Subarray Min-Product", diff: "Medium", topics: "Array, Stack, Prefix Sum, Monotonic Stack", slug: "maximum-subarray-min-product" },
  { id: 1857, title: "Largest Color Value in a Directed Graph", diff: "Hard", topics: "Dynamic Programming, Graph, Topological Sort", slug: "largest-color-value-in-a-directed-graph" },
  { id: 1858, title: "Longest Word With All Prefixes", diff: "Medium", topics: "Hash Table, String, Trie", slug: "longest-word-with-all-prefixes" },
  { id: 1859, title: "Sorting the Sentence", diff: "Easy", topics: "String, Sorting", slug: "sorting-the-sentence" },
  { id: 1860, title: "Incremental Memory Leak", diff: "Medium", topics: "Math, Simulation", slug: "incremental-memory-leak" },
  { id: 1861, title: "Rotating the Box", diff: "Medium", topics: "Array, Two Pointers, Matrix", slug: "rotating-the-box" },
  { id: 1862, title: "Sum of Floored Pairs", diff: "Hard", topics: "Array, Math, Prefix Sum, Counting Sort, Number Theory", slug: "sum-of-floored-pairs" },
  { id: 1863, title: "Sum of All Subset XOR Totals", diff: "Easy", topics: "Array, Bit Manipulation, Backtracking", slug: "sum-of-all-subset-xor-totals" },
  { id: 1864, title: "Minimum Number of Swaps to Make the Binary String Alternating", diff: "Medium", topics: "String, Greedy", slug: "minimum-number-of-swaps-to-make-the-binary-string-alternating" },
  { id: 1865, title: "Finding Pairs With a Certain Sum", diff: "Medium", topics: "Array, Hash Table, Design", slug: "finding-pairs-with-a-certain-sum" },
  { id: 1866, title: "Number of Ways to Rearrange Sticks With K Sticks Visible", diff: "Hard", topics: "Math, Dynamic Programming, Combinatorics", slug: "number-of-ways-to-rearrange-sticks-with-k-sticks-visible" },
  { id: 1867, title: "Orders With Maximum Quantity Above Average", diff: "Medium", topics: "Database", slug: "orders-with-maximum-quantity-above-average" },
  { id: 1868, title: "Product of Two Run-Length Encoded Arrays", diff: "Medium", topics: "Array, Two Pointers", slug: "product-of-two-run-length-encoded-arrays" },
  { id: 1869, title: "Longer Contiguous Segments of Ones than Zeros", diff: "Easy", topics: "String", slug: "longer-contiguous-segments-of-ones-than-zeros" },
  { id: 1870, title: "Minimum Speed to Arrive on Time", diff: "Medium", topics: "Array, Binary Search", slug: "minimum-speed-to-arrive-on-time" },
  { id: 1871, title: "Jump Game VII", diff: "Medium", topics: "String, Dynamic Programming, Prefix Sum, Sliding Window", slug: "jump-game-vii" },
  { id: 1872, title: "Stone Game VIII", diff: "Hard", topics: "Array, Math, Dynamic Programming, Game Theory", slug: "stone-game-viii" },
  { id: 1873, title: "Calculate Special Bonus", diff: "Easy", topics: "Database", slug: "calculate-special-bonus" },
  { id: 1874, title: "Minimize Product Sum of Two Arrays", diff: "Medium", topics: "Array, Greedy, Sorting", slug: "minimize-product-sum-of-two-arrays" },
  { id: 1875, title: "Group Employees of the Same Salary", diff: "Hard", topics: "Database", slug: "group-employees-of-the-same-salary" },
  { id: 1876, title: "Substrings of Size Three with Distinct Characters", diff: "Easy", topics: "Hash Table, String, Sliding Window", slug: "substrings-of-size-three-with-distinct-characters" },
  { id: 1877, title: "Minimize Maximum Pair Sum in Array", diff: "Medium", topics: "Array, Two Pointers, Greedy, Sorting", slug: "minimize-maximum-pair-sum-in-array" },
  { id: 1878, title: "Get Biggest Three Rhombus Sums in a Grid", diff: "Medium", topics: "Array, Matrix, Prefix Sum", slug: "get-biggest-three-rhombus-sums-in-a-grid" },
  { id: 1879, title: "Minimum XOR Sum of Two Arrays", diff: "Hard", topics: "Array, Dynamic Programming, Bit Manipulation", slug: "minimum-xor-sum-of-two-arrays" },
  { id: 1880, title: "Check if Word Equals Summation of Two Words", diff: "Easy", topics: "String", slug: "check-if-word-equals-summation-of-two-words" },
  { id: 1881, title: "Maximum Value after Insertion", diff: "Medium", topics: "String, Greedy", slug: "maximum-value-after-insertion" },
  { id: 1882, title: "Process Tasks Using Servers", diff: "Medium", topics: "Array, Simulation, Heap (Priority Queue)", slug: "process-tasks-using-servers" },
  { id: 1883, title: "Minimum Skips to Arrive at Meeting On Time", diff: "Hard", topics: "Array, Dynamic Programming", slug: "minimum-skips-to-arrive-at-meeting-on-time" },
  { id: 1884, title: "Egg Drop With 2 Eggs and N Floors", diff: "Medium", topics: "Math, Dynamic Programming", slug: "egg-drop-with-2-eggs-and-n-floors" },
  { id: 1885, title: "Count Pairs in Two Arrays", diff: "Medium", topics: "Array, Two Pointers, Binary Search, Sorting", slug: "count-pairs-in-two-arrays" },
  { id: 1886, title: "Determine Whether Matrix Can Be Obtained By Rotation", diff: "Easy", topics: "Array, Matrix", slug: "determine-whether-matrix-can-be-obtained-by-rotation" },
  { id: 1887, title: "Reduction Operations to Make the Array Elements Equal", diff: "Medium", topics: "Array, Greedy, Sorting", slug: "reduction-operations-to-make-the-array-elements-equal" },
  { id: 1888, title: "Minimum Number of Flips to Make the Binary String Alternating", diff: "Medium", topics: "String, Dynamic Programming, Sliding Window", slug: "minimum-number-of-flips-to-make-the-binary-string-alternating" },
  { id: 1889, title: "Minimum Space Wasted From Packaging", diff: "Hard", topics: "Array, Binary Search, Prefix Sum, Sorting", slug: "minimum-space-wasted-from-packaging" },
  { id: 1890, title: "The Latest Login in 2020", diff: "Easy", topics: "Database", slug: "the-latest-login-in-2020" },
  { id: 1891, title: "Cutting Ribbons", diff: "Medium", topics: "Array, Binary Search", slug: "cutting-ribbons" },
  { id: 1892, title: "Page Recommendations II", diff: "Hard", topics: "Database", slug: "page-recommendations-ii" },
  { id: 1893, title: "Check if All the Integers in a Range Are Covered", diff: "Easy", topics: "Array, Prefix Sum", slug: "check-if-all-the-integers-in-a-range-are-covered" },
  { id: 1894, title: "Find the Student that Will Replace the Chalk", diff: "Medium", topics: "Array, Binary Search, Prefix Sum", slug: "find-the-student-that-will-replace-the-chalk" },
  { id: 1895, title: "Largest Magic Square", diff: "Medium", topics: "Array, Matrix, Prefix Sum", slug: "largest-magic-square" },
  { id: 1896, title: "Minimum Cost to Change the Final Value of Expression", diff: "Hard", topics: "String, Stack, Dynamic Programming", slug: "minimum-cost-to-change-the-final-value-of-expression" },
  { id: 1897, title: "Redistribute Characters to Make All Strings Equal", diff: "Easy", topics: "Hash Table, String, Counting", slug: "redistribute-characters-to-make-all-strings-equal" },
  { id: 1898, title: "Maximum Number of Removable Characters", diff: "Medium", topics: "Array, Binary Search, String", slug: "maximum-number-of-removable-characters" },
  { id: 1899, title: "Merge Triplets to Form Target Triplet", diff: "Medium", topics: "Array, Greedy", slug: "merge-triplets-to-form-target-triplet" },
  { id: 1900, title: "The Earliest and Latest Rounds Where Players Compete", diff: "Hard", topics: "Dynamic Programming, Memoization", slug: "the-earliest-and-latest-rounds-where-players-compete" },
  { id: 1901, title: "Find a Peak Element II", diff: "Medium", topics: "Array, Binary Search, Matrix", slug: "find-a-peak-element-ii" },
  { id: 1902, title: "Depth of BST Given Insertion Order", diff: "Medium", topics: "Array, Binary Search Tree, Tree", slug: "depth-of-bst-given-insertion-order" },
  { id: 1903, title: "Largest Odd Number in String", diff: "Easy", topics: "Math, String", slug: "largest-odd-number-in-string" },
  { id: 1904, title: "The Number of Full Rounds You Have Played", diff: "Medium", topics: "Math, String, Simulation", slug: "the-number-of-full-rounds-you-have-played" },
  { id: 1905, title: "Count Sub Islands", diff: "Medium", topics: "Array, Depth-First Search, Breadth-First Search, Union Find, Matrix", slug: "count-sub-islands" },
  { id: 1906, title: "Minimum Absolute Difference Queries", diff: "Medium", topics: "Array, Prefix Sum", slug: "minimum-absolute-difference-queries" },
  { id: 1907, title: "Count Salary Categories", diff: "Medium", topics: "Database", slug: "count-salary-categories" },
  { id: 1908, title: "Game of Nim", diff: "Hard", topics: "Math, Game Theory", slug: "game-of-nim" },
  { id: 1909, title: "Remove One Element to Make the Array Strictly Increasing", diff: "Easy", topics: "Array", slug: "remove-one-element-to-make-the-array-strictly-increasing" },
  { id: 1910, title: "Remove All Occurrences of a Substring", diff: "Medium", topics: "String, Stack, String Matching", slug: "remove-all-occurrences-of-a-substring" },
  { id: 1911, title: "Maximum Alternating Subsequence Sum", diff: "Medium", topics: "Array, Dynamic Programming", slug: "maximum-alternating-subsequence-sum" },
  { id: 1912, title: "Design Movie Rental System", diff: "Hard", topics: "Hash Table, Design, Heap (Priority Queue), Ordered Set", slug: "design-movie-rental-system" },
  { id: 1913, title: "Maximum Product Difference Between Two Pairs", diff: "Easy", topics: "Array, Sorting", slug: "maximum-product-difference-between-two-pairs" },
  { id: 1914, title: "Cyclically Rotating a Grid", diff: "Medium", topics: "Array, Matrix, Simulation", slug: "cyclically-rotating-a-grid" },
  { id: 1915, title: "Number of Wonderful Substrings", diff: "Medium", topics: "Hash Table, String, Bit Manipulation, Prefix Sum", slug: "number-of-wonderful-substrings" },
  { id: 1916, title: "Count Ways to Build Rooms in an Ant Colony", diff: "Hard", topics: "Tree, Dynamic Programming, Combinatorics", slug: "count-ways-to-build-rooms-in-an-ant-colony" },
  { id: 1917, title: "Leetcodify Friends Recommendations", diff: "Hard", topics: "Database", slug: "leetcodify-friends-recommendations" },
  { id: 1918, title: "Kth Smallest Subarray Sum", diff: "Hard", topics: "Array, Binary Search, Sliding Window", slug: "kth-smallest-subarray-sum" },
  { id: 1919, title: "Leetcodify Similar Friends", diff: "Hard", topics: "Database", slug: "leetcodify-similar-friends" },
  { id: 1920, title: "Build Array from Permutation", diff: "Easy", topics: "Array", slug: "build-array-from-permutation" },
  { id: 1921, title: "Eliminate Maximum Number of Monsters", diff: "Medium", topics: "Array, Greedy, Sorting", slug: "eliminate-maximum-number-of-monsters" },
  { id: 1922, title: "Count Good Numbers", diff: "Medium", topics: "Math, Recursion", slug: "count-good-numbers" },
  { id: 1923, title: "Longest Common Subpath", diff: "Hard", topics: "Array, Binary Search, Rolling Hash, Suffix Array, Hash Function", slug: "longest-common-subpath" },
  { id: 1924, title: "Erect the Fence II", diff: "Hard", topics: "Geometry, Math, Randomized", slug: "erect-the-fence-ii" },
  { id: 1925, title: "Count Square Sum Triples", diff: "Easy", topics: "Math, Enumeration", slug: "count-square-sum-triples" },
  { id: 1926, title: "Nearest Exit from Entrance in Maze", diff: "Medium", topics: "Array, Breadth-First Search, Matrix", slug: "nearest-exit-from-entrance-in-maze" },
  { id: 1927, title: "Sum Game", diff: "Medium", topics: "Math, Greedy, Game Theory", slug: "sum-game" },
  { id: 1928, title: "Minimum Cost to Reach Destination in Time", diff: "Hard", topics: "Dynamic Programming, Graph, Heap (Priority Queue), Shortest Path", slug: "minimum-cost-to-reach-destination-in-time" },
  { id: 1929, title: "Concatenation of Array", diff: "Easy", topics: "Array", slug: "concatenation-of-array" },
  { id: 1930, title: "Unique Length-3 Palindromic Subsequences", diff: "Medium", topics: "Hash Table, String, Prefix Sum", slug: "unique-length-3-palindromic-subsequences" },
  { id: 1931, title: "Painting a Grid With Three Different Colors", diff: "Hard", topics: "Dynamic Programming, Bit Manipulation", slug: "painting-a-grid-with-three-different-colors" },
  { id: 1932, title: "Merge BSTs to Create Single BST", diff: "Hard", topics: "Hash Table, Tree, Depth-First Search, Binary Search Tree, Binary Tree", slug: "merge-bsts-to-create-single-bst" },
  { id: 1933, title: "Check if String Is Decomposable Into Value-Equal Substrings", diff: "Easy", topics: "String", slug: "check-if-string-is-decomposable-into-value-equal-substrings" },
  { id: 1934, title: "Confirmation Rate", diff: "Medium", topics: "Database", slug: "confirmation-rate" },
  { id: 1935, title: "Maximum Number of Words You Can Type", diff: "Easy", topics: "Hash Table, String", slug: "maximum-number-of-words-you-can-type" },
  { id: 1936, title: "Add Minimum Number of Rungs", diff: "Medium", topics: "Array, Greedy", slug: "add-minimum-number-of-rungs" },
  { id: 1937, title: "Maximum Number of Points with Cost", diff: "Medium", topics: "Array, Dynamic Programming, Matrix", slug: "maximum-number-of-points-with-cost" },
  { id: 1938, title: "Maximum Genetic Difference Query", diff: "Hard", topics: "Array, Hash Table, Bit Manipulation, Tree, Trie", slug: "maximum-genetic-difference-query" },
  { id: 1939, title: "Users That Actively Request Confirmation Messages", diff: "Easy", topics: "Database", slug: "users-that-actively-request-confirmation-messages" },
  { id: 1940, title: "Longest Common Subsequence Between Sorted Arrays", diff: "Medium", topics: "Array, Hash Table, Counting", slug: "longest-common-subsequence-between-sorted-arrays" },
  { id: 1941, title: "Check if All Characters Have Equal Number of Occurrences", diff: "Easy", topics: "Hash Table, String, Counting", slug: "check-if-all-characters-have-equal-number-of-occurrences" },
  { id: 1942, title: "The Number of the Smallest Unoccupied Chair", diff: "Medium", topics: "Array, Heap (Priority Queue), Simulation", slug: "the-number-of-the-smallest-unoccupied-chair" },
  { id: 1943, title: "Describe the Painting", diff: "Medium", topics: "Array, Prefix Sum, Ordered Set", slug: "describe-the-painting" },
  { id: 1944, title: "Number of Visible People in a Queue", diff: "Hard", topics: "Array, Stack, Monotonic Stack", slug: "number-of-visible-people-in-a-queue" },
  { id: 1945, title: "Sum of Digits of String After Convert", diff: "Easy", topics: "String, Simulation", slug: "sum-of-digits-of-string-after-convert" },
  { id: 1946, title: "Largest Number After Mutating Substring", diff: "Medium", topics: "Array, Greedy, String", slug: "largest-number-after-mutating-substring" },
  { id: 1947, title: "Maximum Compatibility Score Sum", diff: "Medium", topics: "Array, Dynamic Programming, Bit Manipulation", slug: "maximum-compatibility-score-sum" },
  { id: 1948, title: "Delete Duplicate Folders in System", diff: "Hard", topics: "Hash Table, String, Tree, Trie", slug: "delete-duplicate-folders-in-system" },
  { id: 1949, title: "Strong Friendship", diff: "Medium", topics: "Database", slug: "strong-friendship" },
  { id: 1950, title: "Maximum of Minimum Values in All Subarrays", diff: "Hard", topics: "Array, Stack, Monotonic Stack", slug: "maximum-of-minimum-values-in-all-subarrays" },
  { id: 1951, title: "All the Pairs With the Maximum Number of Common Followers", diff: "Medium", topics: "Database", slug: "all-the-pairs-with-the-maximum-number-of-common-followers" },
  { id: 1952, title: "Three Divisors", diff: "Easy", topics: "Math, Number Theory", slug: "three-divisors" },
  { id: 1953, title: "Maximum Number of Weeks for Which You Can Work", diff: "Medium", topics: "Array, Greedy", slug: "maximum-number-of-weeks-for-which-you-can-work" },
  { id: 1954, title: "Minimum Garden Perimeter to Collect Enough Apples", diff: "Medium", topics: "Math, Binary Search", slug: "minimum-garden-perimeter-to-collect-enough-apples" },
  { id: 1955, title: "Count Number of Special Subsequences", diff: "Hard", topics: "Array, Dynamic Programming", slug: "count-number-of-special-subsequences" },
  { id: 1956, title: "Minimum Time For K Virus Variants to Spread", diff: "Hard", topics: "Breadth-First Search", slug: "minimum-time-for-k-virus-variants-to-spread" },
  { id: 1957, title: "Delete Characters to Make Fancy String", diff: "Easy", topics: "String", slug: "delete-characters-to-make-fancy-string" },
  { id: 1958, title: "Check if Move is Legal", diff: "Medium", topics: "Array, Matrix, Simulation", slug: "check-if-move-is-legal" },
  { id: 1959, title: "Minimum Total Space Wasted With K Resizing Operations", diff: "Medium", topics: "Array, Dynamic Programming", slug: "minimum-total-space-wasted-with-k-resizing-operations" },
  { id: 1960, title: "Maximum Product of the Length of Two Palindromic Substrings", diff: "Hard", topics: "String, Dynamic Programming, Rolling Hash, Manacher's Algorithm", slug: "maximum-product-of-the-length-of-two-palindromic-substrings" },
  { id: 1961, title: "Check If String Is a Prefix of Array", diff: "Easy", topics: "Array, String", slug: "check-if-string-is-a-prefix-of-array" },
  { id: 1962, title: "Remove Stones to Minimize the Total", diff: "Medium", topics: "Array, Greedy, Heap (Priority Queue)", slug: "remove-stones-to-minimize-the-total" },
  { id: 1963, title: "Minimum Number of Swaps to Make the String Balanced", diff: "Medium", topics: "String, Stack, Greedy", slug: "minimum-number-of-swaps-to-make-the-string-balanced" },
  { id: 1964, title: "Find the Longest Valid Obstacle Course at Each Position", diff: "Hard", topics: "Array, Binary Search, Dynamic Programming", slug: "find-the-longest-valid-obstacle-course-at-each-position" },
  { id: 1965, title: "Employees With Missing Information", diff: "Easy", topics: "Database", slug: "employees-with-missing-information" },
  { id: 1966, title: "Binary Searchable Numbers in an Unsorted Array", diff: "Medium", topics: "Array", slug: "binary-searchable-numbers-in-an-unsorted-array" },
  { id: 1967, title: "Number of Strings That Appear as Substrings in Word", diff: "Easy", topics: "String", slug: "number-of-strings-that-appear-as-substrings-in-word" },
  { id: 1968, title: "Array With Elements Not Equal to Average of Neighbors", diff: "Medium", topics: "Array, Greedy, Sorting", slug: "array-with-elements-not-equal-to-average-of-neighbors" },
  { id: 1969, title: "Minimum Non-Zero Product of the Array Elements", diff: "Medium", topics: "Math, Greedy", slug: "minimum-non-zero-product-of-the-array-elements" },
  { id: 1970, title: "Last Day Where You Can Still Cross", diff: "Hard", topics: "Array, Binary Search, Depth-First Search, Breadth-First Search, Union Find, Matrix", slug: "last-day-where-you-can-still-cross" },
  { id: 1971, title: "Find if Path Exists in Graph", diff: "Easy", topics: "Depth-First Search, Breadth-First Search, Union Find, Graph", slug: "find-if-path-exists-in-graph" },
  { id: 1972, title: "First and Last Call On the Same Day", diff: "Hard", topics: "Database", slug: "first-and-last-call-on-the-same-day" },
  { id: 1973, title: "Count Nodes Equal to Sum of Descendants", diff: "Medium", topics: "Tree, Depth-First Search, Binary Tree", slug: "count-nodes-equal-to-sum-of-descendants" },
  { id: 1974, title: "Minimum Time to Type Word Using Special Typewriter", diff: "Easy", topics: "String, Greedy", slug: "minimum-time-to-type-word-using-special-typewriter" },
  { id: 1975, title: "Maximum Matrix Sum", diff: "Medium", topics: "Array, Greedy, Matrix", slug: "maximum-matrix-sum" },
  { id: 1976, title: "Number of Ways to Arrive at Destination", diff: "Medium", topics: "Graph, Shortest Path, Heap (Priority Queue)", slug: "number-of-ways-to-arrive-at-destination" },
  { id: 1977, title: "Number of Ways to Separate Numbers", diff: "Hard", topics: "String, Dynamic Programming, Suffix Array", slug: "number-of-ways-to-separate-numbers" },
  { id: 1978, title: "Employees Whose Manager Left the Company", diff: "Easy", topics: "Database", slug: "employees-whose-manager-left-the-company" },
  { id: 1979, title: "Find Greatest Common Divisor of Array", diff: "Easy", topics: "Array, Math, Number Theory", slug: "find-greatest-common-divisor-of-array" },
  { id: 1980, title: "Find Unique Binary String", diff: "Medium", topics: "Array, Hash Table, String, Backtracking", slug: "find-unique-binary-string" },
  { id: 1981, title: "Minimize the Difference Between Target and Chosen Elements", diff: "Medium", topics: "Array, Dynamic Programming, Matrix", slug: "minimize-the-difference-between-target-and-chosen-elements" },
  { id: 1982, title: "Find Array Given Subset Sums", diff: "Hard", topics: "Array, Divide and Conquer, Backtracking", slug: "find-array-given-subset-sums" },
  { id: 1983, title: "Widest Pair of Indices With Equal Range Sum", diff: "Medium", topics: "Array, Hash Table, Prefix Sum", slug: "widest-pair-of-indices-with-equal-range-sum" },
  { id: 1984, title: "Minimum Difference Between Highest and Lowest of K Scores", diff: "Easy", topics: "Array, Sorting", slug: "minimum-difference-between-highest-and-lowest-of-k-scores" },
  { id: 1985, title: "Find the Kth Largest Integer in the Array", diff: "Medium", topics: "Array, String, Sorting, Heap (Priority Queue)", slug: "find-the-kth-largest-integer-in-the-array" },
  { id: 1986, title: "Minimum Number of Work Sessions to Finish the Tasks", diff: "Medium", topics: "Array, Dynamic Programming, Bit Manipulation", slug: "minimum-number-of-work-sessions-to-finish-the-tasks" },
  { id: 1987, title: "Number of Unique Good Subsequences", diff: "Hard", topics: "String, Dynamic Programming", slug: "number-of-unique-good-subsequences" },
  { id: 1988, title: "Find Cutoff Score for Each School", diff: "Medium", topics: "Database", slug: "find-cutoff-score-for-each-school" },
  { id: 1989, title: "Maximum Number of People That Can Be Caught in Tag", diff: "Medium", topics: "Array, Greedy, Two Pointers", slug: "maximum-number-of-people-that-can-be-caught-in-tag" },
  { id: 1990, title: "Count the Number of Experiments", diff: "Medium", topics: "Database", slug: "count-the-number-of-experiments" },
  { id: 1991, title: "Find the Middle Index in Array", diff: "Easy", topics: "Array, Prefix Sum", slug: "find-the-middle-index-in-array" },
  { id: 1992, title: "Find All Groups of Farmland", diff: "Medium", topics: "Array, Depth-First Search, Breadth-First Search, Matrix", slug: "find-all-groups-of-farmland" },
  { id: 1993, title: "Operations on Tree", diff: "Medium", topics: "Hash Table, Tree, Design", slug: "operations-on-tree" },
  { id: 1994, title: "The Number of Good Subsets", diff: "Hard", topics: "Array, Dynamic Programming, Bit Manipulation, Counting", slug: "the-number-of-good-subsets" },
  { id: 1995, title: "Count Special Quadruplets", diff: "Easy", topics: "Array, Hash Table, Enumeration", slug: "count-special-quadruplets" },
  { id: 1996, title: "The Number of Weak Characters in the Game", diff: "Medium", topics: "Array, Greedy, Sorting", slug: "the-number-of-weak-characters-in-the-game" },
  { id: 1997, title: "First Day Where You Have Been in All the Rooms", diff: "Medium", topics: "Dynamic Programming", slug: "first-day-where-you-have-been-in-all-the-rooms" },
  { id: 1998, title: "GCD Sort of an Array", diff: "Hard", topics: "Array, Union Find, Math, Number Theory, Sorting", slug: "gcd-sort-of-an-array" },
  { id: 1999, title: "Smallest Greater Multiple Made of Two Digits", diff: "Hard", topics: "Breadth-First Search, Math", slug: "smallest-greater-multiple-made-of-two-digits" },
  { id: 2000, title: "Reverse Prefix of Word", diff: "Easy", topics: "Two Pointers, String", slug: "reverse-prefix-of-word" }
  
);