window.rawProblems = window.rawProblems || [];

window.rawProblems.push(
  { id: 751, title: "IP to CIDR", diff: "Medium", topics: "Bit Manipulation, String", slug: "ip-to-cidr" },
  { id: 752, title: "Open the Lock", diff: "Medium", topics: "Hash Table, String, Breadth-First Search", slug: "open-the-lock" },
  { id: 753, title: "Cracking the Safe", diff: "Hard", topics: "Depth-First Search, Graph, Eulerian Circuit", slug: "cracking-the-safe" },
  { id: 754, title: "Reach a Number", diff: "Medium", topics: "Math, Binary Search", slug: "reach-a-number" },
  { id: 755, title: "Pour Water", diff: "Medium", topics: "Array, Simulation", slug: "pour-water" },
  { id: 756, title: "Pyramid Transition Matrix", diff: "Medium", topics: "Bit Manipulation, Depth-First Search, Backtracking", slug: "pyramid-transition-matrix" },
  { id: 757, title: "Set Intersection Size At Least Two", diff: "Hard", topics: "Array, Greedy, Sorting", slug: "set-intersection-size-at-least-two" },
  { id: 758, title: "Bold Words in String", diff: "Medium", topics: "Array, Hash Table, String", slug: "bold-words-in-string" },
  { id: 759, title: "Employee Free Time", diff: "Hard", topics: "Array, Line Sweep, Heap (Priority Queue), Sorting", slug: "employee-free-time" },
  { id: 760, title: "Find Anagram Mappings", diff: "Easy", topics: "Array, Hash Table", slug: "find-anagram-mappings" },
  { id: 761, title: "Special Binary String", diff: "Hard", topics: "String, Recursion", slug: "special-binary-string" },
  { id: 762, title: "Prime Number of Set Bits in Binary Representation", diff: "Easy", topics: "Bit Manipulation, Math", slug: "prime-number-of-set-bits-in-binary-representation" },
  { id: 763, title: "Partition Labels", diff: "Medium", topics: "Hash Table, Two Pointers, String, Greedy", slug: "partition-labels" },
  { id: 764, title: "Largest Plus Sign", diff: "Medium", topics: "Array, Dynamic Programming, Matrix", slug: "largest-plus-sign" },
  { id: 765, title: "Couples Holding Hands", diff: "Hard", topics: "Greedy, Depth-First Search, Breadth-First Search, Union Find, Graph", slug: "couples-holding-hands" },
  { id: 766, title: "Toeplitz Matrix", diff: "Easy", topics: "Array, Matrix", slug: "toeplitz-matrix" },
  { id: 767, title: "Reorganize String", diff: "Medium", topics: "Hash Table, String, Greedy, Heap (Priority Queue), Counting", slug: "reorganize-string" },
  { id: 768, title: "Max Chunks To Make Sorted II", diff: "Hard", topics: "Array, Stack, Greedy, Monotonic Stack, Sorting", slug: "max-chunks-to-make-sorted-ii" },
  { id: 769, title: "Max Chunks To Make Sorted", diff: "Medium", topics: "Array, Stack, Greedy, Monotonic Stack", slug: "max-chunks-to-make-sorted" },
  { id: 770, title: "Basic Calculator IV", diff: "Hard", topics: "Hash Table, Math, String, Stack", slug: "basic-calculator-iv" },
  { id: 771, title: "Jewels and Stones", diff: "Easy", topics: "Hash Table, String", slug: "jewels-and-stones" },
  { id: 772, title: "Basic Calculator III", diff: "Hard", topics: "Math, String, Stack, Recursion", slug: "basic-calculator-iii" },
  { id: 773, title: "Sliding Puzzle", diff: "Hard", topics: "Array, Breadth-First Search, Matrix", slug: "sliding-puzzle" },
  { id: 774, title: "Minimize Max Distance to Gas Station", diff: "Hard", topics: "Array, Binary Search, Greedy", slug: "minimize-max-distance-to-gas-station" },
  { id: 775, title: "Global and Local Inversions", diff: "Medium", topics: "Array, Math", slug: "global-and-local-inversions" },
  { id: 776, title: "Split BST", diff: "Medium", topics: "Tree, Binary Search Tree, Recursion, Binary Tree", slug: "split-bst" },
  { id: 777, title: "Swap Adjacent in LR String", diff: "Medium", topics: "Two Pointers, String", slug: "swap-adjacent-in-lr-string" },
  { id: 778, title: "Swim in Rising Water", diff: "Hard", topics: "Array, Binary Search, Depth-First Search, Breadth-First Search, Union Find, Heap (Priority Queue), Matrix", slug: "swim-in-rising-water" },
  { id: 779, title: "K-th Symbol in Grammar", diff: "Medium", topics: "Math, Bit Manipulation, Recursion", slug: "k-th-symbol-in-grammar" },
  { id: 780, title: "Reaching Points", diff: "Hard", topics: "Math", slug: "reaching-points" },
  { id: 781, title: "Rabbits in Forest", diff: "Medium", topics: "Array, Hash Table, Greedy", slug: "rabbits-in-forest" },
  { id: 782, title: "Transform to Chessboard", diff: "Hard", topics: "Array, Bit Manipulation, Matrix", slug: "transform-to-chessboard" },
  { id: 783, title: "Minimum Distance Between BST Nodes", diff: "Easy", topics: "Tree, Depth-First Search, Breadth-First Search, Binary Search Tree, Binary Tree", slug: "minimum-distance-between-bst-nodes" },
  { id: 784, title: "Letter Case Permutation", diff: "Medium", topics: "String, Backtracking, Bit Manipulation", slug: "letter-case-permutation" },
  { id: 785, title: "Is Graph Bipartite?", diff: "Medium", topics: "Depth-First Search, Breadth-First Search, Union Find, Graph", slug: "is-graph-bipartite" },
  { id: 786, title: "K-th Smallest Prime Fraction", diff: "Medium", topics: "Array, Binary Search, Heap (Priority Queue)", slug: "k-th-smallest-prime-fraction" },
  { id: 787, title: "Cheapest Flights Within K Stops", diff: "Medium", topics: "Dynamic Programming, Depth-First Search, Breadth-First Search, Graph, Heap (Priority Queue), Shortest Path", slug: "cheapest-flights-within-k-stops" },
  { id: 788, title: "Rotated Digits", diff: "Medium", topics: "Math, Dynamic Programming", slug: "rotated-digits" },
  { id: 789, title: "Escape The Ghosts", diff: "Medium", topics: "Array, Math", slug: "escape-the-ghosts" },
  { id: 790, title: "Domino and Tromino Tiling", diff: "Medium", topics: "Dynamic Programming", slug: "domino-and-tromino-tiling" },
  { id: 791, title: "Custom Sort String", diff: "Medium", topics: "Hash Table, String, Sorting", slug: "custom-sort-string" },
  { id: 792, title: "Number of Matching Subsequences", diff: "Medium", topics: "Array, Hash Table, String, Trie", slug: "number-of-matching-subsequences" },
  { id: 793, title: "Preimage Size of Factorial Zeroes Function", diff: "Hard", topics: "Math, Binary Search", slug: "preimage-size-of-factorial-zeroes-function" },
  { id: 794, title: "Valid Tic-Tac-Toe State", diff: "Medium", topics: "Array, Matrix", slug: "valid-tic-tac-toe-state" },
  { id: 795, title: "Number of Subarrays with Bounded Maximum", diff: "Medium", topics: "Array, Two Pointers", slug: "number-of-subarrays-with-bounded-maximum" },
  { id: 796, title: "Rotate String", diff: "Easy", topics: "String, String Matching", slug: "rotate-string" },
  { id: 797, title: "All Paths From Source to Target", diff: "Medium", topics: "Backtracking, Depth-First Search, Graph", slug: "all-paths-from-source-to-target" },
  { id: 798, title: "Smallest Rotation with Highest Score", diff: "Hard", topics: "Array, Prefix Sum", slug: "smallest-rotation-with-highest-score" },
  { id: 799, title: "Champagne Tower", diff: "Medium", topics: "Dynamic Programming, Simulation", slug: "champagne-tower" },
  { id: 800, title: "Similar RGB Color", diff: "Easy", topics: "Math, String", slug: "similar-rgb-color" },
  { id: 801, title: "Minimum Swaps To Make Sequences Increasing", diff: "Hard", topics: "Array, Dynamic Programming", slug: "minimum-swaps-to-make-sequences-increasing" },
  { id: 802, title: "Find Eventual Safe States", diff: "Medium", topics: "Depth-First Search, Breadth-First Search, Graph, Topological Sort", slug: "find-eventual-safe-states" },
  { id: 803, title: "Bricks Falling When Hit", diff: "Hard", topics: "Array, Union Find, Matrix", slug: "bricks-falling-when-hit" },
  { id: 804, title: "Unique Morse Code Words", diff: "Easy", topics: "Array, Hash Table, String", slug: "unique-morse-code-words" },
  { id: 805, title: "Split Array With Same Average", diff: "Hard", topics: "Array, Dynamic Programming, Bit Manipulation", slug: "split-array-with-same-average" },
  { id: 806, title: "Number of Lines To Write String", diff: "Easy", topics: "Array, String", slug: "number-of-lines-to-write-string" },
  { id: 807, title: "Max Increase to Keep City Skyline", diff: "Medium", topics: "Array, Greedy, Matrix", slug: "max-increase-to-keep-city-skyline" },
  { id: 808, title: "Soup Servings", diff: "Medium", topics: "Math, Dynamic Programming, Probability and Statistics", slug: "soup-servings" },
  { id: 809, title: "Expressive Words", diff: "Medium", topics: "Array, Two Pointers, String", slug: "expressive-words" },
  { id: 810, title: "Chalkboard XOR Game", diff: "Hard", topics: "Array, Math, Bit Manipulation, Game Theory", slug: "chalkboard-xor-game" },
  { id: 811, title: "Subdomain Visit Count", diff: "Medium", topics: "Array, Hash Table, String, Counting", slug: "subdomain-visit-count" },
  { id: 812, title: "Largest Triangle Area", diff: "Easy", topics: "Array, Math, Geometry", slug: "largest-triangle-area" },
  { id: 813, title: "Largest Sum of Averages", diff: "Medium", topics: "Array, Dynamic Programming", slug: "largest-sum-of-averages" },
  { id: 814, title: "Binary Tree Pruning", diff: "Medium", topics: "Tree, Depth-First Search, Binary Tree", slug: "binary-tree-pruning" },
  { id: 815, title: "Bus Routes", diff: "Hard", topics: "Array, Hash Table, Breadth-First Search", slug: "bus-routes" },
  { id: 816, title: "Ambiguous Coordinates", diff: "Medium", topics: "String, Backtracking", slug: "ambiguous-coordinates" },
  { id: 817, title: "Linked List Components", diff: "Medium", topics: "Array, Hash Table, Linked List", slug: "linked-list-components" },
  { id: 818, title: "Race Car", diff: "Hard", topics: "Dynamic Programming, Breadth-First Search", slug: "race-car" },
  { id: 819, title: "Most Common Word", diff: "Easy", topics: "Hash Table, String, Counting", slug: "most-common-word" },
  { id: 820, title: "Short Encoding of Words", diff: "Medium", topics: "Array, Hash Table, String, Trie", slug: "short-encoding-of-words" },
  { id: 821, title: "Shortest Distance to a Character", diff: "Easy", topics: "Array, Two Pointers, String", slug: "shortest-distance-to-a-character" },
  { id: 822, title: "Card Flipping Game", diff: "Medium", topics: "Array, Hash Table", slug: "card-flipping-game" },
  { id: 823, title: "Binary Trees With Factors", diff: "Medium", topics: "Array, Hash Table, Dynamic Programming, Sorting", slug: "binary-trees-with-factors" },
  { id: 824, title: "Goat Latin", diff: "Easy", topics: "String", slug: "goat-latin" },
  { id: 825, title: "Friends Of Appropriate Ages", diff: "Medium", topics: "Array, Two Pointers, Binary Search, Sorting", slug: "friends-of-appropriate-ages" },
  { id: 826, title: "Most Profit Assigning Work", diff: "Medium", topics: "Array, Two Pointers, Binary Search, Greedy, Sorting", slug: "most-profit-assigning-work" },
  { id: 827, title: "Making A Large Island", diff: "Hard", topics: "Array, Depth-First Search, Breadth-First Search, Union Find, Matrix", slug: "making-a-large-island" },
  { id: 828, title: "Count Unique Characters of All Substrings of a Given String", diff: "Hard", topics: "Hash Table, String, Dynamic Programming", slug: "count-unique-characters-of-all-substrings-of-a-given-string" },
  { id: 829, title: "Consecutive Numbers Sum", diff: "Hard", topics: "Math, Enumeration", slug: "consecutive-numbers-sum" },
  { id: 830, title: "Positions of Large Groups", diff: "Easy", topics: "Two Pointers, String", slug: "positions-of-large-groups" },
  { id: 831, title: "Masking Personal Information", diff: "Medium", topics: "String", slug: "masking-personal-information" },
  { id: 832, title: "Flipping an Image", diff: "Easy", topics: "Array, Two Pointers, Bit Manipulation, Matrix", slug: "flipping-an-image" },
  { id: 833, title: "Find And Replace in String", diff: "Medium", topics: "Array, Hash Table, String, Sorting", slug: "find-and-replace-in-string" },
  { id: 834, title: "Sum of Distances in Tree", diff: "Hard", topics: "Dynamic Programming, Tree, Depth-First Search, Breadth-First Search", slug: "sum-of-distances-in-tree" },
  { id: 835, title: "Image Overlap", diff: "Medium", topics: "Array, Matrix", slug: "image-overlap" },
  { id: 836, title: "Rectangle Overlap", diff: "Easy", topics: "Geometry, Math", slug: "rectangle-overlap" },
  { id: 837, title: "New 21 Game", diff: "Medium", topics: "Math, Dynamic Programming, Sliding Window, Probability and Statistics", slug: "new-21-game" },
  { id: 838, title: "Push Dominoes", diff: "Medium", topics: "Two Pointers, String, Dynamic Programming", slug: "push-dominoes" },
  { id: 839, title: "Similar String Groups", diff: "Hard", topics: "Array, Hash Table, String, Depth-First Search, Breadth-First Search, Union Find", slug: "similar-string-groups" },
  { id: 840, title: "Magic Squares In Grid", diff: "Medium", topics: "Array, Matrix", slug: "magic-squares-in-grid" },
  { id: 841, title: "Keys and Rooms", diff: "Medium", topics: "Depth-First Search, Breadth-First Search, Graph", slug: "keys-and-rooms" },
  { id: 842, title: "Split Array into Fibonacci Sequence", diff: "Medium", topics: "String, Backtracking", slug: "split-array-into-fibonacci-sequence" },
  { id: 843, title: "Guess the Word", diff: "Hard", topics: "Array, String, Interactive", slug: "guess-the-word" },
  { id: 844, title: "Backspace String Compare", diff: "Easy", topics: "Two Pointers, String, Stack", slug: "backspace-string-compare" },
  { id: 845, title: "Longest Mountain in Array", diff: "Medium", topics: "Array, Dynamic Programming, Two Pointers", slug: "longest-mountain-in-array" },
  { id: 846, title: "Hand of Straights", diff: "Medium", topics: "Array, Hash Table, Greedy, Sorting", slug: "hand-of-straights" },
  { id: 847, title: "Shortest Path Visiting All Nodes", diff: "Hard", topics: "Dynamic Programming, Bit Manipulation, Breadth-First Search, Graph", slug: "shortest-path-visiting-all-nodes" },
  { id: 848, title: "Shifting Letters", diff: "Medium", topics: "Array, String, Prefix Sum", slug: "shifting-letters" },
  { id: 849, title: "Maximize Distance to Closest Person", diff: "Medium", topics: "Array", slug: "maximize-distance-to-closest-person" },
  { id: 850, title: "Rectangle Area II", diff: "Hard", topics: "Array, Line Sweep, Segment Tree, Geometry", slug: "rectangle-area-ii" },
  { id: 851, title: "Loud and Rich", diff: "Medium", topics: "Depth-First Search, Breadth-First Search, Graph, Topological Sort", slug: "loud-and-rich" },
  { id: 852, title: "Peak Index in a Mountain Array", diff: "Medium", topics: "Array, Binary Search", slug: "peak-index-in-a-mountain-array" },
  { id: 853, title: "Car Fleet", diff: "Medium", topics: "Array, Stack, Sorting", slug: "car-fleet" },
  { id: 854, title: "K-Similar Strings", diff: "Hard", topics: "Hash Table, String, Breadth-First Search", slug: "k-similar-strings" },
  { id: 855, title: "Exam Room", diff: "Medium", topics: "Design, Ordered Set", slug: "exam-room" },
  { id: 856, title: "Score of Parentheses", diff: "Medium", topics: "String, Stack", slug: "score-of-parentheses" },
  { id: 857, title: "Minimum Cost to Hire K Workers", diff: "Hard", topics: "Array, Greedy, Sorting, Heap (Priority Queue)", slug: "minimum-cost-to-hire-k-workers" },
  { id: 858, title: "Mirror Reflection", diff: "Medium", topics: "Math, Geometry", slug: "mirror-reflection" },
  { id: 859, title: "Buddy Strings", diff: "Easy", topics: "Hash Table, String", slug: "buddy-strings" },
  { id: 860, title: "Lemonade Change", diff: "Easy", topics: "Array, Greedy", slug: "lemonade-change" },
  { id: 861, title: "Score After Flipping Matrix", diff: "Medium", topics: "Array, Greedy, Bit Manipulation, Matrix", slug: "score-after-flipping-matrix" },
  { id: 862, title: "Shortest Subarray with Sum at Least K", diff: "Hard", topics: "Array, Binary Search, Prefix Sum, Queue, Monotonic Queue", slug: "shortest-subarray-with-sum-at-least-k" },
  { id: 863, title: "All Nodes Distance K in Binary Tree", diff: "Medium", topics: "Hash Table, Tree, Depth-First Search, Breadth-First Search, Binary Tree", slug: "all-nodes-distance-k-in-binary-tree" },
  { id: 864, title: "Shortest Path to Get All Keys", diff: "Hard", topics: "Array, Bit Manipulation, Breadth-First Search, Matrix", slug: "shortest-path-to-get-all-keys" },
  { id: 865, title: "Smallest Subtree with all the Deepest Nodes", diff: "Medium", topics: "Hash Table, Tree, Depth-First Search, Breadth-First Search, Binary Tree", slug: "smallest-subtree-with-all-the-deepest-nodes" },
  { id: 866, title: "Prime Palindrome", diff: "Medium", topics: "Math, Number Theory", slug: "prime-palindrome" },
  { id: 867, title: "Transpose Matrix", diff: "Easy", topics: "Array, Matrix, Simulation", slug: "transpose-matrix" },
  { id: 868, title: "Binary Gap", diff: "Easy", topics: "Bit Manipulation", slug: "binary-gap" },
  { id: 869, title: "Reordered Power of 2", diff: "Medium", topics: "Math, Counting, Enumeration", slug: "reordered-power-of-2" },
  { id: 870, title: "Advantage Shuffle", diff: "Medium", topics: "Array, Two Pointers, Greedy, Sorting", slug: "advantage-shuffle" },
  { id: 871, title: "Minimum Number of Refueling Stops", diff: "Hard", topics: "Array, Dynamic Programming, Greedy, Heap (Priority Queue)", slug: "minimum-number-of-refueling-stops" },
  { id: 872, title: "Leaf-Similar Trees", diff: "Easy", topics: "Tree, Depth-First Search, Binary Tree", slug: "leaf-similar-trees" },
  { id: 873, title: "Length of Longest Fibonacci Subsequence", diff: "Medium", topics: "Array, Hash Table, Dynamic Programming", slug: "length-of-longest-fibonacci-subsequence" },
  { id: 874, title: "Walking Robot Simulation", diff: "Medium", topics: "Array, Hash Table, Simulation", slug: "walking-robot-simulation" },
  { id: 875, title: "Koko Eating Bananas", diff: "Medium", topics: "Array, Binary Search", slug: "koko-eating-bananas" },
  { id: 876, title: "Middle of the Linked List", diff: "Easy", topics: "Linked List, Two Pointers", slug: "middle-of-the-linked-list" },
  { id: 877, title: "Stone Game", diff: "Medium", topics: "Array, Math, Dynamic Programming, Game Theory", slug: "stone-game" },
  { id: 878, title: "Nth Magical Number", diff: "Hard", topics: "Math, Binary Search, Number Theory", slug: "nth-magical-number" },
  { id: 879, title: "Profitable Schemes", diff: "Hard", topics: "Array, Dynamic Programming", slug: "profitable-schemes" },
  { id: 880, title: "Decoded String at Index", diff: "Medium", topics: "String", slug: "decoded-string-at-index" },
  { id: 881, title: "Boats to Save People", diff: "Medium", topics: "Array, Two Pointers, Greedy, Sorting", slug: "boats-to-save-people" },
  { id: 882, title: "Reachable Nodes In Subdivided Graph", diff: "Hard", topics: "Graph, Heap (Priority Queue), Shortest Path", slug: "reachable-nodes-in-subdivided-graph" },
  { id: 883, title: "Projection Area of 3D Shapes", diff: "Easy", topics: "Array, Geometry, Matrix", slug: "projection-area-of-3d-shapes" },
  { id: 884, title: "Uncommon Words from Two Sentences", diff: "Easy", topics: "Hash Table, String, Counting", slug: "uncommon-words-from-two-sentences" },
  { id: 885, title: "Spiral Matrix III", diff: "Medium", topics: "Array, Matrix, Simulation", slug: "spiral-matrix-iii" },
  { id: 886, title: "Possible Bipartition", diff: "Medium", topics: "Depth-First Search, Breadth-First Search, Union Find, Graph", slug: "possible-bipartition" },
  { id: 887, title: "Super Egg Drop", diff: "Hard", topics: "Math, Binary Search, Dynamic Programming", slug: "super-egg-drop" },
  { id: 888, title: "Fair Candy Swap", diff: "Easy", topics: "Array, Hash Table, Binary Search, Sorting", slug: "fair-candy-swap" },
  { id: 889, title: "Construct Binary Tree from Preorder and Postorder Traversal", diff: "Medium", topics: "Array, Hash Table, Divide and Conquer, Tree, Binary Tree", slug: "construct-binary-tree-from-preorder-and-postorder-traversal" },
  { id: 890, title: "Find and Replace Pattern", diff: "Medium", topics: "Array, Hash Table, String", slug: "find-and-replace-pattern" },
  { id: 891, title: "Sum of Subsequence Widths", diff: "Hard", topics: "Array, Math, Sorting", slug: "sum-of-subsequence-widths" },
  { id: 892, title: "Surface Area of 3D Shapes", diff: "Easy", topics: "Array, Geometry, Matrix", slug: "surface-area-of-3d-shapes" },
  { id: 893, title: "Groups of Special-Equivalent Strings", diff: "Easy", topics: "Array, Hash Table, String, Sorting", slug: "groups-of-special-equivalent-strings" },
  { id: 894, title: "All Possible Full Binary Trees", diff: "Medium", topics: "Dynamic Programming, Memoization, Tree, Binary Tree", slug: "all-possible-full-binary-trees" },
  { id: 895, title: "Maximum Frequency Stack", diff: "Hard", topics: "Hash Table, Stack, Design", slug: "maximum-frequency-stack" },
  { id: 896, title: "Monotonic Array", diff: "Easy", topics: "Array", slug: "monotonic-array" },
  { id: 897, title: "Increasing Order Search Tree", diff: "Easy", topics: "Stack, Tree, Depth-First Search, Binary Search Tree, Binary Tree", slug: "increasing-order-search-tree" },
  { id: 898, title: "Bitwise ORs of Subarrays", diff: "Medium", topics: "Array, Bit Manipulation", slug: "bitwise-ors-of-subarrays" },
  { id: 899, title: "Orderly Queue", diff: "Hard", topics: "Math, String, Sorting", slug: "orderly-queue" },
  { id: 900, title: "RLE Iterator", diff: "Medium", topics: "Array, Design, Counting, Iterator", slug: "rle-iterator" },
  { id: 901, title: "Online Stock Span", diff: "Medium", topics: "Stack, Design, Data Stream, Monotonic Stack", slug: "online-stock-span" },
  { id: 902, title: "Numbers At Most N Given Digit Set", diff: "Hard", topics: "Array, Math, Dynamic Programming", slug: "numbers-at-most-n-given-digit-set" },
  { id: 903, title: "Valid Permutations for DI Sequence", diff: "Hard", topics: "String, Dynamic Programming", slug: "valid-permutations-for-di-sequence" },
  { id: 904, title: "Fruit Into Baskets", diff: "Medium", topics: "Array, Hash Table, Sliding Window", slug: "fruit-into-baskets" },
  { id: 905, title: "Sort Array By Parity", diff: "Easy", topics: "Array, Two Pointers, Sorting", slug: "sort-array-by-parity" },
  { id: 906, title: "Super Palindromes", diff: "Hard", topics: "Math, Enumeration", slug: "super-palindromes" },
  { id: 907, title: "Sum of Subarray Minimums", diff: "Medium", topics: "Array, Dynamic Programming, Stack, Monotonic Stack", slug: "sum-of-subarray-minimums" },
  { id: 908, title: "Smallest Range I", diff: "Easy", topics: "Array, Math", slug: "smallest-range-i" },
  { id: 909, title: "Snakes and Ladders", diff: "Medium", topics: "Array, Breadth-First Search, Matrix", slug: "snakes-and-ladders" },
  { id: 910, title: "Smallest Range II", diff: "Medium", topics: "Array, Greedy, Sorting", slug: "smallest-range-ii" },
  { id: 911, title: "Online Election", diff: "Medium", topics: "Array, Hash Table, Binary Search, Design", slug: "online-election" },
  { id: 912, title: "Sort an Array", diff: "Medium", topics: "Array, Divide and Conquer, Sorting, Heap (Priority Queue), Merge Sort, Bucket Sort, Radix Sort, Counting Sort", slug: "sort-an-array" },
  { id: 913, title: "Cat and Mouse", diff: "Hard", topics: "Graph, Topological Sort, Game Theory", slug: "cat-and-mouse" },
  { id: 914, title: "X of a Kind in a Deck of Cards", diff: "Easy", topics: "Array, Hash Table, Math, Counting, Number Theory", slug: "x-of-a-kind-in-a-deck-of-cards" },
  { id: 915, title: "Partition Array into Disjoint Intervals", diff: "Medium", topics: "Array", slug: "partition-array-into-disjoint-intervals" },
  { id: 916, title: "Word Subsets", diff: "Medium", topics: "Array, Hash Table, String, Counting", slug: "word-subsets" },
  { id: 917, title: "Reverse Only Letters", diff: "Easy", topics: "Two Pointers, String", slug: "reverse-only-letters" },
  { id: 918, title: "Maximum Sum Circular Subarray", diff: "Medium", topics: "Array, Divide and Conquer, Dynamic Programming, Queue, Monotonic Queue", slug: "maximum-sum-circular-subarray" },
  { id: 919, title: "Complete Binary Tree Inserter", diff: "Medium", topics: "Tree, Breadth-First Search, Design, Binary Tree", slug: "complete-binary-tree-inserter" },
  { id: 920, title: "Number of Music Playlists", diff: "Hard", topics: "Dynamic Programming, Combinatorics", slug: "number-of-music-playlists" },
  { id: 921, title: "Minimum Add to Make Parentheses Valid", diff: "Medium", topics: "String, Stack, Greedy", slug: "minimum-add-to-make-parentheses-valid" },
  { id: 922, title: "Sort Array By Parity II", diff: "Easy", topics: "Array, Two Pointers, Sorting", slug: "sort-array-by-parity-ii" },
  { id: 923, title: "3Sum With Multiplicity", diff: "Medium", topics: "Array, Hash Table, Two Pointers, Sorting, Counting", slug: "3sum-with-multiplicity" },
  { id: 924, title: "Minimize Malware Spread", diff: "Hard", topics: "Depth-First Search, Breadth-First Search, Union Find, Graph", slug: "minimize-malware-spread" },
  { id: 925, title: "Long Pressed Name", diff: "Easy", topics: "Two Pointers, String", slug: "long-pressed-name" },
  { id: 926, title: "Flip String to Monotone Increasing", diff: "Medium", topics: "String, Dynamic Programming", slug: "flip-string-to-monotone-increasing" },
  { id: 927, title: "Three Equal Parts", diff: "Hard", topics: "Array, Math", slug: "three-equal-parts" },
  { id: 928, title: "Minimize Malware Spread II", diff: "Hard", topics: "Depth-First Search, Breadth-First Search, Union Find, Graph", slug: "minimize-malware-spread-ii" },
  { id: 929, title: "Unique Email Addresses", diff: "Easy", topics: "Array, Hash Table, String", slug: "unique-email-addresses" },
  { id: 930, title: "Binary Subarrays With Sum", diff: "Medium", topics: "Array, Hash Table, Sliding Window, Prefix Sum", slug: "binary-subarrays-with-sum" },
  { id: 931, title: "Minimum Falling Path Sum", diff: "Medium", topics: "Array, Dynamic Programming, Matrix", slug: "minimum-falling-path-sum" },
  { id: 932, title: "Beautiful Array", diff: "Medium", topics: "Divide and Conquer, Memoization", slug: "beautiful-array" },
  { id: 933, title: "Number of Recent Calls", diff: "Easy", topics: "Design, Queue, Data Stream", slug: "number-of-recent-calls" },
  { id: 934, title: "Shortest Bridge", diff: "Medium", topics: "Array, Depth-First Search, Breadth-First Search, Matrix", slug: "shortest-bridge" },
  { id: 935, title: "Knight Dialer", diff: "Medium", topics: "Dynamic Programming", slug: "knight-dialer" },
  { id: 936, title: "Stamping The Sequence", diff: "Hard", topics: "String, Greedy", slug: "stamping-the-sequence" },
  { id: 937, title: "Reorder Data in Log Files", diff: "Easy", topics: "Array, String, Sorting", slug: "reorder-data-in-log-files" },
  { id: 938, title: "Range Sum of BST", diff: "Easy", topics: "Tree, Depth-First Search, Binary Search Tree, Binary Tree", slug: "range-sum-of-bst" },
  { id: 939, title: "Minimum Area Rectangle", diff: "Medium", topics: "Array, Hash Table, Geometry", slug: "minimum-area-rectangle" },
  { id: 940, title: "Distinct Subsequences II", diff: "Hard", topics: "String, Dynamic Programming", slug: "distinct-subsequences-ii" },
  { id: 941, title: "Valid Mountain Array", diff: "Easy", topics: "Array", slug: "valid-mountain-array" },
  { id: 942, title: "DI String Match", diff: "Easy", topics: "Array, Two Pointers, String, Greedy", slug: "di-string-match" },
  { id: 943, title: "Find the Shortest Superstring", diff: "Hard", topics: "Array, String, Dynamic Programming, Bit Manipulation", slug: "find-the-shortest-superstring" },
  { id: 944, title: "Delete Columns to Make Sorted", diff: "Easy", topics: "Array, String", slug: "delete-columns-to-make-sorted" },
  { id: 945, title: "Minimum Increment to Make Array Unique", diff: "Medium", topics: "Array, Greedy, Sorting, Counting", slug: "minimum-increment-to-make-array-unique" },
  { id: 946, title: "Validate Stack Sequences", diff: "Medium", topics: "Array, Stack, Simulation", slug: "validate-stack-sequences" },
  { id: 947, title: "Most Stones Removed with Same Row or Column", diff: "Medium", topics: "Depth-First Search, Union Find, Graph", slug: "most-stones-removed-with-same-row-or-column" },
  { id: 948, title: "Bag of Tokens", diff: "Medium", topics: "Array, Two Pointers, Greedy, Sorting", slug: "bag-of-tokens" },
  { id: 949, title: "Largest Time for Given Digits", diff: "Medium", topics: "Array, String, Enumeration", slug: "largest-time-for-given-digits" },
  { id: 950, title: "Reveal Cards In Increasing Order", diff: "Medium", topics: "Array, Queue, Sorting", slug: "reveal-cards-in-increasing-order" },
  { id: 951, title: "Flip Equivalent Binary Trees", diff: "Medium", topics: "Tree, Depth-First Search, Binary Tree", slug: "flip-equivalent-binary-trees" },
  { id: 952, title: "Largest Component Size by Common Factor", diff: "Hard", topics: "Array, Hash Table, Math, Union Find, Number Theory", slug: "largest-component-size-by-common-factor" },
  { id: 953, title: "Verifying an Alien Dictionary", diff: "Easy", topics: "Array, Hash Table, String", slug: "verifying-an-alien-dictionary" },
  { id: 954, title: "Array of Doubled Pairs", diff: "Medium", topics: "Array, Hash Table, Greedy, Sorting", slug: "array-of-doubled-pairs" },
  { id: 955, title: "Delete Columns to Make Sorted II", diff: "Medium", topics: "Array, String, Greedy", slug: "delete-columns-to-make-sorted-ii" },
  { id: 956, title: "Tallest Billboard", diff: "Hard", topics: "Array, Dynamic Programming", slug: "tallest-billboard" },
  { id: 957, title: "Prison Cells After N Days", diff: "Medium", topics: "Array, Hash Table, Bit Manipulation, Simulation", slug: "prison-cells-after-n-days" },
  { id: 958, title: "Check Completeness of a Binary Tree", diff: "Medium", topics: "Tree, Breadth-First Search, Binary Tree", slug: "check-completeness-of-a-binary-tree" },
  { id: 959, title: "Regions Cut By Slashes", diff: "Medium", topics: "Array, Depth-First Search, Breadth-First Search, Union Find, Matrix", slug: "regions-cut-by-slashes" },
  { id: 960, title: "Delete Columns to Make Sorted III", diff: "Hard", topics: "Array, String, Dynamic Programming", slug: "delete-columns-to-make-sorted-iii" },
  { id: 961, title: "N-Repeated Element in Size 2N Array", diff: "Easy", topics: "Array, Hash Table", slug: "n-repeated-element-in-size-2n-array" },
  { id: 962, title: "Maximum Width Ramp", diff: "Medium", topics: "Array, Stack, Monotonic Stack", slug: "maximum-width-ramp" },
  { id: 963, title: "Minimum Area Rectangle II", diff: "Medium", topics: "Array, Math, Geometry", slug: "minimum-area-rectangle-ii" },
  { id: 964, title: "Least Operators to Express Number", diff: "Hard", topics: "Dynamic Programming, Math", slug: "least-operators-to-express-number" },
  { id: 965, title: "Univalued Binary Tree", diff: "Easy", topics: "Tree, Depth-First Search, Breadth-First Search, Binary Tree", slug: "univalued-binary-tree" },
  { id: 966, title: "Vowel Spellchecker", diff: "Medium", topics: "Array, Hash Table, String", slug: "vowel-spellchecker" },
  { id: 967, title: "Numbers With Same Consecutive Differences", diff: "Medium", topics: "Backtracking, Breadth-First Search", slug: "numbers-with-same-consecutive-differences" },
  { id: 968, title: "Binary Tree Cameras", diff: "Hard", topics: "Dynamic Programming, Tree, Depth-First Search, Binary Tree", slug: "binary-tree-cameras" },
  { id: 969, title: "Pancake Sorting", diff: "Medium", topics: "Array, Greedy, Sorting", slug: "pancake-sorting" },
  { id: 970, title: "Powerful Integers", diff: "Medium", topics: "Hash Table, Math", slug: "powerful-integers" },
  { id: 971, title: "Flip Binary Tree To Match Preorder Traversal", diff: "Medium", topics: "Tree, Depth-First Search, Binary Tree", slug: "flip-binary-tree-to-match-preorder-traversal" },
  { id: 972, title: "Equal Rational Numbers", diff: "Hard", topics: "Math, String", slug: "equal-rational-numbers" },
  { id: 973, title: "K Closest Points to Origin", diff: "Medium", topics: "Array, Math, Divide and Conquer, Geometry, Sorting, Heap (Priority Queue), Quickselect", slug: "k-closest-points-to-origin" },
  { id: 974, title: "Subarray Sums Divisible by K", diff: "Medium", topics: "Array, Hash Table, Prefix Sum", slug: "subarray-sums-divisible-by-k" },
  { id: 975, title: "Odd Even Jump", diff: "Hard", topics: "Array, Dynamic Programming, Ordered Set, Monotonic Stack", slug: "odd-even-jump" },
  { id: 976, title: "Largest Perimeter Triangle", diff: "Easy", topics: "Array, Greedy, Math, Sorting", slug: "largest-perimeter-triangle" },
  { id: 977, title: "Squares of a Sorted Array", diff: "Easy", topics: "Array, Two Pointers, Sorting", slug: "squares-of-a-sorted-array" },
  { id: 978, title: "Longest Turbulent Subarray", diff: "Medium", topics: "Array, Dynamic Programming, Sliding Window", slug: "longest-turbulent-subarray" },
  { id: 979, title: "Distribute Coins in Binary Tree", diff: "Medium", topics: "Tree, Depth-First Search, Binary Tree", slug: "distribute-coins-in-binary-tree" },
  { id: 980, title: "Unique Paths III", diff: "Hard", topics: "Array, Backtracking, Bit Manipulation, Matrix", slug: "unique-paths-iii" },
  { id: 981, title: "Time Based Key-Value Store", diff: "Medium", topics: "Hash Table, String, Binary Search, Design", slug: "time-based-key-value-store" },
  { id: 982, title: "Triples with Bitwise AND Equal To Zero", diff: "Hard", topics: "Array, Hash Table, Bit Manipulation", slug: "triples-with-bitwise-and-equal-to-zero" },
  { id: 983, title: "Minimum Cost For Tickets", diff: "Medium", topics: "Array, Dynamic Programming", slug: "minimum-cost-for-tickets" },
  { id: 984, title: "String Without AAA or BBB", diff: "Medium", topics: "String, Greedy", slug: "string-without-aaa-or-bbb" },
  { id: 985, title: "Sum of Even Numbers After Queries", diff: "Medium", topics: "Array, Simulation", slug: "sum-of-even-numbers-after-queries" },
  { id: 986, title: "Interval List Intersections", diff: "Medium", topics: "Array, Two Pointers", slug: "interval-list-intersections" },
  { id: 987, title: "Vertical Order Traversal of a Binary Tree", diff: "Hard", topics: "Hash Table, Tree, Depth-First Search, Breadth-First Search, Binary Tree", slug: "vertical-order-traversal-of-a-binary-tree" },
  { id: 988, title: "Smallest String Starting From Leaf", diff: "Medium", topics: "String, Tree, Depth-First Search, Binary Tree", slug: "smallest-string-starting-from-leaf" },
  { id: 989, title: "Add to Array-Form of Integer", diff: "Easy", topics: "Array, Math", slug: "add-to-array-form-of-integer" },
  { id: 990, title: "Satisfiability of Equality Equations", diff: "Medium", topics: "Array, String, Union Find, Graph", slug: "satisfiability-of-equality-equations" },
  { id: 991, title: "Broken Calculator", diff: "Medium", topics: "Math, Greedy", slug: "broken-calculator" },
  { id: 992, title: "Subarrays with K Different Integers", diff: "Hard", topics: "Array, Hash Table, Sliding Window", slug: "subarrays-with-k-different-integers" },
  { id: 993, title: "Cousins in Binary Tree", diff: "Easy", topics: "Tree, Depth-First Search, Breadth-First Search, Binary Tree", slug: "cousins-in-binary-tree" },
  { id: 994, title: "Rotting Oranges", diff: "Medium", topics: "Array, Breadth-First Search, Matrix", slug: "rotting-oranges" },
  { id: 995, title: "Minimum Number of K Consecutive Bit Flips", diff: "Hard", topics: "Array, Bit Manipulation, Queue, Prefix Sum, Sliding Window", slug: "minimum-number-of-k-consecutive-bit-flips" },
  { id: 996, title: "Number of Squareful Arrays", diff: "Hard", topics: "Array, Dynamic Programming, Backtracking, Bit Manipulation", slug: "number-of-squareful-arrays" },
  { id: 997, title: "Find the Town Judge", diff: "Easy", topics: "Array, Hash Table, Graph", slug: "find-the-town-judge" },
  { id: 998, title: "Maximum Binary Tree II", diff: "Medium", topics: "Tree, Binary Tree", slug: "maximum-binary-tree-ii" },
  { id: 999, title: "Available Captures for Rook", diff: "Easy", topics: "Array, Matrix, Simulation", slug: "available-captures-for-rook" },
  { id: 1000, title: "Minimum Cost to Merge Stones", diff: "Hard", topics: "Array, Dynamic Programming", slug: "minimum-cost-to-merge-stones" }
);