window.rawProblems = window.rawProblems || [];

window.rawProblems.push(
  { id: 2251, title: "Number of Flowers in Full Bloom", diff: "Hard", topics: "Array, Binary Search, Prefix Sum, Sorting", slug: "number-of-flowers-in-full-bloom" },
  { id: 2252, title: "Dynamic Unpivoting of a Table", diff: "Medium", topics: "Database", slug: "dynamic-unpivoting-of-a-table" },
  { id: 2253, title: "Dynamic Pivoting of a Table", diff: "Hard", topics: "Database", slug: "dynamic-pivoting-of-a-table" },
  { id: 2254, title: "Design Video Sharing Platform", diff: "Hard", topics: "Hash Table, Design, Heap (Priority Queue)", slug: "design-video-sharing-platform" },
  { id: 2255, title: "Count Prefixes of a Given String", diff: "Easy", topics: "String", slug: "count-prefixes-of-a-given-string" },
  { id: 2256, title: "Minimum Average Difference", diff: "Medium", topics: "Array, Prefix Sum", slug: "minimum-average-difference" },
  { id: 2257, title: "Count Unguarded Cells in the Grid", diff: "Medium", topics: "Array, Matrix, Simulation", slug: "count-unguarded-cells-in-the-grid" },
  { id: 2258, title: "Escape the Spreading Fire", diff: "Hard", topics: "Array, Breadth-First Search, Binary Search, Matrix", slug: "escape-the-spreading-fire" },
  { id: 2259, title: "Remove Digit From Number to Maximize Result", diff: "Easy", topics: "String, Greedy", slug: "remove-digit-from-number-to-maximize-result" },
  { id: 2260, title: "Minimum Consecutive Cards to Pick Up", diff: "Medium", topics: "Array, Hash Table, Sliding Window", slug: "minimum-consecutive-cards-to-pick-up" },
  { id: 2261, title: "K Divisible Elements Subarrays", diff: "Hard", topics: "Array, Trie, Rolling Hash, Hash Function", slug: "k-divisible-elements-subarrays" },
  { id: 2262, title: "Total Appeal of A String", diff: "Hard", topics: "Hash Table, String", slug: "total-appeal-of-a-string" },
  { id: 2263, title: "Make Array Non-decreasing or Non-increasing", diff: "Hard", topics: "Array, Dynamic Programming, Heap (Priority Queue)", slug: "make-array-non-decreasing-or-non-increasing" },
  { id: 2264, title: "Largest 3-Same-Digit Number in String", diff: "Easy", topics: "String", slug: "largest-3-same-digit-number-in-string" },
  { id: 2265, title: "Count Nodes Equal to Average of Subtree", diff: "Medium", topics: "Tree, Depth-First Search, Binary Tree", slug: "count-nodes-equal-to-average-of-subtree" },
  { id: 2266, title: "Count Number of Texts", diff: "Medium", topics: "String, Dynamic Programming", slug: "count-number-of-texts" },
  { id: 2267, title: "Check if There Is a Valid Parentheses String Path", diff: "Hard", topics: "Array, Dynamic Programming, Matrix", slug: "check-if-there-is-a-valid-parentheses-string-path" },
  { id: 2268, title: "Minimum Number of Keypresses", diff: "Medium", topics: "Hash Table, String, Greedy, Sorting", slug: "minimum-number-of-keypresses" },
  { id: 2269, title: "Find the K-Beauty of a Number", diff: "Easy", topics: "Math, String, Sliding Window", slug: "find-the-k-beauty-of-a-number" },
  { id: 2270, title: "Number of Ways to Split Array", diff: "Medium", topics: "Array, Prefix Sum", slug: "number-of-ways-to-split-array" },
  { id: 2271, title: "Maximum White Tiles Covered by a Carpet", diff: "Medium", topics: "Array, Binary Search, Sliding Window, Sorting", slug: "maximum-white-tiles-covered-by-a-carpet" },
  { id: 2272, title: "Substring With Largest Variance", diff: "Hard", topics: "String, Dynamic Programming, Greedy", slug: "substring-with-largest-variance" },
  { id: 2273, title: "Find Resultant Array After Removing Anagrams", diff: "Easy", topics: "Array, Hash Table, String, Sorting", slug: "find-resultant-array-after-removing-anagrams" },
  { id: 2274, title: "Maximum Consecutive Floors Without Special Floors", diff: "Medium", topics: "Array, Sorting", slug: "maximum-consecutive-floors-without-special-floors" },
  { id: 2275, title: "Largest Combination With Bitwise AND Greater Than Zero", diff: "Medium", topics: "Array, Bit Manipulation", slug: "largest-combination-with-bitwise-and-greater-than-zero" },
  { id: 2276, title: "Count Integers in Intervals", diff: "Hard", topics: "Design, Segment Tree, Ordered Set", slug: "count-integers-in-intervals" },
  { id: 2277, title: "Closest Node to Path in Tree", diff: "Hard", topics: "Tree, Depth-First Search, Lowest Common Ancestor", slug: "closest-node-to-path-in-tree" },
  { id: 2278, title: "Percentage of Letter in String", diff: "Easy", topics: "String", slug: "percentage-of-letter-in-string" },
  { id: 2279, title: "Maximum Bags With Full Capacity of Rocks", diff: "Medium", topics: "Array, Greedy, Sorting", slug: "maximum-bags-with-full-capacity-of-rocks" },
  { id: 2280, title: "Minimum Lines to Represent a Line Chart", diff: "Medium", topics: "Array, Geometry, Math, Sorting", slug: "minimum-lines-to-represent-a-line-chart" },
  { id: 2281, title: "Sum of Total Strength of Wizards", diff: "Hard", topics: "Array, Stack, Prefix Sum, Monotonic Stack", slug: "sum-of-total-strength-of-wizards" },
  { id: 2282, title: "Number of People That Can Be Seen in a Grid", diff: "Medium", topics: "Array, Matrix, Monotonic Stack", slug: "number-of-people-that-can-be-seen-in-a-grid" },
  { id: 2283, title: "Check if Number Has Equal Digit Count and Digit Value", diff: "Easy", topics: "Hash Table, String, Counting", slug: "check-if-number-has-equal-digit-count-and-digit-value" },
  { id: 2284, title: "Sender With Largest Word Count", diff: "Medium", topics: "Hash Table, String", slug: "sender-with-largest-word-count" },
  { id: 2285, title: "Maximum Total Importance of Roads", diff: "Medium", topics: "Greedy, Graph, Sorting", slug: "maximum-total-importance-of-roads" },
  { id: 2286, title: "Booking Concert Tickets in Groups", diff: "Hard", topics: "Array, Design, Segment Tree", slug: "booking-concert-tickets-in-groups" },
  { id: 2287, title: "Rearrange Characters to Make Target String", diff: "Easy", topics: "Hash Table, String, Counting", slug: "rearrange-characters-to-make-target-string" },
  { id: 2288, title: "Apply Discount to Prices", diff: "Medium", topics: "String", slug: "apply-discount-to-prices" },
  { id: 2289, title: "Steps to Make Array Non-decreasing", diff: "Medium", topics: "Array, Stack, Monotonic Stack", slug: "steps-to-make-array-non-decreasing" },
  { id: 2290, title: "Minimum Obstacle Removal to Reach Corner", diff: "Hard", topics: "Array, Breadth-First Search, Graph, Heap (Priority Queue), Matrix", slug: "minimum-obstacle-removal-to-reach-corner" },
  { id: 2291, title: "Maximum Profit From Trading Stocks", diff: "Medium", topics: "Array, Dynamic Programming", slug: "maximum-profit-from-trading-stocks" },
  { id: 2292, title: "Products With Three or More Orders in Two Consecutive Years", diff: "Medium", topics: "Database", slug: "products-with-three-or-more-orders-in-two-consecutive-years" },
  { id: 2293, title: "Min Max Game", diff: "Easy", topics: "Array, Simulation", slug: "min-max-game" },
  { id: 2294, title: "Partition Array Such That Maximum Difference Is K", diff: "Medium", topics: "Array, Greedy, Sorting", slug: "partition-array-such-that-maximum-difference-is-k" },
  { id: 2295, title: "Replace Elements in an Array", diff: "Medium", topics: "Array, Hash Table", slug: "replace-elements-in-an-array" },
  { id: 2296, title: "Design a Text Editor", diff: "Hard", topics: "Stack, Design, Doubly-Linked List", slug: "design-a-text-editor" },
  { id: 2297, title: "Jump Game VIII", diff: "Medium", topics: "Array, Dynamic Programming, Monotonic Stack", slug: "jump-game-viii" },
  { id: 2298, title: "Tasks Count in the Weekend", diff: "Easy", topics: "Database", slug: "tasks-count-in-the-weekend" },
  { id: 2299, title: "Strong Password Checker II", diff: "Easy", topics: "String", slug: "strong-password-checker-ii" },
  { id: 2300, title: "Successful Pairs of Spells and Potions", diff: "Medium", topics: "Array, Two Pointers, Binary Search, Sorting", slug: "successful-pairs-of-spells-and-potions" },
  { id: 2301, title: "Match Substring After Replacement", diff: "Hard", topics: "Hash Table, String, Sliding Window", slug: "match-substring-after-replacement" },
  { id: 2302, title: "Count Subarrays With Score Less Than K", diff: "Hard", topics: "Array, Binary Search, Sliding Window, Prefix Sum", slug: "count-subarrays-with-score-less-than-k" },
  { id: 2303, title: "Calculate Amount Paid in Taxes", diff: "Easy", topics: "Array, Simulation", slug: "calculate-amount-paid-in-taxes" },
  { id: 2304, title: "Minimum Path Cost in a Grid", diff: "Medium", topics: "Array, Dynamic Programming, Matrix", slug: "minimum-path-cost-in-a-grid" },
  { id: 2305, title: "Fair Distribution of Cookies", diff: "Medium", topics: "Array, Backtracking, Bit Manipulation", slug: "fair-distribution-of-cookies" },
  { id: 2306, title: "Naming a Company", diff: "Hard", topics: "Array, Hash Table, String, Bit Manipulation", slug: "naming-a-company" },
  { id: 2307, title: "Check for Contradictions in Equations", diff: "Hard", topics: "Graph, Depth-First Search, Union Find", slug: "check-for-contradictions-in-equations" },
  { id: 2308, title: "Arrange Table by Gender", diff: "Medium", topics: "Database", slug: "arrange-table-by-gender" },
  { id: 2309, title: "Greatest English Letter in Upper and Lower Case", diff: "Easy", topics: "Hash Table, String", slug: "greatest-english-letter-in-upper-and-lower-case" },
  { id: 2310, title: "Sum of Numbers With Units Digit K", diff: "Medium", topics: "Math, Dynamic Programming", slug: "sum-of-numbers-with-units-digit-k" },
  { id: 2311, title: "Longest Binary Subsequence Less Than or Equal to K", diff: "Medium", topics: "String, Greedy, Dynamic Programming", slug: "longest-binary-subsequence-less-than-or-equal-to-k" },
  { id: 2312, title: "Selling Pieces of Wood", diff: "Hard", topics: "Array, Dynamic Programming", slug: "selling-pieces-of-wood" },
  { id: 2313, title: "Minimum Flips in Binary Tree to Get Result", diff: "Hard", topics: "Tree, Dynamic Programming, Binary Tree", slug: "minimum-flips-in-binary-tree-to-get-result" },
  { id: 2314, title: "The First Day of the Maximum Recorded Degree in Each City", diff: "Medium", topics: "Database", slug: "the-first-day-of-the-maximum-recorded-degree-in-each-city" },
  { id: 2315, title: "Count Asterisks", diff: "Easy", topics: "String", slug: "count-asterisks" },
  { id: 2316, title: "Count Unreachable Pairs of Nodes in an Undirected Graph", diff: "Medium", topics: "Depth-First Search, Breadth-First Search, Union Find, Graph", slug: "count-unreachable-pairs-of-nodes-in-an-undirected-graph" },
  { id: 2317, title: "Maximum XOR After Operations", diff: "Medium", topics: "Array, Bit Manipulation, Greedy", slug: "maximum-xor-after-operations" },
  { id: 2318, title: "Number of Distinct Roll Sequences", diff: "Hard", topics: "Dynamic Programming", slug: "number-of-distinct-roll-sequences" },
  { id: 2319, title: "Check if Matrix Is X-Matrix", diff: "Easy", topics: "Array, Matrix", slug: "check-if-matrix-is-x-matrix" },
  { id: 2320, title: "Count Number of Ways to Place Houses", diff: "Medium", topics: "Dynamic Programming", slug: "count-number-of-ways-to-place-houses" },
  { id: 2321, title: "Maximum Score Of Spliced Array", diff: "Hard", topics: "Array, Dynamic Programming", slug: "maximum-score-of-spliced-array" },
  { id: 2322, title: "Minimum Score After Removals on a Tree", diff: "Hard", topics: "Array, Bit Manipulation, Tree, Depth-First Search", slug: "minimum-score-after-removals-on-a-tree" },
  { id: 2323, title: "Find Minimum Time to Finish All Jobs II", diff: "Medium", topics: "Array, Greedy, Sorting", slug: "find-minimum-time-to-finish-all-jobs-ii" },
  { id: 2324, title: "Product Sales Analysis IV", diff: "Medium", topics: "Database", slug: "product-sales-analysis-iv" },
  { id: 2325, title: "Decode the Message", diff: "Easy", topics: "Hash Table, String", slug: "decode-the-message" },
  { id: 2326, title: "Spiral Matrix IV", diff: "Medium", topics: "Array, Linked List, Matrix, Simulation", slug: "spiral-matrix-iv" },
  { id: 2327, title: "Number of People Aware of a Secret", diff: "Medium", topics: "Dynamic Programming, Queue, Prefix Sum", slug: "number-of-people-aware-of-a-secret" },
  { id: 2328, title: "Number of Increasing Paths in a Grid", diff: "Hard", topics: "Array, Dynamic Programming, Depth-First Search, Matrix", slug: "number-of-increasing-paths-in-a-grid" },
  { id: 2329, title: "Product Sales Analysis V", diff: "Easy", topics: "Database", slug: "product-sales-analysis-v" },
  { id: 2330, title: "Valid Palindrome IV", diff: "Medium", topics: "Two Pointers, String", slug: "valid-palindrome-iv" },
  { id: 2331, title: "Evaluate Boolean Binary Tree", diff: "Easy", topics: "Tree, Depth-First Search, Binary Tree", slug: "evaluate-boolean-binary-tree" },
  { id: 2332, title: "The Latest Time to Catch a Bus", diff: "Medium", topics: "Array, Two Pointers, Binary Search, Sorting", slug: "the-latest-time-to-catch-a-bus" },
  { id: 2333, title: "Minimum Sum of Squared Difference", diff: "Medium", topics: "Array, Greedy, Heap (Priority Queue), Binary Search", slug: "minimum-sum-of-squared-difference" },
  { id: 2334, title: "Subarray With Elements Greater Than Varying Threshold", diff: "Hard", topics: "Array, Stack, Monotonic Stack, Union Find", slug: "subarray-with-elements-greater-than-varying-threshold" },
  { id: 2335, title: "Minimum Amount of Time to Fill Cups", diff: "Easy", topics: "Array, Greedy, Heap (Priority Queue)", slug: "minimum-amount-of-time-to-fill-cups" },
  { id: 2336, title: "Smallest Number in Infinite Set", diff: "Medium", topics: "Hash Table, Design, Heap (Priority Queue)", slug: "smallest-number-in-infinite-set" },
  { id: 2337, title: "Move Pieces to Obtain a String", diff: "Medium", topics: "Two Pointers, String", slug: "move-pieces-to-obtain-a-string" },
  { id: 2338, title: "Count the Number of Ideal Arrays", diff: "Hard", topics: "Math, Dynamic Programming, Combinatorics, Number Theory", slug: "count-the-number-of-ideal-arrays" },
  { id: 2339, title: "All the Matches of the League", diff: "Easy", topics: "Database", slug: "all-the-matches-of-the-league" },
  { id: 2340, title: "Minimum Adjacent Swaps to Make a Valid Array", diff: "Medium", topics: "Array, Greedy", slug: "minimum-adjacent-swaps-to-make-a-valid-array" },
  { id: 2341, title: "Maximum Number of Pairs in Array", diff: "Easy", topics: "Array, Hash Table, Counting", slug: "maximum-number-of-pairs-in-array" },
  { id: 2342, title: "Max Sum of a Pair With Equal Sum of Digits", diff: "Medium", topics: "Array, Hash Table", slug: "max-sum-of-a-pair-with-equal-sum-of-digits" },
  { id: 2343, title: "Query Kth Smallest Trimmed Number", diff: "Medium", topics: "Array, String, Sorting, Radix Sort", slug: "query-kth-smallest-trimmed-number" },
  { id: 2344, title: "Minimum Deletions to Make Array Divisible", diff: "Hard", topics: "Array, Math, Number Theory, Sorting", slug: "minimum-deletions-to-make-array-divisible" },
  { id: 2345, title: "Finding the Number of Visible Mountains", diff: "Hard", topics: "Array, Sorting", slug: "finding-the-number-of-visible-mountains" },
  { id: 2346, title: "Compute the Rank as a Percentage", diff: "Medium", topics: "Database", slug: "compute-the-rank-as-a-percentage" },
  { id: 2347, title: "Best Poker Hand", diff: "Easy", topics: "Array, Hash Table, Counting", slug: "best-poker-hand" },
  { id: 2348, title: "Number of Zero-Filled Subarrays", diff: "Medium", topics: "Array, Math", slug: "number-of-zero-filled-subarrays" },
  { id: 2349, title: "Design a Number Container System", diff: "Medium", topics: "Hash Table, Design, Heap (Priority Queue), Ordered Set", slug: "design-a-number-container-system" },
  { id: 2350, title: "Shortest Impossible Sequence of Rolls", diff: "Hard", topics: "Array, Greedy, Hash Table", slug: "shortest-impossible-sequence-of-rolls" },
  { id: 2351, title: "First Letter to Appear Twice", diff: "Easy", topics: "Hash Table, String", slug: "first-letter-to-appear-twice" },
  { id: 2352, title: "Equal Row and Column Pairs", diff: "Medium", topics: "Array, Hash Table, Matrix", slug: "equal-row-and-column-pairs" },
  { id: 2353, title: "Design a Food Rating System", diff: "Medium", topics: "Hash Table, Design, Heap (Priority Queue), Ordered Set", slug: "design-a-food-rating-system" },
  { id: 2354, title: "Number of Excellent Pairs", diff: "Hard", topics: "Array, Hash Table, Bit Manipulation", slug: "number-of-excellent-pairs" },
  { id: 2355, title: "Maximum Number of Books You Can Take", diff: "Hard", topics: "Array, Dynamic Programming, Stack, Monotonic Stack", slug: "maximum-number-of-books-you-can-take" },
  { id: 2356, title: "Number of Unique Subjects Taught by Each Teacher", diff: "Easy", topics: "Database", slug: "number-of-unique-subjects-taught-by-each-teacher" },
  { id: 2357, title: "Make Array Zero by Subtracting Equal Amounts", diff: "Easy", topics: "Array, Hash Table", slug: "make-array-zero-by-subtracting-equal-amounts" },
  { id: 2358, title: "Maximum Number of Groups Entering a Competition", diff: "Medium", topics: "Math, Binary Search, Greedy", slug: "maximum-number-of-groups-entering-a-competition" },
  { id: 2359, title: "Find Closest Node to Given Two Nodes", diff: "Medium", topics: "Depth-First Search, Graph", slug: "find-closest-node-to-given-two-nodes" },
  { id: 2360, title: "Longest Cycle in a Graph", diff: "Hard", topics: "Depth-First Search, Graph", slug: "longest-cycle-in-a-graph" },
  { id: 2361, title: "Minimum Costs Using the Train Line", diff: "Hard", topics: "Array, Dynamic Programming", slug: "minimum-costs-using-the-train-line" },
  { id: 2362, title: "Generate the Invoice", diff: "Medium", topics: "Database", slug: "generate-the-invoice" },
  { id: 2363, title: "Merge Similar Items", diff: "Easy", topics: "Array, Hash Table, Sorting", slug: "merge-similar-items" },
  { id: 2364, title: "Count Number of Bad Pairs", diff: "Medium", topics: "Array, Hash Table, Math, Counting", slug: "count-number-of-bad-pairs" },
  { id: 2365, title: "Task Scheduler II", diff: "Medium", topics: "Array, Hash Table, Simulation", slug: "task-scheduler-ii" },
  { id: 2366, title: "Minimum Replacements to Sort the Array", diff: "Hard", topics: "Array, Greedy, Math", slug: "minimum-replacements-to-sort-the-array" },
  { id: 2367, title: "Number of Arithmetic Triplets", diff: "Easy", topics: "Array, Hash Table, Two Pointers", slug: "number-of-arithmetic-triplets" },
  { id: 2368, title: "Reachable Nodes With Restrictions", diff: "Medium", topics: "Tree, Depth-First Search, Breadth-First Search", slug: "reachable-nodes-with-restrictions" },
  { id: 2369, title: "Check if There is a Valid Partition For The Array", diff: "Medium", topics: "Array, Dynamic Programming", slug: "check-if-there-is-a-valid-partition-for-the-array" },
  { id: 2370, title: "Longest Ideal Subsequence", diff: "Medium", topics: "Hash Table, String, Dynamic Programming", slug: "longest-ideal-subsequence" },
  { id: 2371, title: "Minimize Maximum Value in a Grid", diff: "Hard", topics: "Array, Greedy, Matrix, Sorting", slug: "minimize-maximum-value-in-a-grid" },
  { id: 2372, title: "Calculate the Influence of Each Salesperson", diff: "Medium", topics: "Database", slug: "calculate-the-influence-of-each-salesperson" },
  { id: 2373, title: "Largest Local Values in a Matrix", diff: "Easy", topics: "Array, Matrix", slug: "largest-local-values-in-a-matrix" },
  { id: 2374, title: "Node With Highest Edge Score", diff: "Medium", topics: "Graph", slug: "node-with-highest-edge-score" },
  { id: 2375, title: "Construct Smallest Number From DI String", diff: "Medium", topics: "String, Backtracking, Stack, Greedy", slug: "construct-smallest-number-from-di-string" },
  { id: 2376, title: "Count Special Integers", diff: "Hard", topics: "Math, Dynamic Programming, Bit Manipulation, Digit DP", slug: "count-special-integers" },
  { id: 2377, title: "Sort the Olympic Table", diff: "Medium", topics: "Database", slug: "sort-the-olympic-table" },
  { id: 2378, title: "Choose Edges to Maximize Score in a Tree", diff: "Hard", topics: "Tree, Dynamic Programming, Depth-First Search", slug: "choose-edges-to-maximize-score-in-a-tree" },
  { id: 2379, title: "Minimum Recolors to Get K Consecutive Black Blocks", diff: "Easy", topics: "String, Sliding Window", slug: "minimum-recolors-to-get-k-consecutive-black-blocks" },
  { id: 2380, title: "Time Needed to Rearrange a Binary String", diff: "Medium", topics: "String, Simulation", slug: "time-needed-to-rearrange-a-binary-string" },
  { id: 2381, title: "Shifting Letters II", diff: "Medium", topics: "Array, String, Prefix Sum", slug: "shifting-letters-ii" },
  { id: 2382, title: "Maximum Segment Sum After Removals", diff: "Hard", topics: "Array, Union Find, Prefix Sum", slug: "maximum-segment-sum-after-removals" },
  { id: 2383, title: "Minimum Hours of Training to Win a Competition", diff: "Easy", topics: "Array, Simulation", slug: "minimum-hours-of-training-to-win-a-competition" },
  { id: 2384, title: "Largest Palindromic Number", diff: "Medium", topics: "Hash Table, String, Greedy, Counting", slug: "largest-palindromic-number" },
  { id: 2385, title: "Amount of Time for Binary Tree to Be Infected", diff: "Medium", topics: "Hash Table, Tree, Depth-First Search, Breadth-First Search, Binary Tree", slug: "amount-of-time-for-binary-tree-to-be-infected" },
  { id: 2386, title: "Find the K-Sum of an Array", diff: "Hard", topics: "Array, Greedy, Heap (Priority Queue), Sorting", slug: "find-the-k-sum-of-an-array" },
  { id: 2387, title: "Median of a Row Wise Sorted Matrix", diff: "Hard", topics: "Array, Binary Search, Matrix", slug: "median-of-a-row-wise-sorted-matrix" },
  { id: 2388, title: "Change Null Values in a Table to the Previous Value", diff: "Medium", topics: "Database", slug: "change-null-values-in-a-table-to-the-previous-value" },
  { id: 2389, title: "Longest Subsequence With Limited Sum", diff: "Easy", topics: "Array, Binary Search, Prefix Sum, Sorting", slug: "longest-subsequence-with-limited-sum" },
  { id: 2390, title: "Removing Stars From a String", diff: "Medium", topics: "String, Stack", slug: "removing-stars-from-a-string" },
  { id: 2391, title: "Minimum Amount of Time to Collect Garbage", diff: "Medium", topics: "Array, String, Prefix Sum", slug: "minimum-amount-of-time-to-collect-garbage" },
  { id: 2392, title: "Build a Matrix With Conditions", diff: "Hard", topics: "Graph, Topological Sort, Matrix", slug: "build-a-matrix-with-conditions" },
  { id: 2393, title: "Count Strictly Increasing Subarrays", diff: "Medium", topics: "Array, Sliding Window", slug: "count-strictly-increasing-subarrays" },
  { id: 2394, title: "Employees With Deductions", diff: "Easy", topics: "Database", slug: "employees-with-deductions" },
  { id: 2395, title: "Find Subarrays With Equal Sum", diff: "Easy", topics: "Array, Hash Table", slug: "find-subarrays-with-equal-sum" },
  { id: 2396, title: "Strictly Palindromic Number", diff: "Medium", topics: "Math", slug: "strictly-palindromic-number" },
  { id: 2397, title: "Maximum Rows Covered by Columns", diff: "Medium", topics: "Array, Backtracking, Bit Manipulation, Matrix", slug: "maximum-rows-covered-by-columns" },
  { id: 2398, title: "Maximum Number of Robots Within Budget", diff: "Hard", topics: "Array, Binary Search, Queue, Sliding Window, Heap (Priority Queue), Monotonic Queue", slug: "maximum-number-of-robots-within-budget" },
  { id: 2399, title: "Check Distances Between Same Letters", diff: "Easy", topics: "Hash Table, String", slug: "check-distances-between-same-letters" },
  { id: 2400, title: "Number of Ways to Reach a Position After Exactly k Steps", diff: "Medium", topics: "Math, Dynamic Programming, Combinatorics", slug: "number-of-ways-to-reach-a-position-after-exactly-k-steps" },
  { id: 2401, title: "Longest Nice Subarray", diff: "Medium", topics: "Array, Bit Manipulation, Sliding Window", slug: "longest-nice-subarray" },
  { id: 2402, title: "Meeting Rooms III", diff: "Hard", topics: "Array, Simulation, Heap (Priority Queue), Sorting", slug: "meeting-rooms-iii" },
  { id: 2403, title: "Minimum Time to Kill All Monsters", diff: "Hard", topics: "Dynamic Programming, Bit Manipulation", slug: "minimum-time-to-kill-all-monsters" },
  { id: 2404, title: "Most Frequent Even Element", diff: "Easy", topics: "Array, Hash Table, Counting", slug: "most-frequent-even-element" },
  { id: 2405, title: "Optimal Partition of String", diff: "Medium", topics: "Hash Table, String, Greedy", slug: "optimal-partition-of-string" },
  { id: 2406, title: "Divide Intervals Into Minimum Number of Groups", diff: "Medium", topics: "Array, Heap (Priority Queue), Sorting, Line Sweep", slug: "divide-intervals-into-minimum-number-of-groups" },
  { id: 2407, title: "Longest Increasing Subsequence II", diff: "Hard", topics: "Array, Dynamic Programming, Segment Tree", slug: "longest-increasing-subsequence-ii" },
  { id: 2408, title: "Design SQL", diff: "Medium", topics: "Design", slug: "design-sql" },
  { id: 2409, title: "Count Days Spent Together", diff: "Easy", topics: "Math, String", slug: "count-days-spent-together" },
  { id: 2410, title: "Maximum Matching of Players With Trainers", diff: "Medium", topics: "Array, Two Pointers, Greedy, Sorting", slug: "maximum-matching-of-players-with-trainers" },
  { id: 2411, title: "Smallest Subarrays With Maximum Bitwise OR", diff: "Medium", topics: "Array, Bit Manipulation", slug: "smallest-subarrays-with-maximum-bitwise-or" },
  { id: 2412, title: "Minimum Money Required Before Transactions", diff: "Hard", topics: "Array, Greedy", slug: "minimum-money-required-before-transactions" },
  { id: 2413, title: "Smallest Even Multiple", diff: "Easy", topics: "Math, Number Theory", slug: "smallest-even-multiple" },
  { id: 2414, title: "Length of the Longest Alphabetical Continuous Substring", diff: "Medium", topics: "String", slug: "length-of-the-longest-alphabetical-continuous-substring" },
  { id: 2415, title: "Reverse Odd Levels of Binary Tree", diff: "Medium", topics: "Tree, Depth-First Search, Breadth-First Search, Binary Tree", slug: "reverse-odd-levels-of-binary-tree" },
  { id: 2416, title: "Sum of Prefix Scores of Strings", diff: "Hard", topics: "Array, String, Trie", slug: "sum-of-prefix-scores-of-strings" },
  { id: 2417, title: "Closest Fair Integer", diff: "Medium", topics: "Math, Enumeration", slug: "closest-fair-integer" },
  { id: 2418, title: "Sort the People", diff: "Easy", topics: "Array, Hash Table, Sorting", slug: "sort-the-people" },
  { id: 2419, title: "Longest Subarray With Maximum Bitwise AND", diff: "Medium", topics: "Array", slug: "longest-subarray-with-maximum-bitwise-and" },
  { id: 2420, title: "Find All Good Indices", diff: "Medium", topics: "Array, Dynamic Programming", slug: "find-all-good-indices" },
  { id: 2421, title: "Number of Good Paths", diff: "Hard", topics: "Tree, Union Find, Graph", slug: "number-of-good-paths" },
  { id: 2422, title: "Merge Operations to Turn Array Into a Palindrome", diff: "Medium", topics: "Array, Two Pointers, Greedy", slug: "merge-operations-to-turn-array-into-a-palindrome" },
  { id: 2423, title: "Remove Letter To Equalize Frequency", diff: "Easy", topics: "Hash Table, String, Counting", slug: "remove-letter-to-equalize-frequency" },
  { id: 2424, title: "Longest Uploaded Prefix", diff: "Medium", topics: "Union Find, Design", slug: "longest-uploaded-prefix" },
  { id: 2425, title: "Bitwise XOR of All Pairings", diff: "Medium", topics: "Array, Bit Manipulation", slug: "bitwise-xor-of-all-pairings" },
  { id: 2426, title: "Number of Pairs Satisfying Inequality", diff: "Hard", topics: "Array, Binary Indexed Tree, Segment Tree, Merge Sort, Ordered Set", slug: "number-of-pairs-satisfying-inequality" },
  { id: 2427, title: "Number of Common Factors", diff: "Easy", topics: "Math, Enumeration, Number Theory", slug: "number-of-common-factors" },
  { id: 2428, title: "Maximum Sum of an Hourglass", diff: "Easy", topics: "Array, Matrix", slug: "maximum-sum-of-an-hourglass" },
  { id: 2429, title: "Minimize XOR", diff: "Medium", topics: "Bit Manipulation, Greedy", slug: "minimize-xor" },
  { id: 2430, title: "Maximum Deletions on a String", diff: "Hard", topics: "String, Dynamic Programming, Rolling Hash, Hash Function", slug: "maximum-deletions-on-a-string" },
  { id: 2431, title: "Maximize Total Tastiness of Purchased Fruits", diff: "Medium", topics: "Array, Dynamic Programming", slug: "maximize-total-tastiness-of-purchased-fruits" },
  { id: 2432, title: "The Employee That Worked on the Longest Task", diff: "Easy", topics: "Array", slug: "the-employee-that-worked-on-the-longest-task" },
  { id: 2433, title: "Find The Original Array of Prefix Xor", diff: "Medium", topics: "Array, Bit Manipulation, Prefix Sum", slug: "find-the-original-array-of-prefix-xor" },
  { id: 2434, title: "Using a Robot to Print the Lexicographically Smallest String", diff: "Medium", topics: "String, Stack, Greedy", slug: "using-a-robot-to-print-the-lexicographically-smallest-string" },
  { id: 2435, title: "Paths in Matrix Whose Sum Is Divisible by K", diff: "Hard", topics: "Array, Dynamic Programming, Matrix", slug: "paths-in-matrix-whose-sum-is-divisible-by-k" },
  { id: 2436, title: "Minimum Split Into Subarrays With GCD Greater Than One", diff: "Medium", topics: "Array, Math, Number Theory", slug: "minimum-split-into-subarrays-with-gcd-greater-than-one" },
  { id: 2437, title: "Number of Valid Clock Times", diff: "Easy", topics: "String, Enumeration", slug: "number-of-valid-clock-times" },
  { id: 2438, title: "Range Product Queries of Powers", diff: "Medium", topics: "Array, Bit Manipulation", slug: "range-product-queries-of-powers" },
  { id: 2439, title: "Minimize Maximum of Array", diff: "Medium", topics: "Array, Binary Search, Greedy, Prefix Sum", slug: "minimize-maximum-of-array" },
  { id: 2440, title: "Create Components With Same Value", diff: "Hard", topics: "Tree, Depth-First Search", slug: "create-components-with-same-value" },
  { id: 2441, title: "Largest Positive Integer That Exists With Its Negative", diff: "Easy", topics: "Array, Hash Table, Two Pointers, Sorting", slug: "largest-positive-integer-that-exists-with-its-negative" },
  { id: 2442, title: "Count Number of Distinct Integers After Reverse Operations", diff: "Medium", topics: "Array, Hash Table, Math", slug: "count-number-of-distinct-integers-after-reverse-operations" },
  { id: 2443, title: "Sum of Number and Its Reverse", diff: "Medium", topics: "Math, Enumeration", slug: "sum-of-number-and-its-reverse" },
  { id: 2444, title: "Count Subarrays With Fixed Bounds", diff: "Hard", topics: "Array, Queue, Sliding Window", slug: "count-subarrays-with-fixed-bounds" },
  { id: 2445, title: "Number of Nodes With Value One", diff: "Medium", topics: "Tree, Depth-First Search, Bit Manipulation", slug: "number-of-nodes-with-value-one" },
  { id: 2446, title: "Determine if Two Events Have Conflict", diff: "Easy", topics: "String", slug: "determine-if-two-events-have-conflict" },
  { id: 2447, title: "Number of Subarrays With GCD Equal to K", diff: "Medium", topics: "Array, Math, Number Theory", slug: "number-of-subarrays-with-gcd-equal-to-k" },
  { id: 2448, title: "Minimum Cost to Make Array Equal", diff: "Hard", topics: "Array, Binary Search, Greedy, Prefix Sum, Sorting", slug: "minimum-cost-to-make-array-equal" },
  { id: 2449, title: "Minimum Number of Operations to Make Arrays Similar", diff: "Hard", topics: "Array, Greedy, Math, Sorting", slug: "minimum-number-of-operations-to-make-arrays-similar" },
  { id: 2450, title: "Number of Distinct Binary Strings After Applying Operations", diff: "Medium", topics: "Math, String", slug: "number-of-distinct-binary-strings-after-applying-operations" },
  { id: 2451, title: "Odd String Difference", diff: "Easy", topics: "Array, Hash Table, String", slug: "odd-string-difference" },
  { id: 2452, title: "Words Within Two Edits of Dictionary", diff: "Medium", topics: "Array, String", slug: "words-within-two-edits-of-dictionary" },
  { id: 2453, title: "Destroy Sequential Targets", diff: "Medium", topics: "Array, Hash Table, Math", slug: "destroy-sequential-targets" },
  { id: 2454, title: "Next Greater Element IV", diff: "Hard", topics: "Array, Stack, Heap (Priority Queue), Monotonic Stack", slug: "next-greater-element-iv" },
  { id: 2455, title: "Average Value of Even Numbers That Are Divisible by Three", diff: "Easy", topics: "Array, Math", slug: "average-value-of-even-numbers-that-are-divisible-by-three" },
  { id: 2456, title: "Most Popular Video Creator", diff: "Medium", topics: "Array, Hash Table, Sorting", slug: "most-popular-video-creator" },
  { id: 2457, title: "Minimum Addition to Make Integer Beautiful", diff: "Medium", topics: "Greedy, Math", slug: "minimum-addition-to-make-integer-beautiful" },
  { id: 2458, title: "Height of Binary Tree After Subtree Removal Queries", diff: "Hard", topics: "Tree, Depth-First Search, Breadth-First Search, Binary Tree", slug: "height-of-binary-tree-after-subtree-removal-queries" },
  { id: 2459, title: "Sort Array by Moving Items to Empty Space", diff: "Hard", topics: "Array, Greedy", slug: "sort-array-by-moving-items-to-empty-space" },
  { id: 2460, title: "Apply Operations to an Array", diff: "Easy", topics: "Array, Simulation", slug: "apply-operations-to-an-array" },
  { id: 2461, title: "Maximum Sum of Distinct Subarrays With Length K", diff: "Medium", topics: "Array, Hash Table, Sliding Window", slug: "maximum-sum-of-distinct-subarrays-with-length-k" },
  { id: 2462, title: "Total Cost to Hire K Workers", diff: "Medium", topics: "Array, Two Pointers, Heap (Priority Queue)", slug: "total-cost-to-hire-k-workers" },
  { id: 2463, title: "Minimum Total Distance Traveled", diff: "Hard", topics: "Array, Dynamic Programming, Sorting", slug: "minimum-total-distance-traveled" },
  { id: 2464, title: "Minimum Subarrays in a Valid Split", diff: "Hard", topics: "Array, Dynamic Programming, Number Theory", slug: "minimum-subarrays-in-a-valid-split" },
  { id: 2465, title: "Number of Distinct Averages", diff: "Easy", topics: "Array, Hash Table, Two Pointers, Sorting", slug: "number-of-distinct-averages" },
  { id: 2466, title: "Count Ways To Build Good Strings", diff: "Medium", topics: "Dynamic Programming", slug: "count-ways-to-build-good-strings" },
  { id: 2467, title: "Most Profitable Path in a Tree", diff: "Medium", topics: "Tree, Depth-First Search, Breadth-First Search", slug: "most-profitable-path-in-a-tree" },
  { id: 2468, title: "Split Message Based on Limit", diff: "Hard", topics: "String, Simulation", slug: "split-message-based-on-limit" },
  { id: 2469, title: "Convert the Temperature", diff: "Easy", topics: "Math", slug: "convert-the-temperature" },
  { id: 2470, title: "Number of Subarrays With LCM Equal to K", diff: "Medium", topics: "Array, Math, Number Theory", slug: "number-of-subarrays-with-lcm-equal-to-k" },
  { id: 2471, title: "Minimum Number of Operations to Sort a Binary Tree by Level", diff: "Medium", topics: "Tree, Breadth-First Search, Binary Tree", slug: "minimum-number-of-operations-to-sort-a-binary-tree-by-level" },
  { id: 2472, title: "Maximum Number of Non-overlapping Palindrome Substrings", diff: "Hard", topics: "String, Dynamic Programming", slug: "maximum-number-of-non-overlapping-palindrome-substrings" },
  { id: 2473, title: "Minimum Cost to Buy Apples", diff: "Hard", topics: "Graph, Shortest Path", slug: "minimum-cost-to-buy-apples" },
  { id: 2474, title: "Customers With Strictly Increasing Purchases", diff: "Hard", topics: "Database", slug: "customers-with-strictly-increasing-purchases" },
  { id: 2475, title: "Number of Unequal Triplets in Array", diff: "Easy", topics: "Array, Hash Table, Sorting", slug: "number-of-unequal-triplets-in-array" },
  { id: 2476, title: "Closest Nodes Queries in a Binary Search Tree", diff: "Medium", topics: "Tree, Depth-First Search, Binary Search Tree, Binary Tree", slug: "closest-nodes-queries-in-a-binary-search-tree" },
  { id: 2477, title: "Minimum Fuel Cost to Report to the Capital", diff: "Medium", topics: "Tree, Depth-First Search, Graph", slug: "minimum-fuel-cost-to-report-to-the-capital" },
  { id: 2478, title: "Number of Beautiful Partitions", diff: "Hard", topics: "String, Dynamic Programming", slug: "number-of-beautiful-partitions" },
  { id: 2479, title: "Maximum XOR of Two Non-Overlapping Subtrees", diff: "Hard", topics: "Tree, Trie, Depth-First Search, Bit Manipulation", slug: "maximum-xor-of-two-non-overlapping-subtrees" },
  { id: 2480, title: "Form a Chemical Bond", diff: "Easy", topics: "Database", slug: "form-a-chemical-bond" },
  { id: 2481, title: "Minimum Cuts to Divide a Circle", diff: "Easy", topics: "Math", slug: "minimum-cuts-to-divide-a-circle" },
  { id: 2482, title: "Difference Between Ones and Zeros in Row and Column", diff: "Medium", topics: "Array, Matrix, Prefix Sum", slug: "difference-between-ones-and-zeros-in-row-and-column" },
  { id: 2483, title: "Minimum Penalty for a Shop", diff: "Medium", topics: "String, Prefix Sum", slug: "minimum-penalty-for-a-shop" },
  { id: 2484, title: "Count Palindromic Subsequences", diff: "Hard", topics: "String, Dynamic Programming, Prefix Sum", slug: "count-palindromic-subsequences" },
  { id: 2485, title: "Find the Pivot Integer", diff: "Easy", topics: "Math, Prefix Sum", slug: "find-the-pivot-integer" },
  { id: 2486, title: "Append Characters to String to Make Subsequence", diff: "Medium", topics: "Two Pointers, String, Greedy", slug: "append-characters-to-string-to-make-subsequence" },
  { id: 2487, title: "Remove Nodes From Linked List", diff: "Medium", topics: "Linked List, Stack, Recursion, Monotonic Stack", slug: "remove-nodes-from-linked-list" },
  { id: 2488, title: "Count Subarrays With Median K", diff: "Hard", topics: "Array, Hash Table, Prefix Sum", slug: "count-subarrays-with-median-k" },
  { id: 2489, title: "Number of Substrings With Fixed Ratio", diff: "Hard", topics: "Hash Table, String, Prefix Sum", slug: "number-of-substrings-with-fixed-ratio" },
  { id: 2490, title: "Circular Sentence", diff: "Easy", topics: "String", slug: "circular-sentence" },
  { id: 2491, title: "Divide Players Into Teams of Equal Skill", diff: "Medium", topics: "Array, Hash Table, Greedy, Sorting", slug: "divide-players-into-teams-of-equal-skill" },
  { id: 2492, title: "Minimum Score of a Path Between Two Cities", diff: "Medium", topics: "Depth-First Search, Breadth-First Search, Union Find, Graph", slug: "minimum-score-of-a-path-between-two-cities" },
  { id: 2493, title: "Divide Nodes Into the Maximum Number of Groups", diff: "Hard", topics: "Depth-First Search, Breadth-First Search, Union Find, Graph", slug: "divide-nodes-into-the-maximum-number-of-groups" },
  { id: 2494, title: "Merge Overlapping Events in the Same Hall", diff: "Hard", topics: "Database", slug: "merge-overlapping-events-in-the-same-hall" },
  { id: 2495, title: "Number of Subarrays Having Even Product", diff: "Medium", topics: "Array, Math", slug: "number-of-subarrays-having-even-product" },
  { id: 2496, title: "Maximum Value of a String in an Array", diff: "Easy", topics: "Array, String", slug: "maximum-value-of-a-string-in-an-array" },
  { id: 2497, title: "Maximum Star Sum of a Graph", diff: "Medium", topics: "Array, Graph, Sorting, Heap (Priority Queue)", slug: "maximum-star-sum-of-a-graph" },
  { id: 2498, title: "Frog Jump II", diff: "Medium", topics: "Array, Binary Search, Greedy", slug: "frog-jump-ii" },
  { id: 2499, title: "Minimum Total Cost to Make Arrays Unequal", diff: "Hard", topics: "Array, Greedy, Counting", slug: "minimum-total-cost-to-make-arrays-unequal" },
  { id: 2500, title: "Delete Greatest Value in Each Row", diff: "Easy", topics: "Array, Matrix, Sorting", slug: "delete-greatest-value-in-each-row" }
);