window.rawProblems = window.rawProblems || [];

window.rawProblems.push(
  { id: 1, title: "Two Sum", diff: "Easy", topics: "Array, Hash Table", slug: "two-sum" },
  { id: 2, title: "Add Two Numbers", diff: "Medium", topics: "Linked List, Math, Recursion", slug: "add-two-numbers" },
  { id: 3, title: "Longest Substring Without Repeating Characters", diff: "Medium", topics: "Hash Table, String, Sliding Window", slug: "longest-substring-without-repeating-characters" },
  { id: 4, title: "Median of Two Sorted Arrays", diff: "Hard", topics: "Array, Binary Search, Divide and Conquer", slug: "median-of-two-sorted-arrays" },
  { id: 5, title: "Longest Palindromic Substring", diff: "Medium", topics: "String, Dynamic Programming", slug: "longest-palindromic-substring" },
  { id: 6, title: "Zigzag Conversion", diff: "Medium", topics: "String", slug: "zigzag-conversion" },
  { id: 7, title: "Reverse Integer", diff: "Medium", topics: "Math", slug: "reverse-integer" },
  { id: 8, title: "String to Integer (atoi)", diff: "Medium", topics: "String", slug: "string-to-integer-atoi" },
  { id: 9, title: "Palindrome Number", diff: "Easy", topics: "Math", slug: "palindrome-number" },
  { id: 10, title: "Regular Expression Matching", diff: "Hard", topics: "String, Dynamic Programming, Recursion", slug: "regular-expression-matching" },
  { id: 11, title: "Container With Most Water", diff: "Medium", topics: "Array, Two Pointers, Greedy", slug: "container-with-most-water" },
  { id: 12, title: "Integer to Roman", diff: "Medium", topics: "Hash Table, Math, String", slug: "integer-to-roman" },
  { id: 13, title: "Roman to Integer", diff: "Easy", topics: "Hash Table, Math, String", slug: "roman-to-integer" },
  { id: 14, title: "Longest Common Prefix", diff: "Easy", topics: "String, Trie", slug: "longest-common-prefix" },
  { id: 15, title: "3Sum", diff: "Medium", topics: "Array, Two Pointers, Sorting", slug: "3sum" },
  { id: 16, title: "3Sum Closest", diff: "Medium", topics: "Array, Two Pointers, Sorting", slug: "3sum-closest" },
  { id: 17, title: "Letter Combinations of a Phone Number", diff: "Medium", topics: "Hash Table, String, Backtracking", slug: "letter-combinations-of-a-phone-number" },
  { id: 18, title: "4Sum", diff: "Medium", topics: "Array, Two Pointers, Sorting", slug: "4sum" },
  { id: 19, title: "Remove Nth Node From End of List", diff: "Medium", topics: "Linked List, Two Pointers", slug: "remove-nth-node-from-end-of-list" },
  { id: 20, title: "Valid Parentheses", diff: "Easy", topics: "String, Stack", slug: "valid-parentheses" },
  { id: 21, title: "Merge Two Sorted Lists", diff: "Easy", topics: "Linked List, Recursion", slug: "merge-two-sorted-lists" },
  { id: 22, title: "Generate Parentheses", diff: "Medium", topics: "String, Dynamic Programming, Backtracking", slug: "generate-parentheses" },
  { id: 23, title: "Merge k Sorted Lists", diff: "Hard", topics: "Linked List, Divide and Conquer, Heap (Priority Queue), Merge Sort", slug: "merge-k-sorted-lists" },
  { id: 24, title: "Swap Nodes in Pairs", diff: "Medium", topics: "Linked List", slug: "swap-nodes-in-pairs" },
  { id: 25, title: "Reverse Nodes in k-Group", diff: "Hard", topics: "Linked List", slug: "reverse-nodes-in-k-group" },
  { id: 26, title: "Remove Duplicates from Sorted Array", diff: "Easy", topics: "Array, Two Pointers", slug: "remove-duplicates-from-sorted-array" },
  { id: 27, title: "Remove Element", diff: "Easy", topics: "Array, Two Pointers", slug: "remove-element" },
  { id: 28, title: "Find the Index of the First Occurrence in a String", diff: "Easy", topics: "String, Two Pointers, String Matching", slug: "find-the-index-of-the-first-occurrence-in-a-string" },
  { id: 29, title: "Divide Two Integers", diff: "Medium", topics: "Math, Bit Manipulation", slug: "divide-two-integers" },
  { id: 30, title: "Substring with Concatenation of All Words", diff: "Hard", topics: "Hash Table, String, Sliding Window", slug: "substring-with-concatenation-of-all-words" },
  { id: 31, title: "Next Permutation", diff: "Medium", topics: "Array, Two Pointers", slug: "next-permutation" },
  { id: 32, title: "Longest Valid Parentheses", diff: "Hard", topics: "String, Dynamic Programming, Stack", slug: "longest-valid-parentheses" },
  { id: 33, title: "Search in Rotated Sorted Array", diff: "Medium", topics: "Array, Binary Search", slug: "search-in-rotated-sorted-array" },
  { id: 34, title: "Find First and Last Position of Element in Sorted Array", diff: "Medium", topics: "Array, Binary Search", slug: "find-first-and-last-position-of-element-in-sorted-array" },
  { id: 35, title: "Search Insert Position", diff: "Easy", topics: "Array, Binary Search", slug: "search-insert-position" },
  { id: 36, title: "Valid Sudoku", diff: "Medium", topics: "Array, Hash Table, Matrix", slug: "valid-sudoku" },
  { id: 37, title: "Sudoku Solver", diff: "Hard", topics: "Array, Backtracking, Matrix", slug: "sudoku-solver" },
  { id: 38, title: "Count and Say", diff: "Medium", topics: "String", slug: "count-and-say" },
  { id: 39, title: "Combination Sum", diff: "Medium", topics: "Array, Backtracking", slug: "combination-sum" },
  { id: 40, title: "Combination Sum II", diff: "Medium", topics: "Array, Backtracking", slug: "combination-sum-ii" },
  { id: 41, title: "First Missing Positive", diff: "Hard", topics: "Array, Hash Table", slug: "first-missing-positive" },
  { id: 42, title: "Trapping Rain Water", diff: "Hard", topics: "Array, Two Pointers, Dynamic Programming, Stack, Monotonic Stack", slug: "trapping-rain-water" },
  { id: 43, title: "Multiply Strings", diff: "Medium", topics: "Math, String, Simulation", slug: "multiply-strings" },
  { id: 44, title: "Wildcard Matching", diff: "Hard", topics: "String, Dynamic Programming, Greedy", slug: "wildcard-matching" },
  { id: 45, title: "Jump Game II", diff: "Medium", topics: "Array, Dynamic Programming, Greedy", slug: "jump-game-ii" },
  { id: 46, title: "Permutations", diff: "Medium", topics: "Array, Backtracking", slug: "permutations" },
  { id: 47, title: "Permutations II", diff: "Medium", topics: "Array, Backtracking", slug: "permutations-ii" },
  { id: 48, title: "Rotate Image", diff: "Medium", topics: "Array, Math, Matrix", slug: "rotate-image" },
  { id: 49, title: "Group Anagrams", diff: "Medium", topics: "Array, Hash Table, String, Sorting", slug: "group-anagrams" },
  { id: 50, title: "Pow(x, n)", diff: "Medium", topics: "Math, Recursion", slug: "powx-n" },
  { id: 51, title: "N-Queens", diff: "Hard", topics: "Array, Backtracking", slug: "n-queens" },
  { id: 52, title: "N-Queens II", diff: "Hard", topics: "Backtracking", slug: "n-queens-ii" },
  { id: 53, title: "Maximum Subarray", diff: "Medium", topics: "Array, Divide and Conquer, Dynamic Programming", slug: "maximum-subarray" },
  { id: 54, title: "Spiral Matrix", diff: "Medium", topics: "Array, Matrix, Simulation", slug: "spiral-matrix" },
  { id: 55, title: "Jump Game", diff: "Medium", topics: "Array, Dynamic Programming, Greedy", slug: "jump-game" },
  { id: 56, title: "Merge Intervals", diff: "Medium", topics: "Array, Sorting", slug: "merge-intervals" },
  { id: 57, title: "Insert Interval", diff: "Medium", topics: "Array", slug: "insert-interval" },
  { id: 58, title: "Length of Last Word", diff: "Easy", topics: "String", slug: "length-of-last-word" },
  { id: 59, title: "Spiral Matrix II", diff: "Medium", topics: "Array, Matrix, Simulation", slug: "spiral-matrix-ii" },
  { id: 60, title: "Permutation Sequence", diff: "Hard", topics: "Math, Recursion", slug: "permutation-sequence" },
  { id: 61, title: "Rotate List", diff: "Medium", topics: "Linked List, Two Pointers", slug: "rotate-list" },
  { id: 62, title: "Unique Paths", diff: "Medium", topics: "Math, Dynamic Programming, Combinatorics", slug: "unique-paths" },
  { id: 63, title: "Unique Paths II", diff: "Medium", topics: "Array, Dynamic Programming, Matrix", slug: "unique-paths-ii" },
  { id: 64, title: "Minimum Path Sum", diff: "Medium", topics: "Array, Dynamic Programming, Matrix", slug: "minimum-path-sum" },
  { id: 65, title: "Valid Number", diff: "Hard", topics: "String", slug: "valid-number" },
  { id: 66, title: "Plus One", diff: "Easy", topics: "Array, Math", slug: "plus-one" },
  { id: 67, title: "Add Binary", diff: "Easy", topics: "Math, String, Bit Manipulation, Simulation", slug: "add-binary" },
  { id: 68, title: "Text Justification", diff: "Hard", topics: "Array, String, Simulation", slug: "text-justification" },
  { id: 69, title: "Sqrt(x)", diff: "Easy", topics: "Math, Binary Search", slug: "sqrtx" },
  { id: 70, title: "Climbing Stairs", diff: "Easy", topics: "Math, Dynamic Programming, Memoization", slug: "climbing-stairs" },
  { id: 71, title: "Simplify Path", diff: "Medium", topics: "String, Stack", slug: "simplify-path" },
  { id: 72, title: "Edit Distance", diff: "Medium", topics: "String, Dynamic Programming", slug: "edit-distance" },
  { id: 73, title: "Set Matrix Zeroes", diff: "Medium", topics: "Array, Hash Table, Matrix", slug: "set-matrix-zeroes" },
  { id: 74, title: "Search a 2D Matrix", diff: "Medium", topics: "Array, Binary Search, Matrix", slug: "search-a-2d-matrix" },
  { id: 75, title: "Sort Colors", diff: "Medium", topics: "Array, Two Pointers, Sorting", slug: "sort-colors" },
  { id: 76, title: "Minimum Window Substring", diff: "Hard", topics: "Hash Table, String, Sliding Window", slug: "minimum-window-substring" },
  { id: 77, title: "Combinations", diff: "Medium", topics: "Backtracking", slug: "combinations" },
  { id: 78, title: "Subsets", diff: "Medium", topics: "Array, Backtracking, Bit Manipulation", slug: "subsets" },
  { id: 79, title: "Word Search", diff: "Medium", topics: "Array, String, Backtracking, Matrix", slug: "word-search" },
  { id: 80, title: "Remove Duplicates from Sorted Array II", diff: "Medium", topics: "Array, Two Pointers", slug: "remove-duplicates-from-sorted-array-ii" },
  { id: 81, title: "Search in Rotated Sorted Array II", diff: "Medium", topics: "Array, Binary Search", slug: "search-in-rotated-sorted-array-ii" },
  { id: 82, title: "Remove Duplicates from Sorted List II", diff: "Medium", topics: "Linked List", slug: "remove-duplicates-from-sorted-list-ii" },
  { id: 83, title: "Remove Duplicates from Sorted List", diff: "Easy", topics: "Linked List", slug: "remove-duplicates-from-sorted-list" },
  { id: 84, title: "Largest Rectangle in Histogram", diff: "Hard", topics: "Array, Stack, Monotonic Stack", slug: "largest-rectangle-in-histogram" },
  { id: 85, title: "Maximal Rectangle", diff: "Hard", topics: "Array, Dynamic Programming, Stack, Matrix, Monotonic Stack", slug: "maximal-rectangle" },
  { id: 86, title: "Partition List", diff: "Medium", topics: "Linked List, Two Pointers", slug: "partition-list" },
  { id: 87, title: "Scramble String", diff: "Hard", topics: "String, Dynamic Programming", slug: "scramble-string" },
  { id: 88, title: "Merge Sorted Array", diff: "Easy", topics: "Array, Two Pointers, Sorting", slug: "merge-sorted-array" },
  { id: 89, title: "Gray Code", diff: "Medium", topics: "Math, Backtracking, Bit Manipulation", slug: "gray-code" },
  { id: 90, title: "Subsets II", diff: "Medium", topics: "Array, Backtracking, Bit Manipulation", slug: "subsets-ii" },
  { id: 91, title: "Decode Ways", diff: "Medium", topics: "String, Dynamic Programming", slug: "decode-ways" },
  { id: 92, title: "Reverse Linked List II", diff: "Medium", topics: "Linked List", slug: "reverse-linked-list-ii" },
  { id: 93, title: "Restore IP Addresses", diff: "Medium", topics: "String, Backtracking", slug: "restore-ip-addresses" },
  { id: 94, title: "Binary Tree Inorder Traversal", diff: "Easy", topics: "Stack, Tree, Depth-First Search, Binary Tree", slug: "binary-tree-inorder-traversal" },
  { id: 95, title: "Unique Binary Search Trees II", diff: "Medium", topics: "Dynamic Programming, Backtracking, Tree, Binary Search Tree, Binary Tree", slug: "unique-binary-search-trees-ii" },
  { id: 96, title: "Unique Binary Search Trees", diff: "Medium", topics: "Math, Dynamic Programming, Binary Search Tree", slug: "unique-binary-search-trees" },
  { id: 97, title: "Interleaving String", diff: "Medium", topics: "String, Dynamic Programming", slug: "interleaving-string" },
  { id: 98, title: "Validate Binary Search Tree", diff: "Medium", topics: "Tree, Depth-First Search, Binary Search Tree, Binary Tree", slug: "validate-binary-search-tree" },
  { id: 99, title: "Recover Binary Search Tree", diff: "Medium", topics: "Tree, Depth-First Search, Binary Search Tree, Binary Tree", slug: "recover-binary-search-tree" },
  { id: 100, title: "Same Tree", diff: "Easy", topics: "Tree, Depth-First Search, Breadth-First Search, Binary Tree", slug: "same-tree" },
  { id: 101, title: "Symmetric Tree", diff: "Easy", topics: "Tree, Depth-First Search, Breadth-First Search, Binary Tree", slug: "symmetric-tree" },
  { id: 102, title: "Binary Tree Level Order Traversal", diff: "Medium", topics: "Tree, Breadth-First Search, Binary Tree", slug: "binary-tree-level-order-traversal" },
  { id: 103, title: "Binary Tree Zigzag Level Order Traversal", diff: "Medium", topics: "Tree, Breadth-First Search, Binary Tree", slug: "binary-tree-zigzag-level-order-traversal" },
  { id: 104, title: "Maximum Depth of Binary Tree", diff: "Easy", topics: "Tree, Depth-First Search, Breadth-First Search, Binary Tree", slug: "maximum-depth-of-binary-tree" },
  { id: 105, title: "Construct Binary Tree from Preorder and Inorder Traversal", diff: "Medium", topics: "Array, Hash Table, Divide and Conquer, Tree, Binary Tree", slug: "construct-binary-tree-from-preorder-and-inorder-traversal" },
  { id: 106, title: "Construct Binary Tree from Inorder and Postorder Traversal", diff: "Medium", topics: "Array, Hash Table, Divide and Conquer, Tree, Binary Tree", slug: "construct-binary-tree-from-inorder-and-postorder-traversal" },
  { id: 107, title: "Binary Tree Level Order Traversal II", diff: "Medium", topics: "Tree, Breadth-First Search, Binary Tree", slug: "binary-tree-level-order-traversal-ii" },
  { id: 108, title: "Convert Sorted Array to Binary Search Tree", diff: "Easy", topics: "Array, Divide and Conquer, Tree, Binary Search Tree, Binary Tree", slug: "convert-sorted-array-to-binary-search-tree" },
  { id: 109, title: "Convert Sorted List to Binary Search Tree", diff: "Medium", topics: "Linked List, Divide and Conquer, Tree, Binary Search Tree, Binary Tree", slug: "convert-sorted-list-to-binary-search-tree" },
  { id: 110, title: "Balanced Binary Tree", diff: "Easy", topics: "Tree, Depth-First Search, Binary Tree", slug: "balanced-binary-tree" },
  { id: 111, title: "Minimum Depth of Binary Tree", diff: "Easy", topics: "Tree, Depth-First Search, Breadth-First Search, Binary Tree", slug: "minimum-depth-of-binary-tree" },
  { id: 112, title: "Path Sum", diff: "Easy", topics: "Tree, Depth-First Search, Breadth-First Search, Binary Tree", slug: "path-sum" },
  { id: 113, title: "Path Sum II", diff: "Medium", topics: "Backtracking, Tree, Depth-First Search, Binary Tree", slug: "path-sum-ii" },
  { id: 114, title: "Flatten Binary Tree to Linked List", diff: "Medium", topics: "Linked List, Tree, Depth-First Search, Binary Tree", slug: "flatten-binary-tree-to-linked-list" },
  { id: 115, title: "Distinct Subsequences", diff: "Hard", topics: "String, Dynamic Programming", slug: "distinct-subsequences" },
  { id: 116, title: "Populating Next Right Pointers in Each Node", diff: "Medium", topics: "Linked List, Tree, Depth-First Search, Breadth-First Search", slug: "populating-next-right-pointers-in-each-node" },
  { id: 117, title: "Populating Next Right Pointers in Each Node II", diff: "Medium", topics: "Linked List, Tree, Depth-First Search, Breadth-First Search", slug: "populating-next-right-pointers-in-each-node-ii" },
  { id: 118, title: "Pascal's Triangle", diff: "Easy", topics: "Array, Dynamic Programming", slug: "pascals-triangle" },
  { id: 119, title: "Pascal's Triangle II", diff: "Easy", topics: "Array, Dynamic Programming", slug: "pascals-triangle-ii" },
  { id: 120, title: "Triangle", diff: "Medium", topics: "Array, Dynamic Programming", slug: "triangle" },
  { id: 121, title: "Best Time to Buy and Sell Stock", diff: "Easy", topics: "Array, Dynamic Programming", slug: "best-time-to-buy-and-sell-stock" },
  { id: 122, title: "Best Time to Buy and Sell Stock II", diff: "Medium", topics: "Array, Dynamic Programming, Greedy", slug: "best-time-to-buy-and-sell-stock-ii" },
  { id: 123, title: "Best Time to Buy and Sell Stock III", diff: "Hard", topics: "Array, Dynamic Programming", slug: "best-time-to-buy-and-sell-stock-iii" },
  { id: 124, title: "Binary Tree Maximum Path Sum", diff: "Hard", topics: "Dynamic Programming, Tree, Depth-First Search, Binary Tree", slug: "binary-tree-maximum-path-sum" },
  { id: 125, title: "Valid Palindrome", diff: "Easy", topics: "Two Pointers, String", slug: "valid-palindrome" },
  { id: 126, title: "Word Ladder II", diff: "Hard", topics: "Hash Table, String, Backtracking, Breadth-First Search", slug: "word-ladder-ii" },
  { id: 127, title: "Word Ladder", diff: "Hard", topics: "Hash Table, String, Breadth-First Search", slug: "word-ladder" },
  { id: 128, title: "Longest Consecutive Sequence", diff: "Medium", topics: "Array, Hash Table, Union Find", slug: "longest-consecutive-sequence" },
  { id: 129, title: "Sum Root to Leaf Numbers", diff: "Medium", topics: "Tree, Depth-First Search, Binary Tree", slug: "sum-root-to-leaf-numbers" },
  { id: 130, title: "Surrounded Regions", diff: "Medium", topics: "Array, Depth-First Search, Breadth-First Search, Union Find, Matrix", slug: "surrounded-regions" },
  { id: 131, title: "Palindrome Partitioning", diff: "Medium", topics: "String, Dynamic Programming, Backtracking", slug: "palindrome-partitioning" },
  { id: 132, title: "Palindrome Partitioning II", diff: "Hard", topics: "String, Dynamic Programming", slug: "palindrome-partitioning-ii" },
  { id: 133, title: "Clone Graph", diff: "Medium", topics: "Hash Table, Depth-First Search, Breadth-First Search, Graph", slug: "clone-graph" },
  { id: 134, title: "Gas Station", diff: "Medium", topics: "Array, Greedy", slug: "gas-station" },
  { id: 135, title: "Candy", diff: "Hard", topics: "Array, Greedy", slug: "candy" },
  { id: 136, title: "Single Number", diff: "Easy", topics: "Array, Bit Manipulation", slug: "single-number" },
  { id: 137, title: "Single Number II", diff: "Medium", topics: "Array, Bit Manipulation", slug: "single-number-ii" },
  { id: 138, title: "Copy List with Random Pointer", diff: "Medium", topics: "Hash Table, Linked List", slug: "copy-list-with-random-pointer" },
  { id: 139, title: "Word Break", diff: "Medium", topics: "Hash Table, String, Dynamic Programming, Trie", slug: "word-break" },
  { id: 140, title: "Word Break II", diff: "Hard", topics: "Hash Table, String, Dynamic Programming, Backtracking, Trie", slug: "word-break-ii" },
  { id: 141, title: "Linked List Cycle", diff: "Easy", topics: "Hash Table, Linked List, Two Pointers", slug: "linked-list-cycle" },
  { id: 142, title: "Linked List Cycle II", diff: "Medium", topics: "Hash Table, Linked List, Two Pointers", slug: "linked-list-cycle-ii" },
  { id: 143, title: "Reorder List", diff: "Medium", topics: "Linked List, Two Pointers, Stack, Recursion", slug: "reorder-list" },
  { id: 144, title: "Binary Tree Preorder Traversal", diff: "Easy", topics: "Stack, Tree, Depth-First Search, Binary Tree", slug: "binary-tree-preorder-traversal" },
  { id: 145, title: "Binary Tree Postorder Traversal", diff: "Easy", topics: "Stack, Tree, Depth-First Search, Binary Tree", slug: "binary-tree-postorder-traversal" },
  { id: 146, title: "LRU Cache", diff: "Medium", topics: "Hash Table, Linked List, Design, Doubly-Linked List", slug: "lru-cache" },
  { id: 147, title: "Insertion Sort List", diff: "Medium", topics: "Linked List, Sorting", slug: "insertion-sort-list" },
  { id: 148, title: "Sort List", diff: "Medium", topics: "Linked List, Two Pointers, Divide and Conquer, Sorting, Merge Sort", slug: "sort-list" },
  { id: 149, title: "Max Points on a Line", diff: "Hard", topics: "Array, Hash Table, Geometry, Math", slug: "max-points-on-a-line" },
  { id: 150, title: "Evaluate Reverse Polish Notation", diff: "Medium", topics: "Array, Math, Stack", slug: "evaluate-reverse-polish-notation" },
  { id: 151, title: "Reverse Words in a String", diff: "Medium", topics: "Two Pointers, String", slug: "reverse-words-in-a-string" },
  { id: 152, title: "Maximum Product Subarray", diff: "Medium", topics: "Array, Dynamic Programming", slug: "maximum-product-subarray" },
  { id: 153, title: "Find Minimum in Rotated Sorted Array", diff: "Medium", topics: "Array, Binary Search", slug: "find-minimum-in-rotated-sorted-array" },
  { id: 154, title: "Find Minimum in Rotated Sorted Array II", diff: "Hard", topics: "Array, Binary Search", slug: "find-minimum-in-rotated-sorted-array-ii" },
  { id: 155, title: "Min Stack", diff: "Medium", topics: "Stack, Design", slug: "min-stack" },
  { id: 156, title: "Binary Tree Upside Down", diff: "Medium", topics: "Tree, Depth-First Search, Binary Tree", slug: "binary-tree-upside-down" },
  { id: 157, title: "Read N Characters Given Read4", diff: "Easy", topics: "String, Interactive, Simulation", slug: "read-n-characters-given-read4" },
  { id: 158, title: "Read N Characters Given Read4 II - Call Multiple Times", diff: "Hard", topics: "String, Interactive, Simulation", slug: "read-n-characters-given-read4-ii-call-multiple-times" },
  { id: 159, title: "Longest Substring with At Most Two Distinct Characters", diff: "Medium", topics: "Hash Table, String, Sliding Window", slug: "longest-substring-with-at-most-two-distinct-characters" },
  { id: 160, title: "Intersection of Two Linked Lists", diff: "Easy", topics: "Hash Table, Linked List, Two Pointers", slug: "intersection-of-two-linked-lists" },
  { id: 161, title: "One Edit Distance", diff: "Medium", topics: "Two Pointers, String", slug: "one-edit-distance" },
  { id: 162, title: "Find Peak Element", diff: "Medium", topics: "Array, Binary Search", slug: "find-peak-element" },
  { id: 163, title: "Missing Ranges", diff: "Easy", topics: "Array", slug: "missing-ranges" },
  { id: 164, title: "Maximum Gap", diff: "Medium", topics: "Array, Bucket Sort, Radix Sort, Sorting", slug: "maximum-gap" },
  { id: 165, title: "Compare Version Numbers", diff: "Medium", topics: "Two Pointers, String", slug: "compare-version-numbers" },
  { id: 166, title: "Fraction to Recurring Decimal", diff: "Medium", topics: "Hash Table, Math, String", slug: "fraction-to-recurring-decimal" },
  { id: 167, title: "Two Sum II - Input Array Is Sorted", diff: "Medium", topics: "Array, Two Pointers, Binary Search", slug: "two-sum-ii-input-array-is-sorted" },
  { id: 168, title: "Excel Sheet Column Title", diff: "Easy", topics: "Math, String", slug: "excel-sheet-column-title" },
  { id: 169, title: "Majority Element", diff: "Easy", topics: "Array, Hash Table, Divide and Conquer, Sorting, Counting", slug: "majority-element" },
  { id: 170, title: "Two Sum III - Data Structure Design", diff: "Easy", topics: "Hash Table, Design", slug: "two-sum-iii-data-structure-design" },
  { id: 171, title: "Excel Sheet Column Number", diff: "Easy", topics: "Math, String", slug: "excel-sheet-column-number" },
  { id: 172, title: "Factorial Trailing Zeroes", diff: "Medium", topics: "Math", slug: "factorial-trailing-zeroes" },
  { id: 173, title: "Binary Search Tree Iterator", diff: "Medium", topics: "Stack, Tree, Design, Binary Search Tree, Binary Tree, Iterator", slug: "binary-search-tree-iterator" },
  { id: 174, title: "Dungeon Game", diff: "Hard", topics: "Array, Dynamic Programming, Matrix", slug: "dungeon-game" },
  { id: 175, title: "Combine Two Tables", diff: "Easy", topics: "Database", slug: "combine-two-tables" },
  { id: 176, title: "Second Highest Salary", diff: "Medium", topics: "Database", slug: "second-highest-salary" },
  { id: 177, title: "Nth Highest Salary", diff: "Medium", topics: "Database", slug: "nth-highest-salary" },
  { id: 178, title: "Rank Scores", diff: "Medium", topics: "Database", slug: "rank-scores" },
  { id: 179, title: "Largest Number", diff: "Medium", topics: "Array, String, Greedy, Sorting", slug: "largest-number" },
  { id: 180, title: "Consecutive Numbers", diff: "Medium", topics: "Database", slug: "consecutive-numbers" },
  { id: 181, title: "Employees Earning More Than Their Managers", diff: "Easy", topics: "Database", slug: "employees-earning-more-than-their-managers" },
  { id: 182, title: "Duplicate Emails", diff: "Easy", topics: "Database", slug: "duplicate-emails" },
  { id: 183, title: "Customers Who Never Order", diff: "Easy", topics: "Database", slug: "customers-who-never-order" },
  { id: 184, title: "Department Highest Salary", diff: "Medium", topics: "Database", slug: "department-highest-salary" },
  { id: 185, title: "Department Top Three Salaries", diff: "Hard", topics: "Database", slug: "department-top-three-salaries" },
  { id: 186, title: "Reverse Words in a String II", diff: "Medium", topics: "Two Pointers, String", slug: "reverse-words-in-a-string-ii" },
  { id: 187, title: "Repeated DNA Sequences", diff: "Medium", topics: "Hash Table, String, Bit Manipulation, Rolling Hash, Hash Function", slug: "repeated-dna-sequences" },
  { id: 188, title: "Best Time to Buy and Sell Stock IV", diff: "Hard", topics: "Array, Dynamic Programming", slug: "best-time-to-buy-and-sell-stock-iv" },
  { id: 189, title: "Rotate Array", diff: "Medium", topics: "Array, Math, Two Pointers", slug: "rotate-array" },
  { id: 190, title: "Reverse Bits", diff: "Easy", topics: "Divide and Conquer, Bit Manipulation", slug: "reverse-bits" },
  { id: 191, title: "Number of 1 Bits", diff: "Easy", topics: "Divide and Conquer, Bit Manipulation", slug: "number-of-1-bits" },
  { id: 192, title: "Word Frequency", diff: "Medium", topics: "Shell", slug: "word-frequency" },
  { id: 193, title: "Valid Phone Numbers", diff: "Easy", topics: "Shell", slug: "valid-phone-numbers" },
  { id: 194, title: "Transpose File", diff: "Medium", topics: "Shell", slug: "transpose-file" },
  { id: 195, title: "Tenth Line", diff: "Easy", topics: "Shell", slug: "tenth-line" },
  { id: 196, title: "Delete Duplicate Emails", diff: "Easy", topics: "Database", slug: "delete-duplicate-emails" },
  { id: 197, title: "Rising Temperature", diff: "Easy", topics: "Database", slug: "rising-temperature" },
  { id: 198, title: "House Robber", diff: "Medium", topics: "Array, Dynamic Programming", slug: "house-robber" },
  { id: 199, title: "Binary Tree Right Side View", diff: "Medium", topics: "Tree, Depth-First Search, Breadth-First Search, Binary Tree", slug: "binary-tree-right-side-view" },
  { id: 200, title: "Number of Islands", diff: "Medium", topics: "Array, Depth-First Search, Breadth-First Search, Union Find, Matrix", slug: "number-of-islands" },
  { id: 201, title: "Bitwise AND of Numbers Range", diff: "Medium", topics: "Bit Manipulation", slug: "bitwise-and-of-numbers-range" },
  { id: 202, title: "Happy Number", diff: "Easy", topics: "Hash Table, Math, Two Pointers", slug: "happy-number" },
  { id: 203, title: "Remove Linked List Elements", diff: "Easy", topics: "Linked List, Recursion", slug: "remove-linked-list-elements" },
  { id: 204, title: "Count Primes", diff: "Medium", topics: "Array, Math, Enumeration, Number Theory", slug: "count-primes" },
  { id: 205, title: "Isomorphic Strings", diff: "Easy", topics: "Hash Table, String", slug: "isomorphic-strings" },
  { id: 206, title: "Reverse Linked List", diff: "Easy", topics: "Linked List, Recursion", slug: "reverse-linked-list" },
  { id: 207, title: "Course Schedule", diff: "Medium", topics: "Depth-First Search, Breadth-First Search, Graph, Topological Sort", slug: "course-schedule" },
  { id: 208, title: "Implement Trie (Prefix Tree)", diff: "Medium", topics: "Hash Table, String, Design, Trie", slug: "implement-trie-prefix-tree" },
  { id: 209, title: "Minimum Size Subarray Sum", diff: "Medium", topics: "Array, Binary Search, Sliding Window, Prefix Sum", slug: "minimum-size-subarray-sum" },
  { id: 210, title: "Course Schedule II", diff: "Medium", topics: "Depth-First Search, Breadth-First Search, Graph, Topological Sort", slug: "course-schedule-ii" },
  { id: 211, title: "Design Add and Search Words Data Structure", diff: "Medium", topics: "String, Depth-First Search, Design, Trie", slug: "design-add-and-search-words-data-structure" },
  { id: 212, title: "Word Search II", diff: "Hard", topics: "Array, String, Backtracking, Trie, Matrix", slug: "word-search-ii" },
  { id: 213, title: "House Robber II", diff: "Medium", topics: "Array, Dynamic Programming", slug: "house-robber-ii" },
  { id: 214, title: "Shortest Palindrome", diff: "Hard", topics: "String, Rolling Hash, String Matching, Hash Function", slug: "shortest-palindrome" },
  { id: 215, title: "Kth Largest Element in an Array", diff: "Medium", topics: "Array, Divide and Conquer, Sorting, Heap (Priority Queue), Quickselect", slug: "kth-largest-element-in-an-array" },
  { id: 216, title: "Combination Sum III", diff: "Medium", topics: "Array, Backtracking", slug: "combination-sum-iii" },
  { id: 217, title: "Contains Duplicate", diff: "Easy", topics: "Array, Hash Table, Sorting", slug: "contains-duplicate" },
  { id: 218, title: "The Skyline Problem", diff: "Hard", topics: "Array, Divide and Conquer, Binary Indexed Tree, Segment Tree, Heap (Priority Queue), Line Sweep", slug: "the-skyline-problem" },
  { id: 219, title: "Contains Duplicate II", diff: "Easy", topics: "Array, Hash Table, Sliding Window", slug: "contains-duplicate-ii" },
  { id: 220, title: "Contains Duplicate III", diff: "Hard", topics: "Array, Sliding Window, Sorting, Bucket Sort, Ordered Set", slug: "contains-duplicate-iii" },
  { id: 221, title: "Maximal Square", diff: "Medium", topics: "Array, Dynamic Programming, Matrix", slug: "maximal-square" },
  { id: 222, title: "Count Complete Tree Nodes", diff: "Easy", topics: "Binary Search, Bit Manipulation, Tree, Binary Tree", slug: "count-complete-tree-nodes" },
  { id: 223, title: "Rectangle Area", diff: "Medium", topics: "Geometry, Math", slug: "rectangle-area" },
  { id: 224, title: "Basic Calculator", diff: "Hard", topics: "Math, String, Stack, Recursion", slug: "basic-calculator" },
  { id: 225, title: "Implement Stack using Queues", diff: "Easy", topics: "Stack, Design, Queue", slug: "implement-stack-using-queues" },
  { id: 226, title: "Invert Binary Tree", diff: "Easy", topics: "Tree, Depth-First Search, Breadth-First Search, Binary Tree", slug: "invert-binary-tree" },
  { id: 227, title: "Basic Calculator II", diff: "Medium", topics: "Math, String, Stack", slug: "basic-calculator-ii" },
  { id: 228, title: "Summary Ranges", diff: "Easy", topics: "Array", slug: "summary-ranges" },
  { id: 229, title: "Majority Element II", diff: "Medium", topics: "Array, Hash Table, Sorting, Counting", slug: "majority-element-ii" },
  { id: 230, title: "Kth Smallest Element in a BST", diff: "Medium", topics: "Tree, Depth-First Search, Binary Search Tree, Binary Tree", slug: "kth-smallest-element-in-a-bst" },
  { id: 231, title: "Power of Two", diff: "Easy", topics: "Math, Bit Manipulation, Recursion", slug: "power-of-two" },
  { id: 232, title: "Implement Queue using Stacks", diff: "Easy", topics: "Stack, Design, Queue", slug: "implement-queue-using-stacks" },
  { id: 233, title: "Number of Digit One", diff: "Hard", topics: "Math, Dynamic Programming, Recursion", slug: "number-of-digit-one" },
  { id: 234, title: "Palindrome Linked List", diff: "Easy", topics: "Linked List, Two Pointers, Stack, Recursion", slug: "palindrome-linked-list" },
  { id: 235, title: "Lowest Common Ancestor of a Binary Search Tree", diff: "Medium", topics: "Tree, Depth-First Search, Binary Search Tree, Binary Tree", slug: "lowest-common-ancestor-of-a-binary-search-tree" },
  { id: 236, title: "Lowest Common Ancestor of a Binary Tree", diff: "Medium", topics: "Tree, Depth-First Search, Binary Tree", slug: "lowest-common-ancestor-of-a-binary-tree" },
  { id: 237, title: "Delete Node in a Linked List", diff: "Medium", topics: "Linked List", slug: "delete-node-in-a-linked-list" },
  { id: 238, title: "Product of Array Except Self", diff: "Medium", topics: "Array, Prefix Sum", slug: "product-of-array-except-self" },
  { id: 239, title: "Sliding Window Maximum", diff: "Hard", topics: "Array, Queue, Sliding Window, Heap (Priority Queue), Monotonic Queue", slug: "sliding-window-maximum" },
  { id: 240, title: "Search a 2D Matrix II", diff: "Medium", topics: "Array, Binary Search, Divide and Conquer, Matrix", slug: "search-a-2d-matrix-ii" },
  { id: 241, title: "Different Ways to Add Parentheses", diff: "Medium", topics: "Math, String, Dynamic Programming, Recursion, Memoization", slug: "different-ways-to-add-parentheses" },
  { id: 242, title: "Valid Anagram", diff: "Easy", topics: "Hash Table, String, Sorting", slug: "valid-anagram" },
  { id: 243, title: "Shortest Word Distance", diff: "Easy", topics: "Array, String", slug: "shortest-word-distance" },
  { id: 244, title: "Shortest Word Distance II", diff: "Medium", topics: "Hash Table, String, Design", slug: "shortest-word-distance-ii" },
  { id: 245, title: "Shortest Word Distance III", diff: "Medium", topics: "Array, String", slug: "shortest-word-distance-iii" },
  { id: 246, title: "Strobogrammatic Number", diff: "Easy", topics: "Hash Table, Two Pointers, String", slug: "strobogrammatic-number" },
  { id: 247, title: "Strobogrammatic Number II", diff: "Medium", topics: "Array, String, Recursion", slug: "strobogrammatic-number-ii" },
  { id: 248, title: "Strobogrammatic Number III", diff: "Hard", topics: "Math, String, Recursion", slug: "strobogrammatic-number-iii" },
  { id: 249, title: "Group Shifted Strings", diff: "Medium", topics: "Array, Hash Table, String", slug: "group-shifted-strings" },
  { id: 250, title: "Count Univalue Subtrees", diff: "Medium", topics: "Tree, Depth-First Search, Binary Tree", slug: "count-univalue-subtrees" }
);