window.rawProblems = window.rawProblems || [];

window.rawProblems.push(
  { id: 2751, title: "Robot Collisions", diff: "Hard", topics: "Array, Stack, Simulation, Sorting", slug: "robot-collisions" },
  { id: 2752, title: "Customers with Maximum Number of Transactions on Consecutive Days", diff: "Hard", topics: "Database", slug: "customers-with-maximum-number-of-transactions-on-consecutive-days" },
  { id: 2753, title: "Count Houses in a Circular Street II", diff: "Hard", topics: "Interactive", slug: "count-houses-in-a-circular-street-ii" },
  { id: 2754, title: "Bind Function to Context", diff: "Medium", topics: "JavaScript", slug: "bind-function-to-context" },
  { id: 2755, title: "Deep Merge of Two Objects", diff: "Medium", topics: "JavaScript", slug: "deep-merge-of-two-objects" },
  { id: 2756, title: "Buy Two Chocolates", diff: "Easy", topics: "Array, Sorting", slug: "buy-two-chocolates" },
  { id: 2757, title: "Generate Circular Array Values", diff: "Easy", topics: "JavaScript", slug: "generate-circular-array-values" },
  { id: 2758, title: "Next Day", diff: "Easy", topics: "JavaScript", slug: "next-day" },
  { id: 2759, title: "Convert JSON String to Object", diff: "Hard", topics: "JavaScript", slug: "convert-json-string-to-object" },
  { id: 2760, title: "Longest Even Odd Subarray With Threshold", diff: "Easy", topics: "Array, Sliding Window", slug: "longest-even-odd-subarray-with-threshold" },
  { id: 2761, title: "Prime Pairs With Target Sum", diff: "Medium", topics: "Array, Math, Number Theory", slug: "prime-pairs-with-target-sum" },
  { id: 2762, title: "Continuous Subarrays", diff: "Medium", topics: "Array, Ordered Set, Sliding Window, Queue", slug: "continuous-subarrays" },
  { id: 2763, title: "Sum of Imbalance Numbers of All Subarrays", diff: "Hard", topics: "Array, Enumeration, Monotonic Stack", slug: "sum-of-imbalance-numbers-of-all-subarrays" },
  { id: 2764, title: "Is Array a Preorder of Some Binary Tree", diff: "Medium", topics: "Tree, Stack", slug: "is-array-a-preorder-of-some-binary-tree" },
  { id: 2765, title: "Longest Alternating Subarray", diff: "Easy", topics: "Array", slug: "longest-alternating-subarray" },
  { id: 2766, title: "Relocate Marbles", diff: "Medium", topics: "Array, Hash Table, Simulation", slug: "relocate-marbles" },
  { id: 2767, title: "Partition String Into Minimum Beautiful Substrings", diff: "Medium", topics: "String, Backtracking, Dynamic Programming", slug: "partition-string-into-minimum-beautiful-substrings" },
  { id: 2768, title: "Number of Black Blocks", diff: "Medium", topics: "Array, Hash Table", slug: "number-of-black-blocks" },
  { id: 2769, title: "Find the Maximum Achievable Number", diff: "Easy", topics: "Math", slug: "find-the-maximum-achievable-number" },
  { id: 2770, title: "Maximum Number of Jumps to Reach the Last Index", diff: "Medium", topics: "Array, Dynamic Programming", slug: "maximum-number-of-jumps-to-reach-the-last-index" },
  { id: 2771, title: "Longest Non-decreasing Subarray From Two Arrays", diff: "Medium", topics: "Array, Dynamic Programming", slug: "longest-non-decreasing-subarray-from-two-arrays" },
  { id: 2772, title: "Apply Operations to Make All Array Elements Equal to Zero", diff: "Medium", topics: "Array, Greedy, Prefix Sum", slug: "apply-operations-to-make-all-array-elements-equal-to-zero" },
  { id: 2773, title: "Height of Special Binary Tree", diff: "Medium", topics: "Tree, Depth-First Search", slug: "height-of-special-binary-tree" },
  { id: 2774, title: "Array Upper Bound", diff: "Easy", topics: "JavaScript", slug: "array-upper-bound" },
  { id: 2775, title: "Undefined to Null", diff: "Easy", topics: "JavaScript", slug: "undefined-to-null" },
  { id: 2776, title: "Convert Callback Based Function to Promise Based Function", diff: "Medium", topics: "JavaScript", slug: "convert-callback-based-function-to-promise-based-function" },
  { id: 2777, title: "Date Range Generator", diff: "Easy", topics: "JavaScript", slug: "date-range-generator" },
  { id: 2778, title: "Sum of Squares of Special Elements", diff: "Easy", topics: "Array, Math", slug: "sum-of-squares-of-special-elements" },
  { id: 2779, title: "Maximum Beauty of an Array After Applying Operation", diff: "Medium", topics: "Array, Binary Search, Sliding Window, Sorting", slug: "maximum-beauty-of-an-array-after-applying-operation" },
  { id: 2780, title: "Minimum Index of a Valid Split", diff: "Medium", topics: "Array, Hash Table", slug: "minimum-index-of-a-valid-split" },
  { id: 2781, title: "Length of the Longest Valid Substring", diff: "Hard", topics: "Hash Table, String, Sliding Window, Trie", slug: "length-of-the-longest-valid-substring" },
  { id: 2782, title: "Number of Unique Categories", diff: "Medium", topics: "Interactive", slug: "number-of-unique-categories" },
  { id: 2783, title: "Flight Occupancy and Waitlist Analysis", diff: "Medium", topics: "Database", slug: "flight-occupancy-and-waitlist-analysis" },
  { id: 2784, title: "Check if Array is Good", diff: "Easy", topics: "Array, Hash Table, Sorting", slug: "check-if-array-is-good" },
  { id: 2785, title: "Sort Vowels in a String", diff: "Medium", topics: "String, Sorting", slug: "sort-vowels-in-a-string" },
  { id: 2786, title: "Visit Array Positions to Maximize Score", diff: "Medium", topics: "Array, Dynamic Programming", slug: "visit-array-positions-to-maximize-score" },
  { id: 2787, title: "Ways to Express an Integer as Sum of Powers", diff: "Medium", topics: "Dynamic Programming", slug: "ways-to-express-an-integer-as-sum-of-powers" },
  { id: 2788, title: "Split Strings by Separator", diff: "Easy", topics: "Array, String", slug: "split-strings-by-separator" },
  { id: 2789, title: "Largest Element in an Array after Merge Operations", diff: "Medium", topics: "Array, Greedy", slug: "largest-element-in-an-array-after-merge-operations" },
  { id: 2790, title: "Maximum Number of Groups With Increasing Length", diff: "Hard", topics: "Array, Greedy, Sorting", slug: "maximum-number-of-groups-with-increasing-length" },
  { id: 2791, title: "Count Paths That Can Form a Palindrome in a Tree", diff: "Hard", topics: "Bit Manipulation, Hash Table, Tree, Depth-First Search", slug: "count-paths-that-can-form-a-palindrome-in-a-tree" },
  { id: 2792, title: "Count Nodes That Are Great Enough", diff: "Hard", topics: "Tree, Depth-First Search, Heap (Priority Queue)", slug: "count-nodes-that-are-great-enough" },
  { id: 2793, title: "Status of Flight Tickets", diff: "Medium", topics: "Database", slug: "status-of-flight-tickets" },
  { id: 2794, title: "Create Object from Two Arrays", diff: "Easy", topics: "JavaScript", slug: "create-object-from-two-arrays" },
  { id: 2795, title: "Parallel Execution of Promises for Individual Results Retrieval", diff: "Medium", topics: "JavaScript", slug: "parallel-execution-of-promises-for-individual-results-retrieval" },
  { id: 2796, title: "Repeat String", diff: "Easy", topics: "JavaScript", slug: "repeat-string" },
  { id: 2797, title: "Partial Function with Placeholders", diff: "Medium", topics: "JavaScript", slug: "partial-function-with-placeholders" },
  { id: 2798, title: "Number of Employees Who Met the Target", diff: "Easy", topics: "Array", slug: "number-of-employees-who-met-the-target" },
  { id: 2799, title: "Count Complete Subarrays in an Array", diff: "Medium", topics: "Array, Hash Table, Sliding Window", slug: "count-complete-subarrays-in-an-array" },
  { id: 2800, title: "Shortest String That Contains Three Strings", diff: "Medium", topics: "String, Enumeration, Greedy", slug: "shortest-string-that-contains-three-strings" },
  { id: 2801, title: "Count Stepping Numbers in Range", diff: "Hard", topics: "Math, Dynamic Programming, Digit DP", slug: "count-stepping-numbers-in-range" },
  { id: 2802, title: "Find The K-th Lucky Number", diff: "Hard", topics: "Math, Bit Manipulation", slug: "find-the-k-th-lucky-number" },
  { id: 2803, title: "Factorial Generator", diff: "Easy", topics: "JavaScript", slug: "factorial-generator" },
  { id: 2804, title: "Array Prototype ForEach", diff: "Easy", topics: "JavaScript", slug: "array-prototype-foreach" },
  { id: 2805, title: "Custom Interval", diff: "Medium", topics: "JavaScript", slug: "custom-interval" },
  { id: 2806, title: "Account Balance After Rounded Purchase", diff: "Easy", topics: "Math", slug: "account-balance-after-rounded-purchase" },
  { id: 2807, title: "Insert Greatest Common Divisors in Linked List", diff: "Medium", topics: "Linked List, Math, Number Theory", slug: "insert-greatest-common-divisors-in-linked-list" },
  { id: 2808, title: "Minimum Seconds to Equalize a Circular Array", diff: "Medium", topics: "Array, Hash Table", slug: "minimum-seconds-to-equalize-a-circular-array" },
  { id: 2809, title: "Minimum Time to Make Array Sum At Most x", diff: "Hard", topics: "Array, Dynamic Programming, Sorting", slug: "minimum-time-to-make-array-sum-at-most-x" },
  { id: 2810, title: "Faulty Keyboard", diff: "Easy", topics: "String, Simulation", slug: "faulty-keyboard" },
  { id: 2811, title: "Check if it is Possible to Split Array", diff: "Medium", topics: "Array, Dynamic Programming, Greedy", slug: "check-if-it-is-possible-to-split-array" },
  { id: 2812, title: "Find the Safest Path in a Grid", diff: "Medium", topics: "Array, Breadth-First Search, Binary Search, Matrix, Heap (Priority Queue)", slug: "find-the-safest-path-in-a-grid" },
  { id: 2813, title: "Maximum Elegance of a K-Length Subsequence", diff: "Hard", topics: "Array, Greedy, Sorting", slug: "maximum-elegance-of-a-k-length-subsequence" },
  { id: 2814, title: "Minimum Time Takes to Reach Destination Without Drowning", diff: "Hard", topics: "Array, Breadth-First Search, Matrix", slug: "minimum-time-takes-to-reach-destination-without-drowning" },
  { id: 2815, title: "Max Pair Sum in an Array", diff: "Easy", topics: "Array, Hash Table", slug: "max-pair-sum-in-an-array" },
  { id: 2816, title: "Double a Number Represented as a Linked List", diff: "Medium", topics: "Linked List, Math, Stack, Recursion", slug: "double-a-number-represented-as-a-linked-list" },
  { id: 2817, title: "Minimum Absolute Difference Between Elements With Constraint", diff: "Medium", topics: "Array, Ordered Set, Sliding Window", slug: "minimum-absolute-difference-between-elements-with-constraint" },
  { id: 2818, title: "Apply Operations to Maximize Score", diff: "Hard", topics: "Array, Math, Monotonic Stack, Greedy, Number Theory", slug: "apply-operations-to-maximize-score" },
  { id: 2819, title: "Minimum Relative Loss After Buying Chocolates", diff: "Hard", topics: "Array, Binary Search, Prefix Sum, Sorting", slug: "minimum-relative-loss-after-buying-chocolates" },
  { id: 2820, title: "Election Results", diff: "Medium", topics: "Database", slug: "election-results" },
  { id: 2821, title: "Delay the Resolution of Each Promise", diff: "Medium", topics: "JavaScript", slug: "delay-the-resolution-of-each-promise" },
  { id: 2822, title: "Inversion of Object", diff: "Easy", topics: "JavaScript", slug: "inversion-of-object" },
  { id: 2823, title: "Deep Object Filter", diff: "Medium", topics: "JavaScript", slug: "deep-object-filter" },
  { id: 2824, title: "Count Pairs Whose Sum is Less than Target", diff: "Easy", topics: "Array, Two Pointers, Binary Search, Sorting", slug: "count-pairs-whose-sum-is-less-than-target" },
  { id: 2825, title: "Make String a Subsequence Using Cyclic Increments", diff: "Medium", topics: "Two Pointers, String, Greedy", slug: "make-string-a-subsequence-using-cyclic-increments" },
  { id: 2826, title: "Sorting Three Groups", diff: "Medium", topics: "Array, Dynamic Programming", slug: "sorting-three-groups" },
  { id: 2827, title: "Number of Beautiful Integers in the Range", diff: "Hard", topics: "Math, Dynamic Programming, Digit DP", slug: "number-of-beautiful-integers-in-the-range" },
  { id: 2828, title: "Check if a String Is an Acronym of Words", diff: "Easy", topics: "Array, String", slug: "check-if-a-string-is-an-acronym-of-words" },
  { id: 2829, title: "Determine the Minimum Sum of a k-avoiding Array", diff: "Medium", topics: "Array, Greedy, Hash Table", slug: "determine-the-minimum-sum-of-a-k-avoiding-array" },
  { id: 2830, title: "Maximize the Profit as the Salesman", diff: "Medium", topics: "Array, Dynamic Programming, Binary Search, Sorting", slug: "maximize-the-profit-as-the-salesman" },
  { id: 2831, title: "Find the Longest Equal Subarray", diff: "Medium", topics: "Array, Hash Table, Sliding Window", slug: "find-the-longest-equal-subarray" },
  { id: 2832, title: "Maximal Range That Each Element Is Maximum in It", diff: "Medium", topics: "Array, Monotonic Stack", slug: "maximal-range-that-each-element-is-maximum-in-it" },
  { id: 2833, title: "Furthest Point From Origin", diff: "Easy", topics: "Math, String, Greedy", slug: "furthest-point-from-origin" },
  { id: 2834, title: "Find the Minimum Possible Sum of a Beautiful Array", diff: "Medium", topics: "Math, Greedy", slug: "find-the-minimum-possible-sum-of-a-beautiful-array" },
  { id: 2835, title: "Minimum Operations to Form Subsequence With Target Sum", diff: "Hard", topics: "Bit Manipulation, Greedy", slug: "minimum-operations-to-form-subsequence-with-target-sum" },
  { id: 2836, title: "Maximize Value of Function in a Ball Passing Game", diff: "Hard", topics: "Dynamic Programming, Bit Manipulation, Graph", slug: "maximize-value-of-function-in-a-ball-passing-game" },
  { id: 2837, title: "Total Traveled Distance", diff: "Easy", topics: "Database", slug: "total-traveled-distance" },
  { id: 2838, title: "Maximum Coins Heroes Can Collect", diff: "Medium", topics: "Array, Binary Search, Prefix Sum, Sorting", slug: "maximum-coins-heroes-can-collect" },
  { id: 2839, title: "Check if Strings Can be Made Equal With Operations I", diff: "Easy", topics: "String", slug: "check-if-strings-can-be-made-equal-with-operations-i" },
  { id: 2840, title: "Check if Strings Can be Made Equal With Operations II", diff: "Medium", topics: "Hash Table, String, Sorting", slug: "check-if-strings-can-be-made-equal-with-operations-ii" },
  { id: 2841, title: "Maximum Sum of Almost Unique Subarray", diff: "Medium", topics: "Array, Hash Table, Sliding Window", slug: "maximum-sum-of-almost-unique-subarray" },
  { id: 2842, title: "Count K-Subsequences of a String With Maximum Beauty", diff: "Hard", topics: "Hash Table, String, Math, Combinatorics, Counting", slug: "count-k-subsequences-of-a-string-with-maximum-beauty" },
  { id: 2843, title: "Count Symmetric Integers", diff: "Easy", topics: "Math, Enumeration", slug: "count-symmetric-integers" },
  { id: 2844, title: "Minimum Operations to Make a Special Number", diff: "Medium", topics: "String, Greedy", slug: "minimum-operations-to-make-a-special-number" },
  { id: 2845, title: "Count of Interesting Subarrays", diff: "Medium", topics: "Array, Hash Table, Prefix Sum", slug: "count-of-interesting-subarrays" },
  { id: 2846, title: "Minimum Edge Weight Equilibrium Queries in a Tree", diff: "Hard", topics: "Tree, Depth-First Search, Binary Lifting, Prefix Sum", slug: "minimum-edge-weight-equilibrium-queries-in-a-tree" },
  { id: 2847, title: "Smallest Number With Given Digit Product", diff: "Medium", topics: "Math, Greedy", slug: "smallest-number-with-given-digit-product" },
  { id: 2848, title: "Points That Intersect With Cars", diff: "Easy", topics: "Array, Prefix Sum", slug: "points-that-intersect-with-cars" },
  { id: 2849, title: "Determine if a Cell Is Reachable at a Given Time", diff: "Medium", topics: "Math", slug: "determine-if-a-cell-is-reachable-at-a-given-time" },
  { id: 2850, title: "Minimum Moves to Spread Stones Over Grid", diff: "Medium", topics: "Array, Backtracking, Breadth-First Search, Matrix", slug: "minimum-moves-to-spread-stones-over-grid" },
  { id: 2851, title: "String Transformation", diff: "Hard", topics: "String, Dynamic Programming, Matrix, Math", slug: "string-transformation" },
  { id: 2852, title: "Sum of Remoteness of All Cells", diff: "Medium", topics: "Array, Depth-First Search, Union Find, Matrix", slug: "sum-of-remoteness-of-all-cells" },
  { id: 2853, title: "Highest Salaries Difference", diff: "Medium", topics: "Database", slug: "highest-salaries-difference" },
  { id: 2854, title: "Rolling Average Steps", diff: "Medium", topics: "Database", slug: "rolling-average-steps" },
  { id: 2855, title: "Minimum Right Shifts to Sort the Array", diff: "Easy", topics: "Array", slug: "minimum-right-shifts-to-sort-the-array" },
  { id: 2856, title: "Minimum Array Length After Pair Removals", diff: "Medium", topics: "Array, Binary Search, Greedy, Two Pointers", slug: "minimum-array-length-after-pair-removals" },
  { id: 2857, title: "Count Pairs of Points With Distance k", diff: "Medium", topics: "Array, Hash Table, Bit Manipulation", slug: "count-pairs-of-points-with-distance-k" },
  { id: 2858, title: "Minimum Edge Reversals So Every Node Is Reachable", diff: "Hard", topics: "Tree, Depth-First Search, Dynamic Programming", slug: "minimum-edge-reversals-so-every-node-is-reachable" },
  { id: 2859, title: "Sum of Values at Indices With K Set Bits", diff: "Easy", topics: "Array, Bit Manipulation", slug: "sum-of-values-at-indices-with-k-set-bits" },
  { id: 2860, title: "Happy Students", diff: "Medium", topics: "Array, Sorting", slug: "happy-students" },
  { id: 2861, title: "Maximum Number of Alloys", diff: "Medium", topics: "Array, Binary Search", slug: "maximum-number-of-alloys" },
  { id: 2862, title: "Maximum Element-Sum of a Complete Subset of Indices", diff: "Hard", topics: "Array, Math, Number Theory", slug: "maximum-element-sum-of-a-complete-subset-of-indices" },
  { id: 2863, title: "Maximum Length of Semi-Decreasing Subarrays", diff: "Medium", topics: "Array, Binary Search, Monotonic Stack", slug: "maximum-length-of-semi-decreasing-subarrays" },
  { id: 2864, title: "Maximum Odd Binary Number", diff: "Easy", topics: "String, Greedy", slug: "maximum-odd-binary-number" },
  { id: 2865, title: "Beautiful Towers I", diff: "Medium", topics: "Array, Dynamic Programming, Monotonic Stack", slug: "beautiful-towers-i" },
  { id: 2866, title: "Beautiful Towers II", diff: "Hard", topics: "Array, Monotonic Stack, Prefix Sum", slug: "beautiful-towers-ii" },
  { id: 2867, title: "Count Valid Paths in a Tree", diff: "Hard", topics: "Tree, Depth-First Search, Union Find, Number Theory", slug: "count-valid-paths-in-a-tree" },
  { id: 2868, title: "The Wording Game", diff: "Hard", topics: "Greedy, String", slug: "the-wording-game" },
  { id: 2869, title: "Minimum Operations to Collect Elements", diff: "Easy", topics: "Array, Hash Table, Simulation", slug: "minimum-operations-to-collect-elements" },
  { id: 2870, title: "Minimum Number of Operations to Make Array Empty", diff: "Medium", topics: "Array, Hash Table, Greedy, Counting", slug: "minimum-number-of-operations-to-make-array-empty" },
  { id: 2871, title: "Split Array Into Maximum Number of Subarrays", diff: "Medium", topics: "Array, Bit Manipulation, Greedy", slug: "split-array-into-maximum-number-of-subarrays" },
  { id: 2872, title: "Maximum Number of K-Divisible Components", diff: "Hard", topics: "Tree, Depth-First Search, Greedy", slug: "maximum-number-of-k-divisible-components" },
  { id: 2873, title: "Maximum Value of an Ordered Triplet I", diff: "Easy", topics: "Array", slug: "maximum-value-of-an-ordered-triplet-i" },
  { id: 2874, title: "Maximum Value of an Ordered Triplet II", diff: "Medium", topics: "Array, Prefix Sum", slug: "maximum-value-of-an-ordered-triplet-ii" },
  { id: 2875, title: "Minimum Size Subarray in Infinite Array", diff: "Medium", topics: "Array, Hash Table, Prefix Sum, Sliding Window", slug: "minimum-size-subarray-in-infinite-array" },
  { id: 2876, title: "Count Visited Nodes in a Directed Graph", diff: "Hard", topics: "Depth-First Search, Graph, Topological Sort", slug: "count-visited-nodes-in-a-directed-graph" },
  { id: 2877, title: "Create a DataFrame from List", diff: "Easy", topics: "Pandas", slug: "create-a-dataframe-from-list" },
  { id: 2878, title: "Get the Size of a DataFrame", diff: "Easy", topics: "Pandas", slug: "get-the-size-of-a-dataframe" },
  { id: 2879, title: "Display the First Three Rows", diff: "Easy", topics: "Pandas", slug: "display-the-first-three-rows" },
  { id: 2880, title: "Select Data", diff: "Easy", topics: "Pandas", slug: "select-data" },
  { id: 2881, title: "Create a New Column", diff: "Easy", topics: "Pandas", slug: "create-a-new-column" },
  { id: 2882, title: "Drop Duplicate Rows", diff: "Easy", topics: "Pandas", slug: "drop-duplicate-rows" },
  { id: 2883, title: "Drop Missing Data", diff: "Easy", topics: "Pandas", slug: "drop-missing-data" },
  { id: 2884, title: "Modify Columns", diff: "Easy", topics: "Pandas", slug: "modify-columns" },
  { id: 2885, title: "Rename Columns", diff: "Easy", topics: "Pandas", slug: "rename-columns" },
  { id: 2886, title: "Change Data Type", diff: "Easy", topics: "Pandas", slug: "change-data-type" },
  { id: 2887, title: "Fill Missing Data", diff: "Easy", topics: "Pandas", slug: "fill-missing-data" },
  { id: 2888, title: "Reshape Data: Concatenate", diff: "Easy", topics: "Pandas", slug: "reshape-data-concatenate" },
  { id: 2889, title: "Reshape Data: Pivot", diff: "Easy", topics: "Pandas", slug: "reshape-data-pivot" },
  { id: 2890, title: "Reshape Data: Melt", diff: "Easy", topics: "Pandas", slug: "reshape-data-melt" },
  { id: 2891, title: "Method Chaining", diff: "Easy", topics: "Pandas", slug: "method-chaining" },
  { id: 2892, title: "Minimizing Array After Replacing Pairs With Their Product", diff: "Medium", topics: "Array, Greedy", slug: "minimizing-array-after-replacing-pairs-with-their-product" },
  { id: 2893, title: "Calculate Orders Within Each Interval", diff: "Medium", topics: "Database", slug: "calculate-orders-within-each-interval" },
  { id: 2894, title: "Divisible and Non-divisible Sums Difference", diff: "Easy", topics: "Math", slug: "divisible-and-non-divisible-sums-difference" },
  { id: 2895, title: "Minimum Processing Time", diff: "Medium", topics: "Array, Greedy, Sorting", slug: "minimum-processing-time" },
  { id: 2896, title: "Apply Operations to Make Two Strings Equal", diff: "Hard", topics: "String, Dynamic Programming", slug: "apply-operations-to-make-two-strings-equal" },
  { id: 2897, title: "Apply Operations on Array to Maximize Sum of Squares", diff: "Hard", topics: "Array, Bit Manipulation, Greedy", slug: "apply-operations-on-array-to-maximize-sum-of-squares" },
  { id: 2898, title: "Maximum Linear Stock Score", diff: "Medium", topics: "Hash Table, Dynamic Programming", slug: "maximum-linear-stock-score" },
  { id: 2899, title: "Last Visited Integers", diff: "Easy", topics: "Array, Simulation", slug: "last-visited-integers" },
  { id: 2900, title: "Longest Unequal Adjacent Groups Subsequence I", diff: "Easy", topics: "Array, String", slug: "longest-unequal-adjacent-groups-subsequence-i" },
  { id: 2901, title: "Longest Unequal Adjacent Groups Subsequence II", diff: "Medium", topics: "Array, Dynamic Programming, String", slug: "longest-unequal-adjacent-groups-subsequence-ii" },
  { id: 2902, title: "Count of Sub-Multisets With Bounded Sum", diff: "Hard", topics: "Array, Dynamic Programming", slug: "count-of-sub-multisets-with-bounded-sum" },
  { id: 2903, title: "Find Indices With Index and Value Difference I", diff: "Easy", topics: "Array", slug: "find-indices-with-index-and-value-difference-i" },
  { id: 2904, title: "Shortest and Lexicographically Smallest Beautiful String", diff: "Medium", topics: "String, Sliding Window", slug: "shortest-and-lexicographically-smallest-beautiful-string" },
  { id: 2905, title: "Find Indices With Index and Value Difference II", diff: "Medium", topics: "Array, Sliding Window", slug: "find-indices-with-index-and-value-difference-ii" },
  { id: 2906, title: "Construct Product Matrix", diff: "Medium", topics: "Array, Matrix, Prefix Sum", slug: "construct-product-matrix" },
  { id: 2907, title: "Maximum Profitable Triplets With Increasing Prices I", diff: "Medium", topics: "Array, Binary Indexed Tree, Dynamic Programming", slug: "maximum-profitable-triplets-with-increasing-prices-i" },
  { id: 2908, title: "Minimum Sum of Mountain Triplets I", diff: "Easy", topics: "Array", slug: "minimum-sum-of-mountain-triplets-i" },
  { id: 2909, title: "Minimum Sum of Mountain Triplets II", diff: "Medium", topics: "Array, Prefix Sum", slug: "minimum-sum-of-mountain-triplets-ii" },
  { id: 2910, title: "Minimum Number of Groups to Create a Valid Assignment", diff: "Hard", topics: "Array, Hash Table, Greedy, Counting", slug: "minimum-number-of-groups-to-create-a-valid-assignment" },
  { id: 2911, title: "Minimum Changes to Make K Semi-palindromes", diff: "Hard", topics: "String, Dynamic Programming", slug: "minimum-changes-to-make-k-semi-palindromes" },
  { id: 2912, title: "Number of Ways to Reach Destination in the Grid", diff: "Hard", topics: "Dynamic Programming, Math", slug: "number-of-ways-to-reach-destination-in-the-grid" },
  { id: 2913, title: "Subarrays Distinct Element Sum of Squares I", diff: "Easy", topics: "Array, Hash Table, Enumeration", slug: "subarrays-distinct-element-sum-of-squares-i" },
  { id: 2914, title: "Minimum Number of Changes to Make Binary String Beautiful", diff: "Medium", topics: "String, Greedy", slug: "minimum-number-of-changes-to-make-binary-string-beautiful" },
  { id: 2915, title: "Length of the Longest Subsequence That Sums to Target", diff: "Medium", topics: "Array, Dynamic Programming", slug: "length-of-the-longest-subsequence-that-sums-to-target" },
  { id: 2916, title: "Subarrays Distinct Element Sum of Squares II", diff: "Hard", topics: "Array, Segment Tree, Lazy Propagation", slug: "subarrays-distinct-element-sum-of-squares-ii" },
  { id: 2917, title: "Find the K-or of an Array", diff: "Easy", topics: "Array, Bit Manipulation", slug: "find-the-k-or-of-an-array" },
  { id: 2918, title: "Minimum Equal Sum of Two Arrays After Replacing Zeros", diff: "Medium", topics: "Array, Greedy", slug: "minimum-equal-sum-of-two-arrays-after-replacing-zeros" },
  { id: 2919, title: "Minimum Increment Operations to Make Array Beautiful", diff: "Medium", topics: "Array, Dynamic Programming", slug: "minimum-increment-operations-to-make-array-beautiful" },
  { id: 2920, title: "Maximum Points After Collecting Coins From All Nodes", diff: "Hard", topics: "Tree, Dynamic Programming, Depth-First Search", slug: "maximum-points-after-collecting-coins-from-all-nodes" },
  { id: 2921, title: "Maximum Profitable Triplets With Increasing Prices II", diff: "Hard", topics: "Array, Binary Indexed Tree, Segment Tree", slug: "maximum-profitable-triplets-with-increasing-prices-ii" },
  { id: 2922, title: "Market Analysis III", diff: "Hard", topics: "Database", slug: "market-analysis-iii" },
  { id: 2923, title: "Find Champion I", diff: "Easy", topics: "Array, Matrix", slug: "find-champion-i" },
  { id: 2924, title: "Find Champion II", diff: "Medium", topics: "Graph", slug: "find-champion-ii" },
  { id: 2925, title: "Maximum Score After Applying Operations on a Tree", diff: "Medium", topics: "Tree, Depth-First Search, Dynamic Programming", slug: "maximum-score-after-applying-operations-on-a-tree" },
  { id: 2926, title: "Maximum Balanced Subsequence Sum", diff: "Hard", topics: "Array, Binary Indexed Tree, Dynamic Programming", slug: "maximum-balanced-subsequence-sum" },
  { id: 2927, title: "Distribute Candies Among Children III", diff: "Hard", topics: "Math, Combinatorics", slug: "distribute-candies-among-children-iii" },
  { id: 2928, title: "Distribute Candies Among Children I", diff: "Easy", topics: "Math, Enumeration", slug: "distribute-candies-among-children-i" },
  { id: 2929, title: "Distribute Candies Among Children II", diff: "Medium", topics: "Math, Combinatorics", slug: "distribute-candies-among-children-ii" },
  { id: 2930, title: "Number of Strings Which Can Be Rearranged to Contain Substring", diff: "Hard", topics: "Dynamic Programming, Combinatorics", slug: "number-of-strings-which-can-be-rearranged-to-contain-substring" },
  { id: 2931, title: "Maximum Spending After Buying Items", diff: "Medium", topics: "Array, Greedy, Heap (Priority Queue), Matrix", slug: "maximum-spending-after-buying-items" },
  { id: 2932, title: "Maximum Strong Pair XOR I", diff: "Easy", topics: "Array, Bit Manipulation, Trie", slug: "maximum-strong-pair-xor-i" },
  { id: 2933, title: "High-Access Employees", diff: "Medium", topics: "Array, Hash Table, Sorting", slug: "high-access-employees" },
  { id: 2934, title: "Minimum Operations to Maximize Last Elements in Arrays", diff: "Medium", topics: "Array, Greedy", slug: "minimum-operations-to-maximize-last-elements-in-arrays" },
  { id: 2935, title: "Maximum Strong Pair XOR II", diff: "Hard", topics: "Array, Bit Manipulation, Trie, Sliding Window", slug: "maximum-strong-pair-xor-ii" },
  { id: 2936, title: "Number of Equal Numbers Blocks", diff: "Medium", topics: "Database", slug: "number-of-equal-numbers-blocks" },
  { id: 2937, title: "Make Three Strings Equal", diff: "Easy", topics: "String", slug: "make-three-strings-equal" },
  { id: 2938, title: "Separate Black and White Balls", diff: "Medium", topics: "Two Pointers, String, Greedy", slug: "separate-black-and-white-balls" },
  { id: 2939, title: "Maximum Xor Product", diff: "Medium", topics: "Bit Manipulation, Greedy, Math", slug: "maximum-xor-product" },
  { id: 2940, title: "Find Building Where Alice and Bob Can Meet", diff: "Hard", topics: "Array, Binary Search, Monotonic Stack, Segment Tree", slug: "find-building-where-alice-and-bob-can-meet" },
  { id: 2941, title: "Maximum GCD-Sum of a Subarray", diff: "Hard", topics: "Array, Number Theory", slug: "maximum-gcd-sum-of-a-subarray" },
  { id: 2942, title: "Find Words Containing Character", diff: "Easy", topics: "Array, String", slug: "find-words-containing-character" },
  { id: 2943, title: "Maximize Area of Square Hole in Grid", diff: "Medium", topics: "Array, Greedy, Sorting", slug: "maximize-area-of-square-hole-in-grid" },
  { id: 2944, title: "Minimum Number of Coins for Fruits", diff: "Medium", topics: "Array, Dynamic Programming, Monotonic Queue", slug: "minimum-number-of-coins-for-fruits" },
  { id: 2945, title: "Find Maximum Non-decreasing Array Length", diff: "Hard", topics: "Array, Dynamic Programming, Binary Search", slug: "find-maximum-non-decreasing-array-length" },
  { id: 2946, title: "Matrix Similarity After Cyclic Shifts", diff: "Easy", topics: "Array, Matrix", slug: "matrix-similarity-after-cyclic-shifts" },
  { id: 2947, title: "Count Beautiful Substrings I", diff: "Medium", topics: "String, Hash Table, Prefix Sum", slug: "count-beautiful-substrings-i" },
  { id: 2948, title: "Make Lexicographically Smallest Array by Swapping Elements", diff: "Medium", topics: "Array, Union Find, Sorting", slug: "make-lexicographically-smallest-array-by-swapping-elements" },
  { id: 2949, title: "Count Beautiful Substrings II", diff: "Hard", topics: "String, Hash Table, Prefix Sum, Number Theory", slug: "count-beautiful-substrings-ii" },
  { id: 2950, title: "Number of Divisible Substrings", diff: "Hard", topics: "String, Hash Table, Prefix Sum", slug: "number-of-divisible-substrings" },
  { id: 2951, title: "Find the Peaks", diff: "Easy", topics: "Array", slug: "find-the-peaks" },
  { id: 2952, title: "Minimum Number of Coins to be Added", diff: "Medium", topics: "Array, Greedy", slug: "minimum-number-of-coins-to-be-added" },
  { id: 2953, title: "Count Complete Substrings", diff: "Hard", topics: "String, Hash Table, Sliding Window", slug: "count-complete-substrings" },
  { id: 2954, title: "Count the Number of Infection Sequences", diff: "Hard", topics: "Math, Combinatorics", slug: "count-the-number-of-infection-sequences" },
  { id: 2955, title: "Number of Same-End Substrings", diff: "Medium", topics: "Database", slug: "number-of-same-end-substrings" },
  { id: 2956, title: "Find Common Elements Between Two Arrays", diff: "Easy", topics: "Array, Hash Table", slug: "find-common-elements-between-two-arrays" },
  { id: 2957, title: "Remove Adjacent Almost-Equal Characters", diff: "Easy", topics: "String, Greedy", slug: "remove-adjacent-almost-equal-characters" },
  { id: 2958, title: "Length of Longest Subarray With at Most K Frequency", diff: "Medium", topics: "Array, Hash Table, Sliding Window", slug: "length-of-longest-subarray-with-at-most-k-frequency" },
  { id: 2959, title: "Number of Possible Sets of Closing Branches", diff: "Hard", topics: "Bit Manipulation, Graph, Floyd Warshall, Enumeration", slug: "number-of-possible-sets-of-closing-branches" },
  { id: 2960, title: "Count Tested Devices After Test Operations", diff: "Easy", topics: "Array, Simulation", slug: "count-tested-devices-after-test-operations" },
  { id: 2961, title: "Double Modular Exponentiation", diff: "Medium", topics: "Array, Math, Simulation", slug: "double-modular-exponentiation" },
  { id: 2962, title: "Count Subarrays Where Max Element Appears at Least K Times", diff: "Medium", topics: "Array, Sliding Window", slug: "count-subarrays-where-max-element-appears-at-least-k-times" },
  { id: 2963, title: "Count the Number of Good Partitions", diff: "Hard", topics: "Array, Hash Table, Greedy", slug: "count-the-number-of-good-partitions" },
  { id: 2964, title: "Number of Divisible Triplet Sums", diff: "Medium", topics: "Array, Hash Table", slug: "number-of-divisible-triplet-sums" },
  { id: 2965, title: "Find Missing and Repeated Values", diff: "Easy", topics: "Array, Hash Table, Matrix, Math", slug: "find-missing-and-repeated-values" },
  { id: 2966, title: "Divide Array Into Arrays With Max Difference", diff: "Medium", topics: "Array, Greedy, Sorting", slug: "divide-array-into-arrays-with-max-difference" },
  { id: 2967, title: "Minimum Cost to Make Array Equalindromic", diff: "Hard", topics: "Array, Math, Sorting", slug: "minimum-cost-to-make-array-equalindromic" },
  { id: 2968, title: "Apply Operations to Maximize Frequency Score", diff: "Hard", topics: "Array, Binary Search, Prefix Sum, Sliding Window", slug: "apply-operations-to-maximize-frequency-score" },
  { id: 2969, title: "Minimum Number of Coins for Fruits II", diff: "Hard", topics: "Array, Dynamic Programming, Monotonic Queue", slug: "minimum-number-of-coins-for-fruits-ii" },
  { id: 2970, title: "Count the Number of Incremovable Subarrays I", diff: "Easy", topics: "Array, Two Pointers", slug: "count-the-number-of-incremovable-subarrays-i" },
  { id: 2971, title: "Find Polygon With the Largest Perimeter", diff: "Medium", topics: "Array, Greedy, Sorting", slug: "find-polygon-with-the-largest-perimeter" },
  { id: 2972, title: "Count the Number of Incremovable Subarrays II", diff: "Hard", topics: "Array, Two Pointers, Binary Search", slug: "count-the-number-of-incremovable-subarrays-ii" },
  { id: 2973, title: "Find Number of Coins to Place in Tree Nodes", diff: "Hard", topics: "Tree, Depth-First Search, Dynamic Programming", slug: "find-number-of-coins-to-place-in-tree-nodes" },
  { id: 2974, title: "Minimum Number Game", diff: "Easy", topics: "Array, Heap (Priority Queue), Sorting", slug: "minimum-number-game" },
  { id: 2975, title: "Maximum Square Area by Removing Fences From a Field", diff: "Medium", topics: "Array, Hash Table, Math", slug: "maximum-square-area-by-removing-fences-from-a-field" },
  { id: 2976, title: "Minimum Cost to Convert String I", diff: "Medium", topics: "Graph, Floyd Warshall, String", slug: "minimum-cost-to-convert-string-i" },
  { id: 2977, title: "Minimum Cost to Convert String II", diff: "Hard", topics: "Graph, Trie, Dynamic Programming, String", slug: "minimum-cost-to-convert-string-ii" },
  { id: 2978, title: "Symmetric Coordinates", diff: "Medium", topics: "Database", slug: "symmetric-coordinates" },
  { id: 2979, title: "Most Expensive Item That Can Not Be Bought", diff: "Medium", topics: "Math, Number Theory", slug: "most-expensive-item-that-can-not-be-bought" },
  { id: 2980, title: "Check if Bitwise OR Has Trailing Zeros", diff: "Easy", topics: "Array, Bit Manipulation", slug: "check-if-bitwise-or-has-trailing-zeros" },
  { id: 2981, title: "Find Longest Special Substring That Occurs Thrice I", diff: "Medium", topics: "String, Binary Search", slug: "find-longest-special-substring-that-occurs-thrice-i" },
  { id: 2982, title: "Find Longest Special Substring That Occurs Thrice II", diff: "Hard", topics: "String, Binary Search", slug: "find-longest-special-substring-that-occurs-thrice-ii" },
  { id: 2983, title: "Palindrome Rearrangement Queries", diff: "Hard", topics: "String, Prefix Sum", slug: "palindrome-rearrangement-queries" },
  { id: 2984, title: "Find Peak Calling Hours for Each City", diff: "Medium", topics: "Database", slug: "find-peak-calling-hours-for-each-city" },
  { id: 2985, title: "Calculate Compressed Mean", diff: "Easy", topics: "Pandas", slug: "calculate-compressed-mean" },
  { id: 2986, title: "Find Third Transaction", diff: "Medium", topics: "Database", slug: "find-third-transaction" },
  { id: 2987, title: "Find Expensive Cities", diff: "Easy", topics: "Database", slug: "find-expensive-cities" },
  { id: 2988, title: "Manager of the Largest Department", diff: "Medium", topics: "Database", slug: "manager-of-the-largest-department" },
  { id: 2989, title: "Class Performance", diff: "Medium", topics: "Database", slug: "class-performance" },
  { id: 2990, title: "Loan Types", diff: "Easy", topics: "Database", slug: "loan-types" },
  { id: 2991, title: "Top Three Wineries", diff: "Medium", topics: "Database", slug: "top-three-wineries" },
  { id: 2992, title: "Number of Self-Divisible Permutations", diff: "Hard", topics: "Backtracking, Bit Manipulation, Dynamic Programming", slug: "number-of-self-divisible-permutations" },
  { id: 2993, title: "Friday Purchases I", diff: "Easy", topics: "Database", slug: "friday-purchases-i" },
  { id: 2994, title: "Friday Purchases II", diff: "Medium", topics: "Database", slug: "friday-purchases-ii" },
  { id: 2995, title: "Viewers Turned Streamers", diff: "Medium", topics: "Database", slug: "viewers-turned-streamers" },
  { id: 2996, title: "Smallest Missing Integer Greater Than Sequential Prefix Sum", diff: "Easy", topics: "Array, Hash Table", slug: "smallest-missing-integer-greater-than-sequential-prefix-sum" },
  { id: 2997, title: "Minimum Number of Operations to Make Array XOR Equal to K", diff: "Medium", topics: "Array, Bit Manipulation", slug: "minimum-number-of-operations-to-make-array-xor-equal-to-k" },
  { id: 2998, title: "Minimum Number of Operations to Make X and Y Equal", diff: "Medium", topics: "Breadth-First Search, Math", slug: "minimum-number-of-operations-to-make-x-and-y-equal" },
  { id: 2999, title: "Count the Number of Powerful Integers", diff: "Hard", topics: "Math, Dynamic Programming, Digit DP", slug: "count-the-number-of-powerful-integers" },
  { id: 3000, title: "Maximum Area of Longest Diagonal Rectangle", diff: "Easy", topics: "Array, Math", slug: "maximum-area-of-longest-diagonal-rectangle" }

);