window.rawProblems = window.rawProblems || [];

window.rawProblems.push(
  { id: 251, title: "Flatten 2D Vector", diff: "Medium", topics: "Array, Design, Iterator", slug: "flatten-2d-vector" },
  { id: 252, title: "Meeting Rooms", diff: "Easy", topics: "Array, Sorting", slug: "meeting-rooms" },
  { id: 253, title: "Meeting Rooms II", diff: "Medium", topics: "Array, Two Pointers, Sorting, Heap (Priority Queue), Prefix Sum", slug: "meeting-rooms-ii" },
  { id: 254, title: "Factor Combinations", diff: "Medium", topics: "Backtracking", slug: "factor-combinations" },
  { id: 255, title: "Verify Preorder Sequence in Binary Search Tree", diff: "Medium", topics: "Array, Stack, Tree, Binary Search Tree, Monotonic Stack", slug: "verify-preorder-sequence-in-binary-search-tree" },
  { id: 256, title: "Paint House", diff: "Medium", topics: "Array, Dynamic Programming", slug: "paint-house" },
  { id: 257, title: "Binary Tree Paths", diff: "Easy", topics: "String, Backtracking, Tree, Depth-First Search, Binary Tree", slug: "binary-tree-paths" },
  { id: 258, title: "Add Digits", diff: "Easy", topics: "Math, Simulation, Number Theory", slug: "add-digits" },
  { id: 259, title: "3Sum Smaller", diff: "Medium", topics: "Array, Two Pointers, Sorting", slug: "3sum-smaller" },
  { id: 260, title: "Single Number III", diff: "Medium", topics: "Array, Bit Manipulation", slug: "single-number-iii" },
  { id: 261, title: "Graph Valid Tree", diff: "Medium", topics: "Depth-First Search, Breadth-First Search, Union Find, Graph", slug: "graph-valid-tree" },
  { id: 262, title: "Trips and Users", diff: "Hard", topics: "Database", slug: "trips-and-users" },
  { id: 263, title: "Ugly Number", diff: "Easy", topics: "Math", slug: "ugly-number" },
  { id: 264, title: "Ugly Number II", diff: "Medium", topics: "Hash Table, Math, Dynamic Programming, Heap (Priority Queue)", slug: "ugly-number-ii" },
  { id: 265, title: "Paint House II", diff: "Hard", topics: "Array, Dynamic Programming", slug: "paint-house-ii" },
  { id: 266, title: "Palindrome Permutation", diff: "Easy", topics: "Hash Table, String, Bit Manipulation", slug: "palindrome-permutation" },
  { id: 267, title: "Palindrome Permutation II", diff: "Medium", topics: "Hash Table, String, Backtracking", slug: "palindrome-permutation-ii" },
  { id: 268, title: "Missing Number", diff: "Easy", topics: "Array, Hash Table, Math, Binary Search, Bit Manipulation, Sorting", slug: "missing-number" },
  { id: 269, title: "Alien Dictionary", diff: "Hard", topics: "String, Depth-First Search, Breadth-First Search, Graph, Topological Sort", slug: "alien-dictionary" },
  { id: 270, title: "Closest Binary Search Tree Value", diff: "Easy", topics: "Binary Search, Tree, Depth-First Search, Binary Search Tree, Binary Tree", slug: "closest-binary-search-tree-value" },
  { id: 271, title: "Encode and Decode Strings", diff: "Medium", topics: "Array, Hash Table, String, Design", slug: "encode-and-decode-strings" },
  { id: 272, title: "Closest Binary Search Tree Value II", diff: "Hard", topics: "Stack, Tree, Depth-First Search, Binary Search Tree, Heap (Priority Queue), Binary Tree", slug: "closest-binary-search-tree-value-ii" },
  { id: 273, title: "Integer to English Words", diff: "Hard", topics: "Math, String, Recursion", slug: "integer-to-english-words" },
  { id: 274, title: "H-Index", diff: "Medium", topics: "Array, Sorting, Counting Sort", slug: "h-index" },
  { id: 275, title: "H-Index II", diff: "Medium", topics: "Array, Binary Search", slug: "h-index-ii" },
  { id: 276, title: "Paint Fence", diff: "Medium", topics: "Dynamic Programming", slug: "paint-fence" },
  { id: 277, title: "Find the Celebrity", diff: "Medium", topics: "Two Pointers, Graph, Interactive", slug: "find-the-celebrity" },
  { id: 278, title: "First Bad Version", diff: "Easy", topics: "Binary Search, Interactive", slug: "first-bad-version" },
  { id: 279, title: "Perfect Squares", diff: "Medium", topics: "Math, Dynamic Programming, Breadth-First Search", slug: "perfect-squares" },
  { id: 280, title: "Wiggle Sort", diff: "Medium", topics: "Array, Greedy, Sorting", slug: "wiggle-sort" },
  { id: 281, title: "Zigzag Iterator", diff: "Medium", topics: "Array, Design, Queue, Iterator", slug: "zigzag-iterator" },
  { id: 282, title: "Expression Add Operators", diff: "Hard", topics: "Math, String, Backtracking", slug: "expression-add-operators" },
  { id: 283, title: "Move Zeroes", diff: "Easy", topics: "Array, Two Pointers", slug: "move-zeroes" },
  { id: 284, title: "Peeking Iterator", diff: "Medium", topics: "Design, Iterator", slug: "peeking-iterator" },
  { id: 285, title: "Inorder Successor in BST", diff: "Medium", topics: "Tree, Depth-First Search, Binary Search Tree, Binary Tree", slug: "inorder-successor-in-bst" },
  { id: 286, title: "Walls and Gates", diff: "Medium", topics: "Array, Breadth-First Search, Matrix", slug: "walls-and-gates" },
  { id: 287, title: "Find the Duplicate Number", diff: "Medium", topics: "Array, Two Pointers, Binary Search, Bit Manipulation", slug: "find-the-duplicate-number" },
  { id: 288, title: "Unique Word Abbreviation", diff: "Medium", topics: "Array, Hash Table, String, Design", slug: "unique-word-abbreviation" },
  { id: 289, title: "Game of Life", diff: "Medium", topics: "Array, Matrix, Simulation", slug: "game-of-life" },
  { id: 290, title: "Word Pattern", diff: "Easy", topics: "Hash Table, String", slug: "word-pattern" },
  { id: 291, title: "Word Pattern II", diff: "Medium", topics: "Hash Table, String, Backtracking", slug: "word-pattern-ii" },
  { id: 292, title: "Nim Game", diff: "Easy", topics: "Math, Brainteaser, Game Theory", slug: "nim-game" },
  { id: 293, title: "Flip Game", diff: "Easy", topics: "String", slug: "flip-game" },
  { id: 294, title: "Flip Game II", diff: "Medium", topics: "Math, Dynamic Programming, Backtracking, Memoization, Game Theory", slug: "flip-game-ii" },
  { id: 295, title: "Find Median from Data Stream", diff: "Hard", topics: "Two Pointers, Design, Sorting, Heap (Priority Queue), Data Stream", slug: "find-median-from-data-stream" },
  { id: 296, title: "Best Meeting Point", diff: "Hard", topics: "Array, Math, Matrix, Sorting", slug: "best-meeting-point" },
  { id: 297, title: "Serialize and Deserialize Binary Tree", diff: "Hard", topics: "String, Tree, Depth-First Search, Breadth-First Search, Design, Binary Tree", slug: "serialize-and-deserialize-binary-tree" },
  { id: 298, title: "Binary Tree Longest Consecutive Sequence", diff: "Medium", topics: "Tree, Depth-First Search, Binary Tree", slug: "binary-tree-longest-consecutive-sequence" },
  { id: 299, title: "Bulls and Cows", diff: "Medium", topics: "Hash Table, String", slug: "bulls-and-cows" },
  { id: 300, title: "Longest Increasing Subsequence", diff: "Medium", topics: "Array, Binary Search, Dynamic Programming", slug: "longest-increasing-subsequence" },
  { id: 301, title: "Remove Invalid Parentheses", diff: "Hard", topics: "String, Backtracking, Breadth-First Search", slug: "remove-invalid-parentheses" },
  { id: 302, title: "Smallest Rectangle Enclosing Black Pixels", diff: "Hard", topics: "Array, Binary Search, Matrix", slug: "smallest-rectangle-enclosing-black-pixels" },
  { id: 303, title: "Range Sum Query - Immutable", diff: "Easy", topics: "Array, Design, Prefix Sum", slug: "range-sum-query-immutable" },
  { id: 304, title: "Range Sum Query 2D - Immutable", diff: "Medium", topics: "Array, Design, Matrix, Prefix Sum", slug: "range-sum-query-2d-immutable" },
  { id: 305, title: "Number of Islands II", diff: "Hard", topics: "Array, Union Find, Matrix", slug: "number-of-islands-ii" },
  { id: 306, title: "Additive Number", diff: "Medium", topics: "String, Backtracking", slug: "additive-number" },
  { id: 307, title: "Range Sum Query - Mutable", diff: "Medium", topics: "Array, Design, Binary Indexed Tree, Segment Tree", slug: "range-sum-query-mutable" },
  { id: 308, title: "Range Sum Query 2D - Mutable", diff: "Hard", topics: "Array, Design, Binary Indexed Tree, Segment Tree, Matrix", slug: "range-sum-query-2d-mutable" },
  { id: 309, title: "Best Time to Buy and Sell Stock with Cooldown", diff: "Medium", topics: "Array, Dynamic Programming", slug: "best-time-to-buy-and-sell-stock-with-cooldown" },
  { id: 310, title: "Minimum Height Trees", diff: "Medium", topics: "Depth-First Search, Breadth-First Search, Graph, Topological Sort", slug: "minimum-height-trees" },
  { id: 311, title: "Sparse Matrix Multiplication", diff: "Medium", topics: "Array, Hash Table, Matrix", slug: "sparse-matrix-multiplication" },
  { id: 312, title: "Burst Balloons", diff: "Hard", topics: "Array, Dynamic Programming", slug: "burst-balloons" },
  { id: 313, title: "Super Ugly Number", diff: "Medium", topics: "Array, Math, Dynamic Programming, Heap (Priority Queue)", slug: "super-ugly-number" },
  { id: 314, title: "Binary Tree Vertical Order Traversal", diff: "Medium", topics: "Hash Table, Tree, Depth-First Search, Breadth-First Search, Binary Tree", slug: "binary-tree-vertical-order-traversal" },
  { id: 315, title: "Count of Smaller Numbers After Self", diff: "Hard", topics: "Array, Binary Indexed Tree, Segment Tree, Divide and Conquer, Ordered Set, Merge Sort", slug: "count-of-smaller-numbers-after-self" },
  { id: 316, title: "Remove Duplicate Letters", diff: "Medium", topics: "String, Stack, Greedy, Monotonic Stack", slug: "remove-duplicate-letters" },
  { id: 317, title: "Shortest Distance from All Buildings", diff: "Hard", topics: "Array, Breadth-First Search, Matrix", slug: "shortest-distance-from-all-buildings" },
  { id: 318, title: "Maximum Product of Word Lengths", diff: "Medium", topics: "Array, String, Bit Manipulation", slug: "maximum-product-of-word-lengths" },
  { id: 319, title: "Bulb Switcher", diff: "Medium", topics: "Math, Brainteaser", slug: "bulb-switcher" },
  { id: 320, title: "Generalized Abbreviation", diff: "Medium", topics: "String, Backtracking, Bit Manipulation", slug: "generalized-abbreviation" },
  { id: 321, title: "Create Maximum Number", diff: "Hard", topics: "Array, Greedy, Stack, Monotonic Stack", slug: "create-maximum-number" },
  { id: 322, title: "Coin Change", diff: "Medium", topics: "Array, Dynamic Programming, Breadth-First Search", slug: "coin-change" },
  { id: 323, title: "Number of Connected Components in an Undirected Graph", diff: "Medium", topics: "Depth-First Search, Breadth-First Search, Union Find, Graph", slug: "number-of-connected-components-in-an-undirected-graph" },
  { id: 324, title: "Wiggle Sort II", diff: "Medium", topics: "Array, Divide and Conquer, Sorting, Quickselect", slug: "wiggle-sort-ii" },
  { id: 325, title: "Maximum Size Subarray Sum Equals k", diff: "Medium", topics: "Array, Hash Table, Prefix Sum", slug: "maximum-size-subarray-sum-equals-k" },
  { id: 326, title: "Power of Three", diff: "Easy", topics: "Math, Recursion", slug: "power-of-three" },
  { id: 327, title: "Count of Range Sum", diff: "Hard", topics: "Array, Binary Indexed Tree, Segment Tree, Divide and Conquer, Ordered Set, Merge Sort", slug: "count-of-range-sum" },
  { id: 328, title: "Odd Even Linked List", diff: "Medium", topics: "Linked List", slug: "odd-even-linked-list" },
  { id: 329, title: "Longest Increasing Path in a Matrix", diff: "Hard", topics: "Array, Dynamic Programming, Depth-First Search, Breadth-First Search, Graph, Topological Sort, Matrix, Memoization", slug: "longest-increasing-path-in-a-matrix" },
  { id: 330, title: "Patching Array", diff: "Hard", topics: "Array, Greedy", slug: "patching-array" },
  { id: 331, title: "Verify Preorder Serialization of a Binary Tree", diff: "Medium", topics: "String, Stack, Tree, Binary Tree", slug: "verify-preorder-serialization-of-a-binary-tree" },
  { id: 332, title: "Reconstruct Itinerary", diff: "Hard", topics: "Depth-First Search, Graph, Eulerian Circuit", slug: "reconstruct-itinerary" },
  { id: 333, title: "Largest BST Subtree", diff: "Medium", topics: "Dynamic Programming, Tree, Depth-First Search, Binary Search Tree, Binary Tree", slug: "largest-bst-subtree" },
  { id: 334, title: "Increasing Triplet Subsequence", diff: "Medium", topics: "Array, Greedy", slug: "increasing-triplet-subsequence" },
  { id: 335, title: "Self Crossing", diff: "Hard", topics: "Array, Math, Geometry", slug: "self-crossing" },
  { id: 336, title: "Palindrome Pairs", diff: "Hard", topics: "Array, Hash Table, String, Trie", slug: "palindrome-pairs" },
  { id: 337, title: "House Robber III", diff: "Medium", topics: "Dynamic Programming, Tree, Depth-First Search, Binary Tree", slug: "house-robber-iii" },
  { id: 338, title: "Counting Bits", diff: "Easy", topics: "Dynamic Programming, Bit Manipulation", slug: "counting-bits" },
  { id: 339, title: "Nested List Weight Sum", diff: "Medium", topics: "Depth-First Search, Breadth-First Search", slug: "nested-list-weight-sum" },
  { id: 340, title: "Longest Substring with At Most K Distinct Characters", diff: "Medium", topics: "Hash Table, String, Sliding Window", slug: "longest-substring-with-at-most-k-distinct-characters" },
  { id: 341, title: "Flatten Nested List Iterator", diff: "Medium", topics: "Stack, Tree, Design, Iterator", slug: "flatten-nested-list-iterator" },
  { id: 342, title: "Power of Four", diff: "Easy", topics: "Math, Bit Manipulation, Recursion", slug: "power-of-four" },
  { id: 343, title: "Integer Break", diff: "Medium", topics: "Math, Dynamic Programming", slug: "integer-break" },
  { id: 344, title: "Reverse String", diff: "Easy", topics: "Two Pointers, String", slug: "reverse-string" },
  { id: 345, title: "Reverse Vowels of a String", diff: "Easy", topics: "Two Pointers, String", slug: "reverse-vowels-of-a-string" },
  { id: 346, title: "Moving Average from Data Stream", diff: "Easy", topics: "Array, Design, Queue, Data Stream", slug: "moving-average-from-data-stream" },
  { id: 347, title: "Top K Frequent Elements", diff: "Medium", topics: "Array, Hash Table, Divide and Conquer, Sorting, Heap (Priority Queue), Bucket Sort, Quickselect", slug: "top-k-frequent-elements" },
  { id: 348, title: "Design Tic-Tac-Toe", diff: "Medium", topics: "Array, Hash Table, Design, Matrix", slug: "design-tic-tac-toe" },
  { id: 349, title: "Intersection of Two Arrays", diff: "Easy", topics: "Array, Hash Table, Binary Search, Sorting", slug: "intersection-of-two-arrays" },
  { id: 350, title: "Intersection of Two Arrays II", diff: "Easy", topics: "Array, Hash Table, Two Pointers, Binary Search, Sorting", slug: "intersection-of-two-arrays-ii" },
  { id: 351, title: "Android Unlock Patterns", diff: "Medium", topics: "Backtracking", slug: "android-unlock-patterns" },
  { id: 352, title: "Data Stream as Disjoint Intervals", diff: "Hard", topics: "Binary Search, Design, Ordered Set, Data Stream", slug: "data-stream-as-disjoint-intervals" },
  { id: 353, title: "Design Snake Game", diff: "Medium", topics: "Array, Hash Table, Design, Queue", slug: "design-snake-game" },
  { id: 354, title: "Russian Doll Envelopes", diff: "Hard", topics: "Array, Binary Search, Dynamic Programming, Sorting", slug: "russian-doll-envelopes" },
  { id: 355, title: "Design Twitter", diff: "Medium", topics: "Hash Table, Linked List, Design, Heap (Priority Queue)", slug: "design-twitter" },
  { id: 356, title: "Line Reflection", diff: "Medium", topics: "Array, Hash Table, Geometry, Math", slug: "line-reflection" },
  { id: 357, title: "Count Numbers with Unique Digits", diff: "Medium", topics: "Math, Dynamic Programming, Backtracking", slug: "count-numbers-with-unique-digits" },
  { id: 358, title: "Rearrange String k Distance Apart", diff: "Hard", topics: "Hash Table, String, Greedy, Sorting, Heap (Priority Queue)", slug: "rearrange-string-k-distance-apart" },
  { id: 359, title: "Logger Rate Limiter", diff: "Easy", topics: "Hash Table, Design, Data Stream", slug: "logger-rate-limiter" },
  { id: 360, title: "Sort Transformed Array", diff: "Medium", topics: "Array, Math, Two Pointers, Sorting", slug: "sort-transformed-array" },
  { id: 361, title: "Bomb Enemy", diff: "Medium", topics: "Array, Dynamic Programming, Matrix", slug: "bomb-enemy" },
  { id: 362, title: "Design Hit Counter", diff: "Medium", topics: "Array, Binary Search, Design, Queue, Data Stream", slug: "design-hit-counter" },
  { id: 363, title: "Max Sum of Rectangle No Larger Than K", diff: "Hard", topics: "Array, Binary Search, Matrix, Prefix Sum, Ordered Set", slug: "max-sum-of-rectangle-no-larger-than-k" },
  { id: 364, title: "Nested List Weight Sum II", diff: "Medium", topics: "Depth-First Search, Breadth-First Search", slug: "nested-list-weight-sum-ii" },
  { id: 365, title: "Water and Jug Problem", diff: "Medium", topics: "Math, Depth-First Search, Breadth-First Search", slug: "water-and-jug-problem" },
  { id: 366, title: "Find Leaves of Binary Tree", diff: "Medium", topics: "Tree, Depth-First Search, Binary Tree", slug: "find-leaves-of-binary-tree" },
  { id: 367, title: "Valid Perfect Square", diff: "Easy", topics: "Math, Binary Search", slug: "valid-perfect-square" },
  { id: 368, title: "Largest Divisible Subset", diff: "Medium", topics: "Array, Math, Dynamic Programming, Sorting", slug: "largest-divisible-subset" },
  { id: 369, title: "Plus One Linked List", diff: "Medium", topics: "Linked List, Math", slug: "plus-one-linked-list" },
  { id: 370, title: "Range Addition", diff: "Medium", topics: "Array, Prefix Sum", slug: "range-addition" },
  { id: 371, title: "Sum of Two Integers", diff: "Medium", topics: "Math, Bit Manipulation", slug: "sum-of-two-integers" },
  { id: 372, title: "Super Pow", diff: "Medium", topics: "Math, Divide and Conquer", slug: "super-pow" },
  { id: 373, title: "Find K Pairs with Smallest Sums", diff: "Medium", topics: "Array, Heap (Priority Queue)", slug: "find-k-pairs-with-smallest-sums" },
  { id: 374, title: "Guess Number Higher or Lower", diff: "Easy", topics: "Binary Search, Interactive", slug: "guess-number-higher-or-lower" },
  { id: 375, title: "Guess Number Higher or Lower II", diff: "Medium", topics: "Dynamic Programming, Game Theory", slug: "guess-number-higher-or-lower-ii" },
  { id: 376, title: "Wiggle Subsequence", diff: "Medium", topics: "Array, Dynamic Programming, Greedy", slug: "wiggle-subsequence" },
  { id: 377, title: "Combination Sum IV", diff: "Medium", topics: "Array, Dynamic Programming", slug: "combination-sum-iv" },
  { id: 378, title: "Kth Smallest Element in a Sorted Matrix", diff: "Medium", topics: "Array, Binary Search, Heap (Priority Queue), Matrix", slug: "kth-smallest-element-in-a-sorted-matrix" },
  { id: 379, title: "Design Phone Directory", diff: "Medium", topics: "Hash Table, Design, Queue", slug: "design-phone-directory" },
  { id: 380, title: "Insert Delete GetRandom O(1)", diff: "Medium", topics: "Array, Hash Table, Math, Design, Randomized", slug: "insert-delete-getrandom-o1" },
  { id: 381, title: "Insert Delete GetRandom O(1) - Duplicates allowed", diff: "Hard", topics: "Array, Hash Table, Math, Design, Randomized", slug: "insert-delete-getrandom-o1-duplicates-allowed" },
  { id: 382, title: "Linked List Random Node", diff: "Medium", topics: "Linked List, Math, Reservoir Sampling, Randomized", slug: "linked-list-random-node" },
  { id: 383, title: "Ransom Note", diff: "Easy", topics: "Hash Table, String, Counting", slug: "ransom-note" },
  { id: 384, title: "Shuffle an Array", diff: "Medium", topics: "Array, Math, Design, Randomized", slug: "shuffle-an-array" },
  { id: 385, title: "Mini Parser", diff: "Medium", topics: "String, Stack, Depth-First Search", slug: "mini-parser" },
  { id: 386, title: "Lexicographical Numbers", diff: "Medium", topics: "Depth-First Search, Trie", slug: "lexicographical-numbers" },
  { id: 387, title: "First Unique Character in a String", diff: "Easy", topics: "Hash Table, String, Queue, Counting", slug: "first-unique-character-in-a-string" },
  { id: 388, title: "Longest Absolute File Path", diff: "Medium", topics: "String, Stack, Depth-First Search", slug: "longest-absolute-file-path" },
  { id: 389, title: "Find the Difference", diff: "Easy", topics: "Hash Table, String, Bit Manipulation, Sorting", slug: "find-the-difference" },
  { id: 390, title: "Elimination Game", diff: "Medium", topics: "Math, Recursion", slug: "elimination-game" },
  { id: 391, title: "Perfect Rectangle", diff: "Hard", topics: "Array, Line Sweep", slug: "perfect-rectangle" },
  { id: 392, title: "Is Subsequence", diff: "Easy", topics: "Two Pointers, String, Dynamic Programming", slug: "is-subsequence" },
  { id: 393, title: "UTF-8 Validation", diff: "Medium", topics: "Array, Bit Manipulation", slug: "utf-8-validation" },
  { id: 394, title: "Decode String", diff: "Medium", topics: "String, Stack, Recursion", slug: "decode-string" },
  { id: 395, title: "Longest Substring with At Least K Repeating Characters", diff: "Medium", topics: "Hash Table, String, Divide and Conquer, Sliding Window", slug: "longest-substring-with-at-least-k-repeating-characters" },
  { id: 396, title: "Rotate Function", diff: "Medium", topics: "Array, Math, Dynamic Programming", slug: "rotate-function" },
  { id: 397, title: "Integer Replacement", diff: "Medium", topics: "Math, Bit Manipulation, Memoization", slug: "integer-replacement" },
  { id: 398, title: "Random Pick Index", diff: "Medium", topics: "Hash Table, Math, Reservoir Sampling, Randomized", slug: "random-pick-index" },
  { id: 399, title: "Evaluate Division", diff: "Medium", topics: "Array, String, Depth-First Search, Breadth-First Search, Union Find, Graph", slug: "evaluate-division" },
  { id: 400, title: "Nth Digit", diff: "Medium", topics: "Math, Binary Search", slug: "nth-digit" },
  { id: 401, title: "Binary Watch", diff: "Easy", topics: "Backtracking, Bit Manipulation", slug: "binary-watch" },
  { id: 402, title: "Remove K Digits", diff: "Medium", topics: "String, Stack, Greedy, Monotonic Stack", slug: "remove-k-digits" },
  { id: 403, title: "Frog Jump", diff: "Hard", topics: "Array, Dynamic Programming", slug: "frog-jump" },
  { id: 404, title: "Sum of Left Leaves", diff: "Easy", topics: "Tree, Depth-First Search, Breadth-First Search, Binary Tree", slug: "sum-of-left-leaves" },
  { id: 405, title: "Convert a Number to Hexadecimal", diff: "Easy", topics: "Math, Bit Manipulation", slug: "convert-a-number-to-hexadecimal" },
  { id: 406, title: "Queue Reconstruction by Height", diff: "Medium", topics: "Array, Greedy, Sorting", slug: "queue-reconstruction-by-height" },
  { id: 407, title: "Trapping Rain Water II", diff: "Hard", topics: "Array, Breadth-First Search, Heap (Priority Queue), Matrix", slug: "trapping-rain-water-ii" },
  { id: 408, title: "Valid Word Abbreviation", diff: "Easy", topics: "Two Pointers, String", slug: "valid-word-abbreviation" },
  { id: 409, title: "Longest Palindrome", diff: "Easy", topics: "Hash Table, String, Greedy", slug: "longest-palindrome" },
  { id: 410, title: "Split Array Largest Sum", diff: "Hard", topics: "Array, Binary Search, Dynamic Programming, Greedy", slug: "split-array-largest-sum" },
  { id: 411, title: "Minimum Unique Word Abbreviation", diff: "Hard", topics: "String, Backtracking, Bit Manipulation", slug: "minimum-unique-word-abbreviation" },
  { id: 412, title: "Fizz Buzz", diff: "Easy", topics: "Math, String, Simulation", slug: "fizz-buzz" },
  { id: 413, title: "Arithmetic Slices", diff: "Medium", topics: "Array, Dynamic Programming", slug: "arithmetic-slices" },
  { id: 414, title: "Third Maximum Number", diff: "Easy", topics: "Array, Sorting", slug: "third-maximum-number" },
  { id: 415, title: "Add Strings", diff: "Easy", topics: "Math, String, Simulation", slug: "add-strings" },
  { id: 416, title: "Partition Equal Subset Sum", diff: "Medium", topics: "Array, Dynamic Programming", slug: "partition-equal-subset-sum" },
  { id: 417, title: "Pacific Atlantic Water Flow", diff: "Medium", topics: "Array, Depth-First Search, Breadth-First Search, Matrix", slug: "pacific-atlantic-water-flow" },
  { id: 418, title: "Sentence Screen Fitting", diff: "Medium", topics: "String, Dynamic Programming", slug: "sentence-screen-fitting" },
  { id: 419, title: "Battleships in a Board", diff: "Medium", topics: "Array, Depth-First Search, Matrix", slug: "battleships-in-a-board" },
  { id: 420, title: "Strong Password Checker", diff: "Hard", topics: "String, Greedy, Heap (Priority Queue)", slug: "strong-password-checker" },
  { id: 421, title: "Maximum XOR of Two Numbers in an Array", diff: "Medium", topics: "Array, Hash Table, Bit Manipulation, Trie", slug: "maximum-xor-of-two-numbers-in-an-array" },
  { id: 422, title: "Valid Word Square", diff: "Easy", topics: "Array, Matrix", slug: "valid-word-square" },
  { id: 423, title: "Reconstruct Original Digits from English", diff: "Medium", topics: "Hash Table, Math, String", slug: "reconstruct-original-digits-from-english" },
  { id: 424, title: "Longest Repeating Character Replacement", diff: "Medium", topics: "Hash Table, String, Sliding Window", slug: "longest-repeating-character-replacement" },
  { id: 425, title: "Word Squares", diff: "Hard", topics: "Array, String, Backtracking, Trie", slug: "word-squares" },
  { id: 426, title: "Convert Binary Search Tree to Sorted Doubly Linked List", diff: "Medium", topics: "Linked List, Stack, Tree, Depth-First Search, Binary Search Tree", slug: "convert-binary-search-tree-to-sorted-doubly-linked-list" },
  { id: 427, title: "Construct Quad Tree", diff: "Medium", topics: "Array, Divide and Conquer, Tree, Matrix", slug: "construct-quad-tree" },
  { id: 428, title: "Serialize and Deserialize N-ary Tree", diff: "Hard", topics: "String, Tree, Depth-First Search, Breadth-First Search, Design", slug: "serialize-and-deserialize-n-ary-tree" },
  { id: 429, title: "N-ary Tree Level Order Traversal", diff: "Medium", topics: "Tree, Breadth-First Search", slug: "n-ary-tree-level-order-traversal" },
  { id: 430, title: "Flatten a Multilevel Doubly Linked List", diff: "Medium", topics: "Linked List, Depth-First Search", slug: "flatten-a-multilevel-doubly-linked-list" },
  { id: 431, title: "Encode N-ary Tree to Binary Tree", diff: "Hard", topics: "Tree, Depth-First Search, Breadth-First Search, Design", slug: "encode-n-ary-tree-to-binary-tree" },
  { id: 432, title: "All O`one Data Structure", diff: "Hard", topics: "Hash Table, Linked List, Design", slug: "all-oone-data-structure" },
  { id: 433, title: "Minimum Genetic Mutation", diff: "Medium", topics: "Hash Table, String, Breadth-First Search", slug: "minimum-genetic-mutation" },
  { id: 434, title: "Number of Segments in a String", diff: "Easy", topics: "String", slug: "number-of-segments-in-a-string" },
  { id: 435, title: "Non-overlapping Intervals", diff: "Medium", topics: "Array, Dynamic Programming, Greedy, Sorting", slug: "non-overlapping-intervals" },
  { id: 436, title: "Find Right Interval", diff: "Medium", topics: "Array, Binary Search, Sorting", slug: "find-right-interval" },
  { id: 437, title: "Path Sum III", diff: "Medium", topics: "Hash Table, Tree, Depth-First Search, Binary Tree", slug: "path-sum-iii" },
  { id: 438, title: "Find All Anagrams in a String", diff: "Medium", topics: "Hash Table, String, Sliding Window", slug: "find-all-anagrams-in-a-string" },
  { id: 439, title: "Ternary Expression Parser", diff: "Medium", topics: "String, Stack, Recursion", slug: "ternary-expression-parser" },
  { id: 440, title: "K-th Smallest in Lexicographical Order", diff: "Hard", topics: "Trie", slug: "k-th-smallest-in-lexicographical-order" },
  { id: 441, title: "Arranging Coins", diff: "Easy", topics: "Math, Binary Search", slug: "arranging-coins" },
  { id: 442, title: "Find All Duplicates in an Array", diff: "Medium", topics: "Array", slug: "find-all-duplicates-in-an-array" },
  { id: 443, title: "String Compression", diff: "Medium", topics: "Two Pointers, String", slug: "string-compression" },
  { id: 444, title: "Sequence Reconstruction", diff: "Medium", topics: "Graph, Topological Sort", slug: "sequence-reconstruction" },
  { id: 445, title: "Add Two Numbers II", diff: "Medium", topics: "Linked List, Math, Stack", slug: "add-two-numbers-ii" },
  { id: 446, title: "Arithmetic Slices II - Subsequence", diff: "Hard", topics: "Array, Dynamic Programming", slug: "arithmetic-slices-ii-subsequence" },
  { id: 447, title: "Number of Boomerangs", diff: "Medium", topics: "Array, Hash Table, Math", slug: "number-of-boomerangs" },
  { id: 448, title: "Find All Numbers Disappeared in an Array", diff: "Easy", topics: "Array, Hash Table", slug: "find-all-numbers-disappeared-in-an-array" },
  { id: 449, title: "Serialize and Deserialize BST", diff: "Medium", topics: "String, Tree, Depth-First Search, Breadth-First Search, Binary Search Tree, Design", slug: "serialize-and-deserialize-bst" },
  { id: 450, title: "Delete Node in a BST", diff: "Medium", topics: "Tree, Binary Search Tree, Binary Tree", slug: "delete-node-in-a-bst" },
  { id: 451, title: "Sort Characters By Frequency", diff: "Medium", topics: "Hash Table, String, Sorting, Heap (Priority Queue), Bucket Sort", slug: "sort-characters-by-frequency" },
  { id: 452, title: "Minimum Number of Arrows to Burst Balloons", diff: "Medium", topics: "Array, Greedy, Sorting", slug: "minimum-number-of-arrows-to-burst-balloons" },
  { id: 453, title: "Minimum Moves to Equal Array Elements", diff: "Medium", topics: "Array, Math", slug: "minimum-moves-to-equal-array-elements" },
  { id: 454, title: "4Sum II", diff: "Medium", topics: "Array, Hash Table", slug: "4sum-ii" },
  { id: 455, title: "Assign Cookies", diff: "Easy", topics: "Array, Two Pointers, Greedy, Sorting", slug: "assign-cookies" },
  { id: 456, title: "132 Pattern", diff: "Medium", topics: "Array, Binary Search, Stack, Monotonic Stack, Ordered Set", slug: "132-pattern" },
  { id: 457, title: "Circular Array Loop", diff: "Medium", topics: "Array, Two Pointers", slug: "circular-array-loop" },
  { id: 458, title: "Poor Pigs", diff: "Hard", topics: "Math, Dynamic Programming, Combinatorics", slug: "poor-pigs" },
  { id: 459, title: "Repeated Substring Pattern", diff: "Easy", topics: "String, String Matching", slug: "repeated-substring-pattern" },
  { id: 460, title: "LFU Cache", diff: "Hard", topics: "Hash Table, Linked List, Design, Doubly-Linked List", slug: "lfu-cache" },
  { id: 461, title: "Hamming Distance", diff: "Easy", topics: "Bit Manipulation", slug: "hamming-distance" },
  { id: 462, title: "Minimum Moves to Equal Array Elements II", diff: "Medium", topics: "Array, Math, Sorting", slug: "minimum-moves-to-equal-array-elements-ii" },
  { id: 463, title: "Island Perimeter", diff: "Easy", topics: "Array, Depth-First Search, Breadth-First Search, Matrix", slug: "island-perimeter" },
  { id: 464, title: "Can I Win", diff: "Medium", topics: "Math, Dynamic Programming, Bit Manipulation, Memoization, Game Theory", slug: "can-i-win" },
  { id: 465, title: "Optimal Account Balancing", diff: "Hard", topics: "Array, Dynamic Programming, Backtracking, Bit Manipulation", slug: "optimal-account-balancing" },
  { id: 466, title: "Count The Repetitions", diff: "Hard", topics: "String, Dynamic Programming", slug: "count-the-repetitions" },
  { id: 467, title: "Unique Substrings in Wraparound String", diff: "Medium", topics: "String, Dynamic Programming", slug: "unique-substrings-in-wraparound-string" },
  { id: 468, title: "Validate IP Address", diff: "Medium", topics: "String", slug: "validate-ip-address" },
  { id: 469, title: "Convex Polygon", diff: "Medium", topics: "Geometry, Math", slug: "convex-polygon" },
  { id: 470, title: "Implement Rand10() Using Rand7()", diff: "Medium", topics: "Math, Rejection Sampling, Randomized", slug: "implement-rand10-using-rand7" },
  { id: 471, title: "Encode String with Shortest Length", diff: "Hard", topics: "String, Dynamic Programming", slug: "encode-string-with-shortest-length" },
  { id: 472, title: "Concatenated Words", diff: "Hard", topics: "Array, String, Dynamic Programming, Depth-First Search, Trie", slug: "concatenated-words" },
  { id: 473, title: "Matchsticks to Square", diff: "Medium", topics: "Array, Dynamic Programming, Backtracking, Bit Manipulation", slug: "matchsticks-to-square" },
  { id: 474, title: "Ones and Zeroes", diff: "Medium", topics: "Array, String, Dynamic Programming", slug: "ones-and-zeroes" },
  { id: 475, title: "Heaters", diff: "Medium", topics: "Array, Two Pointers, Binary Search, Sorting", slug: "heaters" },
  { id: 476, title: "Number Complement", diff: "Easy", topics: "Bit Manipulation", slug: "number-complement" },
  { id: 477, title: "Total Hamming Distance", diff: "Medium", topics: "Array, Bit Manipulation", slug: "total-hamming-distance" },
  { id: 478, title: "Generate Random Point in a Circle", diff: "Medium", topics: "Math, Geometry, Randomized", slug: "generate-random-point-in-a-circle" },
  { id: 479, title: "Largest Palindrome Product", diff: "Hard", topics: "Math", slug: "largest-palindrome-product" },
  { id: 480, title: "Sliding Window Median", diff: "Hard", topics: "Array, Hash Table, Sliding Window, Heap (Priority Queue), Ordered Set", slug: "sliding-window-median" },
  { id: 481, title: "Magical String", diff: "Medium", topics: "Two Pointers, String", slug: "magical-string" },
  { id: 482, title: "License Key Formatting", diff: "Easy", topics: "String", slug: "license-key-formatting" },
  { id: 483, title: "Smallest Good Base", diff: "Hard", topics: "Math, Binary Search", slug: "smallest-good-base" },
  { id: 484, title: "Find Permutation", diff: "Medium", topics: "String, Stack, Greedy", slug: "find-permutation" },
  { id: 485, title: "Max Consecutive Ones", diff: "Easy", topics: "Array", slug: "max-consecutive-ones" },
  { id: 486, title: "Predict the Winner", diff: "Medium", topics: "Array, Dynamic Programming, Recursion, Memoization, Game Theory", slug: "predict-the-winner" },
  { id: 487, title: "Max Consecutive Ones II", diff: "Medium", topics: "Array, Dynamic Programming, Sliding Window", slug: "max-consecutive-ones-ii" },
  { id: 488, title: "Zuma Game", diff: "Hard", topics: "String, Breadth-First Search, Backtracking", slug: "zuma-game" },
  { id: 489, title: "Robot Room Cleaner", diff: "Hard", topics: "Backtracking, Interactive", slug: "robot-room-cleaner" },
  { id: 490, title: "The Maze", diff: "Medium", topics: "Array, Depth-First Search, Breadth-First Search, Matrix", slug: "the-maze" },
  { id: 491, title: "Non-decreasing Subsequences", diff: "Medium", topics: "Array, Hash Table, Backtracking", slug: "non-decreasing-subsequences" },
  { id: 492, title: "Construct the Rectangle", diff: "Easy", topics: "Math", slug: "construct-the-rectangle" },
  { id: 493, title: "Reverse Pairs", diff: "Hard", topics: "Array, Binary Indexed Tree, Segment Tree, Divide and Conquer, Ordered Set, Merge Sort", slug: "reverse-pairs" },
  { id: 494, title: "Target Sum", diff: "Medium", topics: "Array, Dynamic Programming, Backtracking", slug: "target-sum" },
  { id: 495, title: "Teemo Attacking", diff: "Easy", topics: "Array, Simulation", slug: "teemo-attacking" },
  { id: 496, title: "Next Greater Element I", diff: "Easy", topics: "Array, Hash Table, Stack, Monotonic Stack", slug: "next-greater-element-i" },
  { id: 497, title: "Random Point in Non-overlapping Rectangles", diff: "Medium", topics: "Array, Math, Binary Search, Prefix Sum, Reservoir Sampling, Randomized", slug: "random-point-in-non-overlapping-rectangles" },
  { id: 498, title: "Diagonal Traverse", diff: "Medium", topics: "Array, Matrix, Simulation", slug: "diagonal-traverse" },
  { id: 499, title: "The Maze III", diff: "Hard", topics: "Array, String, Depth-First Search, Breadth-First Search, Heap (Priority Queue), Matrix", slug: "the-maze-iii" },
  { id: 500, title: "Keyboard Row", diff: "Easy", topics: "Array, Hash Table, String", slug: "keyboard-row" }
);