window.rawProblems = window.rawProblems || [];

window.rawProblems.push(
  { id: 501, title: "Find Mode in Binary Search Tree", diff: "Easy", topics: "Tree, Depth-First Search, Binary Search Tree, Binary Tree", slug: "find-mode-in-binary-search-tree" },
  { id: 502, title: "IPO", diff: "Hard", topics: "Array, Greedy, Sorting, Heap (Priority Queue)", slug: "ipo" },
  { id: 503, title: "Next Greater Element II", diff: "Medium", topics: "Array, Stack, Monotonic Stack", slug: "next-greater-element-ii" },
  { id: 504, title: "Base 7", diff: "Easy", topics: "Math", slug: "base-7" },
  { id: 505, title: "The Maze II", diff: "Medium", topics: "Array, Depth-First Search, Breadth-First Search, Heap (Priority Queue), Matrix", slug: "the-maze-ii" },
  { id: 506, title: "Relative Ranks", diff: "Easy", topics: "Array, Sorting, Heap (Priority Queue)", slug: "relative-ranks" },
  { id: 507, title: "Perfect Number", diff: "Easy", topics: "Math", slug: "perfect-number" },
  { id: 508, title: "Most Frequent Subtree Sum", diff: "Medium", topics: "Hash Table, Tree, Depth-First Search, Binary Tree", slug: "most-frequent-subtree-sum" },
  { id: 509, title: "Fibonacci Number", diff: "Easy", topics: "Math, Dynamic Programming, Recursion, Memoization", slug: "fibonacci-number" },
  { id: 510, title: "Inorder Successor in BST II", diff: "Medium", topics: "Tree, Binary Search Tree, Binary Tree", slug: "inorder-successor-in-bst-ii" },
  { id: 511, title: "Game Play Analysis I", diff: "Easy", topics: "Database", slug: "game-play-analysis-i" },
  { id: 512, title: "Game Play Analysis II", diff: "Easy", topics: "Database", slug: "game-play-analysis-ii" },
  { id: 513, title: "Find Bottom Left Tree Value", diff: "Medium", topics: "Tree, Depth-First Search, Breadth-First Search, Binary Tree", slug: "find-bottom-left-tree-value" },
  { id: 514, title: "Freedom Trail", diff: "Hard", topics: "String, Dynamic Programming, Depth-First Search", slug: "freedom-trail" },
  { id: 515, title: "Find Largest Value in Each Tree Row", diff: "Medium", topics: "Tree, Depth-First Search, Breadth-First Search, Binary Tree", slug: "find-largest-value-in-each-tree-row" },
  { id: 516, title: "Longest Palindromic Subsequence", diff: "Medium", topics: "String, Dynamic Programming", slug: "longest-palindromic-subsequence" },
  { id: 517, title: "Super Washing Machines", diff: "Hard", topics: "Array, Greedy", slug: "super-washing-machines" },
  { id: 518, title: "Coin Change II", diff: "Medium", topics: "Array, Dynamic Programming", slug: "coin-change-ii" },
  { id: 519, title: "Random Flip Matrix", diff: "Medium", topics: "Hash Table, Math, Design, Randomized", slug: "random-flip-matrix" },
  { id: 520, title: "Detect Capital", diff: "Easy", topics: "String", slug: "detect-capital" },
  { id: 521, title: "Longest Uncommon Subsequence I", diff: "Easy", topics: "String", slug: "longest-uncommon-subsequence-i" },
  { id: 522, title: "Longest Uncommon Subsequence II", diff: "Medium", topics: "Array, String, Sorting", slug: "longest-uncommon-subsequence-ii" },
  { id: 523, title: "Continuous Subarray Sum", diff: "Medium", topics: "Array, Hash Table, Math, Prefix Sum", slug: "continuous-subarray-sum" },
  { id: 524, title: "Longest Word in Dictionary through Deleting", diff: "Medium", topics: "Array, Two Pointers, String, Sorting", slug: "longest-word-in-dictionary-through-deleting" },
  { id: 525, title: "Contiguous Array", diff: "Medium", topics: "Array, Hash Table, Prefix Sum", slug: "contiguous-array" },
  { id: 526, title: "Beautiful Arrangement", diff: "Medium", topics: "Dynamic Programming, Backtracking, Bit Manipulation", slug: "beautiful-arrangement" },
  { id: 527, title: "Word Abbreviation", diff: "Hard", topics: "Array, Hash Table, String, Sorting", slug: "word-abbreviation" },
  { id: 528, title: "Random Pick with Weight", diff: "Medium", topics: "Array, Math, Binary Search, Prefix Sum, Randomized", slug: "random-pick-with-weight" },
  { id: 529, title: "Minesweeper", diff: "Medium", topics: "Array, Depth-First Search, Breadth-First Search, Matrix", slug: "minesweeper" },
  { id: 530, title: "Minimum Absolute Difference in BST", diff: "Easy", topics: "Tree, Depth-First Search, Breadth-First Search, Binary Search Tree, Binary Tree", slug: "minimum-absolute-difference-in-bst" },
  { id: 531, title: "Lonely Pixel I", diff: "Medium", topics: "Array, Matrix", slug: "lonely-pixel-i" },
  { id: 532, title: "K-diff Pairs in an Array", diff: "Medium", topics: "Array, Hash Table, Two Pointers, Binary Search, Sorting", slug: "k-diff-pairs-in-an-array" },
  { id: 533, title: "Lonely Pixel II", diff: "Medium", topics: "Array, Hash Table, Matrix", slug: "lonely-pixel-ii" },
  { id: 534, title: "Game Play Analysis III", diff: "Medium", topics: "Database", slug: "game-play-analysis-iii" },
  { id: 535, title: "Encode and Decode TinyURL", diff: "Medium", topics: "Hash Table, String, Design, Hash Function", slug: "encode-and-decode-tinyurl" },
  { id: 536, title: "Construct Binary Tree from String", diff: "Medium", topics: "String, Stack, Tree, Binary Tree", slug: "construct-binary-tree-from-string" },
  { id: 537, title: "Complex Number Multiplication", diff: "Medium", topics: "Math, String, Simulation", slug: "complex-number-multiplication" },
  { id: 538, title: "Convert BST to Greater Tree", diff: "Medium", topics: "Tree, Depth-First Search, Binary Search Tree, Binary Tree", slug: "convert-bst-to-greater-tree" },
  { id: 539, title: "Minimum Time Difference", diff: "Medium", topics: "Array, String, Sorting", slug: "minimum-time-difference" },
  { id: 540, title: "Single Element in a Sorted Array", diff: "Medium", topics: "Array, Binary Search", slug: "single-element-in-a-sorted-array" },
  { id: 541, title: "Reverse String II", diff: "Easy", topics: "Two Pointers, String", slug: "reverse-string-ii" },
  { id: 542, title: "01 Matrix", diff: "Medium", topics: "Array, Dynamic Programming, Breadth-First Search, Matrix", slug: "01-matrix" },
  { id: 543, title: "Diameter of Binary Tree", diff: "Easy", topics: "Tree, Depth-First Search, Binary Tree", slug: "diameter-of-binary-tree" },
  { id: 544, title: "Output Contest Matches", diff: "Medium", topics: "String, Simulation", slug: "output-contest-matches" },
  { id: 545, title: "Boundary of Binary Tree", diff: "Medium", topics: "Tree, Depth-First Search, Binary Tree", slug: "boundary-of-binary-tree" },
  { id: 546, title: "Remove Boxes", diff: "Hard", topics: "Array, Dynamic Programming, Memoization", slug: "remove-boxes" },
  { id: 547, title: "Number of Provinces", diff: "Medium", topics: "Depth-First Search, Breadth-First Search, Union Find, Graph", slug: "number-of-provinces" },
  { id: 548, title: "Split Array with Equal Sum", diff: "Hard", topics: "Array, Prefix Sum", slug: "split-array-with-equal-sum" },
  { id: 549, title: "Binary Tree Longest Consecutive Sequence II", diff: "Medium", topics: "Tree, Depth-First Search, Binary Tree", slug: "binary-tree-longest-consecutive-sequence-ii" },
  { id: 550, title: "Game Play Analysis IV", diff: "Medium", topics: "Database", slug: "game-play-analysis-iv" },
  { id: 551, title: "Student Attendance Record I", diff: "Easy", topics: "String", slug: "student-attendance-record-i" },
  { id: 552, title: "Student Attendance Record II", diff: "Hard", topics: "Dynamic Programming", slug: "student-attendance-record-ii" },
  { id: 553, title: "Optimal Division", diff: "Medium", topics: "Array, Math, Dynamic Programming", slug: "optimal-division" },
  { id: 554, title: "Brick Wall", diff: "Medium", topics: "Array, Hash Table", slug: "brick-wall" },
  { id: 555, title: "Split Concatenated Strings", diff: "Medium", topics: "Array, String, Greedy", slug: "split-concatenated-strings" },
  { id: 556, title: "Next Greater Element III", diff: "Medium", topics: "Math, Two Pointers, String", slug: "next-greater-element-iii" },
  { id: 557, title: "Reverse Words in a String III", diff: "Easy", topics: "Two Pointers, String", slug: "reverse-words-in-a-string-iii" },
  { id: 558, title: "Logical OR of Two Binary Grids Represented as Quad-Trees", diff: "Medium", topics: "Tree, Divide and Conquer", slug: "logical-or-of-two-binary-grids-represented-as-quad-trees" },
  { id: 559, title: "Maximum Depth of N-ary Tree", diff: "Easy", topics: "Tree, Depth-First Search, Breadth-First Search", slug: "maximum-depth-of-n-ary-tree" },
  { id: 560, title: "Subarray Sum Equals K", diff: "Medium", topics: "Array, Hash Table, Prefix Sum", slug: "subarray-sum-equals-k" },
  { id: 561, title: "Array Partition", diff: "Easy", topics: "Array, Greedy, Sorting", slug: "array-partition" },
  { id: 562, title: "Longest Line of Consecutive One in Matrix", diff: "Medium", topics: "Array, Dynamic Programming, Matrix", slug: "longest-line-of-consecutive-one-in-matrix" },
  { id: 563, title: "Binary Tree Tilt", diff: "Easy", topics: "Tree, Depth-First Search, Binary Tree", slug: "binary-tree-tilt" },
  { id: 564, title: "Find the Closest Palindrome", diff: "Hard", topics: "Math, String", slug: "find-the-closest-palindrome" },
  { id: 565, title: "Array Nesting", diff: "Medium", topics: "Array, Depth-First Search", slug: "array-nesting" },
  { id: 566, title: "Reshape the Matrix", diff: "Easy", topics: "Array, Matrix, Simulation", slug: "reshape-the-matrix" },
  { id: 567, title: "Permutation in String", diff: "Medium", topics: "Hash Table, Two Pointers, String, Sliding Window", slug: "permutation-in-string" },
  { id: 568, title: "Maximum Vacation Days", diff: "Hard", topics: "Dynamic Programming", slug: "maximum-vacation-days" },
  { id: 569, title: "Median Employee Salary", diff: "Hard", topics: "Database", slug: "median-employee-salary" },
  { id: 570, title: "Managers with at Least 5 Direct Reports", diff: "Medium", topics: "Database", slug: "managers-with-at-least-5-direct-reports" },
  { id: 571, title: "Find Median Given Frequency of Numbers", diff: "Hard", topics: "Database", slug: "find-median-given-frequency-of-numbers" },
  { id: 572, title: "Subtree of Another Tree", diff: "Easy", topics: "Tree, Depth-First Search, String Matching, Binary Tree, Hash Function", slug: "subtree-of-another-tree" },
  { id: 573, title: "Squirrel Simulation", diff: "Medium", topics: "Array, Math", slug: "squirrel-simulation" },
  { id: 574, title: "Winning Candidate", diff: "Medium", topics: "Database", slug: "winning-candidate" },
  { id: 575, title: "Distribute Candies", diff: "Easy", topics: "Array, Hash Table", slug: "distribute-candies" },
  { id: 576, title: "Out of Boundary Paths", diff: "Medium", topics: "Dynamic Programming", slug: "out-of-boundary-paths" },
  { id: 577, title: "Employee Bonus", diff: "Easy", topics: "Database", slug: "employee-bonus" },
  { id: 578, title: "Get Highest Answer Rate Question", diff: "Medium", topics: "Database", slug: "get-highest-answer-rate-question" },
  { id: 579, title: "Find Cumulative Salary of an Employee", diff: "Hard", topics: "Database", slug: "find-cumulative-salary-of-an-employee" },
  { id: 580, title: "Count Student Number in Departments", diff: "Medium", topics: "Database", slug: "count-student-number-in-departments" },
  { id: 581, title: "Shortest Unsorted Continuous Subarray", diff: "Medium", topics: "Array, Two Pointers, Sorting, Stack, Monotonic Stack", slug: "shortest-unsorted-continuous-subarray" },
  { id: 582, title: "Kill Process", diff: "Medium", topics: "Tree, Depth-First Search, Breadth-First Search", slug: "kill-process" },
  { id: 583, title: "Delete Operation for Two Strings", diff: "Medium", topics: "String, Dynamic Programming", slug: "delete-operation-for-two-strings" },
  { id: 584, title: "Find Customer Referee", diff: "Easy", topics: "Database", slug: "find-customer-referee" },
  { id: 585, title: "Investments in 2016", diff: "Medium", topics: "Database", slug: "investments-in-2016" },
  { id: 586, title: "Customer Placing the Largest Number of Orders", diff: "Easy", topics: "Database", slug: "customer-placing-the-largest-number-of-orders" },
  { id: 587, title: "Erect the Fence", diff: "Hard", topics: "Array, Math, Geometry", slug: "erect-the-fence" },
  { id: 588, title: "Design In-Memory File System", diff: "Hard", topics: "Hash Table, String, Design, Trie", slug: "design-in-memory-file-system" },
  { id: 589, title: "N-ary Tree Preorder Traversal", diff: "Easy", topics: "Stack, Tree, Depth-First Search", slug: "n-ary-tree-preorder-traversal" },
  { id: 590, title: "N-ary Tree Postorder Traversal", diff: "Easy", topics: "Stack, Tree, Depth-First Search", slug: "n-ary-tree-postorder-traversal" },
  { id: 591, title: "Tag Validator", diff: "Hard", topics: "String, Stack", slug: "tag-validator" },
  { id: 592, title: "Fraction Addition and Subtraction", diff: "Medium", topics: "Math, String, Simulation", slug: "fraction-addition-and-subtraction" },
  { id: 593, title: "Valid Square", diff: "Medium", topics: "Math, Geometry", slug: "valid-square" },
  { id: 594, title: "Longest Harmonious Subsequence", diff: "Easy", topics: "Array, Hash Table, Sorting", slug: "longest-harmonious-subsequence" },
  { id: 595, title: "Big Countries", diff: "Easy", topics: "Database", slug: "big-countries" },
  { id: 596, title: "Classes More Than 5 Students", diff: "Easy", topics: "Database", slug: "classes-more-than-5-students" },
  { id: 597, title: "Friend Requests I: Overall Acceptance Rate", diff: "Easy", topics: "Database", slug: "friend-requests-i-overall-acceptance-rate" },
  { id: 598, title: "Range Addition II", diff: "Easy", topics: "Array, Math", slug: "range-addition-ii" },
  { id: 599, title: "Minimum Index Sum of Two Lists", diff: "Easy", topics: "Array, Hash Table, String", slug: "minimum-index-sum-of-two-lists" },
  { id: 600, title: "Non-negative Integers without Consecutive Ones", diff: "Hard", topics: "Dynamic Programming, Bit Manipulation", slug: "non-negative-integers-without-consecutive-ones" },
  { id: 601, title: "Human Traffic of Stadium", diff: "Hard", topics: "Database", slug: "human-traffic-of-stadium" },
  { id: 602, title: "Friend Requests II: Who Has the Most Friends", diff: "Medium", topics: "Database", slug: "friend-requests-ii-who-has-the-most-friends" },
  { id: 603, title: "Consecutive Available Seats", diff: "Easy", topics: "Database", slug: "consecutive-available-seats" },
  { id: 604, title: "Design Compressed String Iterator", diff: "Easy", topics: "String, Design, Iterator", slug: "design-compressed-string-iterator" },
  { id: 605, title: "Can Place Flowers", diff: "Easy", topics: "Array, Greedy", slug: "can-place-flowers" },
  { id: 606, title: "Construct String from Binary Tree", diff: "Easy", topics: "String, Tree, Depth-First Search, Binary Tree", slug: "construct-string-from-binary-tree" },
  { id: 607, title: "Sales Person", diff: "Easy", topics: "Database", slug: "sales-person" },
  { id: 608, title: "Tree Node", diff: "Medium", topics: "Database", slug: "tree-node" },
  { id: 609, title: "Find Duplicate File in System", diff: "Medium", topics: "Array, Hash Table, String, Depth-First Search", slug: "find-duplicate-file-in-system" },
  { id: 610, title: "Triangle Judgement", diff: "Easy", topics: "Database", slug: "triangle-judgement" },
  { id: 611, title: "Valid Triangle Number", diff: "Medium", topics: "Array, Two Pointers, Binary Search, Greedy, Sorting", slug: "valid-triangle-number" },
  { id: 612, title: "Shortest Distance in a Plane", diff: "Medium", topics: "Database", slug: "shortest-distance-in-a-plane" },
  { id: 613, title: "Shortest Distance in a Line", diff: "Easy", topics: "Database", slug: "shortest-distance-in-a-line" },
  { id: 614, title: "Second Degree Follower", diff: "Medium", topics: "Database", slug: "second-degree-follower" },
  { id: 615, title: "Average Salary: Departments VS Company", diff: "Hard", topics: "Database", slug: "average-salary-departments-vs-company" },
  { id: 616, title: "Add Bold Tag in String", diff: "Medium", topics: "String", slug: "add-bold-tag-in-string" },
  { id: 617, title: "Merge Two Binary Trees", diff: "Easy", topics: "Tree, Depth-First Search, Breadth-First Search, Binary Tree", slug: "merge-two-binary-trees" },
  { id: 618, title: "Students Report By Geography", diff: "Hard", topics: "Database", slug: "students-report-by-geography" },
  { id: 619, title: "Biggest Single Number", diff: "Easy", topics: "Database", slug: "biggest-single-number" },
  { id: 620, title: "Not Boring Movies", diff: "Easy", topics: "Database", slug: "not-boring-movies" },
  { id: 621, title: "Task Scheduler", diff: "Medium", topics: "Array, Hash Table, Greedy, Sorting, Heap (Priority Queue), Counting", slug: "task-scheduler" },
  { id: 622, title: "Design Circular Queue", diff: "Medium", topics: "Array, Linked List, Design, Queue", slug: "design-circular-queue" },
  { id: 623, title: "Add One Row to Tree", diff: "Medium", topics: "Tree, Depth-First Search, Breadth-First Search, Binary Tree", slug: "add-one-row-to-tree" },
  { id: 624, title: "Maximum Distance in Arrays", diff: "Medium", topics: "Array, Greedy", slug: "maximum-distance-in-arrays" },
  { id: 625, title: "Minimum Factorization", diff: "Medium", topics: "Math, Greedy", slug: "minimum-factorization" },
  { id: 626, title: "Exchange Seats", diff: "Medium", topics: "Database", slug: "exchange-seats" },
  { id: 627, title: "Swap Salary", diff: "Easy", topics: "Database", slug: "swap-salary" },
  { id: 628, title: "Maximum Product of Three Numbers", diff: "Easy", topics: "Array, Math, Sorting", slug: "maximum-product-of-three-numbers" },
  { id: 629, title: "K Inverse Pairs Array", diff: "Hard", topics: "Dynamic Programming", slug: "k-inverse-pairs-array" },
  { id: 630, title: "Course Schedule III", diff: "Hard", topics: "Array, Greedy, Sorting, Heap (Priority Queue)", slug: "course-schedule-iii" },
  { id: 631, title: "Design Excel Sum Formula", diff: "Hard", topics: "Hash Table, Design, Topological Sort", slug: "design-excel-sum-formula" },
  { id: 632, title: "Smallest Range Covering Elements from K Lists", diff: "Hard", topics: "Array, Hash Table, Greedy, Sliding Window, Sorting, Heap (Priority Queue)", slug: "smallest-range-covering-elements-from-k-lists" },
  { id: 633, title: "Sum of Square Numbers", diff: "Medium", topics: "Math, Two Pointers, Binary Search", slug: "sum-of-square-numbers" },
  { id: 634, title: "Find the Derangement of An Array", diff: "Medium", topics: "Dynamic Programming, Math", slug: "find-the-derangement-of-an-array" },
  { id: 635, title: "Design Log Storage System", diff: "Medium", topics: "Hash Table, String, Design", slug: "design-log-storage-system" },
  { id: 636, title: "Exclusive Time of Functions", diff: "Medium", topics: "Array, Stack", slug: "exclusive-time-of-functions" },
  { id: 637, title: "Average of Levels in Binary Tree", diff: "Easy", topics: "Tree, Depth-First Search, Breadth-First Search, Binary Tree", slug: "average-of-levels-in-binary-tree" },
  { id: 638, title: "Shopping Offers", diff: "Medium", topics: "Array, Dynamic Programming, Backtracking, Bit Manipulation, Memoization", slug: "shopping-offers" },
  { id: 639, title: "Decode Ways II", diff: "Hard", topics: "String, Dynamic Programming", slug: "decode-ways-ii" },
  { id: 640, title: "Solve the Equation", diff: "Medium", topics: "Math, String, Simulation", slug: "solve-the-equation" },
  { id: 641, title: "Design Circular Deque", diff: "Medium", topics: "Array, Linked List, Design, Queue", slug: "design-circular-deque" },
  { id: 642, title: "Design Search Autocomplete System", diff: "Hard", topics: "String, Design, Trie, Heap (Priority Queue)", slug: "design-search-autocomplete-system" },
  { id: 643, title: "Maximum Average Subarray I", diff: "Easy", topics: "Array, Sliding Window", slug: "maximum-average-subarray-i" },
  { id: 644, title: "Maximum Average Subarray II", diff: "Hard", topics: "Array, Binary Search, Prefix Sum", slug: "maximum-average-subarray-ii" },
  { id: 645, title: "Set Mismatch", diff: "Easy", topics: "Array, Hash Table, Bit Manipulation, Sorting", slug: "set-mismatch" },
  { id: 646, title: "Maximum Length of Pair Chain", diff: "Medium", topics: "Array, Dynamic Programming, Greedy, Sorting", slug: "maximum-length-of-pair-chain" },
  { id: 647, title: "Palindromic Substrings", diff: "Medium", topics: "String, Dynamic Programming", slug: "palindromic-substrings" },
  { id: 648, title: "Replace Words", diff: "Medium", topics: "Array, Hash Table, String, Trie", slug: "replace-words" },
  { id: 649, title: "Dota2 Senate", diff: "Medium", topics: "String, Greedy, Queue", slug: "dota2-senate" },
  { id: 650, title: "2 Keys Keyboard", diff: "Medium", topics: "Math, Dynamic Programming, Number Theory", slug: "2-keys-keyboard" },
  { id: 651, title: "4 Keys Keyboard", diff: "Medium", topics: "Math, Dynamic Programming", slug: "4-keys-keyboard" },
  { id: 652, title: "Find Duplicate Subtrees", diff: "Medium", topics: "Hash Table, Tree, Depth-First Search, Binary Tree", slug: "find-duplicate-subtrees" },
  { id: 653, title: "Two Sum IV - Input is a BST", diff: "Easy", topics: "Hash Table, Two Pointers, Tree, Depth-First Search, Binary Search Tree, Binary Tree", slug: "two-sum-iv-input-is-a-bst" },
  { id: 654, title: "Maximum Binary Tree", diff: "Medium", topics: "Array, Divide and Conquer, Stack, Tree, Monotonic Stack, Binary Tree", slug: "maximum-binary-tree" },
  { id: 655, title: "Print Binary Tree", diff: "Medium", topics: "Tree, Depth-First Search, Breadth-First Search, Binary Tree", slug: "print-binary-tree" },
  { id: 656, title: "Coin Path", diff: "Hard", topics: "Array, Dynamic Programming", slug: "coin-path" },
  { id: 657, title: "Robot Return to Origin", diff: "Easy", topics: "String, Simulation", slug: "robot-return-to-origin" },
  { id: 658, title: "Find K Closest Elements", diff: "Medium", topics: "Array, Two Pointers, Binary Search, Sliding Window, Sorting, Heap (Priority Queue)", slug: "find-k-closest-elements" },
  { id: 659, title: "Split Array into Consecutive Subsequences", diff: "Medium", topics: "Array, Hash Table, Greedy, Heap (Priority Queue)", slug: "split-array-into-consecutive-subsequences" },
  { id: 660, title: "Remove 9", diff: "Hard", topics: "Math", slug: "remove-9" },
  { id: 661, title: "Image Smoother", diff: "Easy", topics: "Array, Matrix", slug: "image-smoother" },
  { id: 662, title: "Maximum Width of Binary Tree", diff: "Medium", topics: "Tree, Depth-First Search, Breadth-First Search, Binary Tree", slug: "maximum-width-of-binary-tree" },
  { id: 663, title: "Equal Tree Partition", diff: "Medium", topics: "Tree, Depth-First Search, Binary Tree", slug: "equal-tree-partition" },
  { id: 664, title: "Strange Printer", diff: "Hard", topics: "String, Dynamic Programming", slug: "strange-printer" },
  { id: 665, title: "Non-decreasing Array", diff: "Medium", topics: "Array, Greedy", slug: "non-decreasing-array" },
  { id: 666, title: "Path Sum IV", diff: "Medium", topics: "Tree, Depth-First Search", slug: "path-sum-iv" },
  { id: 667, title: "Beautiful Arrangement II", diff: "Medium", topics: "Array, Math", slug: "beautiful-arrangement-ii" },
  { id: 668, title: "Kth Smallest Number in Multiplication Table", diff: "Hard", topics: "Binary Search, Math", slug: "kth-smallest-number-in-multiplication-table" },
  { id: 669, title: "Trim a Binary Search Tree", diff: "Medium", topics: "Tree, Depth-First Search, Binary Search Tree, Binary Tree", slug: "trim-a-binary-search-tree" },
  { id: 670, title: "Maximum Swap", diff: "Medium", topics: "Math, Greedy", slug: "maximum-swap" },
  { id: 671, title: "Second Minimum Node In a Binary Tree", diff: "Easy", topics: "Tree, Depth-First Search, Binary Tree", slug: "second-minimum-node-in-a-binary-tree" },
  { id: 672, title: "Bulb Switcher II", diff: "Medium", topics: "Math, Bit Manipulation, Brainteaser", slug: "bulb-switcher-ii" },
  { id: 673, title: "Number of Longest Increasing Subsequence", diff: "Medium", topics: "Array, Dynamic Programming", slug: "number-of-longest-increasing-subsequence" },
  { id: 674, title: "Longest Continuous Increasing Subsequence", diff: "Easy", topics: "Array", slug: "longest-continuous-increasing-subsequence" },
  { id: 675, title: "Cut Off Trees for Golf Event", diff: "Hard", topics: "Array, Breadth-First Search, Heap (Priority Queue), Matrix", slug: "cut-off-trees-for-golf-event" },
  { id: 676, title: "Implement Magic Dictionary", diff: "Medium", topics: "Hash Table, String, Design, Trie", slug: "implement-magic-dictionary" },
  { id: 677, title: "Map Sum Pairs", diff: "Medium", topics: "Hash Table, String, Design, Trie", slug: "map-sum-pairs" },
  { id: 678, title: "Valid Parenthesis String", diff: "Medium", topics: "String, Dynamic Programming, Stack, Greedy", slug: "valid-parenthesis-string" },
  { id: 679, title: "24 Game", diff: "Hard", topics: "Array, Math, Backtracking", slug: "24-game" },
  { id: 680, title: "Valid Palindrome II", diff: "Easy", topics: "Two Pointers, String, Greedy", slug: "valid-palindrome-ii" },
  { id: 681, title: "Next Closest Time", diff: "Medium", topics: "String, Backtracking", slug: "next-closest-time" },
  { id: 682, title: "Baseball Game", diff: "Easy", topics: "Array, Stack, Simulation", slug: "baseball-game" },
  { id: 683, title: "K Empty Slots", diff: "Hard", topics: "Array, Binary Search, Ordered Set, Sliding Window", slug: "k-empty-slots" },
  { id: 684, title: "Redundant Connection", diff: "Medium", topics: "Depth-First Search, Breadth-First Search, Union Find, Graph", slug: "redundant-connection" },
  { id: 685, title: "Redundant Connection II", diff: "Hard", topics: "Depth-First Search, Union Find, Graph", slug: "redundant-connection-ii" },
  { id: 686, title: "Repeated String Match", diff: "Medium", topics: "String, String Matching", slug: "repeated-string-match" },
  { id: 687, title: "Longest Univalue Path", diff: "Medium", topics: "Tree, Depth-First Search, Binary Tree", slug: "longest-univalue-path" },
  { id: 688, title: "Knight Probability in Chessboard", diff: "Medium", topics: "Dynamic Programming", slug: "knight-probability-in-chessboard" },
  { id: 689, title: "Maximum Sum of 3 Non-Overlapping Subarrays", diff: "Hard", topics: "Array, Dynamic Programming, Sliding Window", slug: "maximum-sum-of-3-non-overlapping-subarrays" },
  { id: 690, title: "Employee Importance", diff: "Medium", topics: "Hash Table, Depth-First Search, Breadth-First Search", slug: "employee-importance" },
  { id: 691, title: "Stickers to Spell Word", diff: "Hard", topics: "String, Dynamic Programming, Backtracking, Bit Manipulation, Memoization", slug: "stickers-to-spell-word" },
  { id: 692, title: "Top K Frequent Words", diff: "Medium", topics: "Array, Hash Table, String, Trie, Sorting, Heap (Priority Queue), Bucket Sort", slug: "top-k-frequent-words" },
  { id: 693, title: "Binary Number with Alternating Bits", diff: "Easy", topics: "Bit Manipulation", slug: "binary-number-with-alternating-bits" },
  { id: 694, title: "Number of Distinct Islands", diff: "Medium", topics: "Array, Hash Table, Depth-First Search, Breadth-First Search, Union Find, Matrix", slug: "number-of-distinct-islands" },
  { id: 695, title: "Max Area of Island", diff: "Medium", topics: "Array, Depth-First Search, Breadth-First Search, Union Find, Matrix", slug: "max-area-of-island" },
  { id: 696, title: "Count Binary Substrings", diff: "Easy", topics: "String", slug: "count-binary-substrings" },
  { id: 697, title: "Degree of an Array", diff: "Easy", topics: "Array, Hash Table", slug: "degree-of-an-array" },
  { id: 698, title: "Partition to K Equal Sum Subsets", diff: "Medium", topics: "Array, Dynamic Programming, Backtracking, Bit Manipulation, Memoization", slug: "partition-to-k-equal-sum-subsets" },
  { id: 699, title: "Falling Squares", diff: "Hard", topics: "Array, Binary Search, Segment Tree, Ordered Set", slug: "falling-squares" },
  { id: 700, title: "Search in a Binary Search Tree", diff: "Easy", topics: "Tree, Binary Search Tree, Binary Tree", slug: "search-in-a-binary-search-tree" },
  { id: 701, title: "Insert into a Binary Search Tree", diff: "Medium", topics: "Tree, Binary Search Tree, Binary Tree", slug: "insert-into-a-binary-search-tree" },
  { id: 702, title: "Search in a Sorted Array of Unknown Size", diff: "Medium", topics: "Array, Binary Search, Interactive", slug: "search-in-a-sorted-array-of-unknown-size" },
  { id: 703, title: "Kth Largest Element in a Stream", diff: "Easy", topics: "Tree, Design, Binary Search Tree, Heap (Priority Queue), Binary Tree, Data Stream", slug: "kth-largest-element-in-a-stream" },
  { id: 704, title: "Binary Search", diff: "Easy", topics: "Array, Binary Search", slug: "binary-search" },
  { id: 705, title: "Design HashSet", diff: "Easy", topics: "Array, Hash Table, Design, Hash Function", slug: "design-hashset" },
  { id: 706, title: "Design HashMap", diff: "Easy", topics: "Array, Hash Table, Design, Hash Function", slug: "design-hashmap" },
  { id: 707, title: "Design Linked List", diff: "Medium", topics: "Linked List, Design", slug: "design-linked-list" },
  { id: 708, title: "Insert into a Sorted Circular Linked List", diff: "Medium", topics: "Linked List", slug: "insert-into-a-sorted-circular-linked-list" },
  { id: 709, title: "To Lower Case", diff: "Easy", topics: "String", slug: "to-lower-case" },
  { id: 710, title: "Random Pick with Blacklist", diff: "Hard", topics: "Hash Table, Math, Binary Search, Sorting, Randomized", slug: "random-pick-with-blacklist" },
  { id: 711, title: "Number of Distinct Islands II", diff: "Hard", topics: "Array, Hash Table, Depth-First Search, Breadth-First Search, Union Find, Matrix", slug: "number-of-distinct-islands-ii" },
  { id: 712, title: "Minimum ASCII Delete Sum for Two Strings", diff: "Medium", topics: "String, Dynamic Programming", slug: "minimum-ascii-delete-sum-for-two-strings" },
  { id: 713, title: "Subarray Product Less Than K", diff: "Medium", topics: "Array, Sliding Window", slug: "subarray-product-less-than-k" },
  { id: 714, title: "Best Time to Buy and Sell Stock with Transaction Fee", diff: "Medium", topics: "Array, Dynamic Programming, Greedy", slug: "best-time-to-buy-and-sell-stock-with-transaction-fee" },
  { id: 715, title: "Range Module", diff: "Hard", topics: "Design, Segment Tree, Ordered Set", slug: "range-module" },
  { id: 716, title: "Max Stack", diff: "Hard", topics: "Linked List, Stack, Design, Doubly-Linked List, Ordered Set", slug: "max-stack" },
  { id: 717, title: "1-bit and 2-bit Characters", diff: "Easy", topics: "Array", slug: "1-bit-and-2-bit-characters" },
  { id: 718, title: "Maximum Length of Repeated Subarray", diff: "Medium", topics: "Array, Binary Search, Dynamic Programming, Rolling Hash, Hash Function", slug: "maximum-length-of-repeated-subarray" },
  { id: 719, title: "Find K-th Smallest Pair Distance", diff: "Hard", topics: "Array, Binary Search, Sorting", slug: "find-k-th-smallest-pair-distance" },
  { id: 720, title: "Longest Word in Dictionary", diff: "Medium", topics: "Array, Hash Table, String, Trie, Sorting", slug: "longest-word-in-dictionary" },
  { id: 721, title: "Accounts Merge", diff: "Medium", topics: "Array, Hash Table, String, Depth-First Search, Breadth-First Search, Union Find", slug: "accounts-merge" },
  { id: 722, title: "Remove Comments", diff: "Medium", topics: "Array, String", slug: "remove-comments" },
  { id: 723, title: "Candy Crush", diff: "Medium", topics: "Array, Two Pointers, Matrix, Simulation", slug: "candy-crush" },
  { id: 724, title: "Find Pivot Index", diff: "Easy", topics: "Array, Prefix Sum", slug: "find-pivot-index" },
  { id: 725, title: "Split Linked List in Parts", diff: "Medium", topics: "Linked List", slug: "split-linked-list-in-parts" },
  { id: 726, title: "Number of Atoms", diff: "Hard", topics: "Hash Table, String, Stack", slug: "number-of-atoms" },
  { id: 727, title: "Minimum Window Subsequence", diff: "Hard", topics: "String, Dynamic Programming, Sliding Window", slug: "minimum-window-subsequence" },
  { id: 728, title: "Self Dividing Numbers", diff: "Easy", topics: "Math", slug: "self-dividing-numbers" },
  { id: 729, title: "My Calendar I", diff: "Medium", topics: "Binary Search, Design, Segment Tree, Ordered Set", slug: "my-calendar-i" },
  { id: 730, title: "Count Different Palindromic Subsequences", diff: "Hard", topics: "String, Dynamic Programming", slug: "count-different-palindromic-subsequences" },
  { id: 731, title: "My Calendar II", diff: "Medium", topics: "Array, Binary Search, Design, Segment Tree, Ordered Set, Prefix Sum", slug: "my-calendar-ii" },
  { id: 732, title: "My Calendar III", diff: "Hard", topics: "Binary Search, Design, Segment Tree, Ordered Set, Line Sweep", slug: "my-calendar-iii" },
  { id: 733, title: "Flood Fill", diff: "Easy", topics: "Array, Depth-First Search, Breadth-First Search, Matrix", slug: "flood-fill" },
  { id: 734, title: "Sentence Similarity", diff: "Easy", topics: "Array, Hash Table, String", slug: "sentence-similarity" },
  { id: 735, title: "Asteroid Collision", diff: "Medium", topics: "Array, Stack, Simulation", slug: "asteroid-collision" },
  { id: 736, title: "Parse Lisp Expression", diff: "Hard", topics: "String, Stack, Recursion", slug: "parse-lisp-expression" },
  { id: 737, title: "Sentence Similarity II", diff: "Medium", topics: "Array, Hash Table, String, Depth-First Search, Breadth-First Search, Union Find", slug: "sentence-similarity-ii" },
  { id: 738, title: "Monotone Increasing Digits", diff: "Medium", topics: "Math, Greedy", slug: "monotone-increasing-digits" },
  { id: 739, title: "Daily Temperatures", diff: "Medium", topics: "Array, Stack, Monotonic Stack", slug: "daily-temperatures" },
  { id: 740, title: "Delete and Earn", diff: "Medium", topics: "Array, Hash Table, Dynamic Programming", slug: "delete-and-earn" },
  { id: 741, title: "Cherry Pickup", diff: "Hard", topics: "Array, Dynamic Programming, Matrix", slug: "cherry-pickup" },
  { id: 742, title: "Closest Leaf in a Binary Tree", diff: "Medium", topics: "Hash Table, Tree, Depth-First Search, Breadth-First Search, Binary Tree", slug: "closest-leaf-in-a-binary-tree" },
  { id: 743, title: "Network Delay Time", diff: "Medium", topics: "Depth-First Search, Breadth-First Search, Graph, Heap (Priority Queue), Shortest Path", slug: "network-delay-time" },
  { id: 744, title: "Find Smallest Letter Greater Than Target", diff: "Easy", topics: "Array, Binary Search", slug: "find-smallest-letter-greater-than-target" },
  { id: 745, title: "Prefix and Suffix Search", diff: "Hard", topics: "Trie, Design", slug: "prefix-and-suffix-search" },
  { id: 746, title: "Min Cost Climbing Stairs", diff: "Easy", topics: "Array, Dynamic Programming", slug: "min-cost-climbing-stairs" },
  { id: 747, title: "Largest Number At Least Twice of Others", diff: "Easy", topics: "Array, Sorting", slug: "largest-number-at-least-twice-of-others" },
  { id: 748, title: "Shortest Completing Word", diff: "Easy", topics: "Array, Hash Table, String", slug: "shortest-completing-word" },
  { id: 749, title: "Contain Virus", diff: "Hard", topics: "Array, Depth-First Search, Breadth-First Search, Simulation, Matrix", slug: "contain-virus" },
  { id: 750, title: "Number Of Corner Rectangles", diff: "Medium", topics: "Array, Matrix", slug: "number-of-corner-rectangles" }
);