window.rawProblems = window.rawProblems || [];

window.rawProblems.push(
  { id: 1501, title: "Countries You Can Safely Invest In", diff: "Medium", topics: "Database", slug: "countries-you-can-safely-invest-in" },
  { id: 1502, title: "Can Make Arithmetic Progression From Sequence", diff: "Easy", topics: "Array, Sorting", slug: "can-make-arithmetic-progression-from-sequence" },
  { id: 1503, title: "Last Moment Before All Ants Fall Out of a Plank", diff: "Medium", topics: "Math", slug: "last-moment-before-all-ants-fall-out-of-a-plank" },
  { id: 1504, title: "Count Submatrices With All Ones", diff: "Medium", topics: "Array, Dynamic Programming, Stack, Matrix, Monotonic Stack", slug: "count-submatrices-with-all-ones" },
  { id: 1505, title: "Minimum Possible Integer After at Most K Adjacent Swaps On Digits", diff: "Hard", topics: "String, Greedy, Binary Indexed Tree, Segment Tree", slug: "minimum-possible-integer-after-at-most-k-adjacent-swaps-on-digits" },
  { id: 1506, title: "Find Root of N-Ary Tree", diff: "Medium", topics: "Hash Table, Bit Manipulation, Tree", slug: "find-root-of-n-ary-tree" },
  { id: 1507, title: "Reformat Date", diff: "Easy", topics: "String", slug: "reformat-date" },
  { id: 1508, title: "Range Sum of Sorted Subarray Sums", diff: "Medium", topics: "Array, Two Pointers, Binary Search, Sorting, Heap (Priority Queue), Prefix Sum", slug: "range-sum-of-sorted-subarray-sums" },
  { id: 1509, title: "Minimum Difference Between Largest and Smallest Value in Three Moves", diff: "Medium", topics: "Array, Greedy, Sorting", slug: "minimum-difference-between-largest-and-smallest-value-in-three-moves" },
  { id: 1510, title: "Stone Game IV", diff: "Hard", topics: "Math, Dynamic Programming, Game Theory", slug: "stone-game-iv" },
  { id: 1511, title: "Customer Order Frequency", diff: "Easy", topics: "Database", slug: "customer-order-frequency" },
  { id: 1512, title: "Number of Good Pairs", diff: "Easy", topics: "Array, Hash Table, Math, Counting", slug: "number-of-good-pairs" },
  { id: 1513, title: "Number of Substrings With Only 1s", diff: "Medium", topics: "Math, String", slug: "number-of-substrings-with-only-1s" },
  { id: 1514, title: "Path with Maximum Probability", diff: "Medium", topics: "Graph, Shortest Path, Heap (Priority Queue)", slug: "path-with-maximum-probability" },
  { id: 1515, title: "Best Position for a Service Centre", diff: "Hard", topics: "Geometry, Math, Hill Climbing", slug: "best-position-for-a-service-centre" },
  { id: 1516, title: "Move Sub-Tree of N-Ary Tree", diff: "Hard", topics: "Tree, Depth-First Search", slug: "move-sub-tree-of-n-ary-tree" },
  { id: 1517, title: "Find Users With Valid E-Mails", diff: "Easy", topics: "Database", slug: "find-users-with-valid-e-mails" },
  { id: 1518, title: "Water Bottles", diff: "Easy", topics: "Math, Simulation", slug: "water-bottles" },
  { id: 1519, title: "Number of Nodes in the Sub-Tree With the Same Label", diff: "Medium", topics: "Hash Table, Tree, Depth-First Search", slug: "number-of-nodes-in-the-sub-tree-with-the-same-label" },
  { id: 1520, title: "Maximum Number of Non-Overlapping Substrings", diff: "Hard", topics: "String, Greedy", slug: "maximum-number-of-non-overlapping-substrings" },
  { id: 1521, title: "Find a Value of a Mysterious Function Closest to Target", diff: "Hard", topics: "Array, Bit Manipulation", slug: "find-a-value-of-a-mysterious-function-closest-to-target" },
  { id: 1522, title: "Diameter of N-Ary Tree", diff: "Medium", topics: "Tree, Depth-First Search", slug: "diameter-of-n-ary-tree" },
  { id: 1523, title: "Count Odd Numbers in an Interval Range", diff: "Easy", topics: "Math", slug: "count-odd-numbers-in-an-interval-range" },
  { id: 1524, title: "Number of Sub-arrays With Odd Sum", diff: "Medium", topics: "Array, Math, Dynamic Programming, Prefix Sum", slug: "number-of-sub-arrays-with-odd-sum" },
  { id: 1525, title: "Number of Good Ways to Split a String", diff: "Medium", topics: "Hash Table, String", slug: "number-of-good-ways-to-split-a-string" },
  { id: 1526, title: "Minimum Number of Increments on Subarrays to Form a Target Array", diff: "Hard", topics: "Array, Greedy, Stack, Monotonic Stack", slug: "minimum-number-of-increments-on-subarrays-to-form-a-target-array" },
  { id: 1527, title: "Patients With a Condition", diff: "Easy", topics: "Database", slug: "patients-with-a-condition" },
  { id: 1528, title: "Shuffle String", diff: "Easy", topics: "Array, String", slug: "shuffle-string" },
  { id: 1529, title: "Minimum Suffix Flips", diff: "Medium", topics: "String, Greedy", slug: "minimum-suffix-flips" },
  { id: 1530, title: "Number of Good Leaf Nodes Pairs", diff: "Medium", topics: "Dynamic Programming, Tree, Depth-First Search, Binary Tree", slug: "number-of-good-leaf-nodes-pairs" },
  { id: 1531, title: "String Compression II", diff: "Hard", topics: "String, Dynamic Programming", slug: "string-compression-ii" },
  { id: 1532, title: "The Most Recent Three Orders", diff: "Medium", topics: "Database", slug: "the-most-recent-three-orders" },
  { id: 1533, title: "Find the Index of the Large Integer", diff: "Medium", topics: "Binary Search, Interactive", slug: "find-the-index-of-the-large-integer" },
  { id: 1534, title: "Count Good Triplets", diff: "Easy", topics: "Array, Enumeration", slug: "count-good-triplets" },
  { id: 1535, title: "Find the Winner of an Array Game", diff: "Medium", topics: "Array, Simulation", slug: "find-the-winner-of-an-array-game" },
  { id: 1536, title: "Minimum Swaps to Arrange a Binary Grid", diff: "Medium", topics: "Array, Greedy, Matrix", slug: "minimum-swaps-to-arrange-a-binary-grid" },
  { id: 1537, title: "Get the Maximum Score", diff: "Hard", topics: "Array, Two Pointers, Dynamic Programming, Greedy", slug: "get-the-maximum-score" },
  { id: 1538, title: "Guess the Majority in a Hidden Array", diff: "Medium", topics: "Array, Interactive", slug: "guess-the-majority-in-a-hidden-array" },
  { id: 1539, title: "Kth Missing Positive Number", diff: "Easy", topics: "Array, Binary Search", slug: "kth-missing-positive-number" },
  { id: 1540, title: "Can Convert String in K Moves", diff: "Medium", topics: "Hash Table, String, Greedy, Counting", slug: "can-convert-string-in-k-moves" },
  { id: 1541, title: "Minimum Insertions to Balance a Parentheses String", diff: "Medium", topics: "String, Stack, Greedy", slug: "minimum-insertions-to-balance-a-parentheses-string" },
  { id: 1542, title: "Find Longest Awesome Substring", diff: "Hard", topics: "Hash Table, String, Bit Manipulation, Prefix Sum", slug: "find-longest-awesome-substring" },
  { id: 1543, title: "Fix Product Name Format", diff: "Easy", topics: "Database", slug: "fix-product-name-format" },
  { id: 1544, title: "Make The String Great", diff: "Easy", topics: "String, Stack", slug: "make-the-string-great" },
  { id: 1545, title: "Find Kth Bit in Nth Binary String", diff: "Medium", topics: "String, Recursion, Bit Manipulation", slug: "find-kth-bit-in-nth-binary-string" },
  { id: 1546, title: "Maximum Number of Non-Overlapping Subarrays With Sum Equals Target", diff: "Medium", topics: "Array, Hash Table, Greedy, Prefix Sum", slug: "maximum-number-of-non-overlapping-subarrays-with-sum-equals-target" },
  { id: 1547, title: "Minimum Cost to Cut a Stick", diff: "Hard", topics: "Array, Dynamic Programming", slug: "minimum-cost-to-cut-a-stick" },
  { id: 1548, title: "The Most Similar Path in a Graph", diff: "Hard", topics: "Dynamic Programming, Graph", slug: "the-most-similar-path-in-a-graph" },
  { id: 1549, title: "The Most Recent Orders for Each Product", diff: "Medium", topics: "Database", slug: "the-most-recent-orders-for-each-product" },
  { id: 1550, title: "Three Consecutive Odds", diff: "Easy", topics: "Array", slug: "three-consecutive-odds" },
  { id: 1551, title: "Minimum Operations to Make Array Equal", diff: "Medium", topics: "Math", slug: "minimum-operations-to-make-array-equal" },
  { id: 1552, title: "Magnetic Force Between Two Balls", diff: "Medium", topics: "Array, Binary Search, Sorting", slug: "magnetic-force-between-two-balls" },
  { id: 1553, title: "Minimum Number of Days to Eat N Oranges", diff: "Hard", topics: "Dynamic Programming, Memoization", slug: "minimum-number-of-days-to-eat-n-oranges" },
  { id: 1554, title: "Strings Differ by One Character", diff: "Medium", topics: "Hash Table, String, Rolling Hash, Hash Function", slug: "strings-differ-by-one-character" },
  { id: 1555, title: "Bank Account Summary", diff: "Medium", topics: "Database", slug: "bank-account-summary" },
  { id: 1556, title: "Thousand Separator", diff: "Easy", topics: "String", slug: "thousand-separator" },
  { id: 1557, title: "Minimum Number of Vertices to Reach All Nodes", diff: "Medium", topics: "Graph", slug: "minimum-number-of-vertices-to-reach-all-nodes" },
  { id: 1558, title: "Minimum Numbers of Function Calls to Make Target Array", diff: "Medium", topics: "Array, Bit Manipulation, Greedy", slug: "minimum-numbers-of-function-calls-to-make-target-array" },
  { id: 1559, title: "Detect Cycles in 2D Grid", diff: "Medium", topics: "Array, Depth-First Search, Breadth-First Search, Union Find, Matrix", slug: "detect-cycles-in-2d-grid" },
  { id: 1560, title: "Most Visited Sector in a Circular Track", diff: "Easy", topics: "Array, Simulation", slug: "most-visited-sector-in-a-circular-track" },
  { id: 1561, title: "Maximum Number of Coins You Can Get", diff: "Medium", topics: "Array, Greedy, Sorting", slug: "maximum-number-of-coins-you-can-get" },
  { id: 1562, title: "Find Latest Group of Size M", diff: "Medium", topics: "Array, Binary Search, Union Find", slug: "find-latest-group-of-size-m" },
  { id: 1563, title: "Stone Game V", diff: "Hard", topics: "Array, Dynamic Programming", slug: "stone-game-v" },
  { id: 1564, title: "Put Boxes Into the Warehouse I", diff: "Medium", topics: "Array, Greedy, Sorting", slug: "put-boxes-into-the-warehouse-i" },
  { id: 1565, title: "Unique Orders and Customers Per Month", diff: "Easy", topics: "Database", slug: "unique-orders-and-customers-per-month" },
  { id: 1566, title: "Detect Pattern of Length M Repeated K or More Times", diff: "Easy", topics: "Array", slug: "detect-pattern-of-length-m-repeated-k-or-more-times" },
  { id: 1567, title: "Maximum Length of Subarray With Positive Product", diff: "Medium", topics: "Array, Dynamic Programming, Greedy", slug: "maximum-length-of-subarray-with-positive-product" },
  { id: 1568, title: "Minimum Number of Days to Disconnect Island", diff: "Hard", topics: "Array, Depth-First Search, Breadth-First Search, Graph, Matrix", slug: "minimum-number-of-days-to-disconnect-island" },
  { id: 1569, title: "Number of Ways to Reorder Array to Get Same BST", diff: "Hard", topics: "Array, Math, Divide and Conquer, Dynamic Programming, Tree, Binary Search Tree, Combinatorics", slug: "number-of-ways-to-reorder-array-to-get-same-bst" },
  { id: 1570, title: "Dot Product of Two Sparse Vectors", diff: "Medium", topics: "Array, Hash Table, Design", slug: "dot-product-of-two-sparse-vectors" },
  { id: 1571, title: "Warehouse Manager", diff: "Easy", topics: "Database", slug: "warehouse-manager" },
  { id: 1572, title: "Matrix Diagonal Sum", diff: "Easy", topics: "Array, Matrix", slug: "matrix-diagonal-sum" },
  { id: 1573, title: "Number of Ways to Split a String", diff: "Medium", topics: "Math, String", slug: "number-of-ways-to-split-a-string" },
  { id: 1574, title: "Shortest Subarray to be Removed to Make Array Sorted", diff: "Medium", topics: "Array, Two Pointers, Binary Search, Stack, Monotonic Stack", slug: "shortest-subarray-to-be-removed-to-make-array-sorted" },
  { id: 1575, title: "Count All Possible Routes", diff: "Hard", topics: "Array, Dynamic Programming", slug: "count-all-possible-routes" },
  { id: 1576, title: "Replace All ?'s to Avoid Consecutive Repeating Characters", diff: "Easy", topics: "String", slug: "replace-all-s-to-avoid-consecutive-repeating-characters" },
  { id: 1577, title: "Number of Ways Where Square of Number Is Equal to Product of Two Numbers", diff: "Medium", topics: "Array, Hash Table, Two Pointers, Sorting", slug: "number-of-ways-where-square-of-number-is-equal-to-product-of-two-numbers" },
  { id: 1578, title: "Minimum Time to Make Rope Colorful", diff: "Medium", topics: "Array, String, Greedy", slug: "minimum-time-to-make-rope-colorful" },
  { id: 1579, title: "Remove Max Number of Edges to Keep Graph Fully Traversable", diff: "Hard", topics: "Union Find, Graph", slug: "remove-max-number-of-edges-to-keep-graph-fully-traversable" },
  { id: 1580, title: "Put Boxes Into the Warehouse II", diff: "Medium", topics: "Array, Greedy, Sorting", slug: "put-boxes-into-the-warehouse-ii" },
  { id: 1581, title: "Customer Who Visited but Did Not Make Any Transactions", diff: "Easy", topics: "Database", slug: "customer-who-visited-but-did-not-make-any-transactions" },
  { id: 1582, title: "Special Positions in a Binary Matrix", diff: "Easy", topics: "Array, Matrix", slug: "special-positions-in-a-binary-matrix" },
  { id: 1583, title: "Count Unhappy Friends", diff: "Medium", topics: "Array, Hash Table, Simulation", slug: "count-unhappy-friends" },
  { id: 1584, title: "Min Cost to Connect All Points", diff: "Medium", topics: "Array, Union Find, Graph, Minimum Spanning Tree", slug: "min-cost-to-connect-all-points" },
  { id: 1585, title: "Check If String Is Transformable With Substring Sort Operations", diff: "Hard", topics: "String, Queue", slug: "check-if-string-is-transformable-with-substring-sort-operations" },
  { id: 1586, title: "Binary Search Tree Iterator II", diff: "Medium", topics: "Stack, Tree, Design, Binary Search Tree, Binary Tree, Iterator", slug: "binary-search-tree-iterator-ii" },
  { id: 1587, title: "Bank Account Summary II", diff: "Easy", topics: "Database", slug: "bank-account-summary-ii" },
  { id: 1588, title: "Sum of All Odd Length Subarrays", diff: "Easy", topics: "Array, Math, Prefix Sum", slug: "sum-of-all-odd-length-subarrays" },
  { id: 1589, title: "Maximum Sum Obtained of Any Permutation", diff: "Medium", topics: "Array, Greedy, Sorting, Prefix Sum", slug: "maximum-sum-obtained-of-any-permutation" },
  { id: 1590, title: "Make Sum Divisible by P", diff: "Medium", topics: "Array, Hash Table, Prefix Sum", slug: "make-sum-divisible-by-p" },
  { id: 1591, title: "Strange Printer II", diff: "Hard", topics: "Array, Graph, Topological Sort, Matrix", slug: "strange-printer-ii" },
  { id: 1592, title: "Rearrange Spaces Between Words", diff: "Easy", topics: "String", slug: "rearrange-spaces-between-words" },
  { id: 1593, title: "Split a String Into the Max Number of Unique Substrings", diff: "Medium", topics: "Hash Table, String, Backtracking", slug: "split-a-string-into-the-max-number-of-unique-substrings" },
  { id: 1594, title: "Maximum Non Negative Product in a Matrix", diff: "Medium", topics: "Array, Dynamic Programming, Matrix", slug: "maximum-non-negative-product-in-a-matrix" },
  { id: 1595, title: "Minimum Cost to Connect Two Groups of Points", diff: "Hard", topics: "Array, Dynamic Programming, Bit Manipulation", slug: "minimum-cost-to-connect-two-groups-of-points" },
  { id: 1596, title: "The Most Frequently Ordered Products for Each Customer", diff: "Medium", topics: "Database", slug: "the-most-frequently-ordered-products-for-each-customer" },
  { id: 1597, title: "Build Binary Expression Tree From Infix Expression", diff: "Hard", topics: "String, Stack, Tree", slug: "build-binary-expression-tree-from-infix-expression" },
  { id: 1598, title: "Crawler Log Folder", diff: "Easy", topics: "Array, String, Stack", slug: "crawler-log-folder" },
  { id: 1599, title: "Maximum Profit of Operating a Centennial Wheel", diff: "Medium", topics: "Array, Simulation", slug: "maximum-profit-of-operating-a-centennial-wheel" },
  { id: 1600, title: "Throne Inheritance", diff: "Medium", topics: "Hash Table, Tree, Design", slug: "throne-inheritance" },
  { id: 1601, title: "Maximum Number of Achievable Transfer Requests", diff: "Hard", topics: "Array, Backtracking, Bit Manipulation", slug: "maximum-number-of-achievable-transfer-requests" },
  { id: 1602, title: "Find Nearest Right Node in Binary Tree", diff: "Medium", topics: "Tree, Breadth-First Search, Binary Tree", slug: "find-nearest-right-node-in-binary-tree" },
  { id: 1603, title: "Design Parking System", diff: "Easy", topics: "Design", slug: "design-parking-system" },
  { id: 1604, title: "Alert Using Same Key-Card Three or More Times in a One Hour Period", diff: "Medium", topics: "Array, Hash Table, String, Sorting", slug: "alert-using-same-key-card-three-or-more-times-in-a-one-hour-period" },
  { id: 1605, title: "Find Valid Matrix Given Row and Column Sums", diff: "Medium", topics: "Array, Greedy, Matrix", slug: "find-valid-matrix-given-row-and-column-sums" },
  { id: 1606, title: "Find Servers That Handled Most Number of Requests", diff: "Hard", topics: "Array, Ordered Set, Heap (Priority Queue)", slug: "find-servers-that-handled-most-number-of-requests" },
  { id: 1607, title: "Sellers With No Sales", diff: "Easy", topics: "Database", slug: "sellers-with-no-sales" },
  { id: 1608, title: "Special Array With X Elements Greater Than or Equal X", diff: "Easy", topics: "Array, Binary Search, Sorting", slug: "special-array-with-x-elements-greater-than-or-equal-x" },
  { id: 1609, title: "Even Odd Tree", diff: "Medium", topics: "Tree, Breadth-First Search, Binary Tree", slug: "even-odd-tree" },
  { id: 1610, title: "Maximum Number of Visible Points", diff: "Hard", topics: "Array, Math, Geometry, Sliding Window, Sorting", slug: "maximum-number-of-visible-points" },
  { id: 1611, title: "Minimum One Bit Operations to Make Integers Zero", diff: "Hard", topics: "Bit Manipulation, Dynamic Programming", slug: "minimum-one-bit-operations-to-make-integers-zero" },
  { id: 1612, title: "Check If Two Expression Trees are Equivalent", diff: "Medium", topics: "Hash Table, Tree, Depth-First Search", slug: "check-if-two-expression-trees-are-equivalent" },
  { id: 1613, title: "Find the Missing IDs", diff: "Medium", topics: "Database", slug: "find-the-missing-ids" },
  { id: 1614, title: "Maximum Nesting Depth of the Parentheses", diff: "Easy", topics: "String, Stack", slug: "maximum-nesting-depth-of-the-parentheses" },
  { id: 1615, title: "Maximal Network Rank", diff: "Medium", topics: "Graph", slug: "maximal-network-rank" },
  { id: 1616, title: "Split Two Strings to Make Palindrome", diff: "Medium", topics: "Two Pointers, String, Greedy", slug: "split-two-strings-to-make-palindrome" },
  { id: 1617, title: "Count Subtrees With Max Distance Between Cities", diff: "Hard", topics: "Dynamic Programming, Bit Manipulation, Graph, Tree, Enumeration", slug: "count-subtrees-with-max-distance-between-cities" },
  { id: 1618, title: "Maximum Font to Fit a Sentence in a Screen", diff: "Medium", topics: "Array, Binary Search, Interactive", slug: "maximum-font-to-fit-a-sentence-in-a-screen" },
  { id: 1619, title: "Mean of Array After Removing Some Elements", diff: "Easy", topics: "Array, Sorting", slug: "mean-of-array-after-removing-some-elements" },
  { id: 1620, title: "Coordinate With Maximum Network Quality", diff: "Medium", topics: "Array, Math, Enumeration", slug: "coordinate-with-maximum-network-quality" },
  { id: 1621, title: "Number of Sets of K Non-Overlapping Line Segments", diff: "Hard", topics: "Dynamic Programming, Combinatorics", slug: "number-of-sets-of-k-non-overlapping-line-segments" },
  { id: 1622, title: "Fancy Sequence", diff: "Hard", topics: "Math, Design, Segment Tree", slug: "fancy-sequence" },
  { id: 1623, title: "All Valid Triplets That Can Represent a Country", diff: "Easy", topics: "Database", slug: "all-valid-triplets-that-can-represent-a-country" },
  { id: 1624, title: "Largest Substring Between Two Equal Characters", diff: "Easy", topics: "Hash Table, String", slug: "largest-substring-between-two-equal-characters" },
  { id: 1625, title: "Lexicographically Smallest String After Applying Operations", diff: "Medium", topics: "String, Breadth-First Search", slug: "lexicographically-smallest-string-after-applying-operations" },
  { id: 1626, title: "Best Team With No Conflicts", diff: "Medium", topics: "Array, Dynamic Programming, Sorting", slug: "best-team-with-no-conflicts" },
  { id: 1627, title: "Graph Connectivity With Threshold", diff: "Hard", topics: "Union Find, Graph", slug: "graph-connectivity-with-threshold" },
  { id: 1628, title: "Design an Expression Tree With Evaluate Function", diff: "Medium", topics: "Stack, Tree, Design", slug: "design-an-expression-tree-with-evaluate-function" },
  { id: 1629, title: "Slowest Key", diff: "Easy", topics: "Array, String", slug: "slowest-key" },
  { id: 1630, title: "Arithmetic Subarrays", diff: "Medium", topics: "Array, Hash Table, Sorting", slug: "arithmetic-subarrays" },
  { id: 1631, title: "Path With Minimum Effort", diff: "Medium", topics: "Array, Binary Search, Depth-First Search, Breadth-First Search, Union Find, Graph, Heap (Priority Queue), Matrix", slug: "path-with-minimum-effort" },
  { id: 1632, title: "Rank Transform of a Matrix", diff: "Hard", topics: "Array, Union Find, Graph, Sorting, Matrix", slug: "rank-transform-of-a-matrix" },
  { id: 1633, title: "Percentage of Users Attended a Contest", diff: "Easy", topics: "Database", slug: "percentage-of-users-attended-a-contest" },
  { id: 1634, title: "Add Two Polynomials Represented as Linked Lists", diff: "Medium", topics: "Linked List, Math", slug: "add-two-polynomials-represented-as-linked-lists" },
  { id: 1635, title: "Hopper Company Queries I", diff: "Hard", topics: "Database", slug: "hopper-company-queries-i" },
  { id: 1636, title: "Sort Array by Increasing Frequency", diff: "Easy", topics: "Array, Hash Table, Sorting", slug: "sort-array-by-increasing-frequency" },
  { id: 1637, title: "Widest Vertical Area Between Two Points Containing No Points", diff: "Easy", topics: "Array, Sorting", slug: "widest-vertical-area-between-two-points-containing-no-points" },
  { id: 1638, title: "Count Substrings That Differ by One Character", diff: "Medium", topics: "String, Dynamic Programming", slug: "count-substrings-that-differ-by-one-character" },
  { id: 1639, title: "Number of Ways to Form a Target String Given a Dictionary", diff: "Hard", topics: "Array, String, Dynamic Programming", slug: "number-of-ways-to-form-a-target-string-given-a-dictionary" },
  { id: 1640, title: "Check Array Formation Through Concatenation", diff: "Easy", topics: "Array, Hash Table", slug: "check-array-formation-through-concatenation" },
  { id: 1641, title: "Count Sorted Vowel Strings", diff: "Medium", topics: "Math, Dynamic Programming, Combinatorics", slug: "count-sorted-vowel-strings" },
  { id: 1642, title: "Furthest Building You Can Reach", diff: "Medium", topics: "Array, Greedy, Heap (Priority Queue)", slug: "furthest-building-you-can-reach" },
  { id: 1643, title: "Kth Smallest Instructions", diff: "Hard", topics: "Math, Dynamic Programming, Combinatorics", slug: "kth-smallest-instructions" },
  { id: 1644, title: "Lowest Common Ancestor of a Binary Tree II", diff: "Medium", topics: "Tree, Depth-First Search, Binary Tree", slug: "lowest-common-ancestor-of-a-binary-tree-ii" },
  { id: 1645, title: "Hopper Company Queries II", diff: "Hard", topics: "Database", slug: "hopper-company-queries-ii" },
  { id: 1646, title: "Get Maximum in Generated Array", diff: "Easy", topics: "Array, Dynamic Programming", slug: "get-maximum-in-generated-array" },
  { id: 1647, title: "Minimum Deletions to Make Character Frequencies Unique", diff: "Medium", topics: "Hash Table, String, Greedy, Sorting", slug: "minimum-deletions-to-make-character-frequencies-unique" },
  { id: 1648, title: "Sell Diminishing-Valued Colored Balls", diff: "Medium", topics: "Array, Binary Search, Greedy, Sorting, Math", slug: "sell-diminishing-valued-colored-balls" },
  { id: 1649, title: "Create Sorted Array through Instructions", diff: "Hard", topics: "Array, Binary Indexed Tree, Segment Tree, Merge Sort, Ordered Set", slug: "create-sorted-array-through-instructions" },
  { id: 1650, title: "Lowest Common Ancestor of a Binary Tree III", diff: "Medium", topics: "Hash Table, Two Pointers, Tree", slug: "lowest-common-ancestor-of-a-binary-tree-iii" },
  { id: 1651, title: "Hopper Company Queries III", diff: "Hard", topics: "Database", slug: "hopper-company-queries-iii" },
  { id: 1652, title: "Defuse the Bomb", diff: "Easy", topics: "Array, Sliding Window", slug: "defuse-the-bomb" },
  { id: 1653, title: "Minimum Deletions to Make String Balanced", diff: "Medium", topics: "String, Dynamic Programming, Stack, Greedy", slug: "minimum-deletions-to-make-string-balanced" },
  { id: 1654, title: "Minimum Jumps to Reach Home", diff: "Medium", topics: "Array, Breadth-First Search", slug: "minimum-jumps-to-reach-home" },
  { id: 1655, title: "Distribute Repeating Integers", diff: "Hard", topics: "Array, Dynamic Programming, Backtracking, Bit Manipulation", slug: "distribute-repeating-integers" },
  { id: 1656, title: "Design an Ordered Stream", diff: "Easy", topics: "Array, Design, Data Stream", slug: "design-an-ordered-stream" },
  { id: 1657, title: "Determine if Two Strings Are Close", diff: "Medium", topics: "Hash Table, String, Sorting, Counting", slug: "determine-if-two-strings-are-close" },
  { id: 1658, title: "Minimum Operations to Reduce X to Zero", diff: "Medium", topics: "Array, Hash Table, Binary Search, Prefix Sum, Sliding Window", slug: "minimum-operations-to-reduce-x-to-zero" },
  { id: 1659, title: "Maximize Grid Happiness", diff: "Hard", topics: "Dynamic Programming, Bit Manipulation, Matrix", slug: "maximize-grid-happiness" },
  { id: 1660, title: "Correct a Binary Tree", diff: "Medium", topics: "Hash Table, Tree, Depth-First Search, Breadth-First Search, Binary Tree", slug: "correct-a-binary-tree" },
  { id: 1661, title: "Average Time of Process per Machine", diff: "Easy", topics: "Database", slug: "average-time-of-process-per-machine" },
  { id: 1662, title: "Check If Two String Arrays are Equivalent", diff: "Easy", topics: "Array, String", slug: "check-if-two-string-arrays-are-equivalent" },
  { id: 1663, title: "Smallest String With A Given Numeric Value", diff: "Medium", topics: "String, Greedy", slug: "smallest-string-with-a-given-numeric-value" },
  { id: 1664, title: "Ways to Make a Fair Array", diff: "Medium", topics: "Array, Dynamic Programming, Prefix Sum", slug: "ways-to-make-a-fair-array" },
  { id: 1665, title: "Minimum Initial Energy to Finish Tasks", diff: "Hard", topics: "Array, Greedy, Sorting", slug: "minimum-initial-energy-to-finish-tasks" },
  { id: 1666, title: "Change the Root of a Binary Tree", diff: "Medium", topics: "Tree, Depth-First Search, Binary Tree", slug: "change-the-root-of-a-binary-tree" },
  { id: 1667, title: "Fix Names in a Table", diff: "Easy", topics: "Database", slug: "fix-names-in-a-table" },
  { id: 1668, title: "Maximum Repeating Substring", diff: "Easy", topics: "String, String Matching", slug: "maximum-repeating-substring" },
  { id: 1669, title: "Merge In Between Linked Lists", diff: "Medium", topics: "Linked List", slug: "merge-in-between-linked-lists" },
  { id: 1670, title: "Design Front Middle Back Queue", diff: "Medium", topics: "Array, Linked List, Design, Queue", slug: "design-front-middle-back-queue" },
  { id: 1671, title: "Minimum Number of Removals to Make Mountain Array", diff: "Hard", topics: "Array, Dynamic Programming, Binary Search", slug: "minimum-number-of-removals-to-make-mountain-array" },
  { id: 1672, title: "Richest Customer Wealth", diff: "Easy", topics: "Array, Matrix", slug: "richest-customer-wealth" },
  { id: 1673, title: "Find the Most Competitive Subsequence", diff: "Medium", topics: "Array, Stack, Greedy, Monotonic Stack", slug: "find-the-most-competitive-subsequence" },
  { id: 1674, title: "Minimum Moves to Make Array Complementary", diff: "Medium", topics: "Array, Greedy, Prefix Sum", slug: "minimum-moves-to-make-array-complementary" },
  { id: 1675, title: "Minimize Deviation in Array", diff: "Hard", topics: "Array, Greedy, Heap (Priority Queue), Ordered Set", slug: "minimize-deviation-in-array" },
  { id: 1676, title: "Lowest Common Ancestor of a Binary Tree IV", diff: "Medium", topics: "Hash Table, Tree, Depth-First Search, Binary Tree", slug: "lowest-common-ancestor-of-a-binary-tree-iv" },
  { id: 1677, title: "Product's Worth Over Invoices", diff: "Easy", topics: "Database", slug: "products-worth-over-invoices" },
  { id: 1678, title: "Goal Parser Interpretation", diff: "Easy", topics: "String", slug: "goal-parser-interpretation" },
  { id: 1679, title: "Max Number of K-Sum Pairs", diff: "Medium", topics: "Array, Hash Table, Two Pointers, Sorting", slug: "max-number-of-k-sum-pairs" },
  { id: 1680, title: "Concatenation of Consecutive Binary Numbers", diff: "Medium", topics: "Math, Bit Manipulation, Simulation", slug: "concatenation-of-consecutive-binary-numbers" },
  { id: 1681, title: "Minimum Incompatibility", diff: "Hard", topics: "Array, Dynamic Programming, Bit Manipulation", slug: "minimum-incompatibility" },
  { id: 1682, title: "Longest Palindromic Subsequence II", diff: "Medium", topics: "String, Dynamic Programming", slug: "longest-palindromic-subsequence-ii" },
  { id: 1683, title: "Invalid Tweets", diff: "Easy", topics: "Database", slug: "invalid-tweets" },
  { id: 1684, title: "Count the Number of Consistent Strings", diff: "Easy", topics: "Array, Hash Table, String, Bit Manipulation", slug: "count-the-number-of-consistent-strings" },
  { id: 1685, title: "Sum of Absolute Differences in a Sorted Array", diff: "Medium", topics: "Array, Prefix Sum", slug: "sum-of-absolute-differences-in-a-sorted-array" },
  { id: 1686, title: "Stone Game VI", diff: "Medium", topics: "Array, Greedy, Sorting, Game Theory", slug: "stone-game-vi" },
  { id: 1687, title: "Delivering Boxes from Storage to Ports", diff: "Hard", topics: "Array, Dynamic Programming, Queue, Monotonic Queue", slug: "delivering-boxes-from-storage-to-ports" },
  { id: 1688, title: "Count of Matches in Tournament", diff: "Easy", topics: "Math, Simulation", slug: "count-of-matches-in-tournament" },
  { id: 1689, title: "Partitioning Into Minimum Number Of Deci-Binary Numbers", diff: "Medium", topics: "String, Greedy", slug: "partitioning-into-minimum-number-of-deci-binary-numbers" },
  { id: 1690, title: "Stone Game VII", diff: "Medium", topics: "Array, Math, Dynamic Programming, Game Theory", slug: "stone-game-vii" },
  { id: 1691, title: "Maximum Height by Stacking Cuboids", diff: "Hard", topics: "Array, Dynamic Programming, Sorting", slug: "maximum-height-by-stacking-cuboids" },
  { id: 1692, title: "Count Ways to Distribute Candies", diff: "Hard", topics: "Math, Dynamic Programming, Combinatorics", slug: "count-ways-to-distribute-candies" },
  { id: 1693, title: "Daily Leads and Partners", diff: "Easy", topics: "Database", slug: "daily-leads-and-partners" },
  { id: 1694, title: "Reformat Phone Number", diff: "Easy", topics: "String", slug: "reformat-phone-number" },
  { id: 1695, title: "Maximum Erasure Value", diff: "Medium", topics: "Array, Hash Table, Sliding Window", slug: "maximum-erasure-value" },
  { id: 1696, title: "Jump Game VI", diff: "Medium", topics: "Array, Dynamic Programming, Queue, Monotonic Queue", slug: "jump-game-vi" },
  { id: 1697, title: "Checking Existence of Edge Length Limited Paths", diff: "Hard", topics: "Array, Union Find, Graph, Sorting", slug: "checking-existence-of-edge-length-limited-paths" },
  { id: 1698, title: "Number of Distinct Substrings in a String", diff: "Medium", topics: "String, Trie, Suffix Array, Rolling Hash, Hash Function", slug: "number-of-distinct-substrings-in-a-string" },
  { id: 1699, title: "Number of Calls Between Two Persons", diff: "Medium", topics: "Database", slug: "number-of-calls-between-two-persons" },
  { id: 1700, title: "Number of Students Unable to Eat Lunch", diff: "Easy", topics: "Array, Queue, Simulation", slug: "number-of-students-unable-to-eat-lunch" },
  { id: 1701, title: "Average Waiting Time", diff: "Medium", topics: "Array, Simulation", slug: "average-waiting-time" },
  { id: 1702, title: "Maximum Binary String After Change", diff: "Medium", topics: "String, Greedy", slug: "maximum-binary-string-after-change" },
  { id: 1703, title: "Minimum Adjacent Swaps for K Consecutive Ones", diff: "Hard", topics: "Array, Greedy, Prefix Sum, Sliding Window", slug: "minimum-adjacent-swaps-for-k-consecutive-ones" },
  { id: 1704, title: "Determine if String Halves Are Alike", diff: "Easy", topics: "String, Counting", slug: "determine-if-string-halves-are-alike" },
  { id: 1705, title: "Maximum Number of Eaten Apples", diff: "Medium", topics: "Array, Greedy, Heap (Priority Queue)", slug: "maximum-number-of-eaten-apples" },
  { id: 1706, title: "Where Will the Ball Fall", diff: "Medium", topics: "Array, Dynamic Programming, Simulation, Matrix", slug: "where-will-the-ball-fall" },
  { id: 1707, title: "Maximum XOR With an Element From Array", diff: "Hard", topics: "Array, Bit Manipulation, Trie", slug: "maximum-xor-with-an-element-from-array" },
  { id: 1708, title: "Largest Subarray Length K", diff: "Easy", topics: "Array, Greedy", slug: "largest-subarray-length-k" },
  { id: 1709, title: "Biggest Window Between Visits", diff: "Medium", topics: "Database", slug: "biggest-window-between-visits" },
  { id: 1710, title: "Maximum Units on a Truck", diff: "Easy", topics: "Array, Greedy, Sorting", slug: "maximum-units-on-a-truck" },
  { id: 1711, title: "Count Good Meals", diff: "Medium", topics: "Array, Hash Table, Counting", slug: "count-good-meals" },
  { id: 1712, title: "Ways to Split Array Into Three Subarrays", diff: "Medium", topics: "Array, Binary Search, Prefix Sum", slug: "ways-to-split-array-into-three-subarrays" },
  { id: 1713, title: "Minimum Operations to Make a Subsequence", diff: "Hard", topics: "Array, Hash Table, Binary Search", slug: "minimum-operations-to-make-a-subsequence" },
  { id: 1714, title: "Sum Of Special Evenly-Spaced Elements In Array", diff: "Hard", topics: "Array, Dynamic Programming", slug: "sum-of-special-evenly-spaced-elements-in-array" },
  { id: 1715, title: "Count Apples and Oranges", diff: "Easy", topics: "Database", slug: "count-apples-and-oranges" },
  { id: 1716, title: "Calculate Money in Leetcode Bank", diff: "Easy", topics: "Math, Simulation", slug: "calculate-money-in-leetcode-bank" },
  { id: 1717, title: "Maximum Score From Removing Substrings", diff: "Medium", topics: "String, Stack, Greedy", slug: "maximum-score-from-removing-substrings" },
  { id: 1718, title: "Construct the Lexicographically Largest Valid Sequence", diff: "Medium", topics: "Array, Backtracking", slug: "construct-the-lexicographically-largest-valid-sequence" },
  { id: 1719, title: "Number Of Ways To Reconstruct A Tree", diff: "Hard", topics: "Tree, Graph", slug: "number-of-ways-to-reconstruct-a-tree" },
  { id: 1720, title: "Decode XORed Array", diff: "Easy", topics: "Array, Bit Manipulation", slug: "decode-xored-array" },
  { id: 1721, title: "Swapping Nodes in a Linked List", diff: "Medium", topics: "Linked List, Two Pointers", slug: "swapping-nodes-in-a-linked-list" },
  { id: 1722, title: "Minimize Hamming Distance After Swap Operations", diff: "Medium", topics: "Array, Hash Table, Union Find", slug: "minimize-hamming-distance-after-swap-operations" },
  { id: 1723, title: "Find Minimum Time to Finish All Jobs", diff: "Hard", topics: "Array, Backtracking, Bit Manipulation, Binary Search", slug: "find-minimum-time-to-finish-all-jobs" },
  { id: 1724, title: "Checking Existence of Edge Length Limited Paths II", diff: "Hard", topics: "Union Find, Graph, Design", slug: "checking-existence-of-edge-length-limited-paths-ii" },
  { id: 1725, title: "Number Of Rectangles That Can Form The Largest Square", diff: "Easy", topics: "Array", slug: "number-of-rectangles-that-can-form-the-largest-square" },
  { id: 1726, title: "Tuple with Same Product", diff: "Medium", topics: "Array, Hash Table, Counting", slug: "tuple-with-same-product" },
  { id: 1727, title: "Largest Submatrix With Rearrangements", diff: "Medium", topics: "Array, Dynamic Programming, Matrix, Sorting", slug: "largest-submatrix-with-rearrangements" },
  { id: 1728, title: "Cat and Mouse II", diff: "Hard", topics: "Array, Math, Dynamic Programming, Breadth-First Search, Game Theory, Matrix", slug: "cat-and-mouse-ii" },
  { id: 1729, title: "Find Followers Count", diff: "Easy", topics: "Database", slug: "find-followers-count" },
  { id: 1730, title: "Shortest Path to Get Food", diff: "Medium", topics: "Array, Breadth-First Search, Matrix", slug: "shortest-path-to-get-food" },
  { id: 1731, title: "The Number of Employees Which Report to Each Employee", diff: "Easy", topics: "Database", slug: "the-number-of-employees-which-report-to-each-employee" },
  { id: 1732, title: "Find the Highest Altitude", diff: "Easy", topics: "Array, Prefix Sum", slug: "find-the-highest-altitude" },
  { id: 1733, title: "Minimum Number of People to Teach", diff: "Medium", topics: "Array, Hash Table, Greedy", slug: "minimum-number-of-people-to-teach" },
  { id: 1734, title: "Decode XORed Permutation", diff: "Medium", topics: "Array, Bit Manipulation", slug: "decode-xored-permutation" },
  { id: 1735, title: "Count Ways to Make Array With Product", diff: "Hard", topics: "Math, Combinatorics, Number Theory", slug: "count-ways-to-make-array-with-product" },
  { id: 1736, title: "Latest Time by Replacing Hidden Digits", diff: "Easy", topics: "String, Greedy", slug: "latest-time-by-replacing-hidden-digits" },
  { id: 1737, title: "Change Minimum Characters to Satisfy One of Three Conditions", diff: "Medium", topics: "Hash Table, String, Counting, Prefix Sum", slug: "change-minimum-characters-to-satisfy-one-of-three-conditions" },
  { id: 1738, title: "Find Kth Largest XOR Coordinate Value", diff: "Medium", topics: "Array, Bit Manipulation, Matrix, Prefix Sum", slug: "find-kth-largest-xor-coordinate-value" },
  { id: 1739, title: "Building Boxes", diff: "Hard", topics: "Math, Binary Search", slug: "building-boxes" },
  { id: 1740, title: "Find Distance in a Binary Tree", diff: "Medium", topics: "Tree, Depth-First Search, Binary Tree", slug: "find-distance-in-a-binary-tree" },
  { id: 1741, title: "Find Total Time Spent by Each Employee", diff: "Easy", topics: "Database", slug: "find-total-time-spent-by-each-employee" },
  { id: 1742, title: "Maximum Number of Balls in a Box", diff: "Easy", topics: "Hash Table, Math, Counting", slug: "maximum-number-of-balls-in-a-box" },
  { id: 1743, title: "Restore the Array From Adjacent Pairs", diff: "Medium", topics: "Array, Hash Table", slug: "restore-the-array-from-adjacent-pairs" },
  { id: 1744, title: "Can You Eat Your Favorite Candy on Your Favorite Day?", diff: "Medium", topics: "Array, Prefix Sum", slug: "can-you-eat-your-favorite-candy-on-your-favorite-day" },
  { id: 1745, title: "Palindrome Partitioning IV", diff: "Hard", topics: "String, Dynamic Programming", slug: "palindrome-partitioning-iv" },
  { id: 1746, title: "Maximum Subarray Sum After One Operation", diff: "Medium", topics: "Array, Dynamic Programming", slug: "maximum-subarray-sum-after-one-operation" },
  { id: 1747, title: "Leetflex Banned Accounts", diff: "Medium", topics: "Database", slug: "leetflex-banned-accounts" },
  { id: 1748, title: "Sum of Unique Elements", diff: "Easy", topics: "Array, Hash Table, Counting", slug: "sum-of-unique-elements" },
  { id: 1749, title: "Maximum Absolute Sum of Any Subarray", diff: "Medium", topics: "Array, Dynamic Programming", slug: "maximum-absolute-sum-of-any-subarray" },
  { id: 1750, title: "Minimum Length of String After Deleting Similar Ends", diff: "Medium", topics: "Two Pointers, String", slug: "minimum-length-of-string-after-deleting-similar-ends" }
);