window.rawProblems = window.rawProblems || [];

window.rawProblems.push(
  { id: 3501, title: "Maximize Active Section with Trade II", diff: "Hard", topics: "Array, Hash Table, Linked List, Heap (Priority Queue), Simulation, Doubly-Linked List, Ordered Set", slug: "maximize-active-section-with-trade-ii" },
  { id: 3502, title: "Minimum Cost to Reach Every Position", diff: "Easy", topics: "Array, Prefix Sum", slug: "minimum-cost-to-reach-every-position" },
  { id: 3503, title: "Longest Palindrome After Substring Concatenation I", diff: "Medium", topics: "String, Dynamic Programming", slug: "longest-palindrome-after-substring-concatenation-i" },
  { id: 3504, title: "Longest Palindrome After Substring Concatenation II", diff: "Hard", topics: "String, Dynamic Programming", slug: "longest-palindrome-after-substring-concatenation-ii" },
  { id: 3505, title: "Minimum Operations to Make Elements Within K Subarrays Equal", diff: "Hard", topics: "Array, Binary Search, Sliding Window", slug: "minimum-operations-to-make-elements-within-k-subarrays-equal" },
  { id: 3506, title: "Find Time Required to Eliminate Bacterial Strains", diff: "Medium", topics: "Simulation, Queue", slug: "find-time-required-to-eliminate-bacterial-strains" },
  { id: 3507, title: "Minimum Pair Removal to Sort Array I", diff: "Medium", topics: "Array, Simulation", slug: "minimum-pair-removal-to-sort-array-i" },
  { id: 3508, title: "Implement Router", diff: "Medium", topics: "Design, Hash Table, Queue", slug: "implement-router" },
  { id: 3509, title: "Maximum Product of Subsequences With an Alternating Sum Equal to K", diff: "Hard", topics: "Dynamic Programming, Bit Manipulation", slug: "maximum-product-of-subsequences-with-an-alternating-sum-equal-to-k" },
  { id: 3510, title: "Minimum Pair Removal to Sort Array II", diff: "Hard", topics: "Array, Hash Table, Linked List, Heap (Priority Queue), Simulation, Doubly-Linked List, Ordered Set", slug: "minimum-pair-removal-to-sort-array-ii" },
  { id: 3511, title: "Make a Positive Array", diff: "Medium", topics: "Array, Greedy", slug: "make-a-positive-array" },
  { id: 3512, title: "Minimum Operations to Make Array Sum Divisible by K", diff: "Medium", topics: "Array, Greedy, Math", slug: "minimum-operations-to-make-array-sum-divisible-by-k" },
  { id: 3513, title: "Number of Unique XOR Triplets I", diff: "Medium", topics: "Array, Bit Manipulation", slug: "number-of-unique-xor-triplets-i" },
  { id: 3514, title: "Number of Unique XOR Triplets II", diff: "Hard", topics: "Array, Bit Manipulation", slug: "number-of-unique-xor-triplets-ii" },
  { id: 3515, title: "Shortest Path in a Weighted Tree", diff: "Hard", topics: "Tree, Depth-First Search, Binary Lifting", slug: "shortest-path-in-a-weighted-tree" },
  { id: 3516, title: "Find Closest Person", diff: "Easy", topics: "Math", slug: "find-closest-person" },
  { id: 3517, title: "Smallest Palindromic Rearrangement I", diff: "Medium", topics: "String, Greedy, Counting", slug: "smallest-palindromic-rearrangement-i" },
  { id: 3518, title: "Smallest Palindromic Rearrangement II", diff: "Hard", topics: "String, Greedy, Backtracking", slug: "smallest-palindromic-rearrangement-ii" },
  { id: 3519, title: "Count Numbers With Non-Decreasing Digits", diff: "Hard", topics: "Dynamic Programming, Digit DP", slug: "count-numbers-with-non-decreasing-digits" },
  { id: 3520, title: "Find the Connected Component Leader", diff: "Medium", topics: "Database", slug: "find-the-connected-component-leader" },
  { id: 3521, title: "Find Product Recommendation Pairs", diff: "Medium", topics: "Database", slug: "find-product-recommendation-pairs" },
  { id: 3522, title: "Calculate Score After Performing Instructions", diff: "Medium", topics: "Simulation", slug: "calculate-score-after-performing-instructions" },
  { id: 3523, title: "Make Array Non-decreasing", diff: "Medium", topics: "Array, Greedy", slug: "make-array-non-decreasing" },
  { id: 3524, title: "Find X Value of Array I", diff: "Easy", topics: "Array", slug: "find-x-value-of-array-i" },
  { id: 3525, title: "Find X Value of Array II", diff: "Medium", topics: "Array, Prefix Sum", slug: "find-x-value-of-array-ii" },
  { id: 3526, title: "Find X Value of Array III", diff: "Hard", topics: "Array, Segment Tree", slug: "find-x-value-of-array-iii" },
  { id: 3527, title: "Find the Most Common Response", diff: "Easy", topics: "Hash Table, Counting", slug: "find-the-most-common-response" },
  { id: 3528, title: "Unit Conversion I", diff: "Easy", topics: "Math", slug: "unit-conversion-i" },
  { id: 3529, title: "Unit Conversion II", diff: "Medium", topics: "Graph, Depth-First Search", slug: "unit-conversion-ii" },
  { id: 3530, title: "Maximum Profit From Valid Topological Order", diff: "Hard", topics: "Graph, Dynamic Programming", slug: "maximum-profit-from-valid-topological-order" },
  { id: 3531, title: "Count Covered Buildings", diff: "Medium", topics: "Geometry", slug: "count-covered-buildings" },
  { id: 3532, title: "Path Existence Queries in a Graph", diff: "Hard", topics: "Graph, Union Find", slug: "path-existence-queries-in-a-graph" },
  { id: 3533, title: "Concatenated Divisibility", diff: "Hard", topics: "Dynamic Programming, Bit Manipulation", slug: "concatenated-divisibility" },
  { id: 3534, title: "Path Existence Queries II", diff: "Hard", topics: "Graph, Lowest Common Ancestor", slug: "path-existence-queries-ii" },
  { id: 3535, title: "Minimum Deletions for At Most K Distinct Characters", diff: "Medium", topics: "String, Sliding Window", slug: "minimum-deletions-for-at-most-k-distinct-characters" },
  { id: 3536, title: "Maximum Product of Two Digits", diff: "Easy", topics: "Math", slug: "maximum-product-of-two-digits" },
  { id: 3537, title: "Fill a Special Grid", diff: "Medium", topics: "Matrix, Simulation", slug: "fill-a-special-grid" },
  { id: 3538, title: "Merge Operations for Maximum Score", diff: "Hard", topics: "Dynamic Programming", slug: "merge-operations-for-maximum-score" },
  { id: 3539, title: "Find Sum of Array Product of Magical Sequences", diff: "Hard", topics: "Combinatorics, Dynamic Programming", slug: "find-sum-of-array-product-of-magical-sequences" },
  { id: 3540, title: "Minimum Time to Convert String", diff: "Medium", topics: "Graph, Shortest Path", slug: "minimum-time-to-convert-string" },
  { id: 3541, title: "Find Most Frequent Vowel and Consonant", diff: "Easy", topics: "String, Counting", slug: "find-most-frequent-vowel-and-consonant" },
  { id: 3542, title: "Minimum Operations to Convert All Elements", diff: "Medium", topics: "Greedy", slug: "minimum-operations-to-convert-all-elements" },
  { id: 3543, title: "Maximum Weighted K-Edge Path", diff: "Hard", topics: "Tree, Dynamic Programming", slug: "maximum-weighted-k-edge-path" },
  { id: 3544, title: "Subtree Inversion Queries", diff: "Hard", topics: "Tree, Segment Tree", slug: "subtree-inversion-queries" },
  { id: 3545, title: "Minimum Deletions for Balanced Frequency", diff: "Medium", topics: "Hash Table, Greedy", slug: "minimum-deletions-for-balanced-frequency" },
  { id: 3546, title: "Equal Sum Grid Partition I", diff: "Medium", topics: "Matrix, Prefix Sum", slug: "equal-sum-grid-partition-i" },
  { id: 3547, title: "Equal Sum Grid Partition II", diff: "Hard", topics: "Matrix, Prefix Sum", slug: "equal-sum-grid-partition-ii" },
  { id: 3548, title: "Equal Value Paths", diff: "Medium", topics: "Tree, Depth-First Search", slug: "equal-value-paths" },
  { id: 3549, title: "Multiply Two Polynomial Linked Lists", diff: "Medium", topics: "Linked List, Math", slug: "multiply-two-polynomial-linked-lists" },
  { id: 3550, title: "Smallest Index With Digit Sum Equal to Index", diff: "Easy", topics: "Array, Math", slug: "smallest-index-with-digit-sum-equal-to-index" }

);