window.rawProblems = window.rawProblems || [];

window.rawProblems.push(
  { id: 3001, title: "Minimum Moves to Capture The Queen", diff: "Medium", topics: "Math, Greedy", slug: "minimum-moves-to-capture-the-queen" },
  { id: 3002, title: "Maximum Size of a Set After Removals", diff: "Medium", topics: "Array, Hash Table, Greedy", slug: "maximum-size-of-a-set-after-removals" },
  { id: 3003, title: "Maximize the Number of Partitions After Operations", diff: "Hard", topics: "String, Dynamic Programming, Bit Manipulation", slug: "maximize-the-number-of-partitions-after-operations" },
  { id: 3004, title: "Maximum Subtree of the Same Color", diff: "Medium", topics: "Tree, Depth-First Search", slug: "maximum-subtree-of-the-same-color" },
  { id: 3005, title: "Count Elements With Maximum Frequency", diff: "Easy", topics: "Array, Hash Table, Counting", slug: "count-elements-with-maximum-frequency" },
  { id: 3006, title: "Find Beautiful Indices in the Given Array I", diff: "Medium", topics: "String, Two Pointers, KMP", slug: "find-beautiful-indices-in-the-given-array-i" },
  { id: 3007, title: "Maximum Number That Sum of the Prices Is Less Than or Equal to K", diff: "Hard", topics: "Binary Search, Bit Manipulation, Digit DP", slug: "maximum-number-that-sum-of-the-prices-is-less-than-or-equal-to-k" },
  { id: 3008, title: "Find Beautiful Indices in the Given Array II", diff: "Hard", topics: "String, Binary Search, KMP", slug: "find-beautiful-indices-in-the-given-array-ii" },
  { id: 3009, title: "Maximum Number of Intersections on the Chart", diff: "Hard", topics: "Geometry, Sweep Line", slug: "maximum-number-of-intersections-on-the-chart" },
  { id: 3010, title: "Divide an Array Into Subarrays With Minimum Cost I", diff: "Easy", topics: "Array, Greedy", slug: "divide-an-array-into-subarrays-with-minimum-cost-i" },
  { id: 3011, title: "Find if Array Can Be Sorted", diff: "Medium", topics: "Array, Bit Manipulation, Sorting", slug: "find-if-array-can-be-sorted" },
  { id: 3012, title: "Minimize Length of Array Using Operations", diff: "Medium", topics: "Array, Math, Number Theory", slug: "minimize-length-of-array-using-operations" },
  { id: 3013, title: "Divide an Array Into Subarrays With Minimum Cost II", diff: "Hard", topics: "Array, Sliding Window, Heap (Priority Queue)", slug: "divide-an-array-into-subarrays-with-minimum-cost-ii" },
  { id: 3014, title: "Minimum Number of Pushes to Type Word I", diff: "Easy", topics: "Greedy, String", slug: "minimum-number-of-pushes-to-type-word-i" },
  { id: 3015, title: "Count the Number of Houses at a Certain Distance I", diff: "Medium", topics: "Graph, Breadth-First Search", slug: "count-the-number-of-houses-at-a-certain-distance-i" },
  { id: 3016, title: "Minimum Number of Pushes to Type Word II", diff: "Medium", topics: "Greedy, Counting, String", slug: "minimum-number-of-pushes-to-type-word-ii" },
  { id: 3017, title: "Count the Number of Houses at a Certain Distance II", diff: "Hard", topics: "Math, Prefix Sum", slug: "count-the-number-of-houses-at-a-certain-distance-ii" },
  { id: 3018, title: "Maximum Number of Removal Queries That Can Be Processed I", diff: "Hard", topics: "Dynamic Programming", slug: "maximum-number-of-removal-queries-that-can-be-processed-i" },
  { id: 3019, title: "Number of Changing Keys", diff: "Easy", topics: "String", slug: "number-of-changing-keys" },
  { id: 3020, title: "Find the Maximum Number of Elements in Subset", diff: "Medium", topics: "Array, Hash Table, Greedy", slug: "find-the-maximum-number-of-elements-in-subset" },
  { id: 3021, title: "Alice and Bob Playing Flower Game", diff: "Medium", topics: "Math", slug: "alice-and-bob-playing-flower-game" },
  { id: 3022, title: "Minimize OR of Remaining Elements Using Operations", diff: "Hard", topics: "Bit Manipulation, Greedy", slug: "minimize-or-of-remaining-elements-using-operations" },
  { id: 3023, title: "Find Pattern in Infinite Stream I", diff: "Medium", topics: "Interactive", slug: "find-pattern-in-infinite-stream-i" },
  { id: 3024, title: "Type of Triangle", diff: "Easy", topics: "Math, Geometry", slug: "type-of-triangle" },
  { id: 3025, title: "Find the Number of Ways to Place People I", diff: "Medium", topics: "Array, Geometry, Sorting", slug: "find-the-number-of-ways-to-place-people-i" },
  { id: 3026, title: "Maximum Good Subarray Sum", diff: "Medium", topics: "Array, Hash Table, Prefix Sum", slug: "maximum-good-subarray-sum" },
  { id: 3027, title: "Find the Number of Ways to Place People II", diff: "Hard", topics: "Array, Geometry, Sorting", slug: "find-the-number-of-ways-to-place-people-ii" },
  { id: 3028, title: "Ant on the Boundary", diff: "Easy", topics: "Array, Prefix Sum, Simulation", slug: "ant-on-the-boundary" },
  { id: 3029, title: "Minimum Time to Revert Word to Initial State I", diff: "Medium", topics: "String, Simulation", slug: "minimum-time-to-revert-word-to-initial-state-i" },
  { id: 3030, title: "Find the Grid of Region Average", diff: "Medium", topics: "Array, Matrix, Simulation", slug: "find-the-grid-of-region-average" },
  { id: 3031, title: "Minimum Time to Revert Word to Initial State II", diff: "Hard", topics: "String, KMP", slug: "minimum-time-to-revert-word-to-initial-state-ii" },
  { id: 3032, title: "Count Numbers With Unique Digits II", diff: "Medium", topics: "Math, Digit DP", slug: "count-numbers-with-unique-digits-ii" },
  { id: 3033, title: "Modify the Matrix", diff: "Easy", topics: "Array, Matrix", slug: "modify-the-matrix" },
  { id: 3034, title: "Number of Subarrays That Match a Pattern I", diff: "Medium", topics: "Array, String, Sliding Window", slug: "number-of-subarrays-that-match-a-pattern-i" },
  { id: 3035, title: "Maximum Palindromes After Operations", diff: "Medium", topics: "Greedy, Hash Table, String", slug: "maximum-palindromes-after-operations" },
  { id: 3036, title: "Number of Subarrays That Match a Pattern II", diff: "Hard", topics: "String, KMP, Z Function", slug: "number-of-subarrays-that-match-a-pattern-ii" },
  { id: 3037, title: "Find Pattern in Infinite Stream II", diff: "Hard", topics: "Interactive", slug: "find-pattern-in-infinite-stream-ii" },
  { id: 3038, title: "Maximum Number of Operations With the Same Score I", diff: "Easy", topics: "Array, Simulation", slug: "maximum-number-of-operations-with-the-same-score-i" },
  { id: 3039, title: "Apply Operations to Make String Empty", diff: "Medium", topics: "Hash Table, String", slug: "apply-operations-to-make-string-empty" },
  { id: 3040, title: "Maximum Number of Operations With the Same Score II", diff: "Medium", topics: "Array, Dynamic Programming", slug: "maximum-number-of-operations-with-the-same-score-ii" },
  { id: 3041, title: "Maximize Consecutive Elements in an Array After Modification", diff: "Hard", topics: "Array, Dynamic Programming, Sorting", slug: "maximize-consecutive-elements-in-an-array-after-modification" },
  { id: 3042, title: "Count Prefix and Suffix Pairs I", diff: "Easy", topics: "String, Trie", slug: "count-prefix-and-suffix-pairs-i" },
  { id: 3043, title: "Find the Length of the Longest Common Prefix", diff: "Medium", topics: "Array, Hash Table, Trie", slug: "find-the-length-of-the-longest-common-prefix" },
  { id: 3044, title: "Most Frequent Prime", diff: "Medium", topics: "Array, Matrix, Math", slug: "most-frequent-prime" },
  { id: 3045, title: "Count Prefix and Suffix Pairs II", diff: "Hard", topics: "String, Trie, Hashing", slug: "count-prefix-and-suffix-pairs-ii" },
  { id: 3046, title: "Split the Array", diff: "Easy", topics: "Array, Hash Table", slug: "split-the-array" },
  { id: 3047, title: "Find the Largest Area of Square Inside Two Rectangles", diff: "Medium", topics: "Geometry, Math", slug: "find-the-largest-area-of-square-inside-two-rectangles" },
  { id: 3048, title: "Earliest Second to Mark Indices I", diff: "Medium", topics: "Array, Binary Search, Greedy", slug: "earliest-second-to-mark-indices-i" },
  { id: 3049, title: "Earliest Second to Mark Indices II", diff: "Hard", topics: "Array, Binary Search, Greedy, Heap (Priority Queue)", slug: "earliest-second-to-mark-indices-ii" },
  { id: 3050, title: "Pizza Toppings Cost Analysis", diff: "Medium", topics: "Database", slug: "pizza-toppings-cost-analysis" },
  { id: 3051, title: "Find Candidates for Data Scientist Position", diff: "Easy", topics: "Database", slug: "find-candidates-for-data-scientist-position" },
  { id: 3052, title: "Maximize Items", diff: "Medium", topics: "Database", slug: "maximize-items" },
  { id: 3053, title: "Classifying Triangles by Length", diff: "Easy", topics: "Database", slug: "classifying-triangles-by-length" },
  { id: 3054, title: "Binary Tree Nodes", diff: "Medium", topics: "Database", slug: "binary-tree-nodes" },
  { id: 3055, title: "Top Percentile Fraud", diff: "Hard", topics: "Database", slug: "top-percentile-fraud" },
  { id: 3056, title: "Snaps Analysis", diff: "Medium", topics: "Database", slug: "snaps-analysis" },
  { id: 3057, title: "Employees Project Allocation", diff: "Medium", topics: "Database", slug: "employees-project-allocation" },
  { id: 3058, title: "Friends With No Mutual Friends", diff: "Medium", topics: "Database", slug: "friends-with-no-mutual-friends" },
  { id: 3059, title: "Find All Unique Email Domains", diff: "Easy", topics: "Database", slug: "find-all-unique-email-domains" },
  { id: 3060, title: "User Activities within Time Bounds", diff: "Medium", topics: "Database", slug: "user-activities-within-time-bounds" },
  { id: 3061, title: "Calculate Trapping Rain Water", diff: "Hard", topics: "Database", slug: "calculate-trapping-rain-water" },
  { id: 3062, title: "Winner of the Linked List Game", diff: "Easy", topics: "Linked List, Simulation", slug: "winner-of-the-linked-list-game" },
  { id: 3063, title: "Linked List Frequency", diff: "Medium", topics: "Linked List, Hash Table", slug: "linked-list-frequency" },
  { id: 3064, title: "Guess the Number Using Bitwise Questions I", diff: "Medium", topics: "Interactive, Bit Manipulation", slug: "guess-the-number-using-bitwise-questions-i" },
  { id: 3065, title: "Minimum Operations to Exceed Threshold Value I", diff: "Easy", topics: "Array", slug: "minimum-operations-to-exceed-threshold-value-i" },
  { id: 3066, title: "Minimum Operations to Exceed Threshold Value II", diff: "Medium", topics: "Array, Heap (Priority Queue), Simulation", slug: "minimum-operations-to-exceed-threshold-value-ii" },
  { id: 3067, title: "Count Pairs of Connectable Servers in a Weighted Tree Network", diff: "Medium", topics: "Tree, Depth-First Search", slug: "count-pairs-of-connectable-servers-in-a-weighted-tree-network" },
  { id: 3068, title: "Find the Maximum Sum of Node Values", diff: "Hard", topics: "Tree, Dynamic Programming, Greedy, Bit Manipulation", slug: "find-the-maximum-sum-of-node-values" },
  { id: 3069, title: "Distribute Elements Into Two Arrays I", diff: "Easy", topics: "Array, Simulation", slug: "distribute-elements-into-two-arrays-i" },
  { id: 3070, title: "Count Submatrices with Top-Left Element and Sum Less Than k", diff: "Medium", topics: "Array, Matrix, Prefix Sum", slug: "count-submatrices-with-top-left-element-and-sum-less-than-k" },
  { id: 3071, title: "Minimum Operations to Write the Letter Y on a Grid", diff: "Medium", topics: "Array, Matrix, Counting", slug: "minimum-operations-to-write-the-letter-y-on-a-grid" },
  { id: 3072, title: "Distribute Elements Into Two Arrays II", diff: "Hard", topics: "Array, Binary Indexed Tree, Ordered Set", slug: "distribute-elements-into-two-arrays-ii" },
  { id: 3073, title: "Maximum Increasing Triplet Value", diff: "Medium", topics: "Array", slug: "maximum-increasing-triplet-value" },
  { id: 3074, title: "Apple Redistribution into Boxes", diff: "Easy", topics: "Array, Greedy, Sorting", slug: "apple-redistribution-into-boxes" },
  { id: 3075, title: "Maximize Happiness of Selected Children", diff: "Medium", topics: "Array, Greedy, Sorting", slug: "maximize-happiness-of-selected-children" },
  { id: 3076, title: "Shortest Uncommon Substring in an Array", diff: "Medium", topics: "Array, String, Hash Table", slug: "shortest-uncommon-substring-in-an-array" },
  { id: 3077, title: "Maximum Strength of K Disjoint Subarrays", diff: "Hard", topics: "Array, Dynamic Programming", slug: "maximum-strength-of-k-disjoint-subarrays" },
  { id: 3078, title: "Match Alphanumerical Pattern in Matrix I", diff: "Medium", topics: "Array, Matrix, Backtracking", slug: "match-alphanumerical-pattern-in-matrix-i" },
  { id: 3079, title: "Find the Sum of Encrypted Integers", diff: "Easy", topics: "Array, Math", slug: "find-the-sum-of-encrypted-integers" },
  { id: 3080, title: "Mark Elements on Array by Performing Queries", diff: "Medium", topics: "Array, Heap (Priority Queue), Simulation", slug: "mark-elements-on-array-by-performing-queries" },
  { id: 3081, title: "Replace Question Marks in String to Minimize Its Value", diff: "Medium", topics: "String, Greedy, Heap (Priority Queue), Counting", slug: "replace-question-marks-in-string-to-minimize-its-value" },
  { id: 3082, title: "Find the Sum of the Power of All Subsequences", diff: "Hard", topics: "Dynamic Programming, Combinatorics", slug: "find-the-sum-of-the-power-of-all-subsequences" },
  { id: 3083, title: "Existence of a Substring in a String and Its Reverse", diff: "Easy", topics: "String, Hash Table", slug: "existence-of-a-substring-in-a-string-and-its-reverse" },
  { id: 3084, title: "Count Substrings Starting and Ending with Given Character", diff: "Medium", topics: "String, Counting", slug: "count-substrings-starting-and-ending-with-given-character" },
  { id: 3085, title: "Minimum Deletions to Make String K-Special", diff: "Medium", topics: "String, Greedy, Sorting, Counting", slug: "minimum-deletions-to-make-string-k-special" },
  { id: 3086, title: "Minimum Moves to Pick K Ones", diff: "Hard", topics: "Array, Prefix Sum, Sliding Window", slug: "minimum-moves-to-pick-k-ones" },
  { id: 3087, title: "Find Trending Hashtags", diff: "Medium", topics: "Database", slug: "find-trending-hashtags" },
  { id: 3088, title: "Make String Anti-palindrome", diff: "Hard", topics: "String, Greedy, Sorting", slug: "make-string-anti-palindrome" },
  { id: 3089, title: "Find Bursty Behavior", diff: "Hard", topics: "Database", slug: "find-bursty-behavior" },
  { id: 3090, title: "Maximum Length Substring With Two Occurrences", diff: "Easy", topics: "Hash Table, String, Sliding Window", slug: "maximum-length-substring-with-two-occurrences" },
  { id: 3091, title: "Apply Operations to Make Sum of Array Greater Than or Equal to k", diff: "Medium", topics: "Math, Greedy", slug: "apply-operations-to-make-sum-of-array-greater-than-or-equal-to-k" },
  { id: 3092, title: "Most Frequent IDs", diff: "Medium", topics: "Array, Hash Table, Heap (Priority Queue), Ordered Set", slug: "most-frequent-ids" },
  { id: 3093, title: "Longest Common Suffix Queries", diff: "Hard", topics: "String, Trie", slug: "longest-common-suffix-queries" },
  { id: 3094, title: "Guess the Number Using Bitwise Questions II", diff: "Hard", topics: "Interactive, Bit Manipulation", slug: "guess-the-number-using-bitwise-questions-ii" },
  { id: 3095, title: "Shortest Subarray With OR at Least K I", diff: "Easy", topics: "Array, Bit Manipulation, Sliding Window", slug: "shortest-subarray-with-or-at-least-k-i" },
  { id: 3096, title: "Minimum Levels to Gain More Points", diff: "Medium", topics: "Array, Prefix Sum", slug: "minimum-levels-to-gain-more-points" },
  { id: 3097, title: "Shortest Subarray With OR at Least K II", diff: "Hard", topics: "Array, Bit Manipulation, Sliding Window", slug: "shortest-subarray-with-or-at-least-k-ii" },
  { id: 3098, title: "Find the Sum of Subsequence Powers", diff: "Hard", topics: "Array, Dynamic Programming, Sorting", slug: "find-the-sum-of-subsequence-powers" },
  { id: 3099, title: "Harshad Number", diff: "Easy", topics: "Math", slug: "harshad-number" },
  { id: 3100, title: "Water Bottles II", diff: "Medium", topics: "Math, Simulation", slug: "water-bottles-ii" },
  { id: 3101, title: "Count Alternating Subarrays", diff: "Medium", topics: "Array, Dynamic Programming, Sliding Window", slug: "count-alternating-subarrays" },
  { id: 3102, title: "Minimize Manhattan Distances", diff: "Hard", topics: "Array, Geometry, Sorting", slug: "minimize-manhattan-distances" },
  { id: 3103, title: "Find Trending Hashtags II", diff: "Hard", topics: "Database", slug: "find-trending-hashtags-ii" },
  { id: 3104, title: "Find Longest Self-Contained Substring", diff: "Hard", topics: "String, Greedy", slug: "find-longest-self-contained-substring" },
  { id: 3105, title: "Longest Strictly Increasing or Strictly Decreasing Subarray", diff: "Easy", topics: "Array", slug: "longest-strictly-increasing-or-strictly-decreasing-subarray" },
  { id: 3106, title: "Lexicographically Smallest String After Operations With Constraint", diff: "Medium", topics: "String, Greedy", slug: "lexicographically-smallest-string-after-operations-with-constraint" },
  { id: 3107, title: "Minimum Operations to Make Median of Array Equal to K", diff: "Medium", topics: "Array, Greedy, Sorting", slug: "minimum-operations-to-make-median-of-array-equal-to-k" },
  { id: 3108, title: "Minimum Cost Walk in Weighted Graph", diff: "Hard", topics: "Graph, Union Find, Bit Manipulation", slug: "minimum-cost-walk-in-weighted-graph" },
  { id: 3109, title: "Find the Index of Permutation", diff: "Hard", topics: "Math, Binary Indexed Tree, Combinatorics", slug: "find-the-index-of-permutation" },
  { id: 3110, title: "Score of a String", diff: "Easy", topics: "String", slug: "score-of-a-string" },
  { id: 3111, title: "Minimum Rectangles to Cover Points", diff: "Medium", topics: "Array, Greedy, Sorting", slug: "minimum-rectangles-to-cover-points" },
  { id: 3112, title: "Minimum Time to Visit Disappearing Nodes", diff: "Hard", topics: "Graph, Shortest Path, Heap (Priority Queue)", slug: "minimum-time-to-visit-disappearing-nodes" },
  { id: 3113, title: "Find the Number of Subarrays Where Boundary Elements Are Maximum", diff: "Hard", topics: "Array, Monotonic Stack", slug: "find-the-number-of-subarrays-where-boundary-elements-are-maximum" },
  { id: 3114, title: "Latest Time You Can Obtain After Replacing Characters", diff: "Easy", topics: "String, Greedy", slug: "latest-time-you-can-obtain-after-replacing-characters" },
  { id: 3115, title: "Maximum Prime Difference", diff: "Medium", topics: "Array, Math, Number Theory", slug: "maximum-prime-difference" },
  { id: 3116, title: "Kth Smallest Amount With Single Denomination Combination", diff: "Hard", topics: "Math, Binary Search, Inclusion-Exclusion", slug: "kth-smallest-amount-with-single-denomination-combination" },
  { id: 3117, title: "Minimum Sum of Values by Dividing Array", diff: "Hard", topics: "Array, Dynamic Programming, Bit Manipulation", slug: "minimum-sum-of-values-by-dividing-array" },
  { id: 3118, title: "Friday Purchase III", diff: "Medium", topics: "Database", slug: "friday-purchase-iii" },
  { id: 3119, title: "Maximum Number of Potholes That Can Be Fixed", diff: "Medium", topics: "Greedy, String", slug: "maximum-number-of-potholes-that-can-be-fixed" },
  { id: 3120, title: "Count the Number of Special Characters I", diff: "Easy", topics: "Hash Table, String", slug: "count-the-number-of-special-characters-i" },
  { id: 3121, title: "Count the Number of Special Characters II", diff: "Medium", topics: "Hash Table, String", slug: "count-the-number-of-special-characters-ii" },
  { id: 3122, title: "Minimum Number of Operations to Satisfy Conditions", diff: "Medium", topics: "Array, Dynamic Programming, Matrix", slug: "minimum-number-of-operations-to-satisfy-conditions" },
  { id: 3123, title: "Find Edges in Shortest Paths", diff: "Hard", topics: "Graph, Shortest Path", slug: "find-edges-in-shortest-paths" },
  { id: 3124, title: "Find Longest Calls", diff: "Medium", topics: "Database", slug: "find-longest-calls" },
  { id: 3125, title: "Maximum Number That Makes Result of Bitwise AND Zero", diff: "Medium", topics: "Bit Manipulation", slug: "maximum-number-that-makes-result-of-bitwise-and-zero" },
  { id: 3126, title: "Server Utilization Time", diff: "Medium", topics: "Database", slug: "server-utilization-time" },
  { id: 3127, title: "Make a Square with the Same Color", diff: "Easy", topics: "Array, Matrix", slug: "make-a-square-with-the-same-color" },
  { id: 3128, title: "Right Triangles", diff: "Medium", topics: "Array, Matrix, Counting", slug: "right-triangles" },
  { id: 3129, title: "Find All Possible Stable Binary Arrays I", diff: "Medium", topics: "Dynamic Programming", slug: "find-all-possible-stable-binary-arrays-i" },
  { id: 3130, title: "Find All Possible Stable Binary Arrays II", diff: "Hard", topics: "Dynamic Programming", slug: "find-all-possible-stable-binary-arrays-ii" },
  { id: 3131, title: "Find the Integer Added to Array I", diff: "Easy", topics: "Array, Math", slug: "find-the-integer-added-to-array-i" },
  { id: 3132, title: "Find the Integer Added to Array II", diff: "Medium", topics: "Array, Sorting, Two Pointers", slug: "find-the-integer-added-to-array-ii" },
  { id: 3133, title: "Minimum Array End", diff: "Medium", topics: "Bit Manipulation, Greedy", slug: "minimum-array-end" },
  { id: 3134, title: "Find the Median of the Uniqueness Array", diff: "Hard", topics: "Array, Binary Search, Sliding Window", slug: "find-the-median-of-the-uniqueness-array" },
  { id: 3135, title: "Equalize Strings by Adding or Removing Characters at Ends", diff: "Medium", topics: "String, Dynamic Programming", slug: "equalize-strings-by-adding-or-removing-characters-at-ends" },
  { id: 3136, title: "Valid Word", diff: "Easy", topics: "String", slug: "valid-word" },
  { id: 3137, title: "Minimum Number of Operations to Make Word K-Periodic", diff: "Medium", topics: "String, Hash Table, Counting", slug: "minimum-number-of-operations-to-make-word-k-periodic" },
  { id: 3138, title: "Minimum Length of Anagram Concatenation", diff: "Medium", topics: "String, Math", slug: "minimum-length-of-anagram-concatenation" },
  { id: 3139, title: "Minimum Cost to Equalize Array", diff: "Hard", topics: "Array, Greedy, Math", slug: "minimum-cost-to-equalize-array" },
  { id: 3140, title: "Consecutive Available Seats II", diff: "Medium", topics: "Database", slug: "consecutive-available-seats-ii" },
  { id: 3141, title: "Maximum Hamming Distances", diff: "Hard", topics: "Bit Manipulation, Trie", slug: "maximum-hamming-distances" },
  { id: 3142, title: "Check if Grid Satisfies Conditions", diff: "Easy", topics: "Array, Matrix", slug: "check-if-grid-satisfies-conditions" },
  { id: 3143, title: "Maximum Points Inside the Square", diff: "Medium", topics: "Array, Geometry, Hash Table", slug: "maximum-points-inside-the-square" },
  { id: 3144, title: "Minimum Substring Partition of Equal Character Frequency", diff: "Hard", topics: "String, Dynamic Programming", slug: "minimum-substring-partition-of-equal-character-frequency" },
  { id: 3145, title: "Find Products of Elements of Big Array", diff: "Hard", topics: "Bit Manipulation, Math", slug: "find-products-of-elements-of-big-array" },
  { id: 3146, title: "Permutation Difference between Two Strings", diff: "Easy", topics: "Hash Table, String", slug: "permutation-difference-between-two-strings" },
  { id: 3147, title: "Taking Maximum Energy From the Mystic Dungeon", diff: "Medium", topics: "Array, Dynamic Programming", slug: "taking-maximum-energy-from-the-mystic-dungeon" },
  { id: 3148, title: "Maximum Difference Score in a Grid", diff: "Medium", topics: "Array, Dynamic Programming, Matrix", slug: "maximum-difference-score-in-a-grid" },
  { id: 3149, title: "Find the Minimum Cost Array Permutation", diff: "Hard", topics: "Dynamic Programming, Bit Manipulation", slug: "find-the-minimum-cost-array-permutation" },
  { id: 3150, title: "Invalid Tweets II", diff: "Easy", topics: "Database", slug: "invalid-tweets-ii" },
  { id: 3151, title: "Special Array I", diff: "Easy", topics: "Array", slug: "special-array-i" },
  { id: 3152, title: "Special Array II", diff: "Medium", topics: "Array, Prefix Sum", slug: "special-array-ii" },
  { id: 3153, title: "Sum of Digit Differences of All Pairs", diff: "Medium", topics: "Array, Math, Counting", slug: "sum-of-digit-differences-of-all-pairs" },
  { id: 3154, title: "Find Number of Ways to Reach the K-th Stair", diff: "Hard", topics: "Math, Dynamic Programming, Memoization", slug: "find-number-of-ways-to-reach-the-k-th-stair" },
  { id: 3155, title: "Maximum Number of Upgradable Servers", diff: "Medium", topics: "Database", slug: "maximum-number-of-upgradable-servers" },
  { id: 3156, title: "Employee Task Duration and Concurrent Tasks", diff: "Medium", topics: "Database", slug: "employee-task-duration-and-concurrent-tasks" },
  { id: 3157, title: "Find the Level of Tree with Minimum Sum", diff: "Medium", topics: "Tree, Breadth-First Search", slug: "find-the-level-of-tree-with-minimum-sum" },
  { id: 3158, title: "Find the XOR of Numbers Which Appear Twice", diff: "Easy", topics: "Array, Bit Manipulation, Hash Table", slug: "find-the-xor-of-numbers-which-appear-twice" },
  { id: 3159, title: "Find Occurrences of an Element in an Array", diff: "Medium", topics: "Array, Hash Table", slug: "find-occurrences-of-an-element-in-an-array" },
  { id: 3160, title: "Find the Number of Distinct Colors Among the Balls", diff: "Medium", topics: "Hash Table, Simulation", slug: "find-the-number-of-distinct-colors-among-the-balls" },
  { id: 3161, title: "Block Placement Queries", diff: "Hard", topics: "Array, Binary Search, Segment Tree", slug: "block-placement-queries" },
  { id: 3162, title: "Find the Number of Good Pairs I", diff: "Easy", topics: "Array, Hash Table, Math", slug: "find-the-number-of-good-pairs-i" },
  { id: 3163, title: "String Compression III", diff: "Medium", topics: "String", slug: "string-compression-iii" },
  { id: 3164, title: "Find the Number of Good Pairs II", diff: "Medium", topics: "Array, Hash Table, Math, Number Theory", slug: "find-the-number-of-good-pairs-ii" },
  { id: 3165, title: "Maximum Sum of Subsequence With Non-adjacent Elements", diff: "Hard", topics: "Array, Segment Tree", slug: "maximum-sum-of-subsequence-with-non-adjacent-elements" },
  { id: 3166, title: "Calculate Parking Fees and Duration", diff: "Medium", topics: "Database", slug: "calculate-parking-fees-and-duration" },
  { id: 3167, title: "Better Compression of String", diff: "Medium", topics: "String, Hash Table, Sorting", slug: "better-compression-of-string" },
  { id: 3168, title: "Minimum Number of Chairs in a Waiting Room", diff: "Easy", topics: "String, Simulation", slug: "minimum-number-of-chairs-in-a-waiting-room" },
  { id: 3169, title: "Count Days Without Meetings", diff: "Medium", topics: "Array, Sorting", slug: "count-days-without-meetings" },
  { id: 3170, title: "Lexicographically Minimum String After Removing Stars", diff: "Medium", topics: "String, Stack, Greedy, Heap (Priority Queue)", slug: "lexicographically-minimum-string-after-removing-stars" },
  { id: 3171, title: "Find Subarray With Bitwise AND Closest to K", diff: "Hard", topics: "Array, Bit Manipulation", slug: "find-subarray-with-bitwise-and-closest-to-k" },
  { id: 3172, title: "Second Day Verification", diff: "Medium", topics: "Database", slug: "second-day-verification" },
  { id: 3173, title: "Bitwise OR of Adjacent Elements", diff: "Easy", topics: "Array, Bit Manipulation", slug: "bitwise-or-of-adjacent-elements" },
  { id: 3174, title: "Clear Digits", diff: "Easy", topics: "String, Stack", slug: "clear-digits" },
  { id: 3175, title: "Find The First Player to Win K Games in a Row", diff: "Medium", topics: "Array, Simulation", slug: "find-the-first-player-to-win-k-games-in-a-row" },
  { id: 3176, title: "Find the Maximum Length of a Good Subsequence I", diff: "Medium", topics: "Array, Dynamic Programming", slug: "find-the-maximum-length-of-a-good-subsequence-i" },
  { id: 3177, title: "Find the Maximum Length of a Good Subsequence II", diff: "Hard", topics: "Array, Dynamic Programming", slug: "find-the-maximum-length-of-a-good-subsequence-ii" },
  { id: 3178, title: "Find the Child Who Has the Ball After K Seconds", diff: "Easy", topics: "Math, Simulation", slug: "find-the-child-who-has-the-ball-after-k-seconds" },
  { id: 3179, title: "Find the N-th Value After K Seconds", diff: "Medium", topics: "Math, Dynamic Programming, Combinatorics", slug: "find-the-n-th-value-after-k-seconds" },
  { id: 3180, title: "Maximum Total Reward Using Operations I", diff: "Medium", topics: "Array, Dynamic Programming, Bit Manipulation", slug: "maximum-total-reward-using-operations-i" },
  { id: 3181, title: "Maximum Total Reward Using Operations II", diff: "Hard", topics: "Array, Dynamic Programming, Bit Manipulation", slug: "maximum-total-reward-using-operations-ii" },
  { id: 3182, title: "Find Top Scoring Students", diff: "Medium", topics: "Database", slug: "find-top-scoring-students" },
  { id: 3183, title: "The Number of Ways to Make the Sum", diff: "Hard", topics: "Dynamic Programming, Math", slug: "the-number-of-ways-to-make-the-sum" },
  { id: 3184, title: "Count Pairs That Form a Complete Day I", diff: "Easy", topics: "Array, Hash Table, Counting", slug: "count-pairs-that-form-a-complete-day-i" },
  { id: 3185, title: "Count Pairs That Form a Complete Day II", diff: "Medium", topics: "Array, Hash Table, Counting", slug: "count-pairs-that-form-a-complete-day-ii" },
  { id: 3186, title: "Maximum Total Damage With Spell Casting", diff: "Medium", topics: "Array, Dynamic Programming, Sorting", slug: "maximum-total-damage-with-spell-casting" },
  { id: 3187, title: "Peaks in Array", diff: "Hard", topics: "Array, Binary Indexed Tree", slug: "peaks-in-array" },
  { id: 3188, title: "Find Top Scoring Students II", diff: "Hard", topics: "Database", slug: "find-top-scoring-students-ii" },
  { id: 3189, title: "Minimum Moves to Get a Peaceful Board", diff: "Medium", topics: "Greedy, Sorting", slug: "minimum-moves-to-get-a-peaceful-board" },
  { id: 3190, title: "Find Minimum Operations to Make All Elements Divisible by Three", diff: "Easy", topics: "Array, Math", slug: "find-minimum-operations-to-make-all-elements-divisible-by-three" },
  { id: 3191, title: "Minimum Operations to Make Binary Array Elements Equal to One I", diff: "Medium", topics: "Array, Greedy", slug: "minimum-operations-to-make-binary-array-elements-equal-to-one-i" },
  { id: 3192, title: "Minimum Operations to Make Binary Array Elements Equal to One II", diff: "Medium", topics: "Array, Greedy", slug: "minimum-operations-to-make-binary-array-elements-equal-to-one-ii" },
  { id: 3193, title: "Count the Number of Inversions", diff: "Hard", topics: "Dynamic Programming, Combinatorics", slug: "count-the-number-of-inversions" },
  { id: 3194, title: "Minimum Average of Smallest and Largest Elements", diff: "Easy", topics: "Array, Sorting, Two Pointers", slug: "minimum-average-of-smallest-and-largest-elements" },
  { id: 3195, title: "Find the Minimum Area to Cover All Ones I", diff: "Medium", topics: "Array, Matrix", slug: "find-the-minimum-area-to-cover-all-ones-i" },
  { id: 3196, title: "Maximize Total Cost of Alternating Subarrays", diff: "Medium", topics: "Array, Dynamic Programming", slug: "maximize-total-cost-of-alternating-subarrays" },
  { id: 3197, title: "Find the Minimum Area to Cover All Ones II", diff: "Hard", topics: "Array, Matrix, Enumeration", slug: "find-the-minimum-area-to-cover-all-ones-ii" },
  { id: 3198, title: "Find Cities in Each State", diff: "Easy", topics: "Database", slug: "find-cities-in-each-state" },
  { id: 3199, title: "Count Triplets With Even XOR Set Bits I", diff: "Easy", topics: "Bit Manipulation", slug: "count-triplets-with-even-xor-set-bits-i" },
  { id: 3200, title: "Maximum Height of a Triangle", diff: "Easy", topics: "Math, Greedy", slug: "maximum-height-of-a-triangle" },
  { id: 3201, title: "Find the Maximum Length of Valid Subsequence I", diff: "Medium", topics: "Array, Dynamic Programming", slug: "find-the-maximum-length-of-valid-subsequence-i" },
  { id: 3202, title: "Find the Maximum Length of Valid Subsequence II", diff: "Medium", topics: "Array, Dynamic Programming", slug: "find-the-maximum-length-of-valid-subsequence-ii" },
  { id: 3203, title: "Find Minimum Diameter After Merging Two Trees", diff: "Hard", topics: "Tree, Depth-First Search, Breadth-First Search", slug: "find-minimum-diameter-after-merging-two-trees" },
  { id: 3204, title: "Bitwise User Permissions Analysis", diff: "Medium", topics: "Database", slug: "bitwise-user-permissions-analysis" },
  { id: 3205, title: "Maximum Array Hopping Score I", diff: "Medium", topics: "Array, Dynamic Programming", slug: "maximum-array-hopping-score-i" },
  { id: 3206, title: "Alternating Groups I", diff: "Easy", topics: "Array", slug: "alternating-groups-i" },
  { id: 3207, title: "Maximum Points After Enemy Battles", diff: "Medium", topics: "Greedy, Sorting", slug: "maximum-points-after-enemy-battles" },
  { id: 3208, title: "Alternating Groups II", diff: "Medium", topics: "Array, Sliding Window", slug: "alternating-groups-ii" },
  { id: 3209, title: "Number of Subarrays With AND Value of K", diff: "Hard", topics: "Array, Bit Manipulation, Hash Table", slug: "number-of-subarrays-with-and-value-of-k" },
  { id: 3210, title: "Find the Encrypted String", diff: "Easy", topics: "String", slug: "find-the-encrypted-string" },
  { id: 3211, title: "Generate Binary Strings Without Adjacent Zeros", diff: "Medium", topics: "Backtracking, String", slug: "generate-binary-strings-without-adjacent-zeros" },
  { id: 3212, title: "Count Submatrices With Equal Frequency of X and Y", diff: "Medium", topics: "Array, Matrix, Prefix Sum", slug: "count-submatrices-with-equal-frequency-of-x-and-y" },
  { id: 3213, title: "Construct String with Minimum Cost", diff: "Hard", topics: "String, Dynamic Programming, Trie", slug: "construct-string-with-minimum-cost" },
  { id: 3214, title: "Year on Year Growth Rate", diff: "Easy", topics: "Database", slug: "year-on-year-growth-rate" },
  { id: 3215, title: "Count Triplets with Even XOR Set Bits II", diff: "Hard", topics: "Bit Manipulation", slug: "count-triplets-with-even-xor-set-bits-ii" },
  { id: 3216, title: "Lexicographically Smallest String After a Swap", diff: "Easy", topics: "Greedy, String", slug: "lexicographically-smallest-string-after-a-swap" },
  { id: 3217, title: "Delete Nodes From Linked List Present in Array", diff: "Medium", topics: "Linked List, Hash Table", slug: "delete-nodes-from-linked-list-present-in-array" },
  { id: 3218, title: "Minimum Cost for Cutting Cake I", diff: "Medium", topics: "Dynamic Programming, Greedy", slug: "minimum-cost-for-cutting-cake-i" },
  { id: 3219, title: "Minimum Cost for Cutting Cake II", diff: "Hard", topics: "Greedy, Sorting", slug: "minimum-cost-for-cutting-cake-ii" },
  { id: 3220, title: "Odd and Even Transactions", diff: "Medium", topics: "Database", slug: "odd-and-even-transactions" },
  { id: 3221, title: "Maximum Array Hopping Score II", diff: "Hard", topics: "Array, Greedy", slug: "maximum-array-hopping-score-ii" },
  { id: 3222, title: "Find the Winning Player in Coin Game", diff: "Easy", topics: "Math, Game Theory", slug: "find-the-winning-player-in-coin-game" },
  { id: 3223, title: "Minimum Length of String After Operations", diff: "Medium", topics: "String, Greedy, Counting", slug: "minimum-length-of-string-after-operations" },
  { id: 3224, title: "Minimum Array Changes to Make Differences Equal", diff: "Medium", topics: "Array, Prefix Sum", slug: "minimum-array-changes-to-make-differences-equal" },
  { id: 3225, title: "Maximum Score From Grid Operations", diff: "Hard", topics: "Array, Dynamic Programming, Matrix", slug: "maximum-score-from-grid-operations" },
  { id: 3226, title: "Number of Bit Changes to Make Two Integers Equal", diff: "Easy", topics: "Bit Manipulation", slug: "number-of-bit-changes-to-make-two-integers-equal" },
  { id: 3227, title: "Vowels Game in a String", diff: "Medium", topics: "Game Theory, String", slug: "vowels-game-in-a-string" },
  { id: 3228, title: "Maximum Number of Operations to Move Ones to the End", diff: "Medium", topics: "String, Greedy", slug: "maximum-number-of-operations-to-move-ones-to-the-end" },
  { id: 3229, title: "Minimum Operations to Make Array Equal to Target", diff: "Hard", topics: "Array, Greedy", slug: "minimum-operations-to-make-array-equal-to-target" },
  { id: 3230, title: "Customer Purchasing Behavior Analysis", diff: "Medium", topics: "Database", slug: "customer-purchasing-behavior-analysis" },
  { id: 3231, title: "Minimum Number of Increasing Subsequence to Be Removed", diff: "Hard", topics: "Dynamic Programming, Greedy", slug: "minimum-number-of-increasing-subsequence-to-be-removed" },
  { id: 3232, title: "Find if Digit Game Can Be Won", diff: "Easy", topics: "Array, Math, Game Theory", slug: "find-if-digit-game-can-be-won" },
  { id: 3233, title: "Find the Count of Numbers Which Are Not Special", diff: "Medium", topics: "Math, Number Theory", slug: "find-the-count-of-numbers-which-are-not-special" },
  { id: 3234, title: "Count the Number of Substrings With Dominant Ones", diff: "Hard", topics: "String, Sliding Window", slug: "count-the-number-of-substrings-with-dominant-ones" },
  { id: 3235, title: "Check if the Rectangle Corner Is Reachable", diff: "Hard", topics: "Geometry, Union Find", slug: "check-if-the-rectangle-corner-is-reachable" },
  { id: 3236, title: "CEO Subordinate Hierarchy", diff: "Medium", topics: "Database", slug: "ceo-subordinate-hierarchy" },
  { id: 3237, title: "Alt and Tab Simulation", diff: "Medium", topics: "Database", slug: "alt-and-tab-simulation" },
  { id: 3238, title: "Find the Number of Winning Players", diff: "Easy", topics: "Array, Hash Table, Counting", slug: "find-the-number-of-winning-players" },
  { id: 3239, title: "Minimum Number of Flips to Make Binary Grid Palindromic I", diff: "Medium", topics: "Array, Matrix, Greedy", slug: "minimum-number-of-flips-to-make-binary-grid-palindromic-i" },
  { id: 3240, title: "Minimum Number of Flips to Make Binary Grid Palindromic II", diff: "Hard", topics: "Array, Matrix, Greedy", slug: "minimum-number-of-flips-to-make-binary-grid-palindromic-ii" },
  { id: 3241, title: "Time Taken to Mark All Nodes", diff: "Hard", topics: "Tree, Depth-First Search, Dynamic Programming", slug: "time-taken-to-mark-all-nodes" },
  { id: 3242, title: "Design Neighbor Sum Service", diff: "Easy", topics: "Design, Array, Matrix", slug: "design-neighbor-sum-service" },
  { id: 3243, title: "Shortest Distance After Road Addition Queries I", diff: "Medium", topics: "Graph, Breadth-First Search", slug: "shortest-distance-after-road-addition-queries-i" },
  { id: 3244, title: "Shortest Distance After Road Addition Queries II", diff: "Hard", topics: "Graph, Union Find", slug: "shortest-distance-after-road-addition-queries-ii" },
  { id: 3245, title: "Alternating Groups III", diff: "Hard", topics: "Array, Segment Tree", slug: "alternating-groups-iii" },
  { id: 3246, title: "Premier League Table Ranking", diff: "Medium", topics: "Database", slug: "premier-league-table-ranking" },
  { id: 3247, title: "Number of Subsequences with Odd Sum", diff: "Medium", topics: "Dynamic Programming, Math", slug: "number-of-subsequences-with-odd-sum" },
  { id: 3248, title: "Snake in Matrix", diff: "Easy", topics: "Array, Simulation", slug: "snake-in-matrix" },
  { id: 3249, title: "Count the Number of Good Nodes", diff: "Medium", topics: "Tree, Depth-First Search", slug: "count-the-number-of-good-nodes" },
  { id: 3250, title: "Find the Count of Monotonic Pairs I", diff: "Hard", topics: "Dynamic Programming", slug: "find-the-count-of-monotonic-pairs-i" }

);