window.rawProblems = window.rawProblems || [];

window.rawProblems.push(
  { id: 3251, title: "Find the Count of Monotonic Pairs II", diff: "Hard", topics: "Dynamic Programming, Prefix Sum", slug: "find-the-count-of-monotonic-pairs-ii" },
  { id: 3252, title: "Premier League Table Ranking II", diff: "Medium", topics: "Database", slug: "premier-league-table-ranking-ii" },
  { id: 3253, title: "Construct String with Minimum Cost (Easy Version)", diff: "Hard", topics: "String, Dynamic Programming, Trie", slug: "construct-string-with-minimum-cost-easy-version" },
  { id: 3254, title: "Find the Power of K-Size Subarrays I", diff: "Medium", topics: "Array, Sliding Window", slug: "find-the-power-of-k-size-subarrays-i" },
  { id: 3255, title: "Find the Power of K-Size Subarrays II", diff: "Hard", topics: "Array, Sliding Window, Monotonic Queue", slug: "find-the-power-of-k-size-subarrays-ii" },
  { id: 3256, title: "Maximum Value Sum by Placing Three Rooks I", diff: "Hard", topics: "Array, Matrix, Greedy", slug: "maximum-value-sum-by-placing-three-rooks-i" },
  { id: 3257, title: "Maximum Value Sum by Placing Three Rooks II", diff: "Hard", topics: "Array, Matrix, Greedy", slug: "maximum-value-sum-by-placing-three-rooks-ii" },
  { id: 3258, title: "Count Substrings That Satisfy K-Constraint I", diff: "Easy", topics: "String, Sliding Window", slug: "count-substrings-that-satisfy-k-constraint-i" },
  { id: 3259, title: "Maximum Energy Boost From Two Drinks", diff: "Medium", topics: "Dynamic Programming", slug: "maximum-energy-boost-from-two-drinks" },
  { id: 3260, title: "Find the Largest Palindrome Divisible by K", diff: "Hard", topics: "Math, Dynamic Programming", slug: "find-the-largest-palindrome-divisible-by-k" },
  { id: 3261, title: "Count Substrings That Satisfy K-Constraint II", diff: "Hard", topics: "String, Sliding Window, Prefix Sum", slug: "count-substrings-that-satisfy-k-constraint-ii" },
  { id: 3262, title: "Find Overlapping Shifts", diff: "Medium", topics: "Database", slug: "find-overlapping-shifts" },
  { id: 3263, title: "Convert Doubly Linked List to Array I", diff: "Easy", topics: "Linked List", slug: "convert-doubly-linked-list-to-array-i" },
  { id: 3264, title: "Final Array State After K Multiplication Operations I", diff: "Easy", topics: "Array, Heap (Priority Queue), Simulation", slug: "final-array-state-after-k-multiplication-operations-i" },
  { id: 3265, title: "Count Almost Equal Pairs I", diff: "Medium", topics: "Array, Hash Table, Sorting", slug: "count-almost-equal-pairs-i" },
  { id: 3266, title: "Final Array State After K Multiplication Operations II", diff: "Hard", topics: "Array, Heap (Priority Queue), Math", slug: "final-array-state-after-k-multiplication-operations-ii" },
  { id: 3267, title: "Count Almost Equal Pairs II", diff: "Hard", topics: "Array, Hash Table, Sorting", slug: "count-almost-equal-pairs-ii" },
  { id: 3268, title: "Find Overlapping Shifts II", diff: "Hard", topics: "Database", slug: "find-overlapping-shifts-ii" },
  { id: 3269, title: "Constructing Two Increasing Arrays", diff: "Medium", topics: "Greedy", slug: "constructing-two-increasing-arrays" },
  { id: 3270, title: "Find the Key of the Numbers", diff: "Easy", topics: "Math", slug: "find-the-key-of-the-numbers" },
  { id: 3271, title: "Hash Divided String", diff: "Easy", topics: "String", slug: "hash-divided-string" },
  { id: 3272, title: "Find the Count of Good Integers", diff: "Hard", topics: "Math, Combinatorics, Digit DP", slug: "find-the-count-of-good-integers" },
  { id: 3273, title: "Minimum Amount of Damage Dealt to Bob", diff: "Hard", topics: "Greedy, Sorting", slug: "minimum-amount-of-damage-dealt-to-bob" },
  { id: 3274, title: "Check if Two Chessboard Squares Have the Same Color", diff: "Easy", topics: "Math", slug: "check-if-two-chessboard-squares-have-the-same-color" },
  { id: 3275, title: "K-th Nearest Obstacle Queries", diff: "Medium", topics: "Heap (Priority Queue), Geometry", slug: "k-th-nearest-obstacle-queries" },
  { id: 3276, title: "Select Cells in Grid With Maximum Score", diff: "Hard", topics: "Dynamic Programming, Bit Manipulation, Matrix", slug: "select-cells-in-grid-with-maximum-score" },
  { id: 3277, title: "Maximum XOR Score Subarray Queries", diff: "Hard", topics: "Dynamic Programming, Bit Manipulation", slug: "maximum-xor-score-subarray-queries" },
  { id: 3278, title: "Find Candidates for Data Scientist Position II", diff: "Medium", topics: "Database", slug: "find-candidates-for-data-scientist-position-ii" },
  { id: 3279, title: "Maximum Total Area Occupied by Pistons", diff: "Hard", topics: "Geometry, Sweep Line", slug: "maximum-total-area-occupied-by-pistons" },
  { id: 3280, title: "Convert Date to Binary", diff: "Easy", topics: "String", slug: "convert-date-to-binary" },
  { id: 3281, title: "Maximize Score of Numbers in Ranges", diff: "Medium", topics: "Binary Search, Greedy", slug: "maximize-score-of-numbers-in-ranges" },
  { id: 3282, title: "Reach End of Array With Max Score", diff: "Medium", topics: "Greedy", slug: "reach-end-of-array-with-max-score" },
  { id: 3283, title: "Maximum Number of Moves to Kill All Pawns", diff: "Hard", topics: "Dynamic Programming, Game Theory, Breadth-First Search", slug: "maximum-number-of-moves-to-kill-all-pawns" },
  { id: 3284, title: "Sum of Consecutive Subarrays", diff: "Medium", topics: "Array", slug: "sum-of-consecutive-subarrays" },
  { id: 3285, title: "Find Indices of Stable Mountains", diff: "Easy", topics: "Array", slug: "find-indices-of-stable-mountains" },
  { id: 3286, title: "Find a Safe Walk Through a Grid", diff: "Medium", topics: "Graph, Breadth-First Search, Matrix", slug: "find-a-safe-walk-through-a-grid" },
  { id: 3287, title: "Find the Maximum Sequence Value of Array", diff: "Hard", topics: "Dynamic Programming, Bit Manipulation", slug: "find-the-maximum-sequence-value-of-array" },
  { id: 3288, title: "Length of the Longest Increasing Path", diff: "Hard", topics: "Binary Indexed Tree, Dynamic Programming", slug: "length-of-the-longest-increasing-path" },
  { id: 3289, title: "The Two Sneaky Numbers of Digitville", diff: "Easy", topics: "Array, Bit Manipulation", slug: "the-two-sneaky-numbers-of-digitville" },
  { id: 3290, title: "Maximum Multiplication Score", diff: "Medium", topics: "Dynamic Programming", slug: "maximum-multiplication-score" },
  { id: 3291, title: "Minimum Number of Valid Strings to Form Target I", diff: "Hard", topics: "Trie, Dynamic Programming, String", slug: "minimum-number-of-valid-strings-to-form-target-i" },
  { id: 3292, title: "Minimum Number of Valid Strings to Form Target II", diff: "Hard", topics: "Trie, Dynamic Programming, String", slug: "minimum-number-of-valid-strings-to-form-target-ii" },
  { id: 3293, title: "Calculate Product Final Price", diff: "Medium", topics: "Database", slug: "calculate-product-final-price" },
  { id: 3294, title: "Convert Doubly Linked List to Array II", diff: "Medium", topics: "Linked List", slug: "convert-doubly-linked-list-to-array-ii" },
  { id: 3295, title: "Report Spam Message", diff: "Easy", topics: "Hash Table, String", slug: "report-spam-message" },
  { id: 3296, title: "Minimum Number of Seconds to Make Mountain Height Zero", diff: "Medium", topics: "Binary Search, Heap (Priority Queue)", slug: "minimum-number-of-seconds-to-make-mountain-height-zero" },
  { id: 3297, title: "Count Substrings That Can Be Rearranged to Contain a String I", diff: "Medium", topics: "String, Sliding Window", slug: "count-substrings-that-can-be-rearranged-to-contain-a-string-i" },
  { id: 3298, title: "Count Substrings That Can Be Rearranged to Contain a String II", diff: "Hard", topics: "String, Sliding Window", slug: "count-substrings-that-can-be-rearranged-to-contain-a-string-ii" },
  { id: 3299, title: "Sum of Consecutive Subsequences", diff: "Hard", topics: "Dynamic Programming", slug: "sum-of-consecutive-subsequences" },
  { id: 3300, title: "Minimum Element After Replacement With Digit Sum", diff: "Easy", topics: "Array, Math", slug: "minimum-element-after-replacement-with-digit-sum" },
  { id: 3301, title: "Maximize the Total Height of Unique Towers", diff: "Medium", topics: "Array, Greedy, Sorting", slug: "maximize-the-total-height-of-unique-towers" },
  { id: 3302, title: "Find the Lexicographically Smallest Valid Sequence", diff: "Hard", topics: "String, Greedy, Two Pointers", slug: "find-the-lexicographically-smallest-valid-sequence" },
  { id: 3303, title: "Find the Occurrence of First Almost Equal Substring", diff: "Hard", topics: "String, Z Function, Two Pointers", slug: "find-the-occurrence-of-first-almost-equal-substring" },
  { id: 3304, title: "Find the K-th Character in String Game I", diff: "Easy", topics: "String, Simulation", slug: "find-the-k-th-character-in-string-game-i" },
  { id: 3305, title: "Count of Substrings Containing Every Vowel and K Consonants I", diff: "Medium", topics: "String, Sliding Window", slug: "count-of-substrings-containing-every-vowel-and-k-consonants-i" },
  { id: 3306, title: "Count of Substrings Containing Every Vowel and K Consonants II", diff: "Hard", topics: "String, Sliding Window", slug: "count-of-substrings-containing-every-vowel-and-k-consonants-ii" },
  { id: 3307, title: "Find the K-th Character in String Game II", diff: "Hard", topics: "Bit Manipulation, Recursion", slug: "find-the-k-th-character-in-string-game-ii" },
  { id: 3308, title: "Find Top Performing Driver", diff: "Medium", topics: "Database", slug: "find-top-performing-driver" },
  { id: 3309, title: "Maximum Possible Number by Binary Concatenation", diff: "Medium", topics: "Array, Greedy, Sorting", slug: "maximum-possible-number-by-binary-concatenation" },
  { id: 3310, title: "Remove Methods From Project", diff: "Medium", topics: "Graph, Depth-First Search", slug: "remove-methods-from-project" },
  { id: 3311, title: "Construct 2D Grid Matching Graph Layout", diff: "Hard", topics: "Graph, Construction", slug: "construct-2d-grid-matching-graph-layout" },
  { id: 3312, title: "Sorted GCD Pair Queries", diff: "Hard", topics: "Array, Math, Number Theory, Prefix Sum", slug: "sorted-gcd-pair-queries" },
  { id: 3313, title: "Find the Last Marked Nodes in Tree", diff: "Hard", topics: "Tree, Depth-First Search", slug: "find-the-last-marked-nodes-in-tree" },
  { id: 3314, title: "Construct the Minimum Bitwise Array I", diff: "Easy", topics: "Bit Manipulation", slug: "construct-the-minimum-bitwise-array-i" },
  { id: 3315, title: "Construct the Minimum Bitwise Array II", diff: "Medium", topics: "Bit Manipulation", slug: "construct-the-minimum-bitwise-array-ii" },
  { id: 3316, title: "Find Maximum Removals From Source String", diff: "Hard", topics: "String, Dynamic Programming", slug: "find-maximum-removals-from-source-string" },
  { id: 3317, title: "Find the Number of Possible Ways for an Event", diff: "Hard", topics: "Dynamic Programming, Combinatorics, Math", slug: "find-the-number-of-possible-ways-for-an-event" },
  { id: 3318, title: "Find X-Sum of All K-Long Subarrays I", diff: "Easy", topics: "Array, Hash Table, Sliding Window", slug: "find-x-sum-of-all-k-long-subarrays-i" },
  { id: 3319, title: "K-th Largest Perfect Subtree Size in Binary Tree", diff: "Medium", topics: "Tree, Depth-First Search", slug: "k-th-largest-perfect-subtree-size-in-binary-tree" },
  { id: 3320, title: "Count the Number of Winning Sequences", diff: "Hard", topics: "Dynamic Programming", slug: "count-the-number-of-winning-sequences" },
  { id: 3321, title: "Find X-Sum of All K-Long Subarrays II", diff: "Hard", topics: "Array, Hash Table, Sliding Window, Ordered Set", slug: "find-x-sum-of-all-k-long-subarrays-ii" },
  { id: 3322, title: "Premier League Table Ranking III", diff: "Medium", topics: "Database", slug: "premier-league-table-ranking-iii" },
  { id: 3323, title: "Minimize Connected Groups by Inserting Interval", diff: "Hard", topics: "Array, Greedy, Sorting", slug: "minimize-connected-groups-by-inserting-interval" },
  { id: 3324, title: "Find the Sequence of Strings Appeared on the Screen", diff: "Medium", topics: "String, Simulation", slug: "find-the-sequence-of-strings-appeared-on-the-screen" },
  { id: 3325, title: "Count Substrings With K-Frequency Characters I", diff: "Medium", topics: "String, Sliding Window", slug: "count-substrings-with-k-frequency-characters-i" },
  { id: 3326, title: "Minimum Division Operations to Make Array Non Decreasing", diff: "Medium", topics: "Array, Greedy, Number Theory", slug: "minimum-division-operations-to-make-array-non-decreasing" },
  { id: 3327, title: "Check if DFS Strings Are Palindromes", diff: "Hard", topics: "Tree, Hashing, String", slug: "check-if-dfs-strings-are-palindromes" },
  { id: 3328, title: "Find Cities in Each State II", diff: "Medium", topics: "Database", slug: "find-cities-in-each-state-ii" },
  { id: 3329, title: "Count Substrings With K-Frequency Characters II", diff: "Hard", topics: "String, Sliding Window", slug: "count-substrings-with-k-frequency-characters-ii" },
  { id: 3330, title: "Find the Original Typed String I", diff: "Easy", topics: "String", slug: "find-the-original-typed-string-i" },
  { id: 3331, title: "Find Subtree Sizes After Changes", diff: "Hard", topics: "Tree, Depth-First Search", slug: "find-subtree-sizes-after-changes" },
  { id: 3332, title: "Maximum Points Tourist Can Earn", diff: "Medium", topics: "Dynamic Programming", slug: "maximum-points-tourist-can-earn" },
  { id: 3333, title: "Find the Original Typed String II", diff: "Hard", topics: "Dynamic Programming, String", slug: "find-the-original-typed-string-ii" },
  { id: 3334, title: "Find the Maximum Factor Score of Array", diff: "Medium", topics: "Array, Math, Number Theory", slug: "find-the-maximum-factor-score-of-array" },
  { id: 3335, title: "Total Characters in String After Transformations I", diff: "Medium", topics: "Dynamic Programming, String", slug: "total-characters-in-string-after-transformations-i" },
  { id: 3336, title: "Find the Number of Subsequences With Equal GCD", diff: "Hard", topics: "Dynamic Programming, Math, Number Theory", slug: "find-the-number-of-subsequences-with-equal-gcd" },
  { id: 3337, title: "Total Characters in String After Transformations II", diff: "Hard", topics: "Dynamic Programming, Matrix, String", slug: "total-characters-in-string-after-transformations-ii" },
  { id: 3338, title: "Second Highest Salary II", diff: "Easy", topics: "Database", slug: "second-highest-salary-ii" },
  { id: 3339, title: "Find the Number of K-Even Arrays", diff: "Hard", topics: "Dynamic Programming, Math", slug: "find-the-number-of-k-even-arrays" },
  { id: 3340, title: "Check Balanced String", diff: "Easy", topics: "String", slug: "check-balanced-string" },
  { id: 3341, title: "Find Minimum Time to Reach Last Room I", diff: "Medium", topics: "Graph, Shortest Path, Heap (Priority Queue)", slug: "find-minimum-time-to-reach-last-room-i" },
  { id: 3342, title: "Find Minimum Time to Reach Last Room II", diff: "Medium", topics: "Graph, Shortest Path, Heap (Priority Queue)", slug: "find-minimum-time-to-reach-last-room-ii" },
  { id: 3343, title: "Count Number of Balanced Permutations", diff: "Hard", topics: "Dynamic Programming, Combinatorics", slug: "count-number-of-balanced-permutations" },
  { id: 3344, title: "Maximum Sized Array", diff: "Hard", topics: "Math, Binary Search", slug: "maximum-sized-array" },
  { id: 3345, title: "Smallest Divisible Digit Product I", diff: "Easy", topics: "Math, Enumeration", slug: "smallest-divisible-digit-product-i" },
  { id: 3346, title: "Maximum Frequency of an Element After Performing Operations I", diff: "Medium", topics: "Array, Sliding Window, Sorting", slug: "maximum-frequency-of-an-element-after-performing-operations-i" },
  { id: 3347, title: "Maximum Frequency of an Element After Performing Operations II", diff: "Hard", topics: "Array, Sliding Window, Sorting", slug: "maximum-frequency-of-an-element-after-performing-operations-ii" },
  { id: 3348, title: "Smallest Divisible Digit Product II", diff: "Hard", topics: "Math, Digit DP", slug: "smallest-divisible-digit-product-ii" },
  { id: 3349, title: "Adjacent Increasing Subarrays Detection I", diff: "Easy", topics: "Array", slug: "adjacent-increasing-subarrays-detection-i" },
  { id: 3350, title: "Adjacent Increasing Subarrays Detection II", diff: "Medium", topics: "Array", slug: "adjacent-increasing-subarrays-detection-ii" },
  { id: 3351, title: "Sum of Good Subsequences", diff: "Hard", topics: "Array, Dynamic Programming, Hash Table", slug: "sum-of-good-subsequences" },
  { id: 3352, title: "Count K-Reducible Numbers Less Than N", diff: "Hard", topics: "Dynamic Programming, Digit DP, Combinatorics", slug: "count-k-reducible-numbers-less-than-n" },
  { id: 3353, title: "Minimum Total Operations", diff: "Medium", topics: "Database", slug: "minimum-total-operations" },
  { id: 3354, title: "Make Array Elements Equal to Zero", diff: "Medium", topics: "Array, Prefix Sum, Greedy", slug: "make-array-elements-equal-to-zero" },
  { id: 3355, title: "Zero Array Transformation I", diff: "Medium", topics: "Array, Difference Array, Prefix Sum", slug: "zero-array-transformation-i" },
  { id: 3356, title: "Zero Array Transformation II", diff: "Medium", topics: "Array, Binary Search, Difference Array, Prefix Sum", slug: "zero-array-transformation-ii" },
  { id: 3357, title: "Minimize the Maximum Adjacent Element Difference", diff: "Hard", topics: "Array, Binary Search, Greedy", slug: "minimize-the-maximum-adjacent-element-difference" },
  { id: 3358, title: "Books with NULL Ratings", diff: "Easy", topics: "Database", slug: "books-with-null-ratings" },
  { id: 3359, title: "Find Sorted Submatrices With Maximum Element at Most K", diff: "Hard", topics: "Array, Matrix, Monotonic Stack", slug: "find-sorted-submatrices-with-maximum-element-at-most-k" },
  { id: 3360, title: "Stone Removal Game", diff: "Easy", topics: "Math, Game Theory", slug: "stone-removal-game" },
  { id: 3361, title: "Shift Distance Between Two Strings", diff: "Medium", topics: "String, Prefix Sum", slug: "shift-distance-between-two-strings" },
  { id: 3362, title: "Zero Array Transformation III", diff: "Hard", topics: "Array, Greedy, Heap (Priority Queue)", slug: "zero-array-transformation-iii" },
  { id: 3363, title: "Find the Maximum Number of Fruits Collected", diff: "Hard", topics: "Dynamic Programming, Matrix", slug: "find-the-maximum-number-of-fruits-collected" },
  { id: 3364, title: "Minimum Positive Sum Subarray", diff: "Easy", topics: "Array, Prefix Sum, Sliding Window", slug: "minimum-positive-sum-subarray" },
  { id: 3365, title: "Rearrange K Substrings to Form Target String", diff: "Medium", topics: "Hash Table, String, Sorting", slug: "rearrange-k-substrings-to-form-target-string" },
  { id: 3366, title: "Minimum Array Sum", diff: "Hard", topics: "Dynamic Programming, Greedy", slug: "minimum-array-sum" },
  { id: 3367, title: "Maximize Sum of Weights after Edge Removals", diff: "Hard", topics: "Tree, Dynamic Programming, Depth-First Search", slug: "maximize-sum-of-weights-after-edge-removals" },
  { id: 3368, title: "First Letter Capitalization II", diff: "Easy", topics: "Database", slug: "first-letter-capitalization-ii" },
  { id: 3369, title: "Design an Array Statistics Tracker", diff: "Hard", topics: "Design, Heap (Priority Queue), Ordered Set", slug: "design-an-array-statistics-tracker" },
  { id: 3370, title: "Smallest Number With All Set Bits", diff: "Easy", topics: "Bit Manipulation, Math", slug: "smallest-number-with-all-set-bits" },
  { id: 3371, title: "Identify the Largest Outlier in an Array", diff: "Medium", topics: "Array, Hash Table", slug: "identify-the-largest-outlier-in-an-array" },
  { id: 3372, title: "Maximize the Number of Target Nodes After Connecting Trees I", diff: "Medium", topics: "Tree, Breadth-First Search, Depth-First Search", slug: "maximize-the-number-of-target-nodes-after-connecting-trees-i" },
  { id: 3373, title: "Maximize the Number of Target Nodes After Connecting Trees II", diff: "Hard", topics: "Tree, Breadth-First Search, Depth-First Search", slug: "maximize-the-number-of-target-nodes-after-connecting-trees-ii" },
  { id: 3374, title: "First Letter Capitalization", diff: "Easy", topics: "Database", slug: "first-letter-capitalization" },
  { id: 3375, title: "Minimum Operations to Make Array Values Equal to K", diff: "Easy", topics: "Array, Hash Table", slug: "minimum-operations-to-make-array-values-equal-to-k" },
  { id: 3376, title: "Minimum Time to Break Locks I", diff: "Medium", topics: "Backtracking, Bit Manipulation", slug: "minimum-time-to-break-locks-i" },
  { id: 3377, title: "Digit Operations to Make Two Integers Equal", diff: "Hard", topics: "Graph, Shortest Path, Math", slug: "digit-operations-to-make-two-integers-equal" },
  { id: 3378, title: "Count Connected Components in LCM Graph", diff: "Hard", topics: "Union Find, Number Theory", slug: "count-connected-components-in-lcm-graph" },
  { id: 3379, title: "Transformed Array", diff: "Easy", topics: "Array, Simulation", slug: "transformed-array" },
  { id: 3380, title: "Maximum Area Rectangle With Point Constraints I", diff: "Medium", topics: "Geometry, Hash Table", slug: "maximum-area-rectangle-with-point-constraints-i" },
  { id: 3381, title: "Maximum Subarray Sum With Length Divisible by K", diff: "Hard", topics: "Array, Prefix Sum, Hash Table", slug: "maximum-subarray-sum-with-length-divisible-by-k" },
  { id: 3382, title: "Maximum Area Rectangle With Point Constraints II", diff: "Hard", topics: "Geometry, Sweep Line", slug: "maximum-area-rectangle-with-point-constraints-ii" },
  { id: 3383, title: "Minimum Runes to Add to Cast Spell", diff: "Hard", topics: "Graph, Strongly Connected Components", slug: "minimum-runes-to-add-to-cast-spell" },
  { id: 3384, title: "Team Dominance by Pass Success", diff: "Medium", topics: "Database", slug: "team-dominance-by-pass-success" },
  { id: 3385, title: "Minimum Time to Reach Destination in Directed Graph", diff: "Hard", topics: "Graph, Shortest Path", slug: "minimum-time-to-reach-destination-in-directed-graph" },
  { id: 3386, title: "Button with Longest Push Time", diff: "Easy", topics: "Array", slug: "button-with-longest-push-time" },
  { id: 3387, title: "Maximize Amount After Two Days of Conversions", diff: "Medium", topics: "Graph, Depth-First Search", slug: "maximize-amount-after-two-days-of-conversions" },
  { id: 3388, title: "Count Beautiful Splits in an Array", diff: "Hard", topics: "Array, String, Z Function", slug: "count-beautiful-splits-in-an-array" },
  { id: 3389, title: "Minimum Operations to Make Character Frequencies Equal", diff: "Hard", topics: "String, Dynamic Programming, Greedy", slug: "minimum-operations-to-make-character-frequencies-equal" },
  { id: 3390, title: "Longest Team Pass Streak", diff: "Medium", topics: "Database", slug: "longest-team-pass-streak" },
  { id: 3391, title: "Design a 3D Binary Matrix with Efficient Layer Tracking", diff: "Hard", topics: "Design", slug: "design-a-3d-binary-matrix-with-efficient-layer-tracking" },
  { id: 3392, title: "Count Subarrays of Length Three With a Condition", diff: "Easy", topics: "Array", slug: "count-subarrays-of-length-three-with-a-condition" },
  { id: 3393, title: "Count Paths With the Given XOR Value", diff: "Medium", topics: "Dynamic Programming, Matrix", slug: "count-paths-with-the-given-xor-value" },
  { id: 3394, title: "Check if Grid Can Be Cut Into Sections", diff: "Medium", topics: "Geometry, Sorting", slug: "check-if-grid-can-be-cut-into-sections" },
  { id: 3395, title: "Subsequences With a Unique Middle Mode I", diff: "Hard", topics: "Array, Combinatorics", slug: "subsequences-with-a-unique-middle-mode-i" },
  { id: 3396, title: "Minimum Number of Operations to Make Elements in Array Distinct", diff: "Easy", topics: "Array, Hash Table", slug: "minimum-number-of-operations-to-make-elements-in-array-distinct" },
  { id: 3397, title: "Maximum Number of Distinct Elements After Operations", diff: "Medium", topics: "Array, Greedy, Sorting", slug: "maximum-number-of-distinct-elements-after-operations" },
  { id: 3398, title: "Smallest Substring With Identical Characters I", diff: "Medium", topics: "String, Binary Search", slug: "smallest-substring-with-identical-characters-i" },
  { id: 3399, title: "Smallest Substring With Identical Characters II", diff: "Hard", topics: "String, Binary Search", slug: "smallest-substring-with-identical-characters-ii" },
  { id: 3400, title: "Maximum Number of Matching Indices After Right Shifts", diff: "Medium", topics: "Array, Simulation", slug: "maximum-number-of-matching-indices-after-right-shifts" },
  { id: 3401, title: "Find Circular Gift Exchange Chains", diff: "Medium", topics: "Graph, Depth-First Search", slug: "find-circular-gift-exchange-chains" },
  { id: 3402, title: "Minimum Operations to Make Columns Strictly Increasing", diff: "Medium", topics: "Array, Greedy, Matrix", slug: "minimum-operations-to-make-columns-strictly-increasing" },
  { id: 3403, title: "Find the Lexicographically Largest String From the Box I", diff: "Medium", topics: "String, Greedy", slug: "find-the-lexicographically-largest-string-from-the-box-i" },
  { id: 3404, title: "Count Special Subsequences", diff: "Hard", topics: "Array, Hash Table, Combinatorics", slug: "count-special-subsequences" },
  { id: 3405, title: "Count the Number of Arrays with K Matching Adjacent Elements", diff: "Hard", topics: "Dynamic Programming, Combinatorics, Math", slug: "count-the-number-of-arrays-with-k-matching-adjacent-elements" },
  { id: 3406, title: "Find the Lexicographically Largest String From the Box II", diff: "Hard", topics: "String, Greedy", slug: "find-the-lexicographically-largest-string-from-the-box-ii" },
  { id: 3407, title: "Substring Matching Pattern", diff: "Easy", topics: "String, Two Pointers", slug: "substring-matching-pattern" },
  { id: 3408, title: "Design Task Manager", diff: "Medium", topics: "Design, Hash Table, Heap (Priority Queue)", slug: "design-task-manager" },
  { id: 3409, title: "Longest Subsequence With Decreasing Adjacent Difference", diff: "Hard", topics: "Dynamic Programming", slug: "longest-subsequence-with-decreasing-adjacent-difference" },
  { id: 3410, title: "Maximize Subarray Sum After Removing All Occurrences of One Element", diff: "Hard", topics: "Array, Dynamic Programming", slug: "maximize-subarray-sum-after-removing-all-occurrences-of-one-element" },
  { id: 3411, title: "Maximum Subarray With Equal Products", diff: "Easy", topics: "Array, Math, Number Theory", slug: "maximum-subarray-with-equal-products" },
  { id: 3412, title: "Find Mirror Score of a String", diff: "Medium", topics: "String, Stack, Greedy", slug: "find-mirror-score-of-a-string" },
  { id: 3413, title: "Maximum Coins From K Consecutive Bags", diff: "Hard", topics: "Array, Prefix Sum, Sliding Window", slug: "maximum-coins-from-k-consecutive-bags" },
  { id: 3414, title: "Maximum Score of Non-overlapping Intervals", diff: "Hard", topics: "Dynamic Programming, Binary Search, Sorting", slug: "maximum-score-of-non-overlapping-intervals" },
  { id: 3415, title: "Find Products with Three Consecutive Digits", diff: "Medium", topics: "Database", slug: "find-products-with-three-consecutive-digits" },
  { id: 3416, title: "Subsequences with a Unique Middle Mode II", diff: "Hard", topics: "Array, Combinatorics", slug: "subsequences-with-a-unique-middle-mode-ii" },
  { id: 3417, title: "Zigzag Grid Traversal With Skip", diff: "Easy", topics: "Array, Matrix, Simulation", slug: "zigzag-grid-traversal-with-skip" },
  { id: 3418, title: "Maximum Amount of Money Robot Can Earn", diff: "Medium", topics: "Dynamic Programming, Matrix", slug: "maximum-amount-of-money-robot-can-earn" },
  { id: 3419, title: "Minimize the Maximum Edge Weight of Graph", diff: "Hard", topics: "Graph, Binary Search", slug: "minimize-the-maximum-edge-weight-of-graph" },
  { id: 3420, title: "Count Non-Decreasing Subarrays After K Operations", diff: "Hard", topics: "Array, Sliding Window, Monotonic Queue", slug: "count-non-decreasing-subarrays-after-k-operations" },
  { id: 3421, title: "Find Students Who Improved", diff: "Medium", topics: "Database", slug: "find-students-who-improved" },
  { id: 3422, title: "Minimum Operations to Make Subarray Elements Equal", diff: "Hard", topics: "Array, Sliding Window, Heap (Priority Queue)", slug: "minimum-operations-to-make-subarray-elements-equal" },
  { id: 3423, title: "Maximum Difference Between Adjacent Elements in a Circular Array", diff: "Easy", topics: "Array", slug: "maximum-difference-between-adjacent-elements-in-a-circular-array" },
  { id: 3424, title: "Minimum Cost to Make Arrays Identical", diff: "Medium", topics: "Array, Greedy, Sorting", slug: "minimum-cost-to-make-arrays-identical" },
  { id: 3425, title: "Longest Special Path", diff: "Hard", topics: "Tree, Depth-First Search", slug: "longest-special-path" },
  { id: 3426, title: "Manhattan Distances of All Arrangements of Pieces", diff: "Hard", topics: "Math, Combinatorics", slug: "manhattan-distances-of-all-arrangements-of-pieces" },
  { id: 3427, title: "Sum of Variable Length Subarrays", diff: "Easy", topics: "Array, Prefix Sum", slug: "sum-of-variable-length-subarrays" },
  { id: 3428, title: "Maximum and Minimum Sums of at Most Size K Subsequences", diff: "Hard", topics: "Array, Math, Combinatorics", slug: "maximum-and-minimum-sums-of-at-most-size-k-subsequences" },
  { id: 3429, title: "Paint House IV", diff: "Hard", topics: "Dynamic Programming", slug: "paint-house-iv" },
  { id: 3430, title: "Maximum and Minimum Sums of at Most Size K Subarrays", diff: "Hard", topics: "Array, Monotonic Stack", slug: "maximum-and-minimum-sums-of-at-most-size-k-subarrays" },
  { id: 3431, title: "Minimum Unlocked Indices to Sort Nums", diff: "Medium", topics: "Array, Greedy", slug: "minimum-unlocked-indices-to-sort-nums" },
  { id: 3432, title: "Count Partitions with Even Sum Difference", diff: "Easy", topics: "Array, Prefix Sum", slug: "count-partitions-with-even-sum-difference" },
  { id: 3433, title: "Count Mentions Per User", diff: "Medium", topics: "Simulation, Hash Table", slug: "count-mentions-per-user" },
  { id: 3434, title: "Maximum Frequency After Subarray Operation", diff: "Medium", topics: "Array, Prefix Sum", slug: "maximum-frequency-after-subarray-operation" },
  { id: 3435, title: "Frequencies of Shortest Supersequences", diff: "Hard", topics: "Graph, Bit Manipulation, Backtracking", slug: "frequencies-of-shortest-supersequences" },
  { id: 3436, title: "Find Valid Pair of Adjacent Digits in String", diff: "Easy", topics: "String", slug: "find-valid-pair-of-adjacent-digits-in-string" },
  { id: 3437, title: "Permutations III", diff: "Medium", topics: "Backtracking", slug: "permutations-iii" },
  { id: 3438, title: "Find Valid Pairs of Adjacent Digits in String II", diff: "Medium", topics: "String", slug: "find-valid-pairs-of-adjacent-digits-in-string-ii" },
  { id: 3439, title: "Reschedule Meetings for Maximum Free Time I", diff: "Medium", topics: "Greedy, Sliding Window", slug: "reschedule-meetings-for-maximum-free-time-i" },
  { id: 3440, title: "Reschedule Meetings for Maximum Free Time II", diff: "Medium", topics: "Greedy", slug: "reschedule-meetings-for-maximum-free-time-ii" },
  { id: 3441, title: "Minimum Cost Good Caption", diff: "Hard", topics: "String, Dynamic Programming", slug: "minimum-cost-good-caption" },
  { id: 3442, title: "Maximum Difference Between Even and Odd Frequency I", diff: "Easy", topics: "Hash Table, String, Counting", slug: "maximum-difference-between-even-and-odd-frequency-i" },
  { id: 3443, title: "Maximum Manhattan Distance After K Changes", diff: "Medium", topics: "Greedy, String", slug: "maximum-manhattan-distance-after-k-changes" },
  { id: 3444, title: "Minimum Increments for Target Multiples in an Array", diff: "Hard", topics: "Dynamic Programming, Bit Manipulation, Math", slug: "minimum-increments-for-target-multiples-in-an-array" },
  { id: 3445, title: "Maximum Difference Between Even and Odd Frequency II", diff: "Hard", topics: "String, Prefix Sum", slug: "maximum-difference-between-even-and-odd-frequency-ii" },
  { id: 3446, title: "Sort Matrix by Diagonals", diff: "Medium", topics: "Array, Matrix, Sorting", slug: "sort-matrix-by-diagonals" },
  { id: 3447, title: "Assign Elements to Groups with Constraints", diff: "Medium", topics: "Array, Hash Table", slug: "assign-elements-to-groups-with-constraints" },
  { id: 3448, title: "Count Substrings Divisible By Last Digit", diff: "Hard", topics: "String, Dynamic Programming, Math", slug: "count-substrings-divisible-by-last-digit" },
  { id: 3449, title: "Maximize the Minimum Game Score", diff: "Hard", topics: "Binary Search, Greedy", slug: "maximize-the-minimum-game-score" },
  { id: 3450, title: "Maximum Students on a Single Bench", diff: "Easy", topics: "Array, Hash Table", slug: "maximum-students-on-a-single-bench" },
  { id: 3451, title: "Find Invalid IP Addresses", diff: "Easy", topics: "Database", slug: "find-invalid-ip-addresses" },
  { id: 3452, title: "Sum of Good Numbers", diff: "Easy", topics: "Array", slug: "sum-of-good-numbers" },
  { id: 3453, title: "Separate Squares I", diff: "Medium", topics: "Geometry, Binary Search", slug: "separate-squares-i" },
  { id: 3454, title: "Separate Squares II", diff: "Hard", topics: "Geometry, Binary Search", slug: "separate-squares-ii" },
  { id: 3455, title: "Shortest Matching Substring", diff: "Hard", topics: "String, KMP, Two Pointers", slug: "shortest-matching-substring" },
  { id: 3456, title: "Find Special Substring of Length K", diff: "Easy", topics: "String", slug: "find-special-substring-of-length-k" },
  { id: 3457, title: "Eat Pizzas!", diff: "Medium", topics: "Array, Greedy, Sorting", slug: "eat-pizzas" },
  { id: 3458, title: "Select K Disjoint Special Substrings", diff: "Hard", topics: "String, Greedy, Dynamic Programming", slug: "select-k-disjoint-special-substrings" },
  { id: 3459, title: "Length of Longest V-Shaped Diagonal Segment", diff: "Hard", topics: "Dynamic Programming, Matrix", slug: "length-of-longest-v-shaped-diagonal-segment" },
  { id: 3460, title: "Longest Common Prefix After at Most One Removal", diff: "Easy", topics: "String, Two Pointers", slug: "longest-common-prefix-after-at-most-one-removal" },
  { id: 3461, title: "Check If Digits Are Equal in String After Operations I", diff: "Easy", topics: "String, Simulation", slug: "check-if-digits-are-equal-in-string-after-operations-i" },
  { id: 3462, title: "Maximum Sum With at Most K Elements", diff: "Medium", topics: "Array, Greedy, Heap (Priority Queue)", slug: "maximum-sum-with-at-most-k-elements" },
  { id: 3463, title: "Check If Digits Are Equal in String After Operations II", diff: "Hard", topics: "Math, Combinatorics, String", slug: "check-if-digits-are-equal-in-string-after-operations-ii" },
  { id: 3464, title: "Maximize the Distance Between Points on a Square", diff: "Hard", topics: "Geometry, Binary Search", slug: "maximize-the-distance-between-points-on-a-square" },
  { id: 3465, title: "Find Products with Valid Serial Numbers", diff: "Medium", topics: "Database", slug: "find-products-with-valid-serial-numbers" },
  { id: 3466, title: "Maximum Coin Collection", diff: "Hard", topics: "Dynamic Programming, Graph", slug: "maximum-coin-collection" },
  { id: 3467, title: "Transform Array by Parity", diff: "Easy", topics: "Array, Two Pointers", slug: "transform-array-by-parity" },
  { id: 3468, title: "Find the Number of Copy Arrays", diff: "Medium", topics: "Array, Math", slug: "find-the-number-of-copy-arrays" },
  { id: 3469, title: "Find Minimum Cost to Remove Array Elements", diff: "Hard", topics: "Dynamic Programming", slug: "find-minimum-cost-to-remove-array-elements" },
  { id: 3470, title: "Permutations IV", diff: "Hard", topics: "Backtracking, Combinatorics", slug: "permutations-iv" },
  { id: 3471, title: "Find the Largest Almost Missing Integer", diff: "Easy", topics: "Array, Hash Table", slug: "find-the-largest-almost-missing-integer" },
  { id: 3472, title: "Longest Palindromic Subsequence After at Most K Operations", diff: "Hard", topics: "String, Dynamic Programming", slug: "longest-palindromic-subsequence-after-at-most-k-operations" },
  { id: 3473, title: "Sum of K Subarrays With Length at Least M", diff: "Hard", topics: "Array, Dynamic Programming", slug: "sum-of-k-subarrays-with-length-at-least-m" },
  { id: 3474, title: "Lexicographically Smallest Generated String", diff: "Hard", topics: "String, Greedy", slug: "lexicographically-smallest-generated-string" },
  { id: 3475, title: "DNA Pattern Recognition", diff: "Medium", topics: "Database", slug: "dna-pattern-recognition" },
  { id: 3476, title: "Maximize Profit from Task Assignment", diff: "Medium", topics: "Greedy, Heap (Priority Queue)", slug: "maximize-profit-from-task-assignment" },
  { id: 3477, title: "Fruits Into Baskets II", diff: "Easy", topics: "Array, Simulation", slug: "fruits-into-baskets-ii" },
  { id: 3478, title: "Choose K Elements With Maximum Sum", diff: "Medium", topics: "Array, Heap (Priority Queue), Sorting", slug: "choose-k-elements-with-maximum-sum" },
  { id: 3479, title: "Fruits Into Baskets III", diff: "Hard", topics: "Segment Tree, Array", slug: "fruits-into-baskets-iii" },
  { id: 3480, title: "Maximize Subarrays After Removing One Conflicting Pair", diff: "Hard", topics: "Array, Greedy", slug: "maximize-subarrays-after-removing-one-conflicting-pair" },
  { id: 3481, title: "Apply Substitutions", diff: "Medium", topics: "Database", slug: "apply-substitutions" },
  { id: 3482, title: "Analyze Organization Hierarchy", diff: "Hard", topics: "Database", slug: "analyze-organization-hierarchy" },
  { id: 3483, title: "Unique 3-Digit Even Numbers", diff: "Easy", topics: "Array, Hash Table, Enumeration", slug: "unique-3-digit-even-numbers" },
  { id: 3484, title: "Design Spreadsheet", diff: "Medium", topics: "Design, Hash Table", slug: "design-spreadsheet" },
  { id: 3485, title: "Longest Common Prefix of K Strings After Removal", diff: "Hard", topics: "Trie, String", slug: "longest-common-prefix-of-k-strings-after-removal" },
  { id: 3486, title: "Longest Special Path II", diff: "Hard", topics: "Tree, Depth-First Search", slug: "longest-special-path-ii" },
  { id: 3487, title: "Maximum Unique Subarray Sum After Deletion", diff: "Easy", topics: "Array, Greedy", slug: "maximum-unique-subarray-sum-after-deletion" },
  { id: 3488, title: "Closest Equal Element Queries", diff: "Medium", topics: "Array, Hash Table, Binary Search", slug: "closest-equal-element-queries" },
  { id: 3489, title: "Zero Array Transformation IV", diff: "Hard", topics: "Array, Greedy", slug: "zero-array-transformation-iv" },
  { id: 3490, title: "Count Beautiful Numbers", diff: "Medium", topics: "Math, Digit DP", slug: "count-beautiful-numbers" },
  { id: 3491, title: "Phone Number Prefix", diff: "Easy", topics: "Database", slug: "phone-number-prefix" },
  { id: 3492, title: "Maximum Containers on a Ship", diff: "Medium", topics: "Greedy", slug: "maximum-containers-on-a-ship" },
  { id: 3493, title: "Properties Graph", diff: "Medium", topics: "Graph, Union Find", slug: "properties-graph" },
  { id: 3494, title: "Find the Minimum Amount of Time to Brew Potions", diff: "Hard", topics: "Dynamic Programming", slug: "find-the-minimum-amount-of-time-to-brew-potions" },
  { id: 3495, title: "Minimum Operations to Make Array Elements Zero", diff: "Hard", topics: "Bit Manipulation, Greedy", slug: "minimum-operations-to-make-array-elements-zero" },
  { id: 3496, title: "Maximize Score After Pair Deletions", diff: "Medium", topics: "Dynamic Programming", slug: "maximize-score-after-pair-deletions" },
  { id: 3497, title: "Analyze Subscription Conversion", diff: "Medium", topics: "Database", slug: "analyze-subscription-conversion" },
  { id: 3498, title: "Reverse Degree of a String", diff: "Easy", topics: "String", slug: "reverse-degree-of-a-string" },
  { id: 3499, title: "Maximize Active Section with Trade I", diff: "Hard", topics: "Sliding Window, Greedy", slug: "maximize-active-section-with-trade-i" },
  { id: 3500, title: "Minimum Cost for Cutting Cake III", diff: "Hard", topics: "Greedy, Dynamic Programming", slug: "minimum-cost-for-cutting-cake-iii" }

);